# $Id: makefile,v 1.3 2001/04/16 18:53:47 jayadev Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vddrawing/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.3  2001/04/16 18:53:47  jayadev
#	*** empty log message ***
#	
#	Revision 1.2  2001/04/13 15:52:26  ylong
#	*** empty log message ***
#	
#	Revision 1.1.1.1  2001/01/04 21:08:42  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:32:38  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------
TGT = vdidrwimp

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o *.c
