#!/bin/sh
# This script creates the directories, required for building a new version of MODEL
#
mkdir -p /usr2/model34/atp
mkdir -p /usr2/model34/atp/features
mkdir -p /usr2/model34/atp/filesz
mkdir -p /usr2/model34/atp/freeform
mkdir -p /usr2/model34/atp/freeform1
mkdir -p /usr2/model34/atp/msc
mkdir -p /usr2/model34/atp/pattern
mkdir -p /usr2/model34/atp/sectvw
mkdir -p /usr2/model34/atp/sf_graphics
mkdir -p /usr2/model34/atp/shading
mkdir -p /usr2/model34/atp/shading/cas
mkdir -p /usr2/model34/atp/shading/cct
mkdir -p /usr2/model34/atp/shading/cds
mkdir -p /usr2/model34/atp/shading/cpptp
mkdir -p /usr2/model34/atp/shading/crw
mkdir -p /usr2/model34/atp/shading/csa
mkdir -p /usr2/model34/atp/shading/cspf
mkdir -p /usr2/model34/atp/shading/cve
mkdir -p /usr2/model34/atp/shading/cw
mkdir -p /usr2/model34/atp/shading/dls
mkdir -p /usr2/model34/atp/shading/dr
mkdir -p /usr2/model34/atp/shading/dy
mkdir -p /usr2/model34/atp/shading/fv
mkdir -p /usr2/model34/atp/shading/max
mkdir -p /usr2/model34/atp/shading/mvp
mkdir -p /usr2/model34/atp/shading/mvv
mkdir -p /usr2/model34/atp/shading/pdd
mkdir -p /usr2/model34/atp/shading/pml
mkdir -p /usr2/model34/atp/shading/rvada
mkdir -p /usr2/model34/atp/shading/rvb
mkdir -p /usr2/model34/atp/shading/rw
mkdir -p /usr2/model34/atp/shading/sasa
mkdir -p /usr2/model34/atp/shading/sctp
mkdir -p /usr2/model34/atp/shading/sdp
mkdir -p /usr2/model34/atp/shading/seazd
mkdir -p /usr2/model34/atp/shading/sedd
mkdir -p /usr2/model34/atp/shading/sevv
mkdir -p /usr2/model34/atp/shading/shapes
mkdir -p /usr2/model34/atp/shading/si
mkdir -p /usr2/model34/atp/shading/sw
mkdir -p /usr2/model34/atp/shading/swdm
mkdir -p /usr2/model34/atp/shading/sws
mkdir -p /usr2/model34/atp/shading/tdia
mkdir -p /usr2/model34/atp/shading/tile
mkdir -p /usr2/model34/atp/shading/uw
mkdir -p /usr2/model34/atp/shading/wa
mkdir -p /usr2/model34/atp/shading/wc
mkdir -p /usr2/model34/atp/shading/wo
mkdir -p /usr2/model34/atp/shading/zoom
mkdir -p /usr2/model34/atp/xhatch
mkdir -p /usr2/model34/atp_dgn
mkdir -p /usr2/model34/bin
mkdir -p /usr2/model34/config
mkdir -p /usr2/model34/config/dload
mkdir -p /usr2/model34/config/dload/init
mkdir -p /usr2/model34/config/dload/patch
mkdir -p /usr2/model34/config/english
mkdir -p /usr2/model34/ems
mkdir -p /usr2/model34/ems/ems
mkdir -p /usr2/model34/ems/emsui02
mkdir -p /usr2/model34/ems/emsui02/config
mkdir -p /usr2/model34/ems/emsui02/config/english
mkdir -p /usr2/model34/ems/emsui02/config/english/menus
mkdir -p /usr2/model34/ems/emsui02/config/english/menus/src
mkdir -p /usr2/model34/ems/emsui02l
mkdir -p /usr2/model34/ems/emsui02l/config
mkdir -p /usr2/model34/ems/emsui02l/config/english
mkdir -p /usr2/model34/ems/emsui02l/config/english/menus
mkdir -p /usr2/model34/ems/emsui02l/config/english/menus/src
mkdir -p /usr2/model34/ems/emsuilt
mkdir -p /usr2/model34/ems/emsuilt/config
mkdir -p /usr2/model34/ems/emsuilt/config/english
mkdir -p /usr2/model34/ems/emsuilt/config/english/menus
mkdir -p /usr2/model34/ems/emsuilt/config/english/menus/src
mkdir -p /usr2/model34/ems/emsuiltl
mkdir -p /usr2/model34/ems/emsuiltl/config
mkdir -p /usr2/model34/ems/emsuiltl/config/english
mkdir -p /usr2/model34/ems/emsuiltl/config/english/menus
mkdir -p /usr2/model34/ems/emsuiltl/config/english/menus/src
mkdir -p /usr2/model34/ems/emsuiu
mkdir -p /usr2/model34/ems/emsuiu/config
mkdir -p /usr2/model34/ems/emsuiu/config/english
mkdir -p /usr2/model34/ems/emsuiu/config/english/menus
mkdir -p /usr2/model34/ems/emsuiu/config/english/menus/src
mkdir -p /usr2/model34/ems/emsuiul
mkdir -p /usr2/model34/ems/emsuiul/config
mkdir -p /usr2/model34/ems/emsuiul/config/english
mkdir -p /usr2/model34/ems/emsuiul/config/english/menus
mkdir -p /usr2/model34/ems/emsuiul/config/english/menus/src
mkdir -p /usr2/model34/emsapps
mkdir -p /usr2/model34/emspcs
mkdir -p /usr2/model34/emspcs/config
mkdir -p /usr2/model34/emspcs/config/dload
mkdir -p /usr2/model34/emspcs/config/dload/init
mkdir -p /usr2/model34/emspcs/emspcs
mkdir -p /usr2/model34/emsplt
mkdir -p /usr2/model34/emsplt/config
mkdir -p /usr2/model34/emsplt/config/dload
mkdir -p /usr2/model34/emsplt/config/dload/init
mkdir -p /usr2/model34/emsplt/emsplt
mkdir -p /usr2/model34/emsppp
mkdir -p /usr2/model34/emsppp/config
mkdir -p /usr2/model34/emsppp/config/dload
mkdir -p /usr2/model34/emsppp/config/dload/init
mkdir -p /usr2/model34/emsppp/emsppp
mkdir -p /usr2/model34/emsult
mkdir -p /usr2/model34/emsult/bin
mkdir -p /usr2/model34/emsult/config
mkdir -p /usr2/model34/emsult/emspcs
mkdir -p /usr2/model34/emsult/emsplt
mkdir -p /usr2/model34/emsult/emsppp
mkdir -p /usr2/model34/emsult/emsult
mkdir -p /usr2/model34/etc
mkdir -p /usr2/model34/etc/bin
mkdir -p /usr2/model34/etc/lib
mkdir -p /usr2/model34/hplot
mkdir -p /usr2/model34/hplot/config
mkdir -p /usr2/model34/hplot/config/english
mkdir -p /usr2/model34/hplot/config/english/messages
mkdir -p /usr2/model34/hplot/scripts
mkdir -p /usr2/model34/hplot/src
mkdir -p /usr2/model34/hplot/src/doc
mkdir -p /usr2/model34/hplot/src/dump
mkdir -p /usr2/model34/hplot/src/edmf
mkdir -p /usr2/model34/hplot/src/hplot
mkdir -p /usr2/model34/hplot/src/hplot_func
mkdir -p /usr2/model34/hplot/src/load
mkdir -p /usr2/model34/hplot/src/merge
mkdir -p /usr2/model34/hplot/src/preview
mkdir -p /usr2/model34/hplot/src/timing
mkdir -p /usr2/model34/hplot/src/version
mkdir -p /usr2/model34/hsurf
mkdir -p /usr2/model34/hsurf/lib
mkdir -p /usr2/model34/hsurf/lib/isl
mkdir -p /usr2/model34/hsurf/src
mkdir -p /usr2/model34/hsurf/src/asap2
mkdir -p /usr2/model34/hsurf/src/bundle_imp
mkdir -p /usr2/model34/hsurf/src/co_func
mkdir -p /usr2/model34/hsurf/src/co_imp
mkdir -p /usr2/model34/hsurf/src/cob
mkdir -p /usr2/model34/hsurf/src/display_func
mkdir -p /usr2/model34/hsurf/src/display_img
mkdir -p /usr2/model34/hsurf/src/dlist
mkdir -p /usr2/model34/hsurf/src/dpb_imp
mkdir -p /usr2/model34/hsurf/src/driver_func
mkdir -p /usr2/model34/hsurf/src/gragad_imp
mkdir -p /usr2/model34/hsurf/src/hplot_imp
mkdir -p /usr2/model34/hsurf/src/lvhl
mkdir -p /usr2/model34/hsurf/src/make_sh
mkdir -p /usr2/model34/hsurf/src/ncv_func
mkdir -p /usr2/model34/hsurf/src/obsolete
mkdir -p /usr2/model34/hsurf/src/pbust_func
mkdir -p /usr2/model34/hsurf/src/render_imp
mkdir -p /usr2/model34/hsurf/src/solo
mkdir -p /usr2/model34/hsurf/src/spec
mkdir -p /usr2/model34/hsurf/src/tiler_func
mkdir -p /usr2/model34/include
mkdir -p /usr2/model34/include/PWapi
mkdir -p /usr2/model34/include/PWdbapi
mkdir -p /usr2/model34/include/proto
mkdir -p /usr2/model34/integ
mkdir -p /usr2/model34/integ/atp
mkdir -p /usr2/model34/integ/emspriv
mkdir -p /usr2/model34/integ/emspub
mkdir -p /usr2/model34/mds
mkdir -p /usr2/model34/mds/config
mkdir -p /usr2/model34/mds/config/dload
mkdir -p /usr2/model34/mds/config/dload/init
mkdir -p /usr2/model34/mds/mds
mkdir -p /usr2/model34/miniems
mkdir -p /usr2/model34/miniems/api
mkdir -p /usr2/model34/miniems/api/OMuse
mkdir -p /usr2/model34/miniems/api/bdrycre
mkdir -p /usr2/model34/miniems/api/bdryint
mkdir -p /usr2/model34/miniems/api/bdrymod
mkdir -p /usr2/model34/miniems/api/bdryquery
mkdir -p /usr2/model34/miniems/api/cvquery
mkdir -p /usr2/model34/miniems/api/dpb
mkdir -p /usr2/model34/miniems/api/errdbg
mkdir -p /usr2/model34/miniems/api/grmod
mkdir -p /usr2/model34/miniems/api/grquery
mkdir -p /usr2/model34/miniems/api/int2d
mkdir -p /usr2/model34/miniems/api/map
mkdir -p /usr2/model34/miniems/api/math
mkdir -p /usr2/model34/miniems/api/runtypes
mkdir -p /usr2/model34/miniems/api/sfcre
mkdir -p /usr2/model34/miniems/api/sfmod
mkdir -p /usr2/model34/miniems/api/sfquery
mkdir -p /usr2/model34/miniems/api/tolfunc
mkdir -p /usr2/model34/miniems/api/uom
mkdir -p /usr2/model34/miniems/api/util
mkdir -p /usr2/model34/miniems/bin
mkdir -p /usr2/model34/miniems/funk
mkdir -p /usr2/model34/miniems/funk/grnuc
mkdir -p /usr2/model34/miniems/funk/model
mkdir -p /usr2/model34/miniems/imp
mkdir -p /usr2/model34/miniems/imp/grnuc
mkdir -p /usr2/model34/miniems/imp/model
mkdir -p /usr2/model34/miniems/include
mkdir -p /usr2/model34/miniems/include/api
mkdir -p /usr2/model34/miniems/include/api/PWapi
mkdir -p /usr2/model34/miniems/include/grnuc
mkdir -p /usr2/model34/miniems/include/model
mkdir -p /usr2/model34/miniems/lib
mkdir -p /usr2/model34/miniems/miniEMS
mkdir -p /usr2/model34/miniems/nt
mkdir -p /usr2/model34/miniems/nt/build
mkdir -p /usr2/model34/miniems/nt/build/vb
mkdir -p /usr2/model34/miniems/nt/src
mkdir -p /usr2/model34/miniems/spec
mkdir -p /usr2/model34/miniems/spec/grnuc
mkdir -p /usr2/model34/miniems/spec/model
mkdir -p /usr2/model34/miniems/stubs
mkdir -p /usr2/model34/model
mkdir -p /usr2/model34/modeldp
mkdir -p /usr2/model34/modelsrc
mkdir -p /usr2/model34/ppl
mkdir -p /usr2/model34/ppl/bin
mkdir -p /usr2/model34/ppl/cisrc
mkdir -p /usr2/model34/proto_include
mkdir -p /usr2/model34/spec
mkdir -p /usr2/model34/src_assem
mkdir -p /usr2/model34/src_assem/funk
mkdir -p /usr2/model34/src_assem/imp
mkdir -p /usr2/model34/src_assem/ppl
mkdir -p /usr2/model34/src_assem/revasm
mkdir -p /usr2/model34/src_assem/spec
mkdir -p /usr2/model34/src_assoc
mkdir -p /usr2/model34/src_assoc/funk
mkdir -p /usr2/model34/src_assoc/imp
mkdir -p /usr2/model34/src_assoc/impco
mkdir -p /usr2/model34/src_assoc/spec
mkdir -p /usr2/model34/src_bound
mkdir -p /usr2/model34/src_bound/funk
mkdir -p /usr2/model34/src_bound/impbd
mkdir -p /usr2/model34/src_bound/impbs
mkdir -p /usr2/model34/src_bound/impde
mkdir -p /usr2/model34/src_bound/imped
mkdir -p /usr2/model34/src_bound/imple
mkdir -p /usr2/model34/src_bound/implp
mkdir -p /usr2/model34/src_bound/impls
mkdir -p /usr2/model34/src_bound/impne
mkdir -p /usr2/model34/src_bound/impolp
mkdir -p /usr2/model34/src_bound/imppe
mkdir -p /usr2/model34/src_bound/imppted
mkdir -p /usr2/model34/src_bound/spec
mkdir -p /usr2/model34/src_cnstr
mkdir -p /usr2/model34/src_cnstr/imp
mkdir -p /usr2/model34/src_cnstr/spec
mkdir -p /usr2/model34/src_co
mkdir -p /usr2/model34/src_co/funk
mkdir -p /usr2/model34/src_co/imp
mkdir -p /usr2/model34/src_co/slic
mkdir -p /usr2/model34/src_co/spec
mkdir -p /usr2/model34/src_co_mass
mkdir -p /usr2/model34/src_co_mass/funk
mkdir -p /usr2/model34/src_co_mass/imp
mkdir -p /usr2/model34/src_co_mass/spec
mkdir -p /usr2/model34/src_comp
mkdir -p /usr2/model34/src_comp/imp
mkdir -p /usr2/model34/src_comp/spec
mkdir -p /usr2/model34/src_compcv
mkdir -p /usr2/model34/src_compcv/imp
mkdir -p /usr2/model34/src_compcv/spec
mkdir -p /usr2/model34/src_compsf
mkdir -p /usr2/model34/src_compsf/imp
mkdir -p /usr2/model34/src_compsf/spec
mkdir -p /usr2/model34/src_curve
mkdir -p /usr2/model34/src_curve/funk
mkdir -p /usr2/model34/src_curve/imp
mkdir -p /usr2/model34/src_curve/spec
mkdir -p /usr2/model34/src_datum
mkdir -p /usr2/model34/src_datum/funk
mkdir -p /usr2/model34/src_datum/imp
mkdir -p /usr2/model34/src_datum/impco
mkdir -p /usr2/model34/src_datum/spec
mkdir -p /usr2/model34/src_dpb
mkdir -p /usr2/model34/src_dpb/funk
mkdir -p /usr2/model34/src_dpb/imp
mkdir -p /usr2/model34/src_dpb/spec
mkdir -p /usr2/model34/src_dpr
mkdir -p /usr2/model34/src_dpr/funk
mkdir -p /usr2/model34/src_dpr/imp
mkdir -p /usr2/model34/src_dpr/spec
mkdir -p /usr2/model34/src_drawvw
mkdir -p /usr2/model34/src_drawvw/imp
mkdir -p /usr2/model34/src_drawvw/spec
mkdir -p /usr2/model34/src_freeform
mkdir -p /usr2/model34/src_freeform/imp
mkdir -p /usr2/model34/src_freeform/slic
mkdir -p /usr2/model34/src_freeform/spec
mkdir -p /usr2/model34/src_funk
mkdir -p /usr2/model34/src_funk/misc
mkdir -p /usr2/model34/src_gradat
mkdir -p /usr2/model34/src_gradat/funk
mkdir -p /usr2/model34/src_gradat/imp
mkdir -p /usr2/model34/src_gradat/spec
mkdir -p /usr2/model34/src_gralp
mkdir -p /usr2/model34/src_gralp/imp
mkdir -p /usr2/model34/src_gralp/spec
mkdir -p /usr2/model34/src_lib
mkdir -p /usr2/model34/src_lib/isl
mkdir -p /usr2/model34/src_lib/objs
mkdir -p /usr2/model34/src_lib/ris
mkdir -p /usr2/model34/src_lib/ris/ristmp
mkdir -p /usr2/model34/src_listen
mkdir -p /usr2/model34/src_listen/imp
mkdir -p /usr2/model34/src_listen/spec
mkdir -p /usr2/model34/src_mass
mkdir -p /usr2/model34/src_mass/funk
mkdir -p /usr2/model34/src_mass/imp
mkdir -p /usr2/model34/src_nm
mkdir -p /usr2/model34/src_nm/as
mkdir -p /usr2/model34/src_nm/co
mkdir -p /usr2/model34/src_nm/config
mkdir -p /usr2/model34/src_nm/config/english
mkdir -p /usr2/model34/src_nm/config/english/messages
mkdir -p /usr2/model34/src_nm/config/english/messages/src
mkdir -p /usr2/model34/src_nm/dpr
mkdir -p /usr2/model34/src_nm/funk
mkdir -p /usr2/model34/src_nm/include
mkdir -p /usr2/model34/src_nm/int
mkdir -p /usr2/model34/src_nm/lib
mkdir -p /usr2/model34/src_nm/lib/isl
mkdir -p /usr2/model34/src_nm/nm
mkdir -p /usr2/model34/src_nm/spec
mkdir -p /usr2/model34/src_nm/tp
mkdir -p /usr2/model34/src_param
mkdir -p /usr2/model34/src_param/funk
mkdir -p /usr2/model34/src_param/imp
mkdir -p /usr2/model34/src_param/impco
mkdir -p /usr2/model34/src_param/spec
mkdir -p /usr2/model34/src_path
mkdir -p /usr2/model34/src_path/GUItest
mkdir -p /usr2/model34/src_path/OMuse
mkdir -p /usr2/model34/src_path/bdrycre
mkdir -p /usr2/model34/src_path/bdryint
mkdir -p /usr2/model34/src_path/bdrymod
mkdir -p /usr2/model34/src_path/bdryquery
mkdir -p /usr2/model34/src_path/cvcre
mkdir -p /usr2/model34/src_path/cvmod
mkdir -p /usr2/model34/src_path/cvquery
mkdir -p /usr2/model34/src_path/dpb
mkdir -p /usr2/model34/src_path/emsdbg
mkdir -p /usr2/model34/src_path/errdbg
mkdir -p /usr2/model34/src_path/grio
mkdir -p /usr2/model34/src_path/grmod
mkdir -p /usr2/model34/src_path/grquery
mkdir -p /usr2/model34/src_path/include
mkdir -p /usr2/model34/src_path/int2d
mkdir -p /usr2/model34/src_path/map
mkdir -p /usr2/model34/src_path/math
mkdir -p /usr2/model34/src_path/perftest
mkdir -p /usr2/model34/src_path/profcrt
mkdir -p /usr2/model34/src_path/profqry
mkdir -p /usr2/model34/src_path/ref
mkdir -p /usr2/model34/src_path/runtypes
mkdir -p /usr2/model34/src_path/sfcre
mkdir -p /usr2/model34/src_path/sffeature
mkdir -p /usr2/model34/src_path/sfmod
mkdir -p /usr2/model34/src_path/sfquery
mkdir -p /usr2/model34/src_path/sfsfint
mkdir -p /usr2/model34/src_path/tolfunc
mkdir -p /usr2/model34/src_path/uom
mkdir -p /usr2/model34/src_path/util
mkdir -p /usr2/model34/src_path/validate
mkdir -p /usr2/model34/src_place
mkdir -p /usr2/model34/src_place/funk
mkdir -p /usr2/model34/src_ref
mkdir -p /usr2/model34/src_ref/co
mkdir -p /usr2/model34/src_ref/funk
mkdir -p /usr2/model34/src_serim
mkdir -p /usr2/model34/src_shell
mkdir -p /usr2/model34/src_shell/funk
mkdir -p /usr2/model34/src_shell/imp
mkdir -p /usr2/model34/src_shell/spec
mkdir -p /usr2/model34/src_sketch
mkdir -p /usr2/model34/src_sketch/funk
mkdir -p /usr2/model34/src_sketch/imp
mkdir -p /usr2/model34/src_sketch/impco
mkdir -p /usr2/model34/src_sketch/spec
mkdir -p /usr2/model34/src_solid
mkdir -p /usr2/model34/src_solid/imp
mkdir -p /usr2/model34/src_solid/spec
mkdir -p /usr2/model34/src_stub
mkdir -p /usr2/model34/src_surf
mkdir -p /usr2/model34/src_surf/funk
mkdir -p /usr2/model34/src_surf/imp
mkdir -p /usr2/model34/src_surf/spec
mkdir -p /usr2/model34/src_testco
mkdir -p /usr2/model34/src_testco/funk
mkdir -p /usr2/model34/src_testco/imp
mkdir -p /usr2/model34/src_testco/imp/tmp
mkdir -p /usr2/model34/src_testco/include
mkdir -p /usr2/model34/src_testco/slic
mkdir -p /usr2/model34/src_testco/spec
mkdir -p /usr2/model34/src_tol
mkdir -p /usr2/model34/src_tol/funk
mkdir -p /usr2/model34/src_tol/imp
mkdir -p /usr2/model34/src_tol/spec
mkdir -p /usr2/model34/src_util
mkdir -p /usr2/model34/src_util/efpc
mkdir -p /usr2/model34/src_util/graph
mkdir -p /usr2/model34/src_util/plot
mkdir -p /usr2/model34/src_util/surftest
mkdir -p /usr2/model34/src_xforms
mkdir -p /usr2/model34/src_xsec/funk
mkdir -p /usr2/model34/src_xsec/imp
mkdir -p /usr2/model34/src_xsec/spec
mkdir -p /usr2/model34/trans
mkdir -p /usr2/model34/ve
mkdir -p /usr2/model34/ve/lib
mkdir -p /usr2/model34/ve/lib/isl
mkdir -p /usr2/model34/ve/src
mkdir -p /usr2/model34/ve/src/co_imp
mkdir -p /usr2/model34/ve/src/cob
mkdir -p /usr2/model34/ve/src/debug
mkdir -p /usr2/model34/ve/src/dpb_imp
mkdir -p /usr2/model34/ve/src/driver
mkdir -p /usr2/model34/ve/src/gragad_imp
mkdir -p /usr2/model34/ve/src/hiding
mkdir -p /usr2/model34/ve/src/make_sh
mkdir -p /usr2/model34/ve/src/marking
mkdir -p /usr2/model34/ve/src/obsolete
mkdir -p /usr2/model34/ve/src/spec
mkdir -p /usr2/model34/ve/src/util_func
mkdir -p /usr2/model34/ve/src/util_imp
