#ifndef DEFNS_D_INCLUDED 
#define DEFNS_D_INCLUDED 1

#define MAX_SIZE    80	
#define TRUE 1
#define FALSE 0

#define SIZE_IN_BITS(x) (sizeof(x)<<3)

/*--------------------------------------------------------------------------*/
/*  Define bits used in the channel type flags word.  These may or may not  */
/*  be the same as the bits generated by opp for the channel.               */
/*--------------------------------------------------------------------------*/

#define DDP_CHAN_ATT_OO 0x1
#define DDP_CHAN_ATT_OM 0x2
#define DDP_CHAN_ATT_MO 0x4
#define DDP_CHAN_ATT_MM 0x8
#define DDP_CHAN_ATT_ABS 0x100
#define DDP_CHAN_ATT_REL 0x200
#define DDP_CHAN_ATT_RES 0x400

#define MAX_INCLUDE_PATHS 40
#define MAX_PATH_LEN 512
#define MAX_NUM_VERSIONS 4095

#define PRINT_USAGE() \
   error(INFO,"usage: ddp [-r] [-V] [-t] [-I dir] [-D def] [-d dir] specfile ...\n\t-r\treplace identical versions\n\t-V\treport version number\n\t-I dir\tinclude file search directory\n\t-D def\tdefinitions\n\t-d dir\tdictionary directory\n\t-t\tprint table of contents of all classes\n");

#endif
