# -------------------------------------------------------------------
# I/AIM
#
# File:		src/cm/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.3  2002/05/22 20:46:24  ylong
#	*** empty log message ***
#	
#	Revision 1.2  2001/10/29 17:22:22  jdsauby
#	JTS MP TR 5552 - jds
#	
#	Revision 1.1.1.1  2001/06/01 20:06:27  tlstalli
#	Creating aim module
#	
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

TGT = AVDaim_cm

include ${AIM_PATH}/etc/makefiles/lib_only.h
