#!/bin/ksh
# $Id: gen_pantbl,v 1.1.1.1 2001/01/04 21:12:05 cvs Exp $
# -------------------------------------------------------------------
# I/VDS
#
# File: 	vds/config/english/menus/gen_pan_tbl
#
# Description:
#
# Dependencies:
#
# Revision History:
#       $Log: gen_pantbl,v $
#       Revision 1.1.1.1  2001/01/04 21:12:05  cvs
#       Initial import to CVS
#
# Revision 1.2  1996/02/04  15:11:46  pinnacle
# Replaced: config/english/menus/gen_pantbl for:  by r240_int for route240
#
#
# History:
#       MM/DD/YY        AUTHOR          DESCRIPTION
#
# -------------------------------------------------------------------

alias ls=ls

if [ -f route_pan.cmd ]
then
  rm route_pan.cmd
fi

echo "create route panel table"
#
# Creation of dummy ROUTE icons.
#

ls VR[A-Z]* > route_pan.list
for file in `cat route_pan.list`
do
 echo '^"'$file'",'$file',COci,0,0,,"Blank"' >> route_pan.cmd
done
rm route_pan.list

if [ -f route_pan.cmd ]
then
  cp route_pan.cmd ${ROUTE}/config/route_pan_tbl
  rm route_pan.cmd
fi
