#  $Id: makefile,v 1.1.1.1 2001/01/04 21:09:25 cvs Exp $

#***************************************************************************
#* I/VDS
#*
#* File:        vdsup/imp/makefile
#*
#* Description:
#*
#* Dependencies:
#*
#* Revision History:
#*      $Log: makefile,v $
#*      Revision 1.1.1.1  2001/01/04 21:09:25  cvs
#*      Initial import to CVS
#*
# Revision 1.2  1997/10/28  20:39:48  pinnacle
# Added Header
#
# Revision 1.1  1997/10/28  19:13:02  pinnacle
# Added Headers
#
#*
#* History:
#*      MM/DD/YY        AUTHOR          DESCRIPTION
#*      10/28/97        ah              added header
#***************************************************************************/

target: mkfile 
	grmake -r -k -f mkfile

mkfile : vdisup.m
	grmakemake vdisup.m mkfile
