SRC
$(MODEL)/hplot/src/hplot
EXEC
$(MDTARG)/bin/HSplot
LINKLIB
$(MDTARG)/hsurf/src/driver_func/HSckzrange.o
$(MDTARG)/hsurf/src/display_func/HSd_drawtrap.o
$(MDTARG)/hsurf/src/display_func/HSd_fixedpt.o
$(MDTARG)/hsurf/src/tiler_func/tiler_func.o
$(MDTARG)/hsurf/src/pbust_func/HStl_maketrp.o
$(MDTARG)/hsurf/src/pbust_func/HStl_pbust.o
$(MDTARG)/hsurf/src/hplot_imp/HPf_attach.o
$(MDTARG)/hsurf/src/co_func/HSrle_util.o
$(MDTARG)/hplot/src/hplot_func/hplot_func.o
$(MDTARG)/hsurf/src/make_sh/hsurf_global.o
#ifdef CLIX
#ifdef __cpu_c400__
$(BS)/lib/c400/bnfc_ap4.a
$(BS)/lib/c400/bsem_ap4.a
$(BS)/lib/c400/bsma_ap4.a
$(BS)/lib/c400/bsmd_ap4.a
/usr/lib/c400/libxc.a
/usr/lib/libodiC4_s.a
/usr/lib/libRCEC4.a
/usr/lib/libdbeamC4.a
/usr/lib/libscreenC4.a
/usr/lib/c400/libcfile_s.a
#else
$(BS)/lib/c100/bnfc_ap.a
$(BS)/lib/c100/bsem_ap.a
$(BS)/lib/c100/bsma_ap.a
$(BS)/lib/c100/bsmd_ap.a
/usr/lib/c100/libxc.a
/usr/lib/libodiC1_s.a
/usr/lib/libRCEC1.a
/usr/lib/libdbeamC1.a
/usr/lib/libscreenC1.a
/usr/lib/c100/libcfile_s.a
#endif
/usr/lib/libFS_s.a
/usr/lib/libgpipe_s.a
/usr/lib/libtools_s.a
/lib/libm.a
/usr/lib/libix.a
/usr/lib/libbsd.a
/lib/libc_s.a
#else
#if defined (IRIX)
$(BS)/lib/bnfc_sg.a
$(BS)/lib/bsem_sg.a
$(BS)/lib/bsma_sg.a
$(BS)/lib/bsmd_sg.a
/usr/lib/libm.a
$(INGRHOME)/lib/libxc.a
/usr/lib/libc_s.a
#else
$(BS)/lib/bnfc_sn5.a
$(BS)/lib/bsem_sn5.a
$(BS)/lib/bsma_sn5.a
$(BS)/lib/bsmd_sn5.a
/lib/libm.a
$(INGRHOME)/lib/libxc.a
/lib/libc.a
#endif
#endif
#if defined (CLIX)
$(INGRHOME)/ums/lib/$(CPUTYPE)/libUMS.a
#else
#if defined (INTEL)
$(INGRHOME)/ums/lib/i86pc/libUMS.a
#else
#if defined (IRIX)
$(INGRHOME)/lib/libUMS.a
#else
$(INGRHOME)/ums/lib/sun4/libUMS.a
#endif
#endif
#endif
#ifdef SUNOS
CC
cc
#else
CC
acc -knr
#endif
COPT
-ga
INCLUDE
$(INGRHOME)/include
$(GRNUC)/ingrsys
$(EXNUC)/include
$(GRNUC)/include
$(MODEL)/include
$(MODEL)/proto_include
#if defined (X11)
$(XINC)
$(XINC)/X11
#endif
#if defined (XGL)
$(XGLHOME)/include
$(XGLHOME)/include/xgl
#endif
$(INGRHOME)/ums/include
SOURCE
HPdload.c
HPglobal.c
HPimport.c
HPinit.c
HPinterp.c
HPlice_stub.c
HPmain.c
HPmessage.c
HPplot.c
HPread_ctbl.c
HPread_curv.c
HPread_soo.c
HPread_surf.c
HPreader.c
HPset.c
HPstubs.c
HPversion.c
HPx11_stub.c
