[
n_catalogname=square_bar
n_itemname='SB4x4x18.82'
n_itemrev='aluminium'
n_itemdesc=''
n_creator='nfmadmin'
n_creationdate='04/28/90'
p_parttype='P'
Height=4.000000
n_cofilename='VSmacro'
]
[
n_catalogname=square_bar
n_itemname='SB2x2x4.704'
n_itemrev='aluminium'
n_itemdesc=''
n_creator='nfmadmin'
n_creationdate='04/28/90'
p_parttype='P'
Height=2.000000
n_cofilename='VSmacro'
]
