#!/bin/ksh

# An exit value of zero (0) indicates that
# Native X is EITHER loaded OR soon to be loaded.

# An exit value of (255) indicates that
# Native X is NEITHER loaded NOR soon to be loaded.

case "$(/bin/grep "UNIXBOOT.*Native X" /usr/ip32/.defaults 2> /dev/null | cut -f3 -d#)" in

    [Yy]* ) exit 0 ;;

    [Nn]* ) exit 255 ;;

        * ) [[ -f /usr/ip32/unixboot/.X ]] && exit 0 || exit 255 ;;

esac

