/*  ARCHAIC FILE, SHARED LIBS NO LONGER BEING BUILT

#include "OMminimum.h"
#include "igrtypedef.h"
#include "igetypedef.h"
#include <stdio.h>

#ifdef RASSHLIB

#define MAgauss (*libras_MAgauss)
#define MAaddmx (*libras_MAaddmx)
#define MArtrnmx (*libras_MArtrnmx)
#define RScmyktorgb (*libras_RScmyktorgb)
#define RScmykdefmodel (*libras_RScmykdefmodel)
#define getline32 (*libras_getline32)
#define putpixelblock32 (*libras_putpixelblock32)
#define OM_Gp_NULL_MESSAGE (*libras_OM_Gp_NULL_MESSAGE)
#define GRrg$GRpylcutpaste_method_index (*libras_GRrg$GRpylcutpaste_method_index)
#define GRrg$GRputrgprops_method_index (*libras_GRrg$GRputrgprops_method_index)
#define GRraster$GRgetstdapp_method_index (*libras_GRraster$GRgetstdapp_method_index)
#define GRrspg_init (*libras_GRrspg_init)
#define COgetraspf (*libras_COgetraspf)
#define GRrg$GRlpolytcopy_method_index (*libras_GRrg$GRlpolytcopy_method_index)
#define GRrg$GRlpolycopy_method_index (*libras_GRrg$GRlpolycopy_method_index)
#define GUget_symb_level (*libras_GUget_symb_level)
#define GRadd_component_to_active_owner (*libras_GRadd_component_to_active_owner)
#define sys_write (*libras_sys_write)
#define fdopen (*libras_fdopen)
#define fflush (*libras_fflush)
#define GRpre_update (*libras_GRpre_update)
#define GRpost_update (*libras_GRpost_update)
#define RCE_open (*libras_RCE_open)
#define RCE_output_format (*libras_RCE_output_format)
#define RCE_input_format (*libras_RCE_input_format)
#define RCE_expansion_mode (*libras_RCE_expansion_mode)
#define RCE_expand (*libras_RCE_expand)
#define RCE_compress (*libras_RCE_compress)
#define RCE_compression_mode (*libras_RCE_compression_mode)
#define GUotype6 (*libras_GUotype6)
#define RSmixdismiss (*libras_RSmixdismiss)
#define GRrsmixinitdith (*libras_GRrsmixinitdith)
#define GRrg$GRiednpass_method_index (*libras_GRrg$GRiednpass_method_index)
#define GRrg$GRinvokedfunc_method_index (*libras_GRrg$GRinvokedfunc_method_index)
#define LCadd_class (*libras_LCadd_class)
#define RSgetfginfo (*libras_RSgetfginfo)
#define RSfgloadctb (*libras_RSfgloadctb)
#define RSfgputpixelblock (*libras_RSfgputpixelblock)
#define MAtlncbclip (*libras_MAtlncbclip)
#define DPset_load_vlt_ptr (*libras_DPset_load_vlt_ptr)
#define MApower (*libras_MApower)
#define Loadvlt (*libras_Loadvlt)
#define IGEreadresclr (*libras_IGEreadresclr)
#define ftruncate (*libras_ftruncate)
#define system (*libras_system)
#define GRcomprast$GRrmtempfiles_method_index (*libras_GRcomprast$GRrmtempfiles_method_index)
#define num_log_colors (*libras_num_log_colors)
#define OM_Gp_CurSpaceMap (*libras_OM_Gp_CurSpaceMap)
#define IGEcnctclrtab (*libras_IGEcnctclrtab)
#define GRraster$GRgenhdrrast_method_index (*libras_GRraster$GRgenhdrrast_method_index)
#define OPP_OMCluster_class_id (*libras_OPP_OMCluster_class_id)
#define OMCluster$init_OMCluster_method_index (*libras_OMCluster$init_OMCluster_method_index)
#define GRraster$GRdithyourself_method_index (*libras_GRraster$GRdithyourself_method_index)
#define ftell (*libras_ftell)
#define IGEmodclrtab (*libras_IGEmodclrtab)
#define GRfrastmgr$GRfrastpass_method_index (*libras_GRfrastmgr$GRfrastpass_method_index)
#define GRraster$GRcolortabchange_method_index (*libras_GRraster$GRcolortabchange_method_index)
#define GRrg$GRputfprops_method_index (*libras_GRrg$GRputfprops_method_index)
#define OPP_GRfrastmgr_class_id (*libras_OPP_GRfrastmgr_class_id)
#define GRfrastmgr$GRputcurid_method_index (*libras_GRfrastmgr$GRputcurid_method_index)
#define NULL_CHANNUM (*libras_NULL_CHANNUM)
#define OM_GA_primitives (*libras_OM_GA_primitives)
#define EX_findmod (*libras_EX_findmod)
#define EX_file_status (*libras_EX_file_status)
#define GRfrastmgr$GRgetcurid_method_index (*libras_GRfrastmgr$GRgetcurid_method_index)
#define Root$wild_disconnect_method_index (*libras_Root$wild_disconnect_method_index)
#define OPP_Root_class_id (*libras_OPP_Root_class_id)
#define OM_Gw_current_OS (*libras_OM_Gw_current_OS)
#define GRrg$GRfrwrite_method_index (*libras_GRrg$GRfrwrite_method_index)
#define OPP_GRrg_class_id (*libras_OPP_GRrg_class_id)
#define GRgraphics$GRdisyourself_method_index (*libras_GRgraphics$GRdisyourself_method_index)
#define OPP_GRgraphics_class_id (*libras_OPP_GRgraphics_class_id)
#define GRrg$GRchgrgprops_method_index (*libras_GRrg$GRchgrgprops_method_index)
#define NULL_OBJID (*libras_NULL_OBJID)
#define EX_get_oid_nodname (*libras_EX_get_oid_nodname)
#define Super_rfmgr$Super_passon_method_index (*libras_Super_rfmgr$Super_passon_method_index)
#define OPP_Super_rfmgr_class_id (*libras_OPP_Super_rfmgr_class_id)
#define GRgraphics$GRplotyourself_method_index (*libras_GRgraphics$GRplotyourself_method_index)
#define GRfrastgg$GRgetggid_method_index (*libras_GRfrastgg$GRgetggid_method_index)
#define OPP_GRfrastgg_class_id (*libras_OPP_GRfrastgg_class_id)
#define OM_GS_NULL_NEIGHBOR (*libras_OM_GS_NULL_NEIGHBOR)
#define OM_GS_NULL_MESSAGE (*libras_OM_GS_NULL_MESSAGE)
#define Root$connect_method_index (*libras_Root$connect_method_index)
#define Root$delete_method_index (*libras_Root$delete_method_index)
#define GRgraphics$GRgetprops_method_index (*libras_GRgraphics$GRgetprops_method_index)
#define OPP_GRvg_class_id (*libras_OPP_GRvg_class_id)
#define Root$disconnect_method_index (*libras_Root$disconnect_method_index)
#define GRrg$GRisfr_method_index (*libras_GRrg$GRisfr_method_index)
#define GRrg$GRgetfilnm_method_index (*libras_GRrg$GRgetfilnm_method_index)
#define strcmp (*libras_strcmp)
#define GRdpb_get (*libras_GRdpb_get)
#define IGEwinsup$pre_update_method_index (*libras_IGEwinsup$pre_update_method_index)
#define OPP_IGEwinsup_class_id (*libras_OPP_IGEwinsup_class_id)
#define IGEwinsup$post_update_method_index (*libras_IGEwinsup$post_update_method_index)
#define IGEwinsup$pre_plot_method_index (*libras_IGEwinsup$pre_plot_method_index)
#define IGEwinsup$post_plot_method_index (*libras_IGEwinsup$post_plot_method_index)
#define GRrg$GRputattline_method_index (*libras_GRrg$GRputattline_method_index)
#define GRgraphics$GRdisplay_method_index (*libras_GRgraphics$GRdisplay_method_index)
#define free (*libras_free)
#define DPdisbyoid (*libras_DPdisbyoid)
#define GRraster$GRgetrastgeom_method_index (*libras_GRraster$GRgetrastgeom_method_index)
#define OPP_GRraster_class_id (*libras_OPP_GRraster_class_id)
#define MAptsxform (*libras_MAptsxform)
#define MAlnpsproj (*libras_MAlnpsproj)
#define MAinvmx (*libras_MAinvmx)
#define MAidmx (*libras_MAidmx)
#define MAmulmx (*libras_MAmulmx)
#define GRmodule$GRmdremove_method_index (*libras_GRmodule$GRmdremove_method_index)
#define OPP_GRmodule_class_id (*libras_OPP_GRmodule_class_id)
#define GRmodule$GRmdaddwrng_method_index (*libras_GRmodule$GRmdaddwrng_method_index)
#define GRraster$GRputrastgeom_method_index (*libras_GRraster$GRputrastgeom_method_index)
#define DPelem (*libras_DPelem)
#define flushbuffer (*libras_flushbuffer)
#define pushattributes (*libras_pushattributes)
#define GRraster$GRgenrast_method_index (*libras_GRraster$GRgenrast_method_index)
#define GRvg$GRgetsymb_method_index (*libras_GRvg$GRgetsymb_method_index)
#define GRrg$GRgetdpinfo_method_index (*libras_GRrg$GRgetdpinfo_method_index)
#define dynamics_in_progress (*libras_dynamics_in_progress)
#define IGEinq_term_info (*libras_IGEinq_term_info)
#define MApyextents (*libras_MApyextents)
#define MApyfrlb (*libras_MApyfrlb)
#define popattributes (*libras_popattributes)
#define malloc (*libras_malloc)
#define GRgraphics$GRconstruct_method_index (*libras_GRgraphics$GRconstruct_method_index)
#define blkmv (*libras_blkmv)
#define GRraster$GRsetdim_method_index (*libras_GRraster$GRsetdim_method_index)
#define GRraster$GRputrast_method_index (*libras_GRraster$GRputrast_method_index)
#define OM_Gw_TransOSnum_0 (*libras_OM_Gw_TransOSnum_0)
#define fopen (*libras_fopen)
#define fclose (*libras_fclose)
#define strcpy (*libras_strcpy)
#define strcat (*libras_strcat)
#define sprintf (*libras_sprintf)
#define DPsetinqgragad (*libras_DPsetinqgragad)
#define MAtypemx (*libras_MAtypemx)
#define floor (*libras_floor)
#define BSlbs_infnc (*libras_BSlbs_infnc)
#define BSlbsincfnc (*libras_BSlbsincfnc)
#define GRgraphics$GRcopy_method_index (*libras_GRgraphics$GRcopy_method_index)
#define EX_get_modid_given_osnum (*libras_EX_get_modid_given_osnum)
#define OPP_GRlocrast_class_id (*libras_OPP_GRlocrast_class_id)
#define GRcomprast$GRputfcd_method_index (*libras_GRcomprast$GRputfcd_method_index)
#define OPP_GRcomprast_class_id (*libras_OPP_GRcomprast_class_id)
#define som_vla_set_dimension (*libras_som_vla_set_dimension)
#define OPP_GRclrast_class_id (*libras_OPP_GRclrast_class_id)
#define MA2cuberel (*libras_MA2cuberel)
#define Inq_screen_info (*libras_Inq_screen_info)
#define Inq_win_vs (*libras_Inq_win_vs)
#define hidecursor (*libras_hidecursor)
#define getline (*libras_getline)
#define printf (*libras_printf)
#define memcpy (*libras_memcpy)
#define showcursor (*libras_showcursor)
#define GRvg$GRputname_method_index (*libras_GRvg$GRputname_method_index)
#define GRvg$GRputsymb_method_index (*libras_GRvg$GRputsymb_method_index)
#define GRrg$GRchgfgbg_method_index (*libras_GRrg$GRchgfgbg_method_index)
#define GRraster$GRreadrast_method_index (*libras_GRraster$GRreadrast_method_index)
#define MAsubvc (*libras_MAsubvc)
#define MAunitvc (*libras_MAunitvc)
#define flt32_to_fltvax (*libras_flt32_to_fltvax)
#define GUwrite_element (*libras_GUwrite_element)
#define MAoptsxform (*libras_MAoptsxform)
#define GRcomprast$GRinitsubfile_method_index (*libras_GRcomprast$GRinitsubfile_method_index)
#define EX_rm (*libras_EX_rm)
#define GRcomprast$GRgetlocalclass_method_index (*libras_GRcomprast$GRgetlocalclass_method_index)
#define GRraster$GRreadsubrast_method_index (*libras_GRraster$GRreadsubrast_method_index)
#define strlen (*libras_strlen)
#define GRcomprast$GRdetsubfiles_method_index (*libras_GRcomprast$GRdetsubfiles_method_index)
#define GRcomprast$GRainitsubfile_method_index (*libras_GRcomprast$GRainitsubfile_method_index)
#define GRgraphics$GRxform_method_index (*libras_GRgraphics$GRxform_method_index)
#define GRrg$GRiputattline_method_index (*libras_GRrg$GRiputattline_method_index)
#define GRrg$GRgetattribute_method_index (*libras_GRrg$GRgetattribute_method_index)
#define GRrg$GRputattpix_method_index (*libras_GRrg$GRputattpix_method_index)
#define EX_mv (*libras_EX_mv)
#define GRgraphics$GRdelete_method_index (*libras_GRgraphics$GRdelete_method_index)
#define unlink (*libras_unlink)
#define EX_cp (*libras_EX_cp)
#define GRrg$GRputfilnm_method_index (*libras_GRrg$GRputfilnm_method_index)
#define GRvg$GRchgcolor_method_index (*libras_GRvg$GRchgcolor_method_index)
#define GRvg$GRchgdp_method_index (*libras_GRvg$GRchgdp_method_index)
#define GRvg$GRchglevel_method_index (*libras_GRvg$GRchglevel_method_index)
#define MApapromx (*libras_MApapromx)
#define GRrg$GRblcutconst_method_index (*libras_GRrg$GRblcutconst_method_index)
#define GRgraphics$GRchgprops_method_index (*libras_GRgraphics$GRchgprops_method_index)
#define GRgraphics$GRgetrang_method_index (*libras_GRgraphics$GRgetrang_method_index)
#define GRrg$GRinvokefunc_method_index (*libras_GRrg$GRinvokefunc_method_index)
#define GRgraphics$GRformatele_method_index (*libras_GRgraphics$GRformatele_method_index)
#define realloc (*libras_realloc)
#define MAsqrt (*libras_MAsqrt)
#define MAlnxform (*libras_MAlnxform)
#define MApytobc (*libras_MApytobc)
#define MAlnplisect (*libras_MAlnplisect)
#define MAptinpg (*libras_MAptinpg)
#define MAlnpyproj (*libras_MAlnpyproj)
#define MAdetplane (*libras_MAdetplane)
#define MA2ptdis (*libras_MA2ptdis)
#define fgcolor (*libras_fgcolor)
#define drawbitmap (*libras_drawbitmap)
#define putpixelblock (*libras_putpixelblock)
#define rectf (*libras_rectf)
#define enableplane (*libras_enableplane)
#define blendarea (*libras_blendarea)
#define polyf (*libras_polyf)
#define MAtrnmx (*libras_MAtrnmx)
#define fread (*libras_fread)
#define fseek (*libras_fseek)
#define fwrite (*libras_fwrite)
#define EX_get_super (*libras_EX_get_super)
#define IGEstop (*libras_IGEstop)
#define DPcolor_map (*libras_DPcolor_map)
#define OM_GA_active_classes (*libras_OM_GA_active_classes)
#define GRraster$GRaddpacket_method_index (*libras_GRraster$GRaddpacket_method_index)
#define fscanf (*libras_fscanf)
#define IGEgetabsclrindx (*libras_IGEgetabsclrindx)
#define GRraster$GRdelpacket_method_index (*libras_GRraster$GRdelpacket_method_index)
#define IGEreadclrtab (*libras_IGEreadclrtab)
#define GRraster$GRgetpacket_method_index (*libras_GRraster$GRgetpacket_method_index)
#define IGEchgclrtab (*libras_IGEchgclrtab)
#define IGEconclrtab (*libras_IGEconclrtab)
#define MA2pt2dis (*libras_MA2pt2dis)
#define GRraster$GRhistogram_method_index (*libras_GRraster$GRhistogram_method_index)
#define IGEchgresclr (*libras_IGEchgresclr)
#define OM_GA_OSDs (*libras_OM_GA_OSDs)
#define GRfrastmgr$GRgetpacket_method_index (*libras_GRfrastmgr$GRgetpacket_method_index)
#define GRfrastmgr$GRdelpacket_method_index (*libras_GRfrastmgr$GRdelpacket_method_index)
#define GRfrastmgr$GRaddpacket_method_index (*libras_GRfrastmgr$GRaddpacket_method_index)
#define IGEgetnumactcol (*libras_IGEgetnumactcol)

#endif


extern IGRboolean MAaddmx();
extern IGRboolean MAgauss();
extern IGRboolean MArtrnmx();
extern IGRboolean RScmyktorgb();
extern IGRboolean RScmykdefmodel();
extern int getline32();
extern int putpixelblock32();
extern OMuword GRrg$GRpylcutpaste_method_index;
extern OMuword GRrg$GRputrgprops_method_index;
extern OM_p_MESSAGE OM_Gp_NULL_MESSAGE;
extern OMuword GRraster$GRgetstdapp_method_index;
extern int GRrspg_init();
extern int COgetraspf();
extern OMuword GRrg$GRlpolytcopy_method_index;
extern OMuword GRrg$GRlpolycopy_method_index;
extern IGRint GUget_symb_level();
extern int GRadd_component_to_active_owner();
extern int sys_write();
extern FILE *fdopen();
extern int fflush();
extern IGRlong GRpre_update();
extern IGRlong GRpost_update();
extern int RCE_open();
extern int RCE_output_format();
extern int RCE_input_format();
extern int RCE_expansion_mode();
extern int RCE_expand();
extern int RCE_compress();
extern int RCE_compression_mode();
extern int GUotype6();
extern IGRboolean RSmixdismiss();
extern IGRboolean GRrsmixinitdith();
extern OMuword GRrg$GRiednpass_method_index;
extern OMuword GRrg$GRinvokedfunc_method_index;
extern int LCadd_class();
extern IGRboolean RSgetfginfo();
extern IGRboolean RSfgloadctb();
extern int RSfgputpixelblock();
extern IGRboolean MAtlncbclip();
extern int *DPset_load_vlt_ptr();
extern IGRdouble MApower();
extern int Loadvlt();
extern IGRint IGEreadresclr();
extern IGRint ftruncate();
extern int system();
extern OMuword GRcomprast$GRrmtempfiles_method_index;
extern IGRshort num_log_colors[2];
extern IGRshort DPcolor_map[2][512];
extern OM_p_SPAMAPENT OM_Gp_CurSpaceMap;
extern IGRint IGEcnctclrtab();
extern OMuword GRraster$GRgenhdrrast_method_index;
extern OMuword OPP_OMCluster_class_id;
extern OMuword OMCluster$init_OMCluster_method_index;
extern OMuword GRraster$GRdithyourself_method_index;
extern long ftell();
extern IGRint IGEmodclrtab();
extern OMuword GRfrastmgr$GRfrastpass_method_index;
extern OMuword GRraster$GRcolortabchange_method_index;
extern OMuword GRrg$GRputfprops_method_index;
extern OMuword OPP_GRfrastmgr_class_id;
extern OMuword GRfrastmgr$GRputcurid_method_index;
extern OM_S_CHANNUM NULL_CHANNUM;
extern int (*OM_GA_primitives[])();
extern int EX_findmod();
extern int EX_file_status();
extern OMuword GRfrastmgr$GRgetcurid_method_index;
extern OMuword Root$wild_disconnect_method_index;
extern OMuword OPP_Root_class_id;
extern OMuword OM_Gw_current_OS;
extern OMuword GRrg$GRfrwrite_method_index;
extern OMuword OPP_GRrg_class_id;
extern OMuword GRgraphics$GRdisyourself_method_index;
extern OMuword OPP_GRgraphics_class_id;
extern OMuword GRrg$GRchgrgprops_method_index;
extern OM_S_OBJID NULL_OBJID;
extern int EX_get_oid_nodname();
extern OMuword Super_rfmgr$Super_passon_method_index;
extern OMuword OPP_Super_rfmgr_class_id;
extern OMuword GRgraphics$GRplotyourself_method_index;
extern OMuword GRfrastgg$GRgetggid_method_index;
extern OMuword OPP_GRfrastgg_class_id;
extern OM_S_NEIGHBOR OM_GS_NULL_NEIGHBOR;
extern OM_S_MESSAGE OM_GS_NULL_MESSAGE;
extern OMuword Root$connect_method_index;
extern OMuword Root$delete_method_index;
extern OMuword GRgraphics$GRgetprops_method_index;
extern OMuword OPP_GRvg_class_id;
extern OMuword Root$disconnect_method_index;
extern OMuword GRrg$GRisfr_method_index;
extern OMuword GRrg$GRgetfilnm_method_index;
extern int  strcmp();
extern int GRdpb_get();
extern OMuword IGEwinsup$pre_update_method_index;
extern OMuword OPP_IGEwinsup_class_id;
extern OMuword IGEwinsup$post_update_method_index;
extern OMuword IGEwinsup$pre_plot_method_index;
extern OMuword IGEwinsup$post_plot_method_index;
extern OMuword GRrg$GRputattline_method_index;
extern OMuword GRgraphics$GRdisplay_method_index;
extern void free();
extern int DPdisbyoid();
extern OMuword GRraster$GRgetrastgeom_method_index;
extern OMuword OPP_GRraster_class_id;
extern IGRboolean MAptsxform();
extern IGRboolean MAlnpsproj();
extern IGRboolean MAinvmx();
extern IGRboolean MAidmx();
extern IGRboolean MAmulmx();
extern OMuword GRmodule$GRmdremove_method_index;
extern OMuword OPP_GRmodule_class_id;
extern OMuword GRmodule$GRmdaddwrng_method_index;
extern OMuword GRraster$GRputrastgeom_method_index;
extern int DPelem();
extern int flushbuffer();
extern int pushattributes();
extern OMuword GRraster$GRgenrast_method_index;
extern OMuword GRvg$GRgetsymb_method_index;
extern OMuword GRrg$GRgetdpinfo_method_index;
extern IGRboolean dynamics_in_progress;
extern void IGEinq_term_info();
extern IGRboolean MApyextents();
extern IGRboolean MApyfrlb();
extern int popattributes();
extern char *malloc();
extern OMuword GRgraphics$GRconstruct_method_index;
extern int blkmv();
extern OMuword GRraster$GRsetdim_method_index;
extern OMuword GRraster$GRputrast_method_index;
extern OMuword OM_Gw_TransOSnum_0;
extern FILE *fopen();
extern int fclose();
extern char *strcpy();
extern char *strcat();
extern int sprintf();
extern int DPsetinqgragad();
extern IGRboolean MAtypemx();
extern double floor();
extern void BSlbs_infnc();
extern void BSlbsincfnc();
extern OMuword GRgraphics$GRcopy_method_index;
extern int EX_get_modid_given_osnum();
extern OMuword OPP_GRlocrast_class_id;
extern OMuword GRcomprast$GRputfcd_method_index;
extern OMuword OPP_GRcomprast_class_id;
extern int som_vla_set_dimension();
extern OMuword OPP_GRclrast_class_id;
extern IGRboolean MA2cuberel();
extern int Inq_screen_info();
extern int Inq_win_vs();
extern int hidecursor();
extern int getline();
extern int printf();
extern char *memcpy();
extern int showcursor();
extern OMuword GRvg$GRputname_method_index;
extern OMuword GRvg$GRputsymb_method_index;
extern OMuword GRrg$GRchgfgbg_method_index;
extern OMuword GRraster$GRreadrast_method_index;
extern IGRboolean MAsubvc();
extern IGRboolean MAunitvc();
extern int flt32_to_fltvax();
extern IGRlong GUwrite_element();
extern IGRboolean MAoptsxform();
extern OMuword GRcomprast$GRinitsubfile_method_index;
extern int EX_rm();
extern OMuword GRcomprast$GRgetlocalclass_method_index;
extern OMuword GRraster$GRreadsubrast_method_index;
extern int  strlen();
extern OMuword GRcomprast$GRdetsubfiles_method_index;
extern OMuword GRcomprast$GRainitsubfile_method_index;
extern OMuword GRgraphics$GRxform_method_index;
extern OMuword GRrg$GRiputattline_method_index;
extern OMuword GRrg$GRgetattribute_method_index;
extern OMuword GRrg$GRputattpix_method_index;
extern int EX_mv();
extern OMuword GRgraphics$GRdelete_method_index;
extern int unlink();
extern int EX_cp();
extern OMuword GRrg$GRputfilnm_method_index;
extern OMuword GRvg$GRchgcolor_method_index;
extern OMuword GRvg$GRchgdp_method_index;
extern OMuword GRvg$GRchglevel_method_index;
extern IGRboolean MApapromx();
extern OMuword GRrg$GRblcutconst_method_index;
extern OMuword GRgraphics$GRchgprops_method_index;
extern OMuword GRgraphics$GRgetrang_method_index;
extern OMuword GRrg$GRinvokefunc_method_index;
extern OMuword GRgraphics$GRformatele_method_index;
extern char	*realloc();
extern IGRdouble MAsqrt();
extern IGRboolean MAlnxform();
extern IGRboolean MApytobc();
extern IGRboolean MAlnplisect();
extern IGRboolean MAptinpg();
extern IGRboolean MAlnpyproj();
extern IGRboolean MAdetplane();
extern IGRboolean MA2ptdis();
extern int fgcolor();
extern int drawbitmap();
extern int putpixelblock();
extern int rectf();
extern int enableplane();
extern int blendarea();
extern int polyf();
extern IGRboolean MAtrnmx();
extern int fread();
extern int fseek();
extern int fwrite();
extern int EX_get_super();
extern int IGEstop();
extern OM_p_CLASSDEF *OM_GA_active_classes;
extern OMuword GRraster$GRaddpacket_method_index;
extern int fscanf();
extern int IGEgetabsclrindx();
extern OMuword GRraster$GRdelpacket_method_index;
extern int IGEreadclrtab();
extern OMuword GRraster$GRgetpacket_method_index;
extern int IGEchgclrtab();
extern int IGEconclrtab();
extern IGRboolean MA2pt2dis();
extern OMuword GRraster$GRhistogram_method_index;
extern int IGEchgresclr();
extern OM_p_OSD *OM_GA_OSDs;
extern OMuword GRfrastmgr$GRgetpacket_method_index;
extern OMuword GRfrastmgr$GRdelpacket_method_index;
extern OMuword GRfrastmgr$GRaddpacket_method_index;
extern int IGEgetnumactcol();

*/
