#define PROJECT_FIELD     12
#define PROJECT_TOGGLE    38
#define PROJECT_POPUP     41
#define CATALOG_FIELD     15
#define CATALOG_POPUP     42
#define ITEM_TEXT         19
#define ITEM_FIELD        16
#define ITEM_POPUP        43
#define REVISION_FIELD    21  
#define REVISION_POPUP    44
#define SEARCH_FIELD      33
#define SEARCH_TOGGLE     14
#define SEARCH_POPUP      45
#define SORT_FIELD        34
#define SORT_TOGGLE       22
#define SORT_POPUP        46
#define WA_FIELD          26
#define WA_POPUP          48
#define SA_FIELD          27
#define SA_POPUP          31
#define NODE_FIELD        32
#define NODE_POPUP        40
#define USER_FIELD        47
#define USER_POPUP        52
#define WF_FIELD          53
#define WF_POPUP          55
#define ACL_FIELD         56
#define ACL_POPUP         58
#define COLLAPSE_BUTTON    2
