/***************************************************************************

  This header file contains the command key definitions that are
  stored in the PANEL_MENU and BAR_MENU.

  The "standard" convention for building command keys is as follows:

    The command key can be no longer than 10 characters in total
    length.

    The first two characters denote the product, e.g., "NF".  This
    guarantees uniqueness with other workstation products.

    The verb and each significant noun in the command string is
    abbreviated with the first letter capitalized and all other
    letters are lower-case.

    Each key MUST be unique within the product.

  NOTE:  It is important to note that the use of command keys is
         supported in various software systems in generating
         documentation and on-line help.  Any changes to the command
         key definitions in either the PANEL_MENU or BAR_MENU outline
         files MUST be reflected in this header file AND the appropriate
         person(s) generating documentation and building the help files
         be notified.

****************************************************************************/

#define NFI_M_DISPLAY_NODES                      "NFDsLsNd"
#define NFI_M_ADD_NODE                           "NFAdNd"
#define NFI_M_CHANGE_NODE                        "NFChNd"
#define NFI_M_DELETE_NODE                        "NFDlNd"
#define NFI_M_DISPLAY_SA                         "NFDsLsStAr"
#define NFI_M_DISPLAY_WA_ADMIN                   "NFDsWkAr_A"
#define NFI_M_DISPLAY_WA_USER                    "NFDsWkAr_U"
#define NFI_M_ADD_SA                             "NFAdStAr"
#define NFI_M_CHANGE_SA                          "NFChStAr"
#define NFI_M_CHANGE_SA_PASSWD                   "NFChStArPw"
#define NFI_M_DELETE_SA                          "NFDlStAr"
#define NFI_M_DISPLAY_COPIED_ITEMS_SA            "NFDsCpItLs"
#define NFI_M_REMOVE_COPIED_ITEMS_SA             "NFRmCpIt"
#define NFI_M_DISPLAY_USERS                      "NFDsLsUs"
#define NFI_M_ADD_USER                           "NFAdUs"
#define NFI_M_CHANGE_USER                        "NFChUs"
#define NFI_M_CHANGE_USER_PASSWD                 "NFChUsPw"
#define NFI_M_DELETE_USER                        "NFDlUs"
#define NFI_M_DEFINE_USER_DEFAULTS               "NFDfUsDf"
#define NFI_M_DISPLAY_ACLS                       "NFLsAcCnLs"
#define NFI_M_REVIEW_ACL                         "NFRvAcCnLs"
#define NFI_M_DEFINE_ACL                         "NFDfAcCnLs"
#define NFI_M_CHANGE_ACL                         "NFChAcCnLs"
#define NFI_M_DELETE_ACL                         "NFDlAcCnLs"
#define NFI_M_DISPLAY_CATALOGS                   "NFDsLsCt"
#define NFI_M_CREATE_CATALOG                     "NFCrCt"
#define NFI_M_CHANGE_CATALOG                     "NFChCt"
#define NFI_M_DELETE_CATALOG                     "NFDlCt"
#define NFI_M_ADD_CATALOG_ACL_MAPPING            "NFAdCtMp"
#define NFI_M_DELETE_CATALOG_ACL_MAPPING         "NFADlCtMp"
#define NFI_M_ADD_CATALOG_SA_MAPPING             "NFAdCtSAMp"
#define NFI_M_DELETE_CATALOG_SA_MAPPING          "NFDlCtSAMp"
#define NFI_M_FLAG_CATALOG_FILES_BACKUP          "NFFgCtFlBk"
#define NFI_M_FLAG_CATALOG_FILES_RESTORE         "NFFgCtFlRs"
#define NFI_M_CANCEL_FLAG_CATALOG_FILES          "NFCnFgCtFl"
#define NFI_M_PURGE_FILES_IN_CATALOG             "NFPgFlCt"
#define NFI_M_DISPLAY_SEARCH_CRITERIA            "NFDsLsSrCr"
#define NFI_M_DEFINE_SEARCH_CRITERIA             "NFDfSrCr"
#define NFI_M_DELETE_SEARCH_CRITERIA             "NFDlSrCr"
#define NFI_M_DISPLAY_SORT_CRITERIA              "NFLsSrtCr"
#define NFI_M_DEFINE_SORT_CRITERIA               "NFDfSrtCr"
#define NFI_M_DELETE_SORT_CRITERIA               "NFDlSrtCr"
#define NFI_M_DISPLAY_FILES_FLAGGED_ARCHIVE      "NFLsFlFgAr"
#define NFI_M_ARCHIVE_FLAGGED_FILES              "NFArFgFl"
#define NFI_M_DISPLAY_FILES_FLAGGED_BACKUP       "NFLsFlFgBk"
#define NFI_M_BACKUP_FLAGGED_FILES               "NFBkFgFl"
#define NFI_M_DISPLAY_FILES_FLAGGED_RESTORE      "NFLsFlFgRs"
#define NFI_M_RESTORE_FLAGGED_FILES              "NFRsFgFl"
#define NFI_M_DISPLAY_FILES_FLAGGED_DELETE       "NFLsFlFgDl"
#define NFI_M_DELETE_FLAGGED_FILES               "NFDlFgFl"
#define NFI_M_CHANGE_ITEM_FILE_TO_RESTORED       "NFChItFlRs"
#define NFI_M_DISPLAY_COPIED_FILES               "NFDsLsCpFl"
#define NFI_M_REMOVE_COPIED_FILES                "NFRmCpFl"
#define NFI_M_DEFINE_DEBUG_MODE                  "NFDfDbMd"
#define NFI_M_DISPLAY_WFS                        "NFDsLsWkFw"
#define NFI_M_DISPLAY_PROJECTS                   "NFDsLsPj"
#define NFI_M_DISPLAY_ITEMS_IN_PROJECT           "NFDsLsItPj"
#define NFI_M_ADD_PROJECT                        "NFAdPj"
#define NFI_M_DELETE_PROJECT                     "NFDlPj"
#define NFI_M_ADD_ITEMS_TO_PROJECT               "NFAdItPj"
#define NFI_M_DELETE_ITEMS_FROM_PROJECT          "NFDlItPj"
#define NFI_M_DEFINE_PROJECT_MEMBERS             "NFDfPjMm"
#define NFI_M_ADD_PROJECT_ACL_MAPPING            "NFAdPjACMp"
#define NFI_M_DELETE_PROJECT_ACL_MAPPING         "NFDlPjACMp"
#define NFI_M_ADD_PROJECT_SA_MAPPING             "NFAdPjSAMp"
#define NFI_M_DELETE_PROJECT_SA_MAPPING          "NFDlPjSAMp"
#define NFI_M_FLAG_PROJECT_FILES_ARCHIVE         "NFFgPjFlAr"
#define NFI_M_FLAG_PROJECT_FILES_BACKUP          "NFFgPjFlBk"
#define NFI_M_FLAG_PROJECT_FILES_RESTORE         "NFFgPjFlRs"
#define NFI_M_CANCEL_ARCHIVE_FLAG_PROJECT        "NFCnFgPjAr"
#define NFI_M_CANCEL_BACKUP_FLAG_PROJECT         "NFCnFgPjBk"
#define NFI_M_CANCEL_RESTORE_FLAG_PROJECT        "NFCnFgPjRs"
#define NFI_M_DISPLAY_ITEMS                      "NFDsLsIt"
#define NFI_M_REVIEW_ITEM_ATTRIBUTES             "NFRvItAt"
#define NFI_M_DISPLAY_FILES_IN_ITEM              "NFDsLsFlIt"
#define NFI_M_DISPLAY_WHERE_ITEM_USED_SET        "NFDsWItUSt"
#define NFI_M_DISPLAY_WHERE_ITEM_USED_PROJECT    "NFDsWItUPj"
#define NFI_M_ADD_ITEM                           "NFAdIt"
#define NFI_M_CHANGE_ITEM                        "NFChIt"
#define NFI_M_DELETE_ITEM                        "NFDlIt"
#define NFI_M_LOCK_ITEM                          "NFLkIt"
#define NFI_M_UNLOCK_ITEM                        "NFUnlkIt"
#define NFI_M_CHECK_IN                           "NFCkInIt"
#define NFI_M_CHECK_OUT                          "NFCkOtIt"
#define NFI_M_COPY_ITEM                          "NFCpIt"
#define NFI_M_CANCEL_CHECK_OUT                   "NFCnItCkOt"
#define NFI_M_PURGE_FILES_ITEM                   "NFPrgFlIt"
#define NFI_M_FLAG_ARCHIVE                       "NFFgItFlAr"
#define NFI_M_FLAG_BACKUP                        "NFFgItFlBk"
#define NFI_M_FLAG_RESTORE                       "NFFgItFlRs"
#define NFI_M_FLAG_DELETE                        "NFFgItFlDl"
#define NFI_M_MAKE_ITEM_TRANSITION               "NFMkItTr"
#define NFI_M_SIGNOFF_ITEM                       "NFSnOfIt"
#define NFI_M_DISPLAY_SET_MEMBERS                "NFDsLsStMm"
#define NFI_M_ADD_ITEMS_TO_SET                   "NFAdItSt"
#define NFI_M_DELETE_ITEMS_FROM_SET              "NFDlItSt"
#define NFI_M_DEFINE_SET_MEMBERS                 "NFDfStMm"
#define NFI_M_DELETE_SET_MEMBERS                 "NFDlSTMm"
#define NFI_M_DISPLAY_DEFAULTS                   "NFDsDef"
#define NFI_M_DEFINE_DEFAULTS                    "NFDfDef"
#define NFI_M_CHANGE_PASSWD                      "NFChPswd"
#define NFI_M_CONNECT_TO_SERVER                  "NFCnnSvr"
#define NFI_M_DISCONNECT_FROM_SERVER             "NFDscnSvr"
#define NFI_M_LOGIN_TO_ENVIRONMENT               "NFLgIEnv"
#define NFI_M_LOGOUT_FROM_ENVIRONMENT            "NFLgOEnv"
#define NFI_M_DISPLAY_COPIED_FILES_USER          "NFLsCpUsFl"
#define NFI_M_REMOVE_COPIED_FILES_USER           "NFRmCpUsFl"

/*  Commands that are selected only from the persistent form.
    These need not be only 10 characters long as they are
    not stored in either outline file.                         */

#define NFI_M_DISPLAY_CATALOGS_SHORT             "NFDsLsCtS"
#define NFI_M_DISPLAY_ITEMS_SHORT                "NFDsLsItS"
#define NFI_M_DISPLAY_SETS_SHORT                 "NFDsLsStS"
#define NFI_M_DISPLAY_REVISIONS_SHORT            "NFDsLsItRevS"
#define NFI_M_DISPLAY_SA_SHORT                   "NFDsLsStArS"
#define NFI_M_DISPLAY_PROJECTS_SHORT             "NFDsLsPjS"
#define NFI_M_DISPLAY_SEARCH_CRITERIA_SHORT      "NFDsLsSrCrS"
#define NFI_M_DISPLAY_SORT_CRITERIA_SHORT        "NFLsSrtCrS"
#define NFI_M_DISPLAY_REPORTS_SHORT              "NFDsLsRpS"

/*  Commands that exist only on the BAR_MENU  */

#define NFI_M_HELP                               "NFHlp"
#define NFI_M_EXIT                               "NFExt"

/*  Commands that have been recently added  */

#define NFI_M_DISPLAY_CATALOG_ACL_MAPPING        "NFDsCtACMp"
#define NFI_M_DISPLAY_CATALOG_SA_MAPPING         "NFDsCtSAMp"
#define NFI_M_DISPLAY_PROJECT_ACL_MAPPING        "NFDsPjACMp"
#define NFI_M_DISPLAY_PROJECT_SA_MAPPING         "NFDsPjSAMp"
#define NFI_M_CHANGE_PROJECT                     "NFChPj"
#define NFI_M_CANCEL_ARCHIVE_FLAG                "NFCnArFlIt"
#define NFI_M_CANCEL_BACKUP_FLAG                 "NFCnBkFlIt"
#define NFI_M_CANCEL_DELETE_FLAG                 "NFCnDlFlIt"
#define NFI_M_CANCEL_RESTORE_FLAG                "NFCnRsFlIt"
#define NFI_M_ADD_ACL_CLASS_USERS                "NFAdACClUs"
#define NFI_M_ADD_ACL_CLASS_USERS_DEFINE         "NFAdACClUsD"
#define NFI_M_DELETE_ACL_CLASS_USERS             "NFDlACClUs"
#define NFI_M_ADD_ACL_SIGNOFF_USERS              "NFAdACSnUs"
#define NFI_M_DELETE_ACL_SIGNOFF_USERS           "NFDlACSnUs"
#define NFI_M_RETRIEVE_DEFAULT_DATA              "NFRtDfADt"
#define NFI_M_BEGIN_RECORD_SESSION               "NFBgnRcrd"
#define NFI_M_END_RECORD_SESSION                 "NFEndRcrd"
#define NFI_M_BEGIN_PLAYBACK_SESSION             "NFBgnPlbk"
#define NFI_M_LIST_SIGNOFF_ITEM                  "NFDsLsSoIt"
#define NFI_M_LIST_SIGNOFF_HISTORY               "NFDsSnHist"
#define NFI_M_PURGE_SIGNOFF                      "NFPurSgnof"
#define NFI_M_ADD_UTIL_SA                        "NFAdUtStAr"
#define NFI_M_DISPLAY_ACL_CLASS_USERS            "NFDACLClUs"
#define NFI_M_DISPLAY_ACL_SO_USERS               "NFDACLSoUs"
#define NFI_M_DISPLAY_CATALOGS_ALL               "NFDsLsCtAl"
#define NFI_M_DISPLAY_ITEMS_ALL                  "NFDsLsItAL"
#define NFI_M_ADD_ITEM_FILES                     "NFAdFlIt"
#define NFI_M_DELETE_ITEM_FILES                  "NFDlFlIt"
#define NFI_M_COPY_ITEM_FILES                    "NFCpFl"
#define NFI_M_DISPLAY_LOCAL_FILES                "NFDsLcFl"
#define NFI_M_DISPLAY_SAVESETS                   "NFDsLsSv"
#define NFI_M_DISPLAY_ARCHIVES                   "NFDsLsAr"
#define NFI_M_CLEAR_SAVESET                      "NFClrSv"
#define NFI_M_PROCESS_FLAGGED_FILES              "NFPrFgFl"
#define NFI_M_DISPLAY_ITEMS_ON_TAPE              "NFDsLsItTp"
#define NFI_M_CHANGE_WF_OF_ITEM                  "NFChWfIt"
#define NFI_M_PURGE_FILE_VERSION                 "NFPrFlVr"
#define NFI_M_ROLL_VERSION_FORWARD               "NFRlFlVrF"
#define NFI_M_CHANGE_FILE_ATTRIBUTES             "NFChFlAt"
#define NFI_M_DELETE_COPIED_FILES                "NFDlCpFl"
#define NFI_M_FLAG_SET_ITEM_FOR_BACKUP           "NFFgStFlBk"
#define NFI_M_CHANGE_WA_PASSWD                   "NFChWkArPw"
#define NFI_M_CHECK_IN_SET_ITEM                  "NFCkInSt"
#define NFI_M_CHECK_OUT_SET_ITEM                 "NFCkOtSt"
#define NFI_M_CANCEL_SET_ITEM_CHECK_OUT          "NFCnStCkOt"
#define NFI_M_COPY_SET_ITEM_FILES                "NFCpSt"
#define NFI_M_CAN_SET_ITEM_BACKUP_FLAG           "NFCnBkFlSt"
#define NFI_M_CHANGE_WORKFLOW_OF_ITEM            "NFChWfIt"
#define NFI_M_PLOT_ITEM                          "NFPltItm"
#define NFI_M_PLOT_SET_PARENT                    "NFPltStP"
#define NFI_M_DELETE_LABEL                       "NFDlLbl"
#define NFI_M_SAVE_ITEM                          "NFSvItm"
#define NFI_M_SAVE_SET_PARENT                    "NFSvStP"
#define NFI_M_COPY_ACL_USERS                     "NFCpAcCnLs"
#define NFI_M_DELETE_TAPE_LABELS                 "NFDlTpLbs"
