#define  NFM_DEBUG                   5
#define  NFM_ALL_DEBUG		     7
#define  NFM_INITIALIZE              10
#define  NFM_QUERY_LOGIN             15
#define  NFM_LOGIN                   20
#define  NFM_LOGOUT		     25
#define  NFM_QUERY_ADD_NODE          35
#define  NFM_ADD_NODE                40
#define  NFM_COPY_NODE               50
#define  NFM_DELETE_NODE             60
#define  NFM_QUERY_CHANGE_NODE_ATTR  65
#define  NFM_CHANGE_NODE             66

#define  NFM_QUERY_ADD_SA            75
#define  NFM_ADD_SA                  80
#define  NFM_DELETE_SA               90
#define  NFM_CHANGE_SA_PASSWD        100
#define  NFM_CHANGE_WA_PASSWD        103
#define  NFM_QUERY_CHANGE_SA_ATTR    105
#define  NFM_CHANGE_SA               106

#define  NFM_QUERY_ADD_USER          115
#define  NFM_ADD_USER                120
#define  NFM_DELETE_USER             130
#define  NFM_QUERY_CHANGE_USER_ATTR  135
#define  NFM_CHANGE_USER             136

#define  NFM_CHANGE_LOC_TABLE        140
#define  NFM_CHANGE_SET_TABLE        150
#define  NFM_CHECK_OUT_APPR_1        160
#define  NFM_CHECK_IN_APPR_1         170
#define  NFM_CHECK_IN_APPR_1_REJ     180
#define  NFM_CHECK_IN_APPR_1_COMP    190
#define  NFM_CHECK_OUT_APPR_2        200
#define  NFM_CHECK_IN_APPR_2         210
#define  NFM_CHECK_IN_APPR_2_REJ     220
#define  NFM_CHECK_IN_APPR_2_COMP    230
#define  NFM_CHANGE_USER_PASSWD      260
#define  NFM_QUERY_USER_DEFAULTS     265
#define  NFM_UPDATE_USER_DEFAULTS    270
#define  NFM_CREATE_CATALOG          290
#define  NFM_DELETE_CATALOG          300
#define  NFM_CHANGE_CATALOG          310
#define  NFM_CREATE_TABLE            330
#define  NFM_DELETE_TABLE            340
#define  NFM_CHANGE_TABLE            350
#define  NFM_QUERY_ADD_SET           375
#define  NFM_ADD_SET                 380
#define  NFM_PLOT_SET                390
#define  NFM_ADD_MEMBERS             400
#define  NFM_DELETE_MEMBER           410
#define  NFM_QUERY_SET_MEMBERS       415
#define  NFM_QRY_SET_MEMBERS	     418
#define  NFM_UPDATE_SET_MEMBERS      416
#define  NFM_UPDATE_SET_TREE         417
#define  NFM_CHECK_SET_IN            420
#define  NFM_CHECK_SET_OUT           430
#define  NFM_COPY_SET                440
#define  NFM_FLAG_SET_ARCHIVE        450
#define  NFM_FLAG_SET_BACKUP         460
#define  NFM_FLAG_SET_RESTORE        470
#define  NFM_CANCEL_SET_ARCHIVE_FLAG 480
#define  NFM_CANCEL_SET_BACKUP_FLAG  490
#define  NFM_CANCEL_SET_RESTORE_FLAG 500
#define  NFM_CANCEL_SET_FLAG	     510
#define  NFM_SELECT_SEARCH           530
#define  NFM_DEFINE_SEARCH           540
#define  NFM_QUERY_ADD_ITEM          545
#define  NFM_ADD_ITEM                550
#define  NFM_REVIEW_ITEM             560
#define  NFM_REVIEW_ITEM_STATE       570
#define  NFM_CHECK_OUT               580
#define  NFM_CHECK_IN                590
#define  NFM_CHECK_IN_COMP           600
#define  NFM_COPY_ITEM               610
#define  NFM_CHANGE_WF_ITEM	     612
#define  NFM_PREPARE_UPDATE_ITEM     615
#define  NFM_UPDATE_ITEM             620
#define  NFM_CANCEL_UPDATE_ITEM      625
#define  NFM_DELETE_ITEM             630
#define  NFM_QUERY_FLAG_ARCHIVE      632
#define  NFM_QUERY_FLAG_BACKUP       634
#define  NFM_QUERY_FLAG_RESTORE      636
#define  NFM_QUERY_FLAG_DELETE       638
#define  NFM_FLAG_ITEM_ARCHIVE       640
#define  NFM_FLAG_ITEM_BACKUP        650
#define  NFM_FLAG_ITEM_RESTORE       660
#define  NFM_FLAG_ITEM_DELETE        670
#define  NFM_QUERY_CANCEL_ARCHIVE    672
#define  NFM_QUERY_CANCEL_BACKUP     674
#define  NFM_QUERY_CANCEL_RESTORE    676
#define  NFM_QUERY_CANCEL_DELETE     678
#define  NFM_CANCEL_ITEM_ARCHIVE_FLAG 680
#define  NFM_CANCEL_ITEM_BACKUP_FLAG  681
#define  NFM_CANCEL_ITEM_RESTORE_FLAG 683
#define  NFM_CANCEL_ITEM_DELETE_FLAG  685
#define  NFM_CANCEL_ITEM_FLAG         687
#define  NFM_PLOT_ITEM		     710
#define  NFM_LOCK_ITEM               720
#define  NFM_UNLOCK_ITEM             730
#define  NFM_QUERY_ITEM_VERSIONS     731
#define  NFM_PURGE_VERSIONS 	     732
#define  NFM_ROLL_VERSION_FORWARD    733
#define  NFM_QUERY_PENDING_FLAGS     735
#define  NFM_ARCHIVE_LIST            740
#define  NFM_ARCHIVE                 750
#define  NFM_ARCHIVE_FILE            760
#define  NFM_BACKUP_LIST             770
#define  NFM_BACKUP                  780
#define  NFM_BACKUP_FILE             790
#define  NFM_RESTORE_LIST            800
#define  NFM_RESTORE                 810
#define  NFM_RESTORE_FILE            820
#define  NFM_DELETE_LIST             830
#define  NFM_UTIL_DELETE             840
#define  NFM_DEL_FILES               850
#define  NFM_UTILITIES_UPDATE        855
#define  NFM_UTILITIES_ERROR         856
#define  NFM_QUERY_SAVESETS	     860
#define  NFM_QUERY_ARCHIVES          870
#define  NFM_DELETE_SAVESETS         930
#define  NFM_DELETE_ARCHIVES         932
#define  NFM_MAINTAIN_LABELS         940
#define  NFM_MAINTAIN_FLAGS          950
#define  NFM_LIST_ARCHIVES	     952
#define  NFM_LIST_SAVESETS	     954
#define  NFM_LIST_ITEMS_ON_TAPE	     956
#define  NFM_QUERY_TABLE_TEMP        960
#define  NFM_QUERY_TABLE_DEF         970
#define  NFM_QUERY_TABLE_ATTR        980
#define  NFM_QUERY_TABLE_INFO        985
#define  NFM_QUERY_LOC_DEF           990
#define  NFM_QUERY_ADDTO_LOC_ATTR    1000
#define  NFM_QUERY_CHANGE_LOC_ATTR   1005
#define  NFM_QUERY_LOP_DEF           1010
#define  NFM_QUERY_LOP_ATTR          1020
#define  NFM_QUERY_ADDTO_LOP_ATTR    1021
#define  NFM_QUERY_CHANGE_LOP_ATTR   1022
#define  NFM_QUERY_CIT_DEF           1025
#define  NFM_QUERY_CIT_ATTR          1026
#define  NFM_QUERY_TEMP_DEF          1030
#define  NFM_QUERY_TEMP_ATTR         1040
#define  NFM_QUERY_TEMP_INFO         1045
#define  NFM_QUERY_CATALOG_TEMP      1050
#define  NFM_QUERY_CATALOG_TEMP_N    1051
#define  NFM_QUERY_CATALOG_DEF       1060
#define  NFM_QUERY_CATALOG_ATTR      1070
#define  NFM_QUERY_CATALOG_INFO      1075
#define  NFM_CREATE_TEMPLATE         1080
#define  NFM_DELETE_TEMPLATE         1085
#define  NFM_QUERY_CHANGE_TABLE_ATTR 1090
#define  NFM_QUERY_CHANGE_CATALOG_ATTR  1100
#define  NFM_QUERY_CHANGE_TEMP_ATTR  1110
#define  NFM_CHANGE_TEMPLATE         1120
#define  NFM_RESET_ARCHIVE_FLAG      1160
#define  NFM_RESET_RESTORE_FLAG      1170
#define  NFM_CREATE_CAT_BUFFERS      1180
#define  NFM_CHANGE_CAT_BUFFERS      1190
#define  NFM_ADD_PROJECT             1200
#define  NFM_DELETE_PROJECT          1210
#define  NFM_CHANGE_PROJECT          1215
#define  NFM_FLAG_PROJECT_ARCHIVE    1240
#define  NFM_FLAG_PROJECT_BACKUP     1250
#define  NFM_FLAG_PROJECT_RESTORE    1260
#define  NFM_CANCEL_PROJECT_ARCHIVE  1265
#define  NFM_CANCEL_PROJECT_BACKUP   1270
#define  NFM_CANCEL_PROJECT_RESTORE  1280
#define  NFM_CANCEL_PROJECT_FLAG     1290
#define  NFM_CVT_TO_SET_ITEM         1300
#define  NFM_CVT_TO_ITEM             1310
#define  NFM_PREPARE_ITEM_CHECKIN    1320
#define  NFM_CANCEL_ITEM_CHECKIN     1330
#define  NFM_COMPLETE_ITEM_CHECKIN   1340
#define  NFM_PREPARE_ITEM_CHECKOUT   1350
#define  NFM_CANCEL_ITEM_CHECKOUT    1360
#define  NFM_COMPLETE_ITEM_CHECKOUT  1370
#define  NFM_PREPARE_ITEM_COPY       1380
#define  NFM_CANCEL_ITEM_COPY        1390
#define  NFM_COMPLETE_ITEM_COPY      1400
#define  NFM_PREPARE_SET_CHECKIN     1410
#define  NFM_CANCEL_SET_CHECKIN      1420
#define  NFM_COMPLETE_SET_CHECKIN    1430
#define  NFM_PREPARE_SET_CHECKOUT    1440
#define  NFM_CANCEL_SET_CHECKOUT     1450
#define  NFM_COMPLETE_SET_CHECKOUT   1460
#define  NFM_PREPARE_SET_COPY        1470
#define  NFM_CANCEL_SET_COPY         1480
#define  NFM_COMPLETE_SET_COPY       1490
#define  NFM_QUERY_ITEM_ATTR         1500
#define  NFM_CONVERT_TO_ITEM         1510
#define  NFM_CONVERT_TO_SET          1520
#define  NFM_CANCEL_CHECK_OUT_SET    1521
#define  NFM_CANCEL_CHECKOUT_SET     1522
#define  NFM_CANCEL_CHECKOUT_ITEM    1524
#define  NFM_CANCEL_CHECK_OUT_ITEM   1525
#define  NFM_LIST_ITEMS_SHORT	     1526

#define  NFM_GET_TABLE_NO            1530
#define  NFM_GET_TABLE_NAME          1540
#define  NFM_ATTR_INFO               1550
#define  NFM_GET_ATTR_VALUE          1560
#define  NFM_GET_PROGRAM_NO          1570
#define  NFM_GET_PROGRAM_NAME        1580
#define  NFM_GET_REPORT_NO           1590
#define  NFM_GET_NODE_NO             1600
#define  NFM_GET_NODE_NAME           1610
#define  NFM_GET_SA_NO               1620
#define  NFM_GET_SA_NAME             1630
#define  NFM_GET_SA_NO_INFO          1640
#define  NFM_GET_SA_NO_BUFFER        1650
#define  NFM_GET_USER_NO             1660
#define  NFM_GET_USER_NAME           1670
#define  NFM_GET_CATALOG_NO          1680
#define  NFM_GET_CATALOG_NAME        1690
#define  NFM_GET_PROJECT_NO          1700
#define  NFM_GET_PROJECT_NAME        1710
#define  NFM_GET_ITEM_NO             1720
#define  NFM_GET_ITEM_NAME           1730
#define  NFM_GET_KEYWORDS_FOR_FILES  1732
#define  NFM_CHECK_CO_STATUS         1740
#define  NFM_CHECK_ARCHIVE_STATE     1750
#define  NFM_CHECK_PENDING_FLAG      1760
#define  NFM_CHECK_SET_INDICATOR     1770

#define  NFM_QUERY_PROJ_ACL_MAP      1780
#define  NFM_UPDATE_PROJ_ACL_MAP     1790
#define  NFM_QUERY_PROJ_SA_MAP       1800
#define  NFM_UPDATE_PROJ_SA_MAP      1810
#define  NFM_QUERY_PROJ_MEM          1820
#define  NFM_QRY_PROJ_MEM	     1822
#define  NFM_UPDATE_PROJ_MEM         1830
#define  NFM_QUERY_ITEMS_FOR_PROJ    1835
#define  NFM_QUERY_CAT_ACL_MAP       1840
#define  NFM_UPDATE_CAT_ACL_MAP      1850
#define  NFM_QUERY_CAT_SA_MAP        1860
#define  NFM_UPDATE_CAT_SA_MAP       1870
#define  NFM_VALIDATE_INFO           1880
#define  NFM_GET_USER_DEFAULTS	     1890
#define  NFM_READ_USER_DEFAULTS      1892
#define  NFM_WRITE_USER_DEFAULTS     1894
#define  NFM_SET_USER_DEFAULTS	     1900
#define  NFM_SQL_QUERY		     1910
#define  NFM_SQL_QUERY_PARTIAL	     1915
#define  NFM_SQL_QUERY_MULTIPLE	     1916
#define  NFM_SQL_STMT		     1920
#define  NFM_ADD_DEFAULT_WA	     1921
#define  NFM_GET_BULK_DATA	     1950
#define  NFM_GET_ITEM_VERSIONS	     1952
#define  NFM_CLIENT_INFO             1960
#define  NFM_DEFINE_QUERY	     1962
#define  NFM_DEFINE_FTR_QUERY        1963
#define  NFM_DELETE_QUERY	     1964
#define  NFM_DELETE_FTR_QUERY        1965
#define  NFM_SEARCH_ACROSS_CATALOGS  1968
#define  NFM_BLOCK_SEARCH_ACROSS_CATALOGS  1970
#define  NFM_FTR_SEARCH              1972
#define  NFM_GET_FTR_HIGHLIGHT       1974
#define  NFM_GET_THESAURUS           1976
#define  NFM_GET_MEMBERS	     1978
#define  NFM_GET_VERDVEAL	     1979
#define  NFM_GET_PREVIEW             1980
#define  NFM_LFM_INFORMATION	     1982
#define  NFM_LFM_UPDATE		     1984
#define  NFM_LOG_IN		     1986
#define  NFM_RETRIEVE_FTR_QUERY_INFO 1994
#define  NFM_RETRIEVE_FTR_QUERY      1995
#define  NFM_RETRIEVE_QUERY_INFO     1996
#define  NFM_RETRIEVE_QUERY  	     1997
#define  NFM_SET_WF_STATE	     1998
#define  NFM_VALID_DATE		     1999


#define  WF_VALIDATE_USER            2000
#define  WF_SET_TO_STATE             2010
#define  WF_REVIEW_WORK_FLOW         2020
#define  WF_OVERRIDE_STATE           2030
#define  WF_QUERY_MAKE_TRANSITION    2040
#define  WF_MAKE_TRANSITION          2050
#define  WF_QUERY_ADD_ACL            2060
#define  WF_ADD_ACL                  2070
#define  WF_DELETE_ACL               2080
#define  WF_QUERY_ADD_ACL_USER       2090
#define  WF_ADD_ACL_USER             2100
#define  WF_DELETE_ACL_USER          2110
#define  WF_QUERY_ACL_ATTR_COND      2111
#define  WF_GET_COPY_ACL             2112
#define  WF_COPY_ACL                 2113
#define  WF_QUERY_ADD_SIGNOFF_USER   2120
#define  WF_ADD_SIGNOFF_USER         2130
#define  WF_DELETE_SIGNOFF_USER      2140
#define  WF_LOAD_WORKFLOW            2150
#define  WF_QUERY_ACL_NO             2160
#define  WF_QUERY_COMMAND_ATTR       2170
#define  WF_QUERY_WORKFLOW_ATTR      2180
#define  WF_QUERY_STATES_ATTR        2190
#define  WF_QUERY_CLASSES_ATTR       2200
#define  WF_QUERY_TRANSITIONS_ATTR   2210
#define  WF_QUERY_ACCESS_ATTR        2220
#define  WF_ENTER_COMMANDS           2230
#define  WF_ENTER_WORKFLOW           2240
#define  WF_ENTER_STATES             2250
#define  WF_ENTER_CLASS              2260
#define  WF_ENTER_TRANSITION         2270
#define  WF_ENTER_ACCESS             2280
#define  WF_GET_COMMAND_NO           2290
#define  WF_GET_COMMAND_NAME         2300
#define  WF_GET_WORKFLOW_NO          2310
#define  WF_GET_WORKFLOW_NAME        2320
#define  WF_GET_ACL_NO               2330
#define  WF_GET_ACL_NAME             2340
#define  WF_GET_STATE_NO             2350
#define  WF_GET_STATE_NAME           2360
#define  WF_GET_CLASS_NO             2370
#define  WF_GET_CLASS_NAME           2380
#define  WF_QUERY_SIGNOFF_ATTR       2390
#define  WF_SIGNOFF                  2400
#define  WF_PURGE_SIGNOFF	     2410

#define  NFM_DEFINE_SET_INFO	     2500
#define  NFM_DEFINE_FILE_INFO	     2510
#define  NFM_GET_FILE_INFO	     2520
#define  NFM_CHECKIN_ITEM	     2530
#define  NFM_CHECKIN_ITEM_FTR        2532
#define  NFM_CHECKOUT_ITEM	     2540
#define  NFM_CHECKIN_SET	     2550
#define  NFM_CHECKIN_SET_FTR         2552
#define  NFM_CHECKOUT_SET	     2560
#define  NFM_RESET_FILE_INFO	     2570
#define  NFM_COPY_ITEM_FILES	     2580
#define  NFM_SAVE_ITEM_FILES         2582
#define  NFM_FTR_SAVE_ITEM_FILES     2583
#define  NFM_SAVE_SET_FILES          2584
#define  NFM_FTR_SAVE_SET_FILES      2585
#define  NFM_COPY_SET_FILES	     2590
#define  NFM_COPY_ITEM_N             2592
#define  NFM_FTR_COPY_ITEM_N         2593
#define  NFM_GET_DATE_INFO	     2594
#define  NFM_GET_SET_MESSAGES	     2596
#define  NFM_DELETE_COPIED_FILES     2598
#define  NFM_GET_ACL_LIST_FOR_ITEM   2600
#define  NFM_GET_INTERNAL_SA_LIST_FOR_ITEM  2602
#define  NFM_ADD_RETURN_SA_NAME	     2604
#define  NFM_DELETE_LABEL	     2606

#define  NFM_NO_MORE_BUFFERS	     3497
#define  NFM_MULTI_BUFFER_COMMANDS   3499
#define  NFM_MULTI_BUFFER_MASTER     3500
#define  DSP_DISPLAY_NODES	     3502
#define  DSP_DISPLAY_STORAGE_AREAS   3504
#define  DSP_DISPLAY_WORKING_AREAS   3506
#define  DSP_DISPLAY_USERS	     3508
#define  DSP_DISPLAY_CATALOGS	     3510
#define  DSP_DISPLAY_ITEMS_PARTIAL_S 3511
#define  DSP_DISPLAY_ITEMS	     3512
#define  DSP_DISPLAY_ITEMS_PARTIAL   3513
#define  DSP_DISPLAY_ITEM_FILES	     3514
#define  DSP_DISPLAY_WORKFLOWS	     3516
#define  DSP_DISPLAY_ACLS	     3518
#define  DSP_DISPLAY_CLASSES	     3520
#define  DSP_DISPLAY_TABLES	     3522
#define  DSP_DISPLAY_PROGRAMS	     3524
#define  DSP_DISPLAY_TRANSITIONS     3526
#define  DSP_DISPLAY_QUERYS          3528
#define  DSP_DISPLAY_ACLUSERS        3530
#define  DSP_DISPLAY_SIGNOFF_USERS   3532
#define  DSP_DISPLAY_SO_ON_ITEM      3534
#define  DSP_DISPLAY_SO_HISTORY      3536
#define  DSP_DISPLAY_PROJECTS        3538
#define  DSP_DISPLAY_CATALOG_ACL_MAPPING 3540
#define  DSP_DISPLAY_CATALOG_SA_MAPPING  3542
#define  DSP_DISPLAY_PROJECT_ACL_MAPPING 3544
#define  DSP_DISPLAY_PROJECT_SA_MAPPING  3546
#define  DSP_DISPLAY_SETS	     3548
#define  DSP_DISPLAY_SAVESETS        3550
#define  DSP_DISPLAY_ARCHIVES        3552
#define  DSP_DISPLAY_ITEMS_ON_TAPE   3553
#define  DSP_DISPLAY_ITEMS_SHORT     3554
#define  DSP_DISPLAY_WHERE_USED_SET  3556
#define  DSP_DISPLAY_WHERE_USED_PROJECT 3558
#define  DSP_DISPLAY_SET_MEMBERS        3560
#define  DSP_DISPLAY_SET_MEMBERS_PARTIAL     3561
#define  DSP_DISPLAY_PROJECT_MEMBERS         3562
#define  DSP_DISPLAY_PROJECT_MEMBERS_PARTIAL 3563
#define  DSP_DISPLAY_ARCHIVE_FLAGS	3564
#define  DSP_DISPLAY_BACKUP_FLAGS	3566
#define  DSP_DISPLAY_RESTORE_FLAGS	3568
#define  DSP_DISPLAY_DELETE_FLAGS	3570
#define  DSP_DISPLAY_LABELS             3572
#define  DSP_DISPLAY_RIS_CATALOGS       3574
#define  DSP_DISPLAY_LOCAL_FILES	3580
#define  NFM_GET_WF_AND_COMPLETED_ACL_LIST       3581
#define  NFM_GET_STATE_LIST_FOR_WORKFLOW         3582
#define  NFM_GET_ITEM_ATTR_FOR_COPY     3590
#define  NFM_QRY_FLAG_RESTORE		3592
#define  NFM_SET_CLIENT_INFO		3600
#define  NFM_GET_ACAD_FILE		3610
#define  NFM_GET_RIS_ATTRIBUTES	        3612
#define  NFM_BLOCK_MULTI_CAT_SRCH_M_CRSR  3620
