#ifndef QUILABELS_H
#define QUILABELS_H

/*  Gadgets label definitions go here  */

#define FORM_TITLE              17
#define BEZEL_TITLE             32
#define QUERY_TITLE             14
#define QUERY_FIELD            196
#define DESC_TITLE              26
#define DESC_FIELD              30
#define CATALOG_TITLE           22
#define ATTRIBUTE_TITLE         55
#define OPERATOR_TITLE         143
#define VALUE_TITLE            144
#define DELETE_QUERY_BUTTON     31
#define BROWSE_BUTTON           19
#define DELETE_ROW_BUTTON       13
#define ORDER_BUTTON            11
#define CLEAR_BUTTON           195
#define REVISION_TITLE          29
#define REVISION_TOGGLE         27
#define CHECKIN_TOGGLE         142
#define CHECKIN_TITLE          146
#define OWNER_TITLE             18
#define OWNER_TOGGLE            20
#define SCROLL_BAR             162
#define CHECKBOX1               45
#define CHECKBOX2               46
#define CHECKBOX3               47
#define CHECKBOX4               48
#define CHECKBOX5               49
#define CHECKBOX6               50
#define CHECKBOX7               51
#define CHECKBOX8               52
#define AND_OR_TOGGLE1          37
#define AND_OR_TOGGLE2          38
#define AND_OR_TOGGLE3          39
#define AND_OR_TOGGLE4          40
#define AND_OR_TOGGLE5          41
#define AND_OR_TOGGLE6          42
#define AND_OR_TOGGLE7          43
#define CATALOG_FIELD1         170
#define CATALOG_FIELD2         171
#define CATALOG_FIELD3         172
#define CATALOG_FIELD4         173
#define CATALOG_FIELD5         174
#define CATALOG_FIELD6         175
#define CATALOG_FIELD7         176
#define CATALOG_FIELD8         177
#define ATTRIBUTE_FIELD1        92
#define ATTRIBUTE_FIELD2        93
#define ATTRIBUTE_FIELD3        94
#define ATTRIBUTE_FIELD4        95
#define ATTRIBUTE_FIELD5        96
#define ATTRIBUTE_FIELD6        97
#define ATTRIBUTE_FIELD7        98
#define ATTRIBUTE_FIELD8        99
#define OPERATOR_FIELD1         57
#define OPERATOR_FIELD2         58
#define OPERATOR_FIELD3         59
#define OPERATOR_FIELD4         60
#define OPERATOR_FIELD5         61
#define OPERATOR_FIELD6         62
#define OPERATOR_FIELD7         63
#define OPERATOR_FIELD8         64
#define VALUE_FIELD1           117
#define VALUE_FIELD2           118
#define VALUE_FIELD3           119
#define VALUE_FIELD4           120
#define VALUE_FIELD5           121
#define VALUE_FIELD6           122
#define VALUE_FIELD7           123
#define VALUE_FIELD8           124
#define BACKGROUND_LIST_SYM1   100
#define BACKGROUND_LIST_SYM2   101
#define BACKGROUND_LIST_SYM3   102
#define BACKGROUND_LIST_SYM4   103
#define BACKGROUND_LIST_SYM5   104
#define BACKGROUND_LIST_SYM6   105
#define BACKGROUND_LIST_SYM7   106
#define BACKGROUND_LIST_SYM8   107
#define ASSOC_LIST_SYM1         70
#define ASSOC_LIST_SYM2         71
#define ASSOC_LIST_SYM3         72
#define ASSOC_LIST_SYM4         73
#define ASSOC_LIST_SYM5         74
#define ASSOC_LIST_SYM6         75
#define ASSOC_LIST_SYM7         76
#define ASSOC_LIST_SYM8         77
#define BORDER_LIST_SYM1        78
#define BORDER_LIST_SYM2        79
#define BORDER_LIST_SYM3        80
#define BORDER_LIST_SYM4        81
#define BORDER_LIST_SYM5        82
#define BORDER_LIST_SYM6        83
#define BORDER_LIST_SYM7        84
#define BORDER_LIST_SYM8        85
#define LEFT_SCROLL_BUTTON     700
#define RIGHT_SCROLL_BUTTON    701
#define BEZEL_MESSAGE_STRIP    888
#define BEZEL_MESSAGE_TEXT     999
#define PROMPT_FIELD             9
#define ERROR_FIELD             10

#endif
