#define RPS_REPORT_TYPE     "R" 
#define RPS_SEARCH_TYPE     "W"
#define RPS_SORT_TYPE       "O"

#define APP_NAME     "NFM" 
#define APP_TYPE     "R" 

/* The number of default reports. */

#define RPS_NO_RPTS  68

/* The following is a list of all the default report_names. */

#define RPS_ACCESS                   "access"
#define RPS_ACCESS_ALL               "access_all"
#define RPS_ACLS                     "acls"
#define RPS_ACLUSERS                 "aclusers"
#define RPS_ACTIVITY                 "activity"
#define RPS_ARCHIVES                 "archives"
#define RPS_CATALOGS                 "catalogs"
#define RPS_CATALOGACLMAP            "catalog_aclmap"
#define RPS_CATALOGSAMAP             "catalog_samap"
#define RPS_CLASSES                  "classes"
#define RPS_COMMANDS                 "commands"
#define RPS_FILE_TYPES               "filetypes"
#define RPS_ITEM_FILES               "item_files"
#define RPS_ITEMS                    "items"
#define RPS_NODES                    "nodes"
#define RPS_PROCESSES                "processes"
#define RPS_PROGRAMS                 "programs"
#define RPS_PROJECTS                 "projects"
#define RPS_PROJECTACLMAP            "project_aclmap"
#define RPS_PROJECTSAMAP             "project_samap"
#define RPS_REPORTS                  "reports"
#define RPS_SAFILES                  "safiles"
#define RPS_SETS                     "sets"
#define RPS_STATES                   "states"
#define RPS_STORAGE_AREAS            "storage_areas"
#define RPS_TABLES                   "tables"
#define RPS_TRANSITIONS              "transitions"
#define RPS_USERS                    "users"
#define RPS_WORKFLOWS                "workflows"

#define RPS_S_ACLS                   "s_acls"
#define RPS_S_ACLS_SPEC              "s_acls_spec"
#define RPS_S_ACLS_ITEMS             "s_acls_items"
#define RPS_S_CATALOGS               "s_catalogs"
#define RPS_S_CAT_USERS              "user_catalogs"
#define RPS_S_CAT_SPEC               "s_cat_spec"
#define RPS_S_CLASSES                "s_classes"
#define RPS_S_COMMANDS               "s_commands"
#define RPS_S_CMDS_NFM               "s_trcmds_nfm"
#define RPS_S_ITEMS                  "s_items"
#define RPS_S_NODES                  "s_nodes"
#define RPS_S_PROJECTS               "s_projects"
#define RPS_S_STATES                 "s_states"
#define RPS_S_STATES_SIGNOFF         "signoff_states"
#define RPS_S_STORAGE_AREAS          "s_storage_area"
#define RPS_S_TABLES                 "s_tables"
#define RPS_S_TRANSITIONS            "s_transitions"
#define RPS_S_USERS                  "s_users"
#define RPS_S_WORKFLOWS              "s_workflows"
#define RPS_S_WFLOW_SPEC             "s_wflow_spec"
#define RPS_NFM_COMMANDS             "nfm_commands"

#define RPS_R_CATALOGS               "r_catalogs"
#define RPS_R_CLASSES                "r_classes"
#define RPS_R_PROJECTS               "r_projects"
#define RPS_R_STORAGE_AREAS          "r_storage_area"
#define RPS_R_STATES                 "r_states"
#define RPS_R_STATES_SIGNOFF         "r_sgnof_states"
#define RPS_R_TRANSITIONS            "r_transitions"
#define RPS_R_PROJECTACLMAP          "r_proj_aclmap"
#define RPS_R_PROJECTSAMAP           "r_proj_samap"
#define RPS_ACLSIGNOFFUSERS          "acl_signusers"
#define RPS_FLAGGED_FILES            "flagged_files"
#define RPS_PROGRAMS_TRANS           "programs_trans"
#define RPS_R_USERS                  "r_users"
#define RPS_R_NODES                  "r_nodes"
#define RPS_R_ITEMS                  "r_items"
#define RPS_R_WORKFLOWS              "r_workflows"
#define RPS_SO_ON_ITEM                "so_on_item"
#define RPS_SO_HISTORY                "so_history"
