#define CAUTION_TEXT   13
#define FIRST_LINE     14
#define COMMAND_INFO   15
#define CANCEL_BUTTON  16
#define OK_BUTTON      17

#define CAUTION_TEXT_DELETE_CLASS   13
#define FIRST_LINE_DELETE_CLASS     14
#define COMMAND_INFO_DELETE_CLASS   15
#define CANCEL_BUTTON_DELETE_CLASS  16
#define OK_BUTTON_DELETE_CLASS      17

#define CAUTION_TEXT_DELETE_STATE   13
#define FIRST_LINE_DELETE_STATE     14
#define COMMAND_INFO_DELETE_STATE   15
#define CANCEL_BUTTON_DELETE_STATE  16
#define OK_BUTTON_DELETE_STATE      17

