#define	RV_CHECK		1
#define	RV_EXECUTE		2
#define	RV_RESET		3
#define	RV_CANCEL		4
#define	RV_CHANGE		5

#define	RV_STATUS		10
#define	RV_VISIBLE_COLOR	11
#define	RV_HIDDEN_COLOR		12
#define	RV_VISIBLE_STYLE	13
#define	RV_HIDDEN_STYLE		14
#define	RV_VISIBLE_WEIGHT	15
#define	RV_HIDDEN_WEIGHT	16
#define	RV_VISIBLE_LAYER	17
#define	RV_HIDDEN_LAYER		18
#define	RV_COLOR_TEXT		19
#define	RV_STYLE_TEXT		20
#define	RV_WEIGHT_TEXT		21
#define	RV_LAYER_TEXT		22
#define	RV_VISIBLE_EDGES_TEXT	23
#define	RV_HIDDEN_EDGES_TEXT	24
#define	RV_VECTOR_TYPE		26
#define	RV_VECTOR_TYPE_TEXT	28
#define	RV_OPTIMIZATION		29
#define	RV_OPTIMIZATION_TEXT	30
#define	RV_VISIBLE_HIDDEN	31

