#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:07:58 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdct/imp/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:07:58  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1999/05/28  13:59:18  pinnacle
# ct
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/28/99  ah      creation
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdictimp.m
	grmakemake vdictimp.m mkfile
