
#define MEM_INT_SIZE     10
#define MEM_NO_BUFFER     0
#define MEM_REALLOC_SIZE  MEM_NO_BUFFER    + MEM_INT_SIZE
#define MEM_BUFFER_USED   MEM_REALLOC_SIZE + MEM_INT_SIZE
#define MEM_DATA_OFFSET   MEM_BUFFER_USED  + MEM_INT_SIZE
#define MEM_HEADER_TERM   MEM_DATA_OFFSET  + MEM_INT_SIZE
#define MEM_HEADER_END    MEM_HEADER_TERM  + 1

