#define NFF_STATUS    11
#define NFF_MESSAGE   20
#define NFMR_STATUS   12
#define NFMR_MESSAGE  19
#define NETC_STATUS   13
#define NETC_MESSAGE  18
#define NETS_STATUS   14
#define NETS_MESSAGE  17
#define NFMS_STATUS   15
#define NFMS_MESSAGE  16
#define NFM_STATUS    29
#define NFM_MESSAGE   36
#define SQL_STATUS    31
#define SQL_MESSAGE   37
#define RDBMS_STATUS  34
#define RDBMS_MESSAGE 38
#define RPS_STATUS    35
#define RPS_MESSAGE   39
