#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:09:25 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdtag/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# * $Log: makefile,v $
# * Revision 1.1.1.1  2001/01/04 21:09:25  cvs
# * Initial import to CVS
# *
# Revision 1.1  1998/11/05  17:07:34  pinnacle
# tags
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 11/05/98  ah      creation
# *
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vditag.m
	grmakemake vditag.m mkfile


