#/* $Id: makefile,v 1.1 2001/06/03 15:02:59 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdval/x2/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/06/03 15:02:59  ahundiak
# *      ah
# *
# *      Revision 1.1  2001/05/24 18:50:21  ahundiak
# *      ah
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/29/01  ah      creation
# ***************************************************************************/

TGT = vdivalx2
include ${VDS_PATH}/etc/makefiles/lib_only.h
