
/*
$Author: hans $
$Revision: 1.1.1.1 $
$Date: 2001/12/17 22:40:57 $
$Locker:  $
*/

#ifndef HSsdpform_include
#define HSsdpform_include 1

/* Header file for the form Set Display Parameters */

#define HS_SDP_CHECK 			1
#define HS_SDP_CANCEL			4
#define HS_SDP_CONVERT_WINDOW		5
#define HS_SDP_STATUS			10
#define HS_SDP_FORM_TITLE		11
#define HS_SDP_PGT_TITLE		12
#define HS_SDP_POLY_GENERATION_TOL	13
#define HS_SDP_DISPLAY_HIDDEN_LINES	14
#define HS_SDP_HIDDEN_SYMBOLOGY_TITLE	51 
#define HS_SDP_COLOR_TITLE		16
#define HS_SDP_STYLE_TITLE		17
#define HS_SDP_WEIGHT_TITLE		18
#define HS_SDP_COLOR			19
#define HS_SDP_STYLE			20
#define HS_SDP_WEIGHT			21
#define HS_SDP_DEPTH_CUE_TITLE		22
#define HS_SDP_HUNDRED			23
#define HS_SDP_DEPTH_CUE		24
#define HS_SDP_ZERO			25
#define HS_SDP_STEREO_EYE_TITLE		26
#define HS_SDP_STEREO_EYE_SEP		27
#define HS_SDP_TRANSPARENCY_GRID	28
#define HS_SDP_HIDDEN_SYMBOLOGY_GROUP	29
#define HS_SDP_SHADED_WIREFRAME		48
#define HS_SDP_SHADED_WIREFRAME_TITLE	49
#define HS_SDP_SHADED_WIREFRAME_LEGEND  50
#define HS_SDP_SHADED_WIREFRAME_BRACES  56
#define HS_SDP_LIGHT_SRC_DISPLAY_TITLE	57
#define HS_SDP_LIGHT_SRC_DISPLAY	63
#define HS_SDP_STEREO_BRACKET		64
#define HS_SDP_STEREO_WIREFRAME		65
#define HS_SDP_STEREO_HIDDEN_LINE	66
#define HS_SDP_STEREO_SHADING		67
#define HS_SDP_STEREO_RENDERING		68
#define SHADE_TOL_UPPER			16.0
#define SHADE_TOL_LOWER			0.25

#endif
