
#ifndef coniindex_include
#define coniindex_include


#define CO_ni_dummy_func        0
#define CO_ni_place_circle_by_center                    1         
#define CO_ni_place_hael_axis                           2         
#define CO_ni_place_qrtel_axis                          3         
#define CO_ni_place_el_axis                             4         
#define CO_ni_place_el_cnt                              5         
#define DYrbcirdiam                                     6         
#define DYrbcircnt                                      7         
#define DYrbcirrad                                      8         
#define DYrbellcnt                                      9         
#define DYrbhalfell                                     10        
#define DYrbquartell                                    11        
#define DYrbellaxis                                     12        
#define CO_ni_place_circle_by_diameter                  13        
#define CO_ni_place_linear                              14        
#define DYrblinear                                      15        
#define CO_ni_place_block                               16        
#define CO_ni_place_rotblk                              17        
#define DYrbblock                                       18        
#define DYrbrotblk                                      19        
#define CO_ni_place_point                               20        
#define CO_ni_modify_element                            21        
#define CO_ni_extend_element                            22        
#define CO_ni_split_element                             23        
#define CO_ni_delete_vertex                             24        
#define CO_ni_place_circle_by_3pts                      25        
#define CO_ni_place_circle_by_2pts_radius               26        
#define CO_ni_place_arc_3pts                            27        
#define CO_ni_place_arc_cent                            28        
#define CO_ni_place_arc_radcnt                          29        
#define CO_ni_place_arc_rad                             30        
#define DYrbarc3pt                                      31        
#define DYrbarccnt                                      32        
#define DYrbarccntrad                                   33        
#define DYrbarcrad                                      34        
#define CO_ni_insert_vertex                             35        
#define DYrb2ptmodify                                   -36       
#define CO_ni_modify_axis                               37        
#define DYrbcircle_by_2pts_radius                       38        
#define DYrbcircle_by_3pt                               39        
#define CO_ni_measure_distance_to_projection            40        
#define CO_ni_measure_sweep_angle                       41        
#define CO_ni_measure_length_along_element              42        
#define CO_ni_measure_radius                            43        
#define CO_ni_measure_area                              44        
#define CO_ni_measure_diameter                          45        
#define CO_ni_measure_distance_btwn_2pts                46        
#define CO_ni_measure_length                            47        
#define CO_ni_place_inf_line                            48        
#define CO_ni_place_fillet                              49        
#define CO_ni_partial_delete                            50        
#define CO_ni_move_segment                              51        
#define CO_ni_measure_angle_by_3_pts                    52        
#define DYrbmsang3pt                                    53        
#define CO_ni_extend_1_insect                           54        
#define CO_ni_extend_2_insect                           55        
#define CO_ni_ang2bis                                   56        
#define CO_ni_perbis                                    57        
#define CO_ni_place_equal_pts                           58        
#define CO_ni_measure_angle_by_2_pts                    59        
#define CO_ni_measure_line_angle                        60        
#define CO_ni_measure_angle_between_2_lines             61        
#define DYrbfixed_linear                                -62       
#define CO_ni_fragment_element                          63        
#define CO_ni_place_polygon                             64        
#define CO_ni_place_horizontal_line                     65        
#define CO_ni_place_vertical_line                       66        
#define CO_ni_place_line_at_active_angle                67        
#define DYrbtriangle                                    68        
#define DYrb_add_pt_modify                              -69       
#define DYrbbadmodify                                   -70       
#define DYrbproject_linear                              -71       
#define DYrb_line_active_angle                          72        
#define DYrb_vertical_line                              73        
#define DYrb_horizontal_line                            74        
#define CO_ni_line_at_minimum_distance                  75        
#define CO_ni_place_npoly_by_vertex                     76        
#define DYrbnpolygon                                    77        
#define CO_ni_place_angle_bisector_3pt                  78        
#define DYrbangbis3pt                                   79        
#define DYrbconstruct_line                              80        
#define DYrborthline                                    -81       
#define DYrborthpoly                                    -82       
#define CO_ni_measure_min_dis_2_ele                     83        
#define CO_ni_place_el_2pts                             84        
#define CO_ni_place_el_3pts                             85        
#define DYel_by_2pts                                    86        
#define DYel_by_3pts                                    87        
#define CO_ni_place_tentat_point                        88        
#define DE_ni_change_boundary                           89        
#define DE_ni_copy_soo                                  90        
#define DE_ni_drop_soo                                  91        
#define DE_ni_modify_boundary                           92        
#define DE_ni_place_soo                                 93        
#define DE_ni_remove_boundary                           94        
#define DE_ni_place_total_soo                           95        
#define CO_ni_show_variable                             96        
#define CO_ni_set_variable                              97        
#define CO_ni_set_active_CS_type                        98        
#define CO_ni_point_between_2_pts                       99        
#define CO_const_current_pt_form                        100       
#define CO_ni_delta_view                                101       
#define CO_ni_delta_world                               102       
#define CO_ni_abs_wld_coord                             103       
#define CO_ni_dist_dir_view                             104       
#define CO_ni_pt_along_element                          105       
#define CO_ni_place_crosshatch                          106       
#define CO_ni_measure_angle_of_line_and_axis            107       
#define CO_ni_measure_angle_of_2_pts_and_axis           108       
#define DYrbfixlinear                                   109       
#define DYfixbuflinear                                  110       
#define CO_ni_cd                                        111       
#define CO_ni_cdpath                                    112       
#define CO_ni_mkdir                                     113       
#define CO_ni_pwd                                       114       
#define CO_ni_remove                                    115       
#define CO_ni_rmdir                                     116       
#define CO_ni_shownm                                    117       
#define CO_ni_toggle_dir_mode                           118       
#define CO_ni_place_line_terminator                     119       
#define CO_ni_measure_min_dist_point_to_element         120
#define CO_ni_place_circle_tan_chord                    121
#define DYrbcirchd                                      122
#define CO_ni_place_arc_tan_chord                       123
#define DYrbarcchd                                      124
#define DYrbarcendpt                                    125
#endif
