#/* $Id: makefile.1,v 1.1 2002/04/09 14:44:44 ahundiak Exp $  */

#/***************************************************************************
# * I/LOFT
# *
# * File:        src/vppdf/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile.1,v $
# *      Revision 1.1  2002/04/09 14:44:44  ahundiak
# *      ah
# *
# *      Revision 1.1.1.1  2001/01/04 21:11:59  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1999/05/24  18:35:20  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/24/99  ah      creation
# *
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vpipdf.m
	grmakemake vpipdf.m mkfile
