# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:58 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdcoll/func/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:07:58  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:26:48  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/12/06  23:03:32  pinnacle
# Created:   vdcoll/func/makefile r#
#
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdcollfc.m
	grmakemake vdcollfc.m mkfile
