# Do not alter this SPC information: $Revision: 1.4.4.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt
RIS_PRODUCT=RISCLI
IS_RISSRV=NOT_RISSRV
RM_EXE_DIR=riscli\setup32\bin\$(BINDIR)
RMPROD_DIR=riscli\setup32\remsc
!include $(RISDEVDIR)\riscli\setup32\rmprod\makefile.mak
