#/* $Id: makefile,v 1.3 2001/03/31 19:34:17 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdcty/rrv/makefile
# *
# * Description: 
# *
# * Dependencies:
# *
# * Revision History:
# * $Log: makefile,v $
# * Revision 1.3  2001/03/31 19:34:17  ahundiak
# * ah
# *
# * Revision 1.2  2001/03/30 17:46:14  ahundiak
# * ah
# *
# * Revision 1.1  2001/02/17 14:23:45  ahundiak
# * *** empty log message ***
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 02/15/01  ah      Creation
# ***************************************************************************/

TGT     = vdirrvcmd
TGT_PPL = vdirrvppl

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile pplmkfile *.e *.o

