#/* $Id: makefile,v 1.1 2001/01/14 16:08:21 art Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdctx/s/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/01/14 16:08:21  art
# *      sp merge
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 10/14/01  ah      creation
# ***************************************************************************/

TGT = vdictxs

target: mkfile 
	grmake -r -k -f mkfile

mkfile: ${TGT}.m
	grmakemake ${TGT}.m mkfile
