#!/bin/ksh
#
# I/LOFT
# Does genmenu.
# Creates a fake command for every icon which does not kicks off a command
# but kicks off another menu.
#
MENUS=${LOFT}/config/english/menus

echo "\n\tCreating vl_pan.cmp table\n"

\cd ${MENUS}
/bin/ls VL* > ${MENUS}/vl_pan.list

for file in `cat ${MENUS}/vl_pan.list` ; do
  print '^"'$file'",'$file',COci,0,0,,"Blank"' >> ${MENUS}/vl_pan.cmp
done

rm ${MENUS}/vl_pan.list

if [ -f ${MENUS}/vl_pan.cmp ] ; then
  mv ${MENUS}/vl_pan.cmp ${LOFT}/config
  /bin/ls -ls ${LOFT}/config/vl_pan.cmp
fi
