OBJECT = \
	FlibChFn.o \
	$(GRNUC)/src/fontbuilder/fconv/CF_src/FlibChFn.c

CC = $(COMPILER)

IPATH = \
	-I$(GRNUC)/src/fontbuilder/fconv/include \
	-I$(BS)/include \
	-I$(EXNUC)/include \
	-I$(GRNUC)/include

COPT = $(COMPOPT)

LINKLIB = 

EXC = $(GRLIB)/src/fontbuilder/bin/GRChFn

LIBS = $(GRLIB)/src/fontbuilder/fconv/EX_src/Sunstub.o \
	$(GRLIB)/src/fontbuilder/fconv/EX_src/string16.o 


ARCHIVES = \
	$(GRLIB)/src/fontbuilder/fconv/Flib_src/FlibConv.o \
	$(GRLIB)/src/fontbuilder/fconv/Flib_src/FlibIo.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FSaccess.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FScrypt.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FSfindChdr.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FSfindKern.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FSio.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FSsortChdr.o \
        $(GRLIB)/src/fontbuilder/fconv/FS_src/FSsortKern.o \
	$(GRLIB)/src/fontbuilder/fconv/UT_src/UTstring.o \
	$(GRLIB)/src/fontbuilder/fconv/UT_src/UTck_file.o \
	$(GRLIB)/src/fontbuilder/fconv/UT_src/UTvax_conv.o \
	$(GRLIB)/src/fontbuilder/fconv/UT_src/UTsun_conv.o \
	$(GRLIB)/src/fontbuilder/fconv/FF_src/FFerror.o

${EXC} : ${OBJECT} ${ARCHIVES} ${LIBS}
	@echo ""
	@echo "Remaking ${EXC} because of : $?"
	@echo ""
	ld -o $(EXC) FlibChFn.o $(ARCHIVES) $(LIBS) \
	$(GRNUC)/libgpipe.a \
	-lXFS -lXFI -lm -dl \
        /usr/ip32/mgui/lib/libXt.a /usr/ip32/mgui/lib/libX11.a \
        -lxc \
        -lxcmalloc \
        -lhlib
	@echo ""
	@ls -l ${EXC}
	@echo ""



FlibChFn.o : \
	$(GRNUC)/src/fontbuilder/fconv/CF_src/FlibChFn.c 

.c.o : $*.c 
	@echo "";
	@echo "Remaking $*.o because of : $?"
	@echo "";
	@echo "	$*.c -> $*.o"
	@$(CC) -c $(COPT) $(IPATH) $*.c
	@if test "$(COPT)" = "-g"; then echo "	Debug verion of $*.c compiled";fi
	@echo ""
	@ls -l $*.o
	@echo ""
