#/* $Id: makefile,v 1.3 2001/05/21 12:56:14 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdcvg/makefile
# *
# * Description: CAD Vector Graphics Makefile
# *
# * Dependencies:
# *
# * Revision History:
# * $Log: makefile,v $
# * Revision 1.3  2001/05/21 12:56:14  ahundiak
# * ah
# *
# * Revision 1.2  2001/01/11 19:18:53  art
# * sp merge
# *
# Revision 1.1  2000/04/14  17:06:04  pinnacle
# ah
#
# Revision 1.1  2000/02/22  20:15:30  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 01/26/00  ah      Creation
# * 01/11/01  ah      sp merge
# * 05/21/01  ah      standard makefile
# ***************************************************************************/
TGT = vdicvg
include ${VDS_PATH}/etc/makefiles/lib_only.h


