all:
	@cd $(RIS)/src/com/arch;     make clean; make; cd $(RIS)
	@cd $(RIS)/src/com/network;  make clean; make; cd $(RIS)
	@cd $(RIS)/src/com/common;   make clean; make; cd $(RIS)
	@cd $(RIS)/src/app/app;      make clean; make; cd $(RIS)
	@cd $(RIS)/src/app/interface;make clean; make; cd $(RIS)
	@cd $(RIS)/lib;              make clean; make; cd $(RIS)
