#include "NFMerrordef.h"
#include <stdio.h>
#include <sys/stat.h>
#include "PDUerror.h"
#include "NFMschema.h"
#include "MEMstruct.h"
#include "NFMapi.h"
#include "NFMitems.h"
#include "NFMitemfiles.h"
#include "dbadev.h"
#include "rMRPstr.h"
#include "MRPmessage.h"
#include "PDMproto.h"



#define NFM_TEMP_SIZE1 12

extern int      PDMdebug_on;
extern char     PDM_DEBUG_FILE[];


/*** 
 
  This function will move a report file from one str_area to another.
  This is written for moving the report file generated by DBA (DB Access).


    31/1/92 - Kumar 
***/

long PDMmove_rpt_file (from_area, working_area, file_name )
char *from_area;
char *working_area;
char  *file_name;
{
  char *fname="PDMmove_rpt_file";
  char row_str[3048];
  char nodename[NFM_NODENAME+1], username[NFM_USERNAME+1], 
       passwd[NFM_PASSWD+1], pathname[NFM_PATHNAME+1], 
       devicetype[NFM_DEVICETYPE+1], machid[NFM_MACHID+1], 
       opsys[NFM_OPSYS+1], tcpip[NFM_TCPIP+1], xns[NFM_XNS+1], 
       decnet[NFM_DECNET+1], netware[NFM_NETWARE+1], 
       plattername [NFM_PLATTERNAME+1], partition[NFM_PARTITION+1], 
       nfs[NFM_NFS+1], compress[NFM_COMPRESS+1];
  char nodename1[NFM_NODENAME+1], username1[NFM_USERNAME+1], 
       passwd1[NFM_PASSWD+1], pathname1[NFM_PATHNAME+1], 
       devicetype1[NFM_DEVICETYPE+1], machid1[NFM_MACHID+1], 
       opsys1[NFM_OPSYS+1], tcpip1[NFM_TCPIP+1], xns1[NFM_XNS+1], 
       decnet1[NFM_DECNET+1], netware1[NFM_NETWARE+1], 
       plattername1 [NFM_PLATTERNAME+1], partition1[NFM_PARTITION+1], 
       nfs1[NFM_NFS+1], compress1[NFM_COMPRESS+1];
  long  sano = 0, sano1 = 0;
  long status;
  MEMptr file_list = NULL;


  _PDMdebug ( fname, "ENTER: working_area[%s] \n", working_area);
  _PDMdebug ( fname, "from_area[%s] \n", from_area);

  /* get working storage area information */

  status = NFMget_storage_info (working_area, &sano, nodename, username, passwd, 
                                pathname, devicetype, plattername, partition, 
                                nfs, compress, machid, opsys, tcpip, 
                                xns, decnet, netware);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", working_area, 
                status);
    return (status);
  }

  /* get from storage area information */

  status = NFMget_storage_info(from_area, &sano1, nodename1, username1, passwd1, 
                             pathname1, devicetype1, plattername1, partition1, 
                         nfs1, compress1, machid1, opsys1, tcpip1, 
                         xns1, decnet1, netware1);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", from_area, 
                status);
    return (status);
  }

  _PDMdebug (fname, "prepare file transfer buffer\n");

 status = NFMbuild_fto_buffer (&file_list, 0);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMbuild_fto_buffer 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  } 
    row_str[0] = '\0';
  sprintf (row_str, 
  "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s", 
  sano, 
  nodename, username, passwd, pathname, devicetype, plattername, partition, 
  nfs, compress, machid, opsys, tcpip, xns, decnet, netware, 
  "\1\1\1\1\1\1\1\1\1");

  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  }
   
    row_str[0] = '\0';

/*
  sprintf (row_str, 
"%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1%\1100\12030\1\1\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
 */
  sprintf (row_str, "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
  _PDMdebug (fname, "MEMwrite %s\n", row_str);
     strcat(row_str, "\1");
      strcat(row_str, "100\1");
       strcat(row_str, "2030\1\1\1");
  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
   }

if(PDMdebug_on)
{
MEMprint_buffer("file_list", file_list, PDM_DEBUG_FILE);
 }

/* Move the file using NFMlistener */

  status = _NFMfs_recv_files (&file_list);
  if (status != NFM_S_SUCCESS)
  {
      _PDMdebug (fname, "_NFMfs_recv_files 0x%.8x\n", status);
      _NFMfs_undo_recv_files (&file_list);
      return (status);
  }


  status = MEMclose (&file_list);
  if (status != MEM_S_SUCCESS)
    _PDMdebug (fname, "MEMclose 0x%.8x\n", status);

  _PDMdebug (fname, "EXIT: successful 0x%.8x\n", PDM_S_SUCCESS);
  return (PDM_S_SUCCESS);
}


/*** 
 
  This function will move a RIS report file template from working storage are to reportslib storagearea.
  This is written for moving the report file generated by DBA (DB Access).


    31/8/92 - Kumar 
***/

long PDMimport_ris_rpt (working_area, report, file_move )
char  *working_area;
struct PSUrpt  report;
int   file_move;
{
  char *fname="PDMimport_ris_rpt";
  char row_str[3048];
  char nodename[NFM_NODENAME+1], username[NFM_USERNAME+1], 
       passwd[NFM_PASSWD+1], pathname[NFM_PATHNAME+1], 
       devicetype[NFM_DEVICETYPE+1], machid[NFM_MACHID+1], 
       opsys[NFM_OPSYS+1], tcpip[NFM_TCPIP+1], xns[NFM_XNS+1], 
       decnet[NFM_DECNET+1], netware[NFM_NETWARE+1], 
       plattername [NFM_PLATTERNAME+1], partition[NFM_PARTITION+1], 
       nfs[NFM_NFS+1], compress[NFM_COMPRESS+1];
  char nodename1[NFM_NODENAME+1], username1[NFM_USERNAME+1], 
       passwd1[NFM_PASSWD+1], pathname1[NFM_PATHNAME+1], 
       devicetype1[NFM_DEVICETYPE+1], machid1[NFM_MACHID+1], 
       opsys1[NFM_OPSYS+1], tcpip1[NFM_TCPIP+1], xns1[NFM_XNS+1], 
       decnet1[NFM_DECNET+1], netware1[NFM_NETWARE+1], 
       plattername1 [NFM_PLATTERNAME+1], partition1[NFM_PARTITION+1], 
       nfs1[NFM_NFS+1], compress1[NFM_COMPRESS+1];
  long  sano = 0, sano1 = 0;
  long status;
  int  tempno =0;
  char file_name[15], description[50], output[100], query_file[100];
  MEMptr file_list = NULL;
  struct stat file_status;


  _PDMdebug ( fname, "ENTER: working_area[%s] \n", working_area);

    strcpy(file_name, report.options.template_name);

  /* get to(checkin) storage area information */

    if(file_move)
   {
  status = NFMget_storage_info ("RIS templates", &sano, nodename, username, passwd, 
                                pathname, devicetype, plattername, partition, 
                                nfs, compress, machid, opsys, tcpip, 
                                xns, decnet, netware);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", "reportslib", 
                status);
    return (status);
  }

  /* get working storage area information */

  status = NFMget_storage_info(working_area, &sano1, nodename1, username1, 
                     passwd1, pathname1, devicetype1, plattername1, partition1, 
                         nfs1, compress1, machid1, opsys1, tcpip1, 
                         xns1, decnet1, netware1);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", working_area, 
                status);
    return (status);
  }

  _PDMdebug (fname, "prepare file transfer buffer\n");

 status = NFMbuild_fto_buffer (&file_list, 0);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMbuild_fto_buffer 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  } 
    row_str[0] = '\0';
  sprintf (row_str, 
  "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s", 
  sano, 
  nodename, username, passwd, pathname, devicetype, plattername, partition, 
  nfs, compress, machid, opsys, tcpip, xns, decnet, netware, 
  "\1\1\1\1\1\1\1\1\1");

  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  }
   
    row_str[0] = '\0';

/*
  sprintf (row_str, 
"%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1%\1100\12030\1\1\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
 */
  sprintf (row_str, "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
  _PDMdebug (fname, "MEMwrite %s\n", row_str);
     strcat(row_str, "\1");
      strcat(row_str, "100\1");
       strcat(row_str, "2030\1\1\1");
  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
   }

if(PDMdebug_on)
{
MEMprint_buffer("file_list", file_list, PDM_DEBUG_FILE);
 }

/* Move the file using NFMlistener */

  status = _NFMfs_recv_files (&file_list);
  if (status != NFM_S_SUCCESS)
  {
      _PDMdebug (fname, "_NFMfs_recv_files 0x%.8x\n", status);
      _NFMfs_undo_recv_files (&file_list);
      return (status);
  }

 }

   sprintf(row_str, "Delete from psurptopts where p_templatename = '%s' and p_templatetype = '%s'", report.options.template_name, report.templatetype);
 
       status = SQLstmt(row_str);
 tempno = 0;

/* Fn. expects address of reports. TR# 139526017. 26/may/95 - raj. */
    status = PSUrs_get_tempno( &report, &tempno, 1 );
    if(status != PDM_S_SUCCESS) {
      _PDMdebug (fname, "PSUrs_get_tempno failed : 0x%.8x\n", status);
      _PDMdebug (fname, "Trying PDMi_maxrow_no...\n");
      status = PDMi_maxrow_no("psurptopts","p_templateno",&tempno);
      if(status != PDM_S_SUCCESS) {
         _PDMdebug(fname,"PDMi_maxrow_no failed status %d\n", status); 
         return(status);
         }
      /* Why is this needed? */
/*
      if(tempno == 0) {
         status = PDM_E_WRITE_ROW; 
        _PDMdebug (fname, "Could not get max row no 0x%.8x\n", status);
        return(status);
        }
*/
       }

      ++tempno;

strcpy(row_str, "");
/* This variable is not being used... This used to 
   cause load to work of c300 but not on c400... MaC 030294 */

report.options.title[0] = '\0';
      
        if ( report.templib != NULL )
      {
        if ( !strcmp(report.templib, ""))
        {
          if(report.options.description != NULL)
           {
          if(!strcmp(report.options.description, "")) description[0]='\0';
            else strcpy(description, report.options.description);
            }
         else  description[0]='\0';
          if(report.options.output != NULL)
           {
          if(!strcmp(report.options.output, "")) output[0]='\0';
            else strcpy(output, report.options.output);
            }
         else  output[0]='\0';
        sprintf(row_str, "insert into psurptopts (p_templateno, p_table, p_templatename, p_templatetype, p_output, p_title, p_templib ) values (%d, '%s', '%s', '%s', '%s', '%s', '%s')", 
            tempno, 
            report.options.table, 
            report.options.template_name, 
            report.templatetype, 
            output, 
            report.options.title, 
            report.options.template_name);
/*
            report.templib);
*/
         }
        else
         {
          if(report.options.description != NULL)
           {
          if(!strcmp(report.options.description, "")) description[0]='\0';
            else strcpy(description, report.options.description);
            }
         else  description[0]='\0';
          if(report.options.output != NULL)
           {
          if(!strcmp(report.options.output, "")) output[0]='\0';
            else strcpy(output, report.options.output);
            }
         else  output[0]='\0';
        sprintf(row_str, "insert into psurptopts (p_templateno, p_table, p_templatename, p_templatetype, p_output, p_title ) values (%d, '%s', '%s', '%s', '%s', '%s' )", 
            tempno, 
            report.options.table, 
            report.options.template_name, 
            report.templatetype, 
            output, 
            report.options.title);
           }

        }
        else
        {
          if(report.options.description != NULL)
           {
          if(!strcmp(report.options.description, "")) description[0]='\0';
            else strcpy(description, report.options.description);
            }
         else  description[0]='\0';
          if(report.options.output != NULL)
           {
          if(!strcmp(report.options.output, "")) output[0]='\0';
            else strcpy(output, report.options.output);
            }
         else  output[0]='\0';
        sprintf(row_str, "insert into psurptopts (p_templateno, p_table, p_templatename, p_templatetype, p_output, p_title ) values (%d, '%s', '%s', '%s', '%s', '%s' )", 
            tempno, 
            report.options.table, 
            report.options.template_name, 
            report.templatetype, 
            output, 
            report.options.title);
         }

          _PDMdebug(fname, "SQLstmt: %s\n", row_str);
       status = SQLstmt(row_str);
        if(status != SQL_S_SUCCESS)
          {
      _PDMdebug (fname, "SQLstmt 0x%.8x\n", status);
      _NFMfs_undo_recv_files (&file_list);
      return (status);
          }
      
  status = MEMclose (&file_list);
  if (status != MEM_S_SUCCESS)
    _PDMdebug (fname, "MEMclose 0x%.8x\n", status);

   _PDMdebug(fname, " removing the template lib \n");

      query_file[0] = '\0';

     if(file_move)
     {
     sprintf(query_file, "%s/%s", pathname1, file_name );

             status = stat(query_file, &file_status);
             if (status == 0) /* file exists */
                {
                 /* delete file locally */
                 status = unlink(query_file);
                 if (status == 0)
                    _PDMdebug(fname, "file removal succeeded\n");
                 else
                    _PDMdebug(fname, "file removal failed\n");
                }
             else
                _PDMdebug(fname, "file was not found\n");
      }

  _PDMdebug (fname, "EXIT: successful 0x%.8x\n", PDM_S_SUCCESS);
  return (PDM_S_SUCCESS);
}


/*** 
 
  This function will move a RIS report file template from working storage are to reportslib storagearea.
  This is written for moving the report file generated by DBA (DB Access).


    31/8/92 - Kumar 
***/


long PDMexport_ris_rpt (working_area, report )
char  *working_area;
char   *report;
{
  char *fname="PDMexport_ris_rpt";
  char row_str[3048];
  char nodename[NFM_NODENAME+1] = "", username[NFM_USERNAME+1] = "", 
       passwd[NFM_PASSWD+1]= "", pathname[NFM_PATHNAME+1]="", 
       devicetype[NFM_DEVICETYPE+1]="", machid[NFM_MACHID+1]="", 
       opsys[NFM_OPSYS+1]="", tcpip[NFM_TCPIP+1]="", xns[NFM_XNS+1]="", 
       decnet[NFM_DECNET+1]="", netware[NFM_NETWARE+1]="", 
       plattername [NFM_PLATTERNAME+1]="", partition[NFM_PARTITION+1]="", 
       nfs[NFM_NFS+1]="", compress[NFM_COMPRESS+1]="";
  char nodename1[NFM_NODENAME+1]="", username1[NFM_USERNAME+1]="", 
       passwd1[NFM_PASSWD+1]="", pathname1[NFM_PATHNAME+1]="", 
       devicetype1[NFM_DEVICETYPE+1]="", machid1[NFM_MACHID+1]="", 
       opsys1[NFM_OPSYS+1]="", tcpip1[NFM_TCPIP+1]="", xns1[NFM_XNS+1]="", 
       decnet1[NFM_DECNET+1]="", netware1[NFM_NETWARE+1]="", 
       plattername1 [NFM_PLATTERNAME+1]="", partition1[NFM_PARTITION+1]="", 
       nfs1[NFM_NFS+1]="", compress1[NFM_COMPRESS+1]="";
  long  sano = 0, sano1 = 0;
  long status;
  char file_name[15]="";
  MEMptr file_list = NULL;


  _PDMdebug ( fname, "ENTER: working_area[%s] \n", working_area);
  _PDMdebug ( fname, "ENTER: report[%s] \n", report);

    strcpy(file_name, report);

  /* get to(checkin) storage area information */

  status = NFMget_storage_info (working_area, &sano, nodename, username, passwd, 
                                pathname, devicetype, plattername, partition, 
                                nfs, compress, machid, opsys, tcpip, 
                                xns, decnet, netware);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", "reportslib", 
                status);
    return (status);
  }

  /* get working storage area information */

  status = NFMget_storage_info("RIS templates", &sano1, nodename1, username1, 
                     passwd1, pathname1, devicetype1, plattername1, partition1, 
                         nfs1, compress1, machid1, opsys1, tcpip1, 
                         xns1, decnet1, netware1);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", working_area, 
                status);
    return (status);
  }

  _PDMdebug (fname, "prepare file transfer buffer\n");

 status = NFMbuild_fto_buffer (&file_list, 0);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMbuild_fto_buffer 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  } 
    row_str[0] = '\0';
  sprintf (row_str, 
  "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s", 
  sano, 
  nodename, username, passwd, pathname, devicetype, plattername, partition, 
  nfs, compress, machid, opsys, tcpip, xns, decnet, netware, 
  "\1\1\1\1\1\1\1\1\1");

  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  }
   
    row_str[0] = '\0';

/*
  sprintf (row_str, 
"%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1%\1100\12030\1\1\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
 */
  sprintf (row_str, "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
  _PDMdebug (fname, "MEMwrite %s\n", row_str);
     strcat(row_str, "\1");
      strcat(row_str, "100\1");
       strcat(row_str, "2030\1\1\1");
  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
   }

if(PDMdebug_on)
{
MEMprint_buffer("file_list", file_list, PDM_DEBUG_FILE);
 }

/* Move the file using NFMlistener */

  status = _NFMfs_recv_files (&file_list);
  if (status != NFM_S_SUCCESS)
  {
      _PDMdebug (fname, "_NFMfs_recv_files 0x%.8x\n", status);
      _NFMfs_undo_recv_files (&file_list);
      return (status);
  }

  status = MEMclose (&file_list);
  if (status != MEM_S_SUCCESS)
    _PDMdebug (fname, "MEMclose 0x%.8x\n", status);

  _PDMdebug (fname, "EXIT: successful 0x%.8x\n", PDM_S_SUCCESS);
  return (PDM_S_SUCCESS);
}


/*** 
 
  This function will delete report file [template] from  reportslib storagearea.
  This is written for moving the report file generated by DBA (DB Access).


    1/9/92 - Kumar 
***/

long PDMdelete_ris_rpt (report )
char  *report;
{
  char *fname="PDMdelete_ris_rpt";
  char row_str[3048];
  char nodename[NFM_NODENAME+1], username[NFM_USERNAME+1], 
       passwd[NFM_PASSWD+1], pathname[NFM_PATHNAME+1], 
       devicetype[NFM_DEVICETYPE+1], machid[NFM_MACHID+1], 
       opsys[NFM_OPSYS+1], tcpip[NFM_TCPIP+1], xns[NFM_XNS+1], 
       decnet[NFM_DECNET+1], netware[NFM_NETWARE+1], 
       plattername [NFM_PLATTERNAME+1], partition[NFM_PARTITION+1], 
       nfs[NFM_NFS+1], compress[NFM_COMPRESS+1];
  long  sano = 0;
  long status;
  char file_name[15];
  MEMptr file_list = NULL;


  _PDMdebug ( fname, "ENTER: report[%s] \n", report);

    strcpy(file_name, report);

   if(!strcmp(file_name, ""))
       return(PDM_I_NO_REPORT);

  /* get to(checkin) storage area information */

  status = NFMget_storage_info ("RIS templates", &sano, nodename, username, passwd, 
                                pathname, devicetype, plattername, partition, 
                                nfs, compress, machid, opsys, tcpip, 
                                xns, decnet, netware);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMget_storage_info %s 0x%.8x\n", "reportslib", 
                status);
    return (status);
  }


  _PDMdebug (fname, "prepare file transfer buffer\n");

 status = NFMbuild_fto_buffer (&file_list, 0);
  if (status != NFM_S_SUCCESS)
  {
    _PDMdebug (fname, "NFMbuild_fto_buffer 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  } 
    row_str[0] = '\0';
  sprintf (row_str, 
  "%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s", 
  sano, 
  nodename, username, passwd, pathname, devicetype, plattername, partition, 
  nfs, compress, machid, opsys, tcpip, xns, decnet, netware, 
  "\1\1\1\1\1\1\1\1\1");

  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
  }
   
    row_str[0] = '\0';

/*
  sprintf (row_str, 
"%d\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1%s\1%s\1%s\1%s\1%s\1%s\1%s\1\1\1%s\1%s\1%\1100\12030\1\1\1", sano1, nodename1, username1, passwd1, pathname1, devicetype1, plattername1, partition1, nfs1, compress1, machid1, opsys1, tcpip1, xns1, decnet1, netware1, file_name, file_name);
 */
  sprintf (row_str, "\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1%s\1\1\1%d\1\1\1", file_name, 2044);
  _PDMdebug (fname, "MEMwrite %s\n", row_str);

  status = MEMwrite (file_list, row_str);
  if (status != MEM_S_SUCCESS)
  {
    _PDMdebug (fname, "MEMwrite 0x%.8x\n", status);
    MEMclose (&file_list);
    return (status);
   }

if(PDMdebug_on)
{
MEMprint_buffer("file_list", file_list, PDM_DEBUG_FILE);
 }

/* Delete  the files using NFMlistener */

  status = NFMrm_co_files (&file_list, 0);
  if (status != NFM_S_SUCCESS)
  {
      _PDMdebug (fname, "_NFMfs_recv_files 0x%.8x\n", status);
      return (status);
  }

      
  status = MEMclose (&file_list);
  if (status != MEM_S_SUCCESS)
    _PDMdebug (fname, "MEMclose 0x%.8x\n", status);

  _PDMdebug (fname, "EXIT: successful 0x%.8x\n", PDM_S_SUCCESS);
  return (PDM_S_SUCCESS);
}
