#/* $Id: makefile,v 1.1 2001/08/24 20:10:11 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        route/vrval/om/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/08/24 20:10:11  ahundiak
# *      ah
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 08/02/01  ah      creation
# ***************************************************************************/

TGT = vrivalom
include ${ROUTE_PATH}/etc/makefiles/lib_only.h
