# Do not alter this SPC information: $Revision: 1.24.3.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt
!include $(RISDEVDIR)\riscli\setup32\setupenv.nt


IPATH=  \
        -I"$(NT_SETUP_DIR)\csource" \
	-I"$(NT_SETUP_DIR)\isdklib" \
	-I..\..\..\riscom\internal \
        -I..\..\..\riscli\setup32\bldcui \
        -I..\..\..\riscli\setup32\remove \
        -I"$(NT_SETUP_DIR)\csource\bldcui" \
        -I"$(NT_SETUP_DIR)\remove" \
        -I"$(NT_SETUP_DIR)\licapi" \

NT_SETUPDIR_SETUP32 = $(NT_SETUP_DIR)\setup32
NT_SETUPDIR_CSOURCE= $(NT_SETUP_DIR)\csource
RISSETUP_CSOURCE_OBJ= $(RISDEVDIR)\riscli\setup32\CSOURCE\obj_nt

SETUP_OBJS= \
	$(OBJDIR)\ris.obj \
        $(OBJDIR)\rissrvc.obj \
        $(OBJDIR)\srvctl.obj 


#
# Be sure to remove the -DDONT_VERIFY tag below when building your
# procedure for real!
#
!if "$(DEBUG)" == "yes"
cflags = $(cflags) $(cdebug) $(cvars) -I"$(NT_SETUP_DIR)\setup32" -DDONT_VERIFY -DDEBUG -nologo -DRISCLI
lflags = $(ldebug) 
!else
#cflags = $(cflags) $(cdebug) $(cvars) -I$(NT_SETUP_DIR)\setup32 -DDONT_VERIFY -nologo
cflags = $(cflags) $(cdebug) $(cvars) -I"$(NT_SETUP_DIR)\setup32" -nologo -DRISCLI
# lflags = $(guilflags)
!endif


fast: ..\bin\$(BINDIR)\risshare.exe 

..\bin\$(BINDIR)\risshare.exe: $(SETUPSDK_OBJS) $(SETUP_OBJS) \
	..\bin\$(BINDIR)\rissetup.lib \
	"$(NT_SETUP_DIR)\setup32\ingrstf.lib" \
	$(NT_SETUP_LIBS) 
	@echo.
	@echo	SETUP_OBJS SETUPSDK_OBJS REMOVE_OBJS -to-  $@
	@$(link)			\
	$(guilflags)		\
	-machine:$(CPU)		\
	-out:$@	\
        $(OBJDIR)\ris.obj \
        $(SETUPSDK_OBJS) \
	..\bin\$(BINDIR)\rissetup.lib \
	"$(NT_SETUP_DIR)\setup32\ingrstf.lib" \
	"$(NT_SETUP_DIR)\licapi\dlbrand.lib" \
	"$(NT_SETUP_DIR)\csource\cingrdll.lib" \
	$(NT_SETUP_LIBS) \
        version.lib \
	advapi32.lib  \
	$(guilibsdll) 

..\bin\$(BINDIR)\rissetup.lib: $(OBJDIR)\rissetup.obj $(OBJDIR)\rissrvc.obj $(RISSETUP_CSOURCE_OBJ)\reglib.obj \
$(OBJDIR)\srvctl.obj
	@echo.
	@echo   $(OBJDIR)\rissetup.obj -to-   $@
	@dir/b/s $(OBJDIR)\rissetup.obj $(OBJDIR)\rissrvc.obj \
                $(OBJDIR)\reglib.obj $(OBJDIR)\srvctl.obj > libfiles.txt
	@if exist rissetup.lib del rissetup.lib
	@if exist ..\bin\$(BINDIR)\rissetup.lib del ..\bin\$(BINDIR)\rissetup.lib
	@lib /OUT:..\bin\$(BINDIR)\rissetup.lib @libfiles.txt
	@if exist libfiles.txt del libfiles.txt


#*************** RIS FILES IN CSOURCE ************/ 
$(OBJDIR)\ris.obj: risdpcom.h rissetup.h ris.h ris.c $(RISDEVDIR)\riscom\internal\risver.h setupver.h
	@echo.
	@echo 	ris.c  -to-  $@
	@$(cc) $(cflags) $(IPATH) ris.c /Fo$(OBJDIR)\ris.obj

$(OBJDIR)\risregdb.obj: risregdb.c $(RISDEVDIR)\riscom\internal\risver.h setupver.h
	@echo.
	@echo 	risregdb.c  -to-  $@
	@$(cc) $(cflags) $(IPATH) risregdb.c /Fo$(OBJDIR)\risregdb.obj

$(OBJDIR)\rissrvc.obj: rissrvc.c rissetup.h rissrvc.h \
	$(RISDEVDIR)\riscom\internal\risdebug.h \
	$(RISDEVDIR)\riscom\internal\risver.h 
	@echo.
	@echo 	rissrvc.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) rissrvc.c /Fo$(OBJDIR)\rissrvc.obj


$(OBJDIR)\shareapp.obj: shareapp.c
	@echo.
	@echo 	shareapp.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) shareapp.c /Fo$(OBJDIR)\shareapp.obj


$(OBJDIR)\rissetup.obj: rissetup.c setupver.h rissetup.h $(RISDEVDIR)\riscom\internal\risver.h 
	@echo.
	@echo 	rissetup.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) rissetup.c /Fo$(OBJDIR)\rissetup.obj

#******** FILES THAT ARE IN THE SETUPSDK PRODUCT  *****************************/
$(RISSETUP_CSOURCE_OBJ)\setupapi.obj: "$(NT_SETUPDIR_SETUP32)\setupapi.c" "$(NT_SETUPDIR_SETUP32)\setupapi.h"
	@echo.
	@echo 	setupapi.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) "$(NT_SETUPDIR_SETUP32)\setupapi.c" /Fo$(RISSETUP_CSOURCE_OBJ)\setupapi.obj

$(RISSETUP_CSOURCE_OBJ)\msdetect.obj: "$(NT_SETUPDIR_SETUP32)\msdetect.c" "$(NT_SETUPDIR_SETUP32)\msdetect.h" "$(NT_SETUPDIR_SETUP32)\setupapi.h"
	@echo.
	@echo 	msdetect.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) "$(NT_SETUPDIR_SETUP32)\msdetect.c" /Fo"$(RISSETUP_CSOURCE_OBJ)\msdetect.obj"

$(RISSETUP_CSOURCE_OBJ)\msregdb.obj: "$(NT_SETUPDIR_SETUP32)\msregdb.c" "$(NT_SETUPDIR_SETUP32)\msregdb.h" "$(NT_SETUPDIR_SETUP32)\setupapi.h"
	@echo.
	@echo 	msregdb.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) "$(NT_SETUPDIR_SETUP32)\msregdb.c" /Fo$(RISSETUP_CSOURCE_OBJ)\msregdb.obj

$(RISSETUP_CSOURCE_OBJ)\ingrext.obj: "$(NT_SETUPDIR_CSOURCE)\ingrext.c" "$(NT_SETUPDIR_CSOURCE)\ingrext.h"
	@echo.
	@echo 	ingrext.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) "$(NT_SETUPDIR_CSOURCE)\ingrext.c" /Fo$(RISSETUP_CSOURCE_OBJ)\ingrext.obj

$(RISSETUP_CSOURCE_OBJ)\dirops.obj: "$(NT_SETUPDIR_CSOURCE)\dirops.c"
	@echo.
	@echo 	dirops.c  -to-  $@
	@$(cc) $(cflags) $(IPATH) "$(NT_SETUPDIR_CSOURCE)\dirops.c" /Fo$(RISSETUP_CSOURCE_OBJ)\dirops.obj

$(RISSETUP_CSOURCE_OBJ)\shareapp.obj: "$(NT_SETUPDIR_CSOURCE)\shareapp.c"
	@echo.
	@echo 	shareapp.c  -to-  $@
	@$(cc) $(cflags) $(IPATH) "$(NT_SETUPDIR_CSOURCE)\shareapp.c" /Fo$(RISSETUP_CSOURCE_OBJ)\shareapp.obj

$(RISSETUP_CSOURCE_OBJ)\ingrbld.obj: "$(NT_SETUPDIR_CSOURCE)\ingrbld.c"
	@echo.
	@echo 	ingrbld.c  -to-  $@
	@$(cc) $(cflags) $(IPATH) "$(NT_SETUPDIR_CSOURCE)\ingrbld.c" /Fo$(RISSETUP_CSOURCE_OBJ)\ingrbld.obj

$(RISSETUP_CSOURCE_OBJ)\msdfunc.obj: "$(NT_SETUPDIR_CSOURCE)\msdfunc.c"
	@echo.
	@echo 	msdfunc.c  -to-  $@
	@$(cc) $(cflags) $(IPATH) "$(NT_SETUPDIR_CSOURCE)\msdfunc.c" /Fo$(RISSETUP_CSOURCE_OBJ)\msdfunc.obj

$(OBJDIR)\srvctl.obj: "$(SETUPSDK_DIR)\remove\srvctl.c" \
	"$(SETUPSDK_DIR)\remove\rmdefs.h" \
	"$(SETUPSDK_DIR)\remove\reglib.h" \
	"$(SETUPSDK_DIR)\remove\srvctl.h"
	@echo.
	@echo 	srvctl.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) "$(SETUPSDK_DIR)\remove\srvctl.c"
	@if exist $@ del $@
	@move $(@F) $@


$(RISSETUP_CSOURCE_OBJ)\reglib.obj: "$(SETUPSDK_DIR)\remove\reglib.c" \
	"$(SETUPSDK_DIR)\remove\rmdefs.h" \
	"$(SETUPSDK_DIR)\remove\reglib.h"
	@echo.
	@echo 	reglib.c -to-  $@
	@$(cc) $(cflags) -DCOMPILESETUP $(IPATH) "$(SETUPSDK_DIR)\remove\reglib.c"
	@if exist $@ del $@
	@move $(@F) $@



clean:
	@-del /Q $(OBJDIR)\*.*
        @-del ..\bin\$(BINDIR)\risshare.exe                
