# $Id: makefile,v 1.2 2001/03/30 20:25:26 ahundiak Exp $

# *************************************************************************
# I/VDS
#
#  File:        vdat/pcmk/makefile
#
#  Description:
#
#  Dependencies:
#
#  Revision History:
#       $Log: makefile,v $
#       Revision 1.2  2001/03/30 20:25:26  ahundiak
#       ah
#
#       Revision 1.1  2001/03/16 17:10:46  ahundiak
#       *** empty log message ***
#
#       Revision 1.2  2001/01/11 20:54:47  art
#       sp merge
#
# Revision 1.1  2000/06/27  17:34:38  pinnacle
# ah
#
#
# History:
# MM/DD/YY  AUTHOR  DESCRIPTION
# 06/27/00  ah	    Add ppl
# 01/11/01  ah      sp merge
# 03/30/01  ah      sp262 process
# ************************************************************************/

TGT     = vdiatpcmk2
TGT_PPL = vdiatppl

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfie pplmkfile *.e *.o 
	@rm -f VDefpSrfComp.c VDgeomNatEd2.c VDefpSrfTran.c VDatStdVer.c
