# $Id: makefile,v 1.1.1.1 2001/01/04 21:09:05 cvs Exp $

#***********************************************************************
# I/VDS
#
# File:		vdprotos/makefile
#
# Description:
#
# Dependencies:
#
# Revision History
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:09:05  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  14:51:18  pinnacle
# rep bin w/txt
#
# Revision 1.1  1995/11/29  14:24:46  pinnacle
# Created: ./vdprotos/makefile by azuurhou for vds.240
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	11/29/95	adz		creation date
#
#***********************************************************************

target : mkfile
	grmake -r -k -f mkfile 

mkfile : vdprotos.m
	grmakemake vdprotos.m mkfile
