# This is a sample file to get report of compartment

!col attr = family	width = 15 title = "Comp family"
!col attr = partno	width = 15 title = "Comp Partno"
!col attr = partrev	width = 10 title = "Comp partrev"
!col attr = name	width = 10 title = "Comp Name"
!col attr = location	width = 10 title = "Comp Location"

			=========================
			SAMPLE COMPARTMENT REPORT
			=========================
