# $Id: makefile,v 1.2 2001/05/03 13:03:14 ramarao Exp $

# -------------------------------------------------------------------
# I/STRUCT
#
# File:	struct/pplcmd/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/05/03 13:03:14  ramarao
#	Added a ppl ( COz_cmpPen.u ) to control the recompute of the penetration macros.
#	
#	Revision 1.1.1.1  2001/01/04 21:10:02  cvs
#	Initial import to CVS
#	
# Revision 1.1  1998/01/05  20:23:56  pinnacle
# Created: pplcmd/makefile by s250_int for struct
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

TGT = pplcmd

include ${STRUCT_PATH}/etc/makefiles/ppl_only.h
