/* $Revision: 1.1 $ */
#ifndef RAS_DLL
#define RAS_DLL

#include "ras_dll.h"
extern RAS_FUNCTION_TABLE *ras_func_tbl;

#define dba_attach_file_link               ras_func_tbl->f01
#define dba_attach_note                    ras_func_tbl->f02
#define dba_attach_user_link               ras_func_tbl->f03
#define dba_build_font_list                ras_func_tbl->f04
#define dba_build_note_list                ras_func_tbl->f05
#define dba_count_active_files             ras_func_tbl->f06
#define dba_display_graphics               ras_func_tbl->f07
#define dba_exit_graphics                  ras_func_tbl->f08
#define dba_register_raster                ras_func_tbl->f09
#define dba_fit                            ras_func_tbl->f10
#define dba_get_color                      ras_func_tbl->f11
#define dba_get_extents                    ras_func_tbl->f12
#define dba_get_font                       ras_func_tbl->f13
#define dba_get_level                      ras_func_tbl->f14
#define dba_get_line_width                 ras_func_tbl->f15
#define dba_get_notes                      ras_func_tbl->f16
#define dba_get_rl_text_size               ras_func_tbl->f17
#define dba_get_win_info                   ras_func_tbl->f18
#define dba_get_window                     ras_func_tbl->f19
#define dba_grab_rle                       ras_func_tbl->f20
#define dba_load_file                      ras_func_tbl->f21
#define dba_measure                        ras_func_tbl->f22
#define dba_pan                            ras_func_tbl->f23
#define dba_place_arc                      ras_func_tbl->f24
#define dba_place_arrow                    ras_func_tbl->f25
#define dba_place_circle                   ras_func_tbl->f26
#define dba_place_filled_circle            ras_func_tbl->f27
#define dba_place_filled_rectangle         ras_func_tbl->f28
#define dba_place_filled_shape             ras_func_tbl->f29
#define dba_place_line                     ras_func_tbl->f30
#define dba_place_rectangle                ras_func_tbl->f31
#define dba_place_shape                    ras_func_tbl->f32
#define dba_place_symbol                   ras_func_tbl->f33
#define dba_place_text                     ras_func_tbl->f34
#define dba_plot_window                    ras_func_tbl->f35
#define dba_quit                           ras_func_tbl->f36
#define dba_review_vector_element          ras_func_tbl->f37
#define dba_notify_raster                  ras_func_tbl->f38
#define dba_raster_fence                   ras_func_tbl->f39
#define dba_raster_fence_multi             ras_func_tbl->f40
#define dba_red_draw_ann_text              ras_func_tbl->f41
#define dba_red_draw_arc                   ras_func_tbl->f42
#define dba_red_draw_arrow                 ras_func_tbl->f43
#define dba_red_draw_circle                ras_func_tbl->f44
#define dba_red_draw_filled_circle         ras_func_tbl->f45
#define dba_red_draw_filled_rectangle      ras_func_tbl->f46
#define dba_red_draw_filled_shape          ras_func_tbl->f47
#define dba_red_draw_line                  ras_func_tbl->f48
#define dba_red_draw_rectangle             ras_func_tbl->f49
#define dba_red_draw_shape                 ras_func_tbl->f50
#define dba_red_draw_symbol                ras_func_tbl->f51
#define dba_red_draw_text                  ras_func_tbl->f52
#define dba_red_get_unique_filename        ras_func_tbl->f53
#define dba_red_hash_ascii_value           ras_func_tbl->f54
#define dba_rotate                         ras_func_tbl->f55
#define dba_scroll                         ras_func_tbl->f56
#define dba_set_color                      ras_func_tbl->f57
#define dba_set_font                       ras_func_tbl->f58
#define dba_set_level                      ras_func_tbl->f59
#define dba_set_line_width                 ras_func_tbl->f60
#define dba_set_rl_text_size               ras_func_tbl->f61
#define dba_show_links                     ras_func_tbl->f62
#define dba_update                         ras_func_tbl->f63
#define dba_window                         ras_func_tbl->f64
#define dba_window_area                    ras_func_tbl->f65
#define dba_window_center                  ras_func_tbl->f66
#define dba_window_name                    ras_func_tbl->f67
#define dba_zoom_in                        ras_func_tbl->f68
#define dba_zoom_out                       ras_func_tbl->f69
#define dba_g_fence_exists                 ras_func_tbl->f70
#define dba_g_build_fence                  ras_func_tbl->f71
#define dba_review_raster_element          ras_func_tbl->f72
#define dba_locate_raster_graphics         ras_func_tbl->f73
#define dba_g_attach_linkage               ras_func_tbl->f74
#define dba_g_remove_linkage               ras_func_tbl->f75
#define dba_g_remove_fence                 ras_func_tbl->f76
#define dba_g_process_event                ras_func_tbl->f77
#define dba_g_reset_dmredl                 ras_func_tbl->f78
#define dba_g_load                         ras_func_tbl->f79
#define dba_g_init                         ras_func_tbl->f80
#define dba_g_exit                         ras_func_tbl->f81
#define dba_ras_get_functions              ras_func_tbl->f82
#define dba_place_ellipse                  ras_func_tbl->f83
#define dba_place_filled_ellipse           ras_func_tbl->f84
#define dba_place_freehand                 ras_func_tbl->f85
#define dba_red_draw_ellipse               ras_func_tbl->f86
#define dba_red_draw_filled_ellipse        ras_func_tbl->f87
#define dba_red_draw_freehand              ras_func_tbl->f88
#define dba_locate_vector_graphics         ras_func_tbl->f89

#endif
