#define ERR_MSG1 "No pseudo-terminal device available."
#define ERR_MSG3 "Error creating window."
#define ERR_MSG4 "Error in VT220 initialization."
#define ERR_MSG6 "Error opening specified pseudo-terminal device."
#define ERR_MSG17 "Error opening auxiliary port."
#define ERR_MSG18 "Error reading catalog file."
#define ERR_MSG19 "Error opening catalog file."
#define ERR_MSG20 "Error displaying catalog menu."
#define ERR_MSG21 "Error reading catalog menu."
#define ERR_MSG22 "Error deleting catalog file."
#define ERR_MSG23 "Error writing to catalog file."
#define ERR_MSG24 "Error creating catalog file."
#define ERR_MSG25 "Error read options menu file."
#define ERR_MSG26 "Error reading terminal menu file."
#define ERR_MSG27 "Error creating hostnames file."
#define ERR_MSG28 "Error executing vterm."
#define ERR_MSG30 "Error loading default font."
#define ERR_MSG31 "Error opening printer port."
#define ERR_MSG32 "Error displaying specified menu."
#define ERR_MSG33 "Invalid username/password."
#define ERR_MSG34 "Error reading password menu file."
#define ERR_MSG35 "Error reading username menu file."
#define ERR_MSG37 "Host auxport number and printer auxport number must be different."
#define ERR_MSG38 "Host auxport number out of range."
#define ERR_MSG39 "Printer auxport number out of range."
#define ERR_MSG40 "Console must be a local terminal (-l)."
#define ERR_MSG41 "Username/password used only with command option (-x)."
#define ERR_MSG42 "Vterm must have root privileges."
#define ERR_MSG43 "Error displaying RS232 menu."
#define ERR_MSG44 "Error reading RS232 menu."
