/*
  Functions which write info about mapping of colors, layers and 
  material properties
*/
#include <stdio.h>
#include "sys/stat.h"
#include "OMminimum.h"
#include "OMprimitives.h"
#include "exmacros.h"
#include "msdef.h"
#include "igetypedef.h"
#include "igrtypedef.h"
#include "gr.h"

#include "wl.h"
#include "igecolor.h"
#include "igecolmacros.h"

#include "vderrmacros.h"
#include "SFdef.h"


static short activeLayer = -1;


/*
  color is always layer%12
*/

long SFgetNBfile (
  char		*filename
)
{
long  		sts;
struct GRid	mod_id;
int		len, startChar;


   if ( !filename ) { sts = 0; goto wrapup; }

   sts = 1;
   sts = ex$get_cur_mod ( id = &mod_id.objid,
			  osnum = &mod_id.osnum );
   if ( !(sts&1) ) { sts = 0; goto wrapup; }
   sts = VDget_filename_from_os ( mod_id.osnum, filename );
   if ( !(sts&1) ) { sts = 0; goto wrapup; }

   len = strlen ( filename );
   if ( len == 14 )
   {
      if ( filename[11] == '.' &&
	   filename[12] == 'N' &&
	   filename[13] == 'B'    )
      {
	sts = 0;
	goto wrapup;
      }
   }

   startChar = ( len > 11 ) ? 11 : len;
   strcpy ( &filename[startChar], ".NB" );
   __DBGpr_str ( "filename", filename );

wrapup:
   return sts;
}


/*
  gets the next layer and color that is to be used for
  trace curves.
*/

long  SFgetNextLayerAndColor (
 long			*msg,
 short			*layer,  /* O */
 short unsigned		*color   /* O */
)
{
long 			sts, ii;
char			filename[15], bmstr[81], prpstr[81];
FILE			*fp = NULL;

   if ( !msg || !layer || !color )
   {
     *msg = MSINARG;
     sts = OM_E_INVARG;
     goto wrapup;
   }

   sts = OM_S_SUCCESS;
   *msg = MSSUCC;

   /* if activeLayer != -1, it is incremented and used.
      if activeLayer == -1, try to read from file and make the last
			    layer the active layer.
			    If file not found or no entries in file
			    activeLayer = 99;
   */
   if ( activeLayer == - 1 )
   {
     struct stat Statbuf;

     activeLayer = 99;
     sts = SFgetNBfile ( filename );
     if ( !(sts&1) ) goto wrapup;

     if ( (stat(filename,&Statbuf)<0 ? 0:Statbuf.st_mode) )
     {
	if(  (fp = (FILE *)fopen( filename, "r" )) == NULL )
	{
	   printf("Can not open file [%s] for reading\n", filename);
	   sts = 0;
	   goto wrapup;
	}

	/* skip header info */
	for ( ii=0; ii<5; ii++ )
	  if ( !fgets( bmstr, 81, fp ) ) goto MARCH_AHEAD;

	bmstr[0] = '\0';
	while ( fgets( bmstr, 81, fp) && fgets(prpstr, 81, fp) )
	{ /* do nothing */ }
	fclose ( fp );

	if ( bmstr[0] != '\0' )
	{
	   sscanf( bmstr, "%*s %*s %*s %hd", &activeLayer );
	}
     } /* if ( (stat(filename,&Statbuf)<0 ? 0:Statbuf.st_mode) ) */
   } /* if ( activeLayer == - 1 ) */

MARCH_AHEAD:
   activeLayer = (activeLayer + 1) % 1024;

   *layer = activeLayer;
   *color = activeLayer % 12;

wrapup:
   __DBGpr_int ("BeamActiveLayer" , *layer );
   __DBGpr_int ("BeamActiveColor" , *color );
   if ( fp ) fclose ( fp );
   return sts;
}

/*
   writes to file
*/

long  SFwriteToNBfile(
 long			*msg,
 char			*prpName,  /* I */
 short			layer,     /* I */
 short unsigned		color,     /* I */
 char			BeamOrStfnr  /* (I) = 0 beam, = 1 stiffener */
)
{
long		sts;
char		filename[15], clrname[20];
FILE		*fp = NULL;
struct stat	Statbuf;

   if ( !msg || !prpName )
	{ *msg = MSINARG; sts = OM_E_INVARG; goto wrapup; }

   sts = OM_S_SUCCESS;
   *msg = MSSUCC;

   sts = SFgetNBfile ( filename );
   if ( !(sts&1) ) goto wrapup;

   /* write header if creating for first time */
   if ( stat(filename,&Statbuf) < 0 )
   {
      if ( (fp = (FILE *) fopen( filename, "a" )) == NULL )
      {
	printf("Can not open [%s] for appending\n", filename);
	goto wrapup;
      }

      fprintf(fp,
	"#\n#  File containing mapping of levels and properties\n");
      fprintf(fp,"#  when beams/stiffeners are extracted as trace curves.\n");
      fprintf(fp,"#   ****  PLEASE DO NOT EDIT THIS FILE  ****\n#\n");
      fclose(fp);
   }

   if ( (fp = (FILE *) fopen( filename, "a" )) == NULL )
   {
      printf("Can not open [%s] for appending\n", filename);
      goto wrapup;
   }

   clrname[0] = '\0';
   sts = ige$get_name_from_color( color = color,
				  name  = clrname );
   /* Sometimes there may not be name for color. Assign SUCCESS to sts */ 
   sts = OM_S_SUCCESS;


   if ( BeamOrStfnr == SF_BEAM )
   {
      fprintf(fp, "Beams on Layer\t%hd and Color\t%d",
			layer, (int) color );
      if ( clrname[0] != '\0' )
	fprintf( fp, " [%s]\n", clrname );
      else
	fprintf( fp, "\n", clrname );
      fprintf(fp,"\tProperty Name\t=\t[%s]\n", prpName);
   }
   else
   {
      fprintf(fp, "Stiffeners on Layer\t%hd and Color\t%d",
			layer, (int) color );
      if ( clrname[0] != '\0' )
	fprintf( fp, " [%s]\n", clrname );
      else
	fprintf( fp, "\n", clrname );
      fprintf(fp,"\tProperty Name\t=\t%s\n", prpName);
   }

   fclose ( fp );

wrapup:
   return sts;
}

/*
   for a given property, this tries to get layer and color from the file.
*/
long SFgetLayerFromPrpName (
 long			*msg,
 char			*prpName, /* I */
 short			*layer,   /* O */
 short unsigned		*color,   /* O */
 char			*found    /* O */
)
{
long		sts, ii;
struct stat	Statbuf;
char		filename[15], bmstr[81], prpstr[81], PrpNameRead[20];
FILE		*fp = NULL;

   if ( !msg || !prpName || !layer || !color || !found )
   {
     *msg = MSINARG;
     sts = OM_E_INVARG;
     goto wrapup;
   }

   sts = OM_S_SUCCESS;
   *msg = MSSUCC;

   sts = SFgetNBfile ( filename );
   if ( !(sts&1) ) goto wrapup;

   *found = FALSE;
   if ( (stat(filename,&Statbuf)<0 ? 0:Statbuf.st_mode) )
   {
	if(  (fp = (FILE *)fopen( filename, "r" )) == NULL )
	{
	   printf("Can not open file [%s] for reading\n", filename);
	   goto MARCH_AHEAD;
	}

	/* skip header info */
	for ( ii=0; ii<5; ii++ )
	  if ( !fgets( bmstr, 81, fp ) ) goto MARCH_AHEAD;

	PrpNameRead[0] = '\0';
	while ( fgets( bmstr, 81, fp) && fgets( prpstr, 81, fp) )
	{
	   sscanf( prpstr, "%*s %*s %*s %s", PrpNameRead );
	   if ( !strcmp( prpName, PrpNameRead ) )  break;
	}

	if ( !strcmp(prpName, PrpNameRead) )
	{
	   sscanf( bmstr, "%*s %*s %*s %hd", layer );
	   *found = TRUE;
	}
   } /* if ( (stat(filename,&Statbuf)<0 ? 0:Statbuf.st_mode) ) */

MARCH_AHEAD:
   if ( *found == FALSE )
   {
	if ( activeLayer == -1 )
	   activeLayer = 100;
	else
	   activeLayer = (activeLayer + 1) % 1024;

	*layer = activeLayer;
   }
   *color = (*layer) % 12;
   if ( fp != NULL ) fclose ( fp );

wrapup:
   return sts;
}
