# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:38 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/smstrsf/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:07:38  cvs
#	Initial import to CVS
#	
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target: mkfile  
	grmake -r -k -f mkfile 


mkfile : smstrsfimp.m
	grmakemake smstrsfimp.m mkfile

clean:
	@rm -f mkfile *.o *.c

