SRC
$(MODEL)/src_dpr/imp
OPP
$(EXTARG)/bin/opp
OMCPP
$(EXTARG)/bin/omcpp
INCLUDE
$(INGRHOME)/include
$(XINC)
$(GRNUC)/ingrsys
$(MODEL)/include
$(EXNUC)/include
$(GRNUC)/include
$(BS)/include
$(BS)/include/prototypes
$(BS)/include/prototypes
#if defined (XGL)
$(XGLHOME)/include
$(XGLHOME)/include/xgl
#endif
SPEC
$(EXNUC)/spec
$(GRNUC)/spec
$(MODEL)/spec
LIB
$(MDTARG)/src_lib/EMSdprI.o
SOURCE=grp1
EMaddnode.I
EMaddraftdim.I
EMaddraftgoi.I
EMadrtact.I
EMadrtadrng.I
EMadrtchgx.I
EMadrtckovlp.I
EMadrtdeact.I
EMadrtgetSSI.I
EMadrtgeting.I
EMadrtgtSSIb.I
EMadrtgtSSIs.I
EMadrtgtiinf.I
EMadrtgtoinf.I
EMadrtintcp.I
EMadrtputSSI.I
EMadrtslclas.I
EMadrtsvstdl.I
EMadrtxform.I
EMboolfeagoi.I
EMcapact.I
EMcapckovlp.I
EMcapdeact.I
EMcapgetSSI.I
EMcapgeting.I
EMcapgtSSIb.I
EMcapgtSSIs.I
EMcapgtinif.I
EMcapinit.I
EMcapintcp.I
EMcapputSSI.I
EMcaprstSSI.I
EMcapslclas.I
EMcapsvstdl.I
EMconn_edgs.I
EMdlft_act.I
EMdlft_deac.I
EMdlft_face.I
EMdprLocOwn.I
EMdpractprim.I
EMdprchgcl.I
EMdprckrngov.I
EMdprclcpinf.I
EMdprclnSSI.I
EMdprcmpntch.I
EMdprcontop.I
EMdprcorornt.I
EMdprdeactst.I
EMdprdebug.I
EMdprdelete.I
EMdprdelfea.I
EMdprdisyou.I
EMdprevalops.I
EMdprgetcinx.I
EMdprgetfea.I
EMdprgetminf.I
EMdprgetmrng.I
EMdprgetprop.I
EMdprgetsids.I
EMdpri.I
EMdprlmtree.I
EMdprlocate.I
EMdprmkprim.I
EMdprndbroke.I
EMdpropndchg.I
EMdprpass.I
EMdprpreprx.I
EMdprputcinx.I
EMdprrecover.I
EMdprredo.I
EMdprreex.I
EMdprridel.I
EMdprsendmac.I
EMdprsetprop.I
EMdprsvstdel.I
EMdprtogornt.I
EMdprtreecln.I
EMdprundo.I
EMetcopy.I
EMetdelete.I
EMetdisplay.I
EMetdisyours.I
EMetinit.I
EMetxform.I
EMfeacreatn.I
EMgmaddwrng.I
EMgmintcopy.I
EMlf_addwrng.I
EMlf_getSSI.I
EMlf_getSSIb.I
EMlf_getSSIs.I
EMlf_intcopy.I
EMlf_putSSI.I
EMlf_svstdel.I
EMlf_xform.I
EMlft_act.I
EMlft_deac.I
EMlft_ed.I
EMlft_exec.I
EMlft_face.I
EMlft_vert.I
EMlftckovlap.I
EMlftcontop.I
EMlftgetcinx.I
EMlftgetingm.I
EMlftgetmdsf.I
EMlftgetminf.I
EMlftgetpath.I
EMlftgtininf.I
EMlftgtotinf.I
EMlftintact.I
EMlftintdeac.I
EMlftmatch.I
EMlftndbroke.I
EMlftobjinf.I
EMlftputcinx.I
EMlftsfoprim.I
EMmacfeagoi.I
EMmacrogoi.I
EMmfgetmdsf.I
EMmkfact.I
EMmkfckovlap.I
EMmkfcontop.I
EMmkfdeact.I
EMmkfgetSSI.I
EMmkfgetSSIb.I
EMmkfgetSSIs.I
EMmkfgetingm.I
EMmkfgetpath.I
EMmkfgrexit.I
EMmkfgtininf.I
EMmkfgtotinf.I
EMmkfintcopy.I
EMmkfmatch.I
EMmkfputSSI.I
EMmkfrstSSI.I
EMmkfsvstdel.I
EMmkftrackpt.I
EMmultundo.I
EMmvckovlap.I
EMmvgetSSI.I
EMmvgetSSIb.I
EMmvgetSSIs.I
EMmvgetmdsf.I
EMmvgetminf.I
EMmvintcopy.I
EMmvputSSI.I
EMpartsupp.I
EMpholecopy.I
EMpribcopy.I
SOURCE=grp2
EMpslotcopy.I
EMptcomp.I
EMptplace.I
EMrembound.I
EMribkey.I
EMrnd_act.I
EMrnd_auttrm.I
EMrnd_bndxyz.I
EMrnd_chgx.I
EMrnd_clean.I
EMrnd_deact.I
EMrnd_definf.I
EMrnd_disjnt.I
EMrnd_exec.I
EMrnd_grexit.I
EMrnd_lsadd.I
EMrnd_props.I
EMrnd_reeval.I
EMrnd_round.I
EMrndbdim.I
EMrndckovlap.I
EMrndconsass.I
EMrndcontop.I
EMrnddeact.I
EMrnddim.I
EMrndfix_bnd.I
EMrndgetSSI.I
EMrndgetSSIb.I
EMrndgetSSIs.I
EMrndgetingm.I
EMrndgetmdsf.I
EMrndgetminf.I
EMrndgetpath.I
EMrndgtininf.I
EMrndgtotinf.I
EMrndintcopy.I
EMrndmatch.I
EMrndprepssi.I
EMrndputSSI.I
EMrndround.I
EMrndsvstdel.I
EMsf_lslclas.I
EMsfaddraft.I
EMsfbBool.I
EMsfbDBool.I
EMsfbDlDjAr.I
EMsfbNull.I
EMsfbXtOpTyp.I
EMsfbact.I
EMsfbatbrkup.I
EMsfbcanrc.I
EMsfbchgx.I
EMsfbchkslvr.I
EMsfbckovlap.I
EMsfbcontop.I
EMsfbdeact.I
EMsfbfeainf.I
EMsfbfixSSI.I
EMsfbgetRI.I
EMsfbgetSSI.I
EMsfbgetSSIb.I
EMsfbgetSSIs.I
EMsfbgetacid.I
EMsfbgetcinx.I
EMsfbgetingm.I
EMsfbgetmdsf.I
EMsfbgetminf.I
EMsfbgetmrng.I
EMsfbgpcht.I
EMsfbgtininf.I
EMsfbgtotinf.I
EMsfbgtunevl.I
EMsfbinit.I
EMsfbislm.I
EMsfbjbool.I
EMsfbmatch.I
EMsfbndbroke.I
EMsfbobjinfo.I
EMsfboffset.I
EMsfbprtrd.I
EMsfbputRI.I
EMsfbputSSI.I
EMsfbputcinx.I
EMsfbrebool.I
EMsfbreex.I
EMsfbremopnd.I
EMsfbridel.I
EMsfbrsetSSI.I
EMsfbsfoprim.I
EMsfbslclass.I
EMsfbsvstdel.I
EMsfbtogkdf.I
EMsfbtogornt.I
EMsfbxform.I
EMsfdadd.I
EMsfdaddmgr.I
EMsfdbact.I
EMsfdbadrng.I
EMsfdbchgx.I
EMsfdbckovlp.I
EMsfdbdeact.I
EMsfdbfixSSI.I
EMsfdbgetSSI.I
EMsfdbgeting.I
EMsfdbgtSSIb.I
EMsfdbgtSSIs.I
EMsfdbgtinif.I
EMsfdbgtotif.I
EMsfdbintcp.I
EMsfdbputSSI.I
EMsfdbrstSSI.I
EMsfdbsfoprm.I
EMsfdbsvstdl.I
EMsfdbxform.I
EMsfdcanrc.I
EMsfdckovlap.I
EMsfdcomprcp.I
EMsfddrop.I
EMsfdgetingm.I
EMsfdgetpath.I
EMsfdgetprim.I
EMsfdgtinfcm.I
EMsfdisact.I
EMsfdlslclas.I
EMsfdpri.I
EMsfdprval.I
EMsfdrstSSI.I
EMsfdsfoprim.I
EMsfdtogkdf.I
EMsfeinit.I
EMsffeaconst.I
EMsffeaovrid.I
EMsfffixingm.I
EMsffmatch.I
EMsfhcanrc.I
EMsfhckovlap.I
EMsfhdeactst.I
EMsfhgetSSI.I
EMsfhgetSSIb.I
EMsfhgetacid.I
EMsfhgetpath.I
EMsfhislm.I
EMsfhputSSI.I
EMsfhredo.I
EMsfhslclass.I
EMsfhundo.I
EMsfibgeting.I
EMsfllmtree.I
EMsfmacroi.I
EMsfmcreate.I
SOURCE=grp3
EMsfmfeainf.I
EMsfmgetpath.I
EMsfmkface.I
EMsfmkslclas.I
EMsfmundo.I
EMsfmv_act.I
EMsfmv_add.I
EMsfmv_deact.I
EMsfmv_exec.I
EMsfmvlmtree.I
EMsfmvobjin.I
EMsfmvslclas.I
EMsfrdslclas.I
EMsfrndi.I
EMsfscontop.I
EMsfsgtininf.I
EMsfsgtotinf.I
EMsfsgtunevl.I
EMsfsp_act.I
EMsfsp_deact.I
EMsfsp_splsf.I
EMsfsp_ssdel.I
EMsfsp_topol.I
EMsfspslclas.I
EMsfstSSIb.I
EMsfstSSIs.I
EMsfstact.I
EMsfstdeact.I
EMsfstdebug.I
EMsfstgetSSI.I
EMsfstgetids.I
EMsfstintcp.I
EMsfstmkcomp.I
EMsfstogkdf.I
EMsfstputSSI.I
EMsfstslclas.I
EMsfstsvsdel.I
EMshintcopy.I
EMshslbool.I
EMshslckovlp.I
EMshsldeact.I
EMshsldim.I
EMshslgeting.I
EMsibact.I
EMsibckovlap.I
EMsibcontop.I
EMsibdeact.I
EMsibgetss.I
EMsibgtininf.I
EMsibgtotinf.I
EMsibinit.I
EMsibintcopy.I
EMsibslclass.I
EMsibtrackpt.I
EMslb2ClSf.I
EMslbgetRI.I
EMslboolfeai.I
EMslbopndchg.I
EMslfeadeact.I
EMslfeaovrid.I
EMslfgetingm.I
EMslholeseli.I
EMslmacfeai.I
EMslotkey.I
EMslslogingm.I
EMslslotdeac.I
EMslslotfeai.I
EMspaddwrng.I
EMspgetmdsf.I
EMspintcopy.I
EMsplchgx.I
EMsplckovlap.I
EMsplgetSSI.I
EMsplgetSSIb.I
EMsplgetSSIs.I
EMsplgetcinx.I
EMsplgetminf.I
EMsplgetown.I
EMsplgetpath.I
EMsplndbroke.I
EMsplputSSI.I
EMsplputcinx.I
EMsplsfoprim.I
EMsplxform.I
EMsrmgetSSI.I
EMsrmgetSSIb.I
EMsrmgetSSIs.I
EMsrmgetminf.I
EMsrmprepssi.I
EMsrmputSSI.I
EMsrmsvstdel.I
EMstckovlap.I
EMstgetminf.I
EMsugetprop.I
EMsuppress.I
EMswsact.I
EMswsdeact.I
EMswsimplem.I
EMswsreex.I
EMswsspltwsf.I
EMswsundo.I
EMunitesf.I
EMunsfact.I
EMunsfadrng.I
EMunsfchgx.I
EMunsfckovlp.I
EMunsfdeact.I
EMunsfgetSSI.I
EMunsfgeting.I
EMunsfgtSSIb.I
EMunsfgtSSIs.I
EMunsfgtinif.I
EMunsfgtotif.I
EMunsfintcp.I
EMunsfputSSI.I
EMunsfrstSSI.I
EMunsfsfoprm.I
EMunsfslclas.I
EMunsfsvstdl.I
EMunsfxform.I
EMxsSSIi.I
EMxsacinacs.I
EMxsact.I
EMxsdeact.I
EMxsgetminf.I
EMxsgetrmeds.I
EMxssvstdel.I
EMxstGRcopy.I
EMxstdeacxs.I
EMxstdelete.I
EMxstgetased.I
EMxstintcopy.I
