Create_pd() { printf("Create_pd() is stubed out in xgrstubs.c ! \n"  ); };
Activate_pde_index() { printf("Activate_pde_index() is stubed out in xgrstubs.c ! \n"  ); };
Deactivate_pde_index() { printf("Deactivate_pde_index() is stubed out in xgrstubs.c ! \n"  ); };
Process_pd() { printf("Process_pd() is stubed out in xgrstubs.c ! \n"  ); };
Delete_pde_index() { printf("Delete_pde_index() is stubed out in xgrstubs.c ! \n"  ); };
Add_pde_bottom() { printf("Add_pde_bottom() is stubed out in xgrstubs.c ! \n"  ); };
Wait_timer() { printf("Wait_timer() is stubed out in xgrstubs.c ! \n"  ); };
mouse_position() { printf("mouse_position() is stubed out in xgrstubs.c ! \n"  ); };
drawsymbols() { printf("drawsymbols() is stubed out in xgrstubs.c ! \n"  ); };
Load_symbol_file() { printf("Load_symbol_file() is stubed out in xgrstubs.c ! \n"  ); };
Create_win_user_icon() { printf("Create_win_user_icon() is stubed out in xgrstubs.c ! \n"  ); };
Set_win_user_icon() { printf("Set_win_user_icon() is stubed out in xgrstubs.c ! \n"  ); };
Update_win_icon() { printf("Update_win_icon() is stubed out in xgrstubs.c ! \n"  ); };
defcursor() { printf("defcursor() is stubed out in xgrstubs.c ! \n"  ); };
Set_win_button_mode() { printf("Set_win_button_mode() is stubed out in xgrstubs.c ! \n"  ); };
blockrestore() { printf("blockrestore() is stubed out in xgrstubs.c ! \n"  ); };
blocksave() { printf("blocksave() is stubed out in xgrstubs.c ! \n"  ); };
keybd_bell() { printf("keybd_bell() is stubed out in xgrstubs.c ! \n"  ); };
enableplane() { printf("enableplane() is stubed out in xgrstubs.c ! \n"  ); };
blendarea() { printf("blendarea() is stubed out in xgrstubs.c ! \n"  ); };
texture() { printf("texture() is stubed out in xgrstubs.c ! \n"  ); };
Set_win_buffer_size() { printf("Set_win_buffer_size() is stubed out in xgrstubs.c ! \n"  ); };
Set_win_name() { printf("Set_win_name() is stubed out in xgrstubs.c ! \n"  ); };
Error_box() { printf("Error_box() is stubed out in xgrstubs.c ! \n"  ); };
Mouse_win_position() { printf("Mouse_win_position() is stubed out in xgrstubs.c ! \n"  ); };
enter_db() { printf("enter_db() is stubed out in xgrstubs.c ! \n"  ); };
exit_db() { printf("exit_db() is stubed out in xgrstubs.c ! \n"  ); };
pnt() { printf("pnt() is stubed out in xgrstubs.c ! \n"  ); };
Inq_events() { printf("Inq_events() is stubed out in xgrstubs.c ! \n"  ); };
Inq_button_data() { printf("Inq_button_data() is stubed out in xgrstubs.c ! \n"  ); };
Get_button_data() { printf("Get_button_data() is stubed out in xgrstubs.c ! \n"  ); };
linestring() { printf("linestring() is stubed out in xgrstubs.c ! \n"  ); };
Mouseposition() {printf("Mouseposition() is stubed out in xgrstubs.c ! \n"  ); };
Inq_displayed_vs() {printf("Inq_displayed_vs() stubed in xgrstubs.c \n"); };
Inq_message_location() {printf("Inq_message_loc() stubed in xgrstubs.c \n"); };
drawbitmap() {printf("drawbitmap() stubed in xgrstubs.c \n"); };

