# $Id: makefile,v 1.1.1.1 2001/01/04 21:09:25 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vdsymbhold/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:09:25  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  14:52:08  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target: mkfile 
	grmake -r -k -f mkfile

mkfile: vdsymbhold.m
	grmakemake vdsymbhold.m mkfile
