# $Id: makefile,v 1.1.1.1 2001/01/04 21:09:33 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdweld/cmd/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:09:33  cvs
#	Initial import to CVS
#	
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdweldcmd.m
	grmakemake vdweldcmd.m mkfile
