SRC
$(MODEL)/src_co_mass/imp
OPP
$(EXTARG)/bin/opp
OMCPP
$(EXTARG)/bin/omcpp
INCLUDE
$(INGRHOME)/include
$(GRNUC)/ingrsys
$(MODEL)/include
$(EXNUC)/include
$(GRNUC)/include
$(BS)/include
$(BS)/include/prototypes
SPEC
$(MODEL)/src_co_mass/spec
$(EXNUC)/spec
$(GRNUC)/spec
$(MODEL)/spec
LIB
$(MDTARG)/src_lib/EMScomassI.o
SOURCE
ECdensityi.I
ECmassmanipi.I
ECmasspi.I
