[
n_catalogname(char[12])=stotank
n_catalogdesc(char[100])=equipment
n_cofilename(char[14])=Equipment
n_itemdesc(char[40])=equipment
v_product(char[10])=EQUIPMENT
v_dynamictbl(char[18])=EQUIP_DYNAMIC
v_schdyntbl(char[18])=SCH_EQP_DYNAMIC
v_cittbl(char[18])=EQUIP_CIT
v_pplfile(char[12])=equip_ppl
p_level1(char[40])=EQUIPMENT
p_d1|ref(referential)=ref
p_s2|lo(double)=lo
p_s3|l(double)=l
p_s4|h1(double)=h1
p_s5|ang(double)=ang
p_s6|dn1(double)=dn1
p_s7|dn4(double)=dn4
p_s8|off_noz(double)=off_noz
p_s9|off_pd(double)=off_pd
p_s10|d_pd(double)=d_pd
p_s11|lg_pd(double)=lg_pd
p_s12|noz_len(double)=noz_len
p_v1|system_name(char[12])=System Name
p_v2|tag_number(char[12])=Tag Number
p_v3|comp_note(char[29])=Note
p_v4|a_carlinguer(char[8])=A Carlinguer
p_v5|a_refrigerer(char[8])=A Refrigerer
p_v6|unit_number(char[8])=Unit Number
p_v7|original(smallint)=Original[1]
p_v8|apprv_stat(char[8])=Approval Status[NA]
p_v9|constr_stat(char[8])=Construction Status[N]
p_v10|envelope(real)=Envelope[50]
p_v11|compart_x(char[40])=Compartment
p_v12|deck_x(char[40])=Deck
p_v13|trans_ref(char[8])=Transversal ref
p_v14|longi_ref(char[8])=Longitudinal ref
p_v15|deck_ref(char[8])=Deck ref
p_v16|montage(char[16])=montage[site]
p_v17|ref_plan(char[35])=Ref Plan Number
p_v18|no_mto_flag(char[1])=MTO[N]
p_v19|grp(char[12])=Group
p_v20|insul_type(char[8])=Insulation Type[N]
p_v21|insul_thk(real)=Insulation Thickness[0]
p_v22|zone_number(char[14])=Zone Number
p_v23|layout_id(char[14])=Layout Id
p_v24|support(char[14])=Supporting Structure
p_u0|n_itemname(char[32])=Part Number
p_u0|n_itemrev(char[15])=Part Revision
p_u0|n_itemdesc(char[40])=Part Description
p_u0|n_creator(char[14])=Creator
p_u0|n_creationdate(char[10])=Part Creation Date
p_u0|p_parttype(char[1])=Part Type
p_u0|p_macro(char[20])=Macro Name
p_u0|design(char[20])=Design
p_u0|nom_capacity(double)=Nominal Capacity
p_u0|max_capacity(double)=Maximum Capacity
p_u0|nom_pressure(double)=Nominal Pressure
p_u0|max_pressure(double)=Maximum Pressure
p_u0|material(char[20])=Material
p_u0|jacket(char[20])=Jacket Type
p_u0|heating_method(char[20])=Heating Method
p_u0|cooling_method(char[20])=Cooling Method
p_u0|elec_consum(double)=Electric Consumption
p_u0|dry_weight(double)=Dry Weight
p_u0|wet_weight(double)=Wet Weight
p_u0|manufacturer(char[20])=Manufacturer
p_u0|model(char[20])=Model
p_u0|class(char[20])=Class
p_u0|commodity(char[20])=Commodity Code
p_u0|short_desc(char[40])=Short Description
p_u0|descript(char[80])=Description
p_u0|alt_desc(char[80])=Alternate Description
p_u0|units_set(smallint)=Units Set
p_u0|cogl_x(double)=x coord of local cog
p_u0|cogl_y(double)=y coord of local cog
p_u0|cogl_z(double)=z coord of local cog
p_u0|overall_x(double)=x overall dimension
p_u0|overall_y(double)=y overall dimension
p_u0|overall_z(double)=z overall dimension
p_f0|n_cofilename(char[14])=Local File Name
]
