#!/bin/ksh
#
# Remove - Remove software products
# Copyright 1990 Intergraph Corporation
#

id | grep uid=0 >/dev/null
[ $? -ne 0 ] && echo "Must be super-user." && exit 1

SESSION=$$
ENV=""
export SESSION ENV
STTY=`stty -g`

listoproducts=""
for i in $*
do
    if [ "$i" = "-y" ]
    then
	justdoit=y
	export justdoit
    else
	listoproducts="$listoproducts $i"
    fi
done

case `uname` in
CLIX)
    PLATFORM=CLIX
#   RM=/usr/ip32/deltools/.remove
    RM=`grep deltools /usr/ip32/ingrconfig | cut -d"#" -f6`/.remove
    SHELL=/bin/ksh
    FMLIDIR=/usr/bin
    PDDIR=/usr/bin
    set `who -r`
    runlevel=$3

    if [ $runlevel = S ]
    then
	TERM=vt100-fmli.bs
    else
	TERM=vt100-fmli
    fi

    LINES=${LINES:=24}
    COLUMNS=${COLUMNS:=80}
    export TERM LINES COLUMNS
    ;;
    
SunOS)
    case `uname -r` in
    5.*)
	PLATFORM=Solaris
	INGRHOME=${INGRHOME%%:*}
	INGRHOME=${INGRHOME:=/opt/ingr}
	export INGRHOME
#	RM=$INGRHOME/deltools/.remove	
	RM=`grep deltools $INGRHOME/ingrconfig | cut -d"#" -f6`/.remove
	SHELL=/usr/bin/ksh
	FMLIDIR=/usr/bin
	PDDIR=$INGRHOME/bin
	;;
    4.*)
	PLATFORM=SunOS_4
#	RM=/usr/ip32/deltools/.remove
	RM=`grep deltools /usr/ip32/ingrconfig | cut -d"#" -f6`/.remove
	SHELL=/bin/ksh
	FMLIDIR=/usr/bin
	PDDIR=/usr/bin
	;;
    esac
    ;;
IRIX)
    case `uname -r` in
    5.*)
	PLATFORM=IRIX5
	INGRHOME=${INGRHOME%%:*}
	INGRHOME=${INGRHOME:=/var/opt/ingr}
	export INGRHOME
#    	RM=$INGRHOME/deltools/.remove
	RM=`grep deltools $INGRHOME/ingrconfig | cut -d"#" -f6`/.remove
    	SHELL=/bin/ksh
        FMLIDIR=$INGRHOME/bin
        PDDIR=$INGRHOME/bin
    	;;
    4.*)
    	PLATFORM=IRIX4
#    	RM=/usr/ip32/deltools/.remove
	RM=`grep deltools /usr/ip32/ingrconfig | cut -d"#" -f6`/.remove
    	SHELL=/bin/ksh
        FMLIDIR=/usr/bin
        PDDIR=/usr/bin
    	;;
    esac
    ;;
# mvr:04/30/94  init the env. variables for HP
HP-UX)
    PLATFORM=HP_UX
#   RM=/usr/ip32/deltools/.remove
    RM=`grep deltools /usr/ip32/ingrconfig | cut -d"#" -f6`/.remove
    SHELL=/bin/ksh
    FMLIDIR=/usr/bin
    PDDIR=/usr/bin
    ;;
*)
    PLATFORM=SCO
#   RM=/usr/ip32/deltools/.remove
    RM=`grep deltools /usr/ip32/ingrconfig | cut -d"#" -f6`/.remove
    SHELL=/bin/ksh
    FMLIDIR=/usr/bin
    PDDIR=/usr/bin
    ;;
esac
export PLATFORM RM SHELL

if [ -z "$listoproducts" -a -x $FMLIDIR/fmli ]
then
    if [ $PLATFORM = CLIX -o $PLATFORM = Solaris -o $PLATFORM = SCO ]
    then
	tput clear
    else
	if [ -x /usr/5bin/tput ]
	then
	    /usr/5bin/tput init
	    /usr/5bin/tput clear
	else
	    clear
	fi
    fi
    $FMLIDIR/fmli -i $RM/rm.0i -c $RM/rm.0c $RM/Menu.rm
else
    NOFMLI=y
    export NOFMLI

    if [ -z "$listoproducts" ]
    then
	echo "Usage: remove [-y] {prodnames}"
    else
	for i in $listoproducts
	do
	    args=`$PDDIR/proddata "+%n %p" -x $i`
	    if [ -z "$args" ]
	    then
		echo The product "$i" is not installed on the system.
	    else
		$RM/qmk_conf.sh 1 $args 0
	    fi
	done
    fi
fi

stty $STTY > /dev/null 2>&1
