# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:43 cvs Exp $  

#/***************************************************************************
# * I/VDS
# *
# * File:        vdat/spec/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:07:43  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1997/11/26  21:30:16  pinnacle
# AssyTree
#
# *
# * History:
# *      MM/DD/YY  AUTHOR  DESCRIPTION
# *      10/29/97  ah      added header
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdiatspec.m
	grmakemake vdiatspec.m mkfile

clean:
	@rm -f mkfile *.o *.c

