# Do not alter this SPC information: $Revision: 1.3.3.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt
!include $(RISDEVDIR)\risapp\build\defines.nt

IPATH=\
	-I$(RISDEVDIR)\risapp\internal \
	-I$(RISDEVDIR)\riscom\include \
	-I$(RISDEVDIR)\riscom\internal \
	-I$(ODBCDIR)\include

fast: $(OBJDIR)\i9risu.res $(OBJDIR)\risums.res 

$(OBJDIR)\i9risu.res: $(RISDEVDIR)\riscom\internal\risver.h
$(OBJDIR)\risums.res: $(RISDEVDIR)\riscom\internal\risver.h

.rc{$(OBJDIR)\}.res:
	@echo.
	@echo.  $(@B).rc  -to-  $@
	@echo   Calling RC
	@rc $(IPATH) $(RCFLAGS) -r -DWIN32 -FO $(OBJDIR)\$(@B).res $(@B).rc
