# $Id: makefile,v 1.2 2001/08/01 21:56:58 ramarao Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vdstartup/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/08/01 21:56:58  ramarao
#	Fixed TR# 5480.
#	
#	Revision 1.1.1.1  2001/01/04 21:09:23  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:43:44  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

TGT = vdstartimp

include ${VDS}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o
	@rm -f VDSnopdu_ini.c VDsuperi.c VDScheck_pdu.c VDureflib.c
	@rm -f VDaddPktMenu.c VDsuper.c  VDSudp_init.c  VDSupdrefdep.c

