/* MJG - This is a FORMS stub for the API */

#include <stdio.h>
#include <PDUerror.h>
#include <PDUsts_st.h>
#include <MEMstruct.h>

int FIfld_set_text () {return(1);}
int FIfld_get_text () {return(1);}
int FImcf_get_num_cols () {return(1);}
int FIg_set_standard_variables () {return(1);}
int FIg_activate () {return(1);}
int FIfld_set_attr () {return(1);}
int FIfld_get_attr () {return(1);}
int FIg_set_text () {return(1);}
int FIg_display () {return(1);}
int FIfld_get_text_length () {return(1);}
int FIf_get_next_label () {return(1);}
int FImcf_delete_col () {return(1);}
int FIg_get_font () {return(1);}
int FIg_new () {return(1);}
int FIg_get_dlocation () {return(1);}
int FImcf_insert_col () {return(1);}

void FIg_enable () {}
void FIg_disable () {}
void FIfld_pos_cursor () {}
void FIfld_set_list_default_text () {}
void FIfld_set_list_text () {}
void FIg_get_text_length () {}
void FIg_get_on_text_length () {}
void FIg_get_off_text_length () {}
void FIf_get_attr () {}
void FIf_set_attr () {}
void FIf_display () {}
void FIf_delete () {}
void FIfld_get_num_rows () {}
void FIf_collapse () {}
void FIf_uncollapse () {}
void FIf_erase () {}
void FIf_set_color () {}
void FIfld_erase_cursor () {}
void FIg_delete () {}
void FIg_erase () {}
void FIg_hilite () {}
void FIg_reset () {}
void FIg_unhilite () {}
void FIbtn_set_auto_pop_up_off () {}
void FIbtn_set_auto_pop_up_on () {}
void FIf_set_start_seq () {}
void FIf_set_collapse_location () {}
void FIfld_insert_blank_row () {}
void FIfld_set_max_num_rows () {}
void FIfld_set_num_rows () {}
void FIfld_set_num_vis_rows () {}
void FIg_set_attr () {}
void FIg_set_color () {}
void FIg_set_off_color () {}
void FIg_set_on_color () {}
void FIg_set_state () {}
void FImcf_set_attr () {}
void FImcf_set_scroll_link () {}
void FIfld_delete_rows () {}
void FIfld_set_active_row () {}
void FIfld_set_list_mode () {}
void FIfld_set_list_num_rows () {}
void FIfld_set_list_scroll () {}
void FIfld_set_max_num_chars () {}
void FIfld_set_mode () {}
void FIfld_set_num_vis_chars () {}
void FIg_set_location () {}
void FImcf_set_active_col () {}
void FImcf_set_select () {}
void FIfld_set_active_char () {}
void FIfld_set_list_location () {}
void FIfld_set_list_select () {}
void FIfld_set_list_size () {}
void FIfld_set_select () {}
void FIg_set_off_text () {}
void FIg_set_on_text () {}
void FIg_set_value () {}
void FIfld_get_list_default_text () {}
void FIfld_get_list_text () {}
void FIg_get_text () {}
void FIg_get_on_text () {}
void FIg_get_off_text () {}
void FIfld_get_active_char () {}
void FIfld_get_list_scroll () {}
void FIfld_get_list_text_length () {}
void FIfld_get_list_select () {}
void FIfld_get_select () {}
void FImcf_get_select () {}
void FIfld_get_list_mode () {}
void FIfld_get_num_vis_chars () {}
void FIfld_get_mode () {}
void FImcf_get_attr () {}
void FIg_get_attr () {}
void FIbtn_get_auto_pop_up_state () {}
void FImcf_get_num_vis_cols () {}
void FIf_get_start_seq () {}
void FIf_is_collapsed () {}
void FIf_get_color () {}
void FIf_is_displayed () {}
void FIfld_get_list_num_rows () {}
void FIfld_get_num_vis_rows () {}
void FIg_get_color () {}
void FIg_get_on_color () {}
void FIg_get_off_color () {}
void FIg_get_value () {}
void FIg_get_state () {}
void FIfld_get_row_offset () {}
void FIfld_get_active_row () {}
void FImcf_get_active_col () {}
void FImcf_get_view_data () {}
void FIg_get_location () {}
void FIfld_get_list_location () {}
void FIfld_get_list_size () {}
void FIf_set_seq_off () {}
void FIf_set_notification_routine () {}
void FIg_get_type () {}
void FIg_set_state_off () {}
void FIg_set_state_on () {}
void FIfld_get_list_default_text_length () {}
void FIfld_set_value () {}
void FIfld_get_value () {}
void FIf_set_seq_on () {}
void FIg_get_size () {}
void FIf_set_window_event_routine () {}
void FIf_get_window () {}
void FIfld_get_default_text () {}
void FIg_set_low_value () {}
void FIg_set_high_value () {}
void FIf_reset () {}
void FIg_set_font () {}
void FImcf_set_num_cols () {}
void FImcf_set_num_vis_cols () {}
void FImcf_set_justification () {}
void FIfld_set_type () {}
void FI_process_event () {}
void FIg_get_help_topic () {}
void FIf_set_initial_notification_routine () {}
void FIf_set_button_intercept_routine () {}
void FIf_set_screen () {}
void FIg_set_text_style () {}
void FIgrp_callback () {}
void FIf_process_point () {}
void FIf_get_label () {}
void FI_clear_event () {}
void FIgrp_get_single_select () {}
void FIg_get_on_symbol_index () {}
void FIg_get_default_value () {}
void FIf_get_size () {}
void FIf_get_orig_location () {}
void FIf_get_location () {}
void FIf_get_scaling () {}
void FIf_set_size () {}
void FIf_set_location () {}
void FIgrp_set_single_select_on () {}
void FIgrp_set_single_select_off () {}
void FIgrp_set_pass_off () {}
void FIgrp_set_pass_on () {}
void FIg_set_display () {}
void FIg_set_justification () {}
void FIg_set_next_in_seq () {}
void FIg_add_to_group () {}
void FIf_new () {}
void FIf_set_orig_location () {}
void FIf_set_orig_size () {}
void FIf_set_collapse_symbol () {}
void FIf_get_collapse_symbol () {}
void FIg_set_default_value () {}
void FIg_set_line_weight () {}
void FIg_set_line_style () {}
void FIg_set_line_depth () {}
void FIg_set_orientation () {}
void FIscrl_set_view () {}
void FIg_set_value_format () {}
void FIg_set_increment () {}
void FIg_set_on_symbol_index () {}
void FIfld_set_format_string () {}
void FIfld_set_default_text () {}
void FImcf_set_low_value () {}
void FImcf_set_high_value () {}
void FI_load_font () {}
void FIfld_get_notify_info () {}
void FIg_set_pass_data () {}
void FIdial_set_border_style () {}
void FIg_set_minor_increments () {}
void FIdial_set_zero_location () {}
void FIdial_set_range () {}
void FIfld_get_type () {}
void FIg_start_seq () {}
void FImcf_get_low_value () {}
void FIg_get_next_in_seq () {}
void FIg_get_increment () {}
void FIg_get_line_depth () {}
void FIg_get_group_label () {}
void FIg_set_size () {}
void FIg_get_value_format () {}
void FIg_get_high_value () {}
void FIdial_get_border_style () {}
void FIrect_get_style () {}
void FIfld_get_default_text_length () {}
void FIrect_set_style () {}
void FIg_get_low_value () {}
void FIg_call_notification_routine () {}
void FIg_get_orientation () {}
void FIg_get_minor_increments () {}
void FImcf_get_justification () {}
void FImcf_get_high_value () {}
void FIg_get_line_weight () {}
void FIg_get_justification () {}
void FIg_get_display () {}
void FIg_get_line_style () {}
void FIdial_get_zero_location () {}
void FIscrl_get_view () {}
void FIfld_get_format_string () {}
void FIg_get_text_style () {}
void FIg_get_off_symbol_index () {}
void FImcf_get_scroll_link () {}
void FI_msg_box () {}
void FIg_get_command () {}
void FIgrp_get_pass () {}
void FIdial_get_range () {}
void FIfld_find_row_and_column () {}
void FIfld_get_format_string_length () {}
void FIfld_get_line_color () {}
void FIfld_get_max_num_chars () {}
void FIfld_get_max_num_rows () {}
void FIfld_get_row_height () {}
void FIfld_set_line_color () {}
void FIf_cvrt_to_perm_win () {}
void FIf_find_by_area () {}
void FIf_find_by_point () {}
void FIf_find_gadget () {}
void FIf_get_collapse_location () {}
void FIf_get_max_size () {}
void FIf_get_min_size () {}
void FIf_get_orig_size () {}
void FIf_get_screen () {}
void FIf_get_seq () {}
void FIf_get_user_pointer () {}
void FIf_is_valid () {}
void FIf_look () {}
void FIf_paint_area () {}
void FIf_save () {}
void FIf_set_label () {}
void FIf_set_max_size () {}
void FIf_set_min_size () {}
void FIf_set_rel_location () {}
void FIf_set_resize_off () {}
void FIf_set_resize_on () {}
void FIf_set_scaling_off () {}
void FIf_set_scaling_on () {}
void FIf_set_user_pointer () {}
void FIf_set_window_level () {}
void FIgrp_add_to_group () {}
void FIgrp_delete () {}
void FIg_adjust_size () {}
void FIg_copy () {}
void FIg_get_dsize () {}
void FIg_get_erase_color () {}
void FIg_get_help_topic_length () {}
void FIg_get_notify () {}
void FIg_get_pass_data () {}
void FIg_get_symbol_file () {}
void FIg_get_symbol_index () {}
void FIg_get_user_pointer () {}
void FIg_in_group () {}
void FIg_is_valid () {}
void FIg_set_erase_color () {}
void FIg_set_help_topic () {}
void FIg_set_notify_off () {}
void FIg_set_notify_on () {}
void FIg_set_off_symbol_index () {}
void FIg_set_symbol_file () {}
void FIg_set_symbol_index () {}
void FIg_set_user_pointer () {}
void FImcf_get_col_size () {}
void FImcf_set_col_size () {}
void FI_forms_active () {}
void FI_get_auto_scaling_factors () {}
void FI_get_form () {}
void FI_get_last_notification_type () {}
void FI_get_quiet_mode () {}
void FI_message_box () {}
void FI_message_box2 () {}
void FI_msg_box2 () {}
void FI_set_auto_scaling_factors () {}
void FI_set_quiet_mode_off () {}
void FI_set_quiet_mode_on () {}
void FIg_is_displayed () {}
void FIg_get_off_color2 () {}
void FIg_get_on_color2 () {}
void FIg_set_off_color2 () {}
void FIg_set_on_color2 () {}
void FI_use_normal_bezel () {}
void FI_use_thin_bezel () {}
