#/* $Id: makefile.1,v 1.1 2001/05/17 15:19:11 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdbin/cdom/makefile
# *
# * Description: CDom Testing
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile.1,v $
# *      Revision 1.1  2001/05/17 15:19:11  ahundiak
# *      *** empty log message ***
# *
# *      Revision 1.1  2001/04/12 14:49:41  ahundiak
# *      ah
# *
# *	ld -z text -G -o /usr/tmp/cdom.so cdom_attr.o  cdom_node.o  cdom_xml.o VDctxCdom.o
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 04/12/01  ah      creation
# ***************************************************************************/

TGT = zlib

target: mkfile 
	grmake -r -k -f mkfile

mkfile : ${TGT}.m
	grmakemake ${TGT}.m mkfile

