#include "ECcmd.h"
#include "grcmd.h"
EM_M_MeasRadofSur,EMMRCrSr,ECrdofcrv,1,
EM_M_AssignSolidDensity,EMSadts,ECdensity,0
EM_M_EvalAreaProps,EMEvArPr,ECmassp,1,
EM_M_EvalMassProps,EMEvMsPr,ECmassp,0,
EM_M_AnalyzeTolSim,MDAnTlStRs,ECtol,1,
EM_M_AnalyzeTolWsCs,MDAnTlWrCs,ECworstol,0,
EM_M_DeleteProfileComponent,GRDlPrCm,EC1elecnstr,3
EM_M_PMrCr,EMPMrCr,ECmerge,1,
EM_M_MrCr,EMMrCr,ECmerge,0,
EM_M_AxisParameter,GRAxPr,EClocparam,1
EM_M_PointParameter,GRPnPr,EClocparam,0
EM_M_TgRfPlLc,MDTgRfPlLc,ECsptloc,101,
EM_M_CrtRefPlnfromWindow,MDCrRfPlWn,ECwin,0
EM_M_AnalyzeIntfBatch,EMAnIfIBt,ECintf,4
EM_M_AdParonCur,MDAdPrOnCr,ECcvreparam,0,
EM_M_CrArCr,MDCrArCr,ECmkarea,0,
EM_M_DisCurParaPt,EMShCrPrPn,ECparatpt,0,
EM_M_DisSurParaPt,EMShSrPrPn,ECparatpt,1,
EM_M_Edit_mass_area_props,EMedtmp,ECmassedit,0
EM_M_ManipMassAreaProps,EMCMsPr,ECmassmanip,0,
EM_M_MNrTnSr,EMMNrTnSr,ECtanorm,1,
EM_M_MeaTanBet2Surf,MDMTnBt2Sr,ECtasurfs,0,
EM_M_MvPlonCurve,EMMvPlOnCr,ECmvpole,0,
EM_M_POfCr,EMPOfCr,ECcvoffset,0,
EM_M_PtAtCurPara,EMSlPnCrPr,ECparatpt,2,
EM_M_PtAtSurPara,EMSlPnSrPr,ECparatpt,3,
EM_M_ShStEd,EMShStEd,ECshsted,0,
EM_M_ToggleCompositeBndLocate,EMTgCmBnLc,ECsfbdryloc,1,0,1
EM_M_ToggleSurfaceBndLocate,EMTgSrBnLc,ECsfbdryloc,0,0,1
EM_M_0023,EMPCn3Pn2T,ECconstruct,23,
EM_M_0024,EMPCn4Pn1T,ECconstruct,24,
EM_M_0025,EMPCn5Pn,ECconstruct,25,
EM_M_0032,EMExPrCr,ECconstruct,32,
EM_M_0033,EMPPrTnT2C,ECconstruct,33,
EM_M_0034,EMPBlCrBt2,ECconstruct,34,
EM_M_0035,EMPPlEnPlE,ECautoplane,35,
EM_M_0036,EMPHl,ECfit,36,
EM_M_0040,EMPrCrSrAl,ECconstruct,40,
EM_M_0041,EMPrPnAlVc,ECconstruct,41,
EM_M_0042,EMPrCrAlVc,ECconstruct,42,
EM_M_0051,EMRvMdPr,ECfidpb,0,0,1
EM_M_0052,EMExIsCrSr,ECconstruct,52,
EM_M_0053,EMPCrPlPn,ECcurbypol,53,
EM_M_0054,EMPCrPlLn,ECfitcur,54,
EM_M_0056,EMPCrDrFt,ECfitcur,56,
EM_M_0057,EMPCrLsSqF,ECfitcur,57,
EM_M_0073,EMInOrCr,ECmodify,73,
EM_M_0075,EMCRlLDs,ECmodify,75,
EM_M_0077,EMTgCnPlDs,ECmodify,77,
EM_M_0078,EMInPlWtCh,ECmodify,78,
EM_M_0079,EMInKn,ECmodify,79,
EM_M_0089,EMCnBsCrBz,ECmodify,89,
EM_M_0099,EMInPl,COintplane,0,
EM_M_0101,EMInPlCrSc,COintplane,3,
EM_M_0107,EMRdCrDt,ECmodify,107
EM_M_0110,EMCCrDr,ECmodify,110
EM_M_0112,EMPWrMd,ECconstruct,112
EM_M_0113,EMPPrL,ECconstruct,113
EM_M_0202,MDDsIs,ECconstruct,202
EM_M_PlLnArCm,GRPlLnArCm,ECdraw,0
EM_M_AnalyzeIntfPBatch,EMAnIfPBt,COci,0,0,,"ECintfbatch"
EM_M_TgRlLnDs,MDTgRlLnDs,ECruletog,0
EM_M_PlHrCsEd,MDPlHrCsEd,EChoriz,0
EM_M_DlHrEd,MDDlHrEd,EChoriz,1
EM_M_SlAcRfPl,MDSlAcRfPl,EConoff,2,
EM_M_TrnRfPlDsOn,MDTrOnRfDs,EConoff,0
EM_M_TrnRfPlDsOff,MDTrOfRfDs,EConoff,1
EM_M_CrScVw,MDCrScVw,ECsectvw,2
^EM_M_PlaceSfFea,EMSsunit3,COimpbnd,1
GRC_M_AddBndCrosHat,GRAdBnTCrG,ECaxhatch,0
GRC_M_XHSpaceAng,GRCSpAnCr,ECaxhatch,0
GRC_M_XH,GRCSpAnCr,ECaxhatch,0
GRC_M_RemBndsCrosHat,GRRmBnFrCr,ECaxhatch,0
GRC_M_RevCroHatGem,GRRvCrGm,ECaxhatch,0
GRC_M_CreateXHatch,GRCrCr,ECaxhatch,0
EM_M_CrRfPlAnPl,MDCrRfPAnP,ECdtmppang,1,
EM_M_CrRfPlPrPL,MDCrRfPPrP,ECdtmangpar,0,
EM_M_CpInPlc,GRCpPl,ECmirror,1
EM_M_CrMrCpRfPl,MDCpMrPl,ECmirror,0
EM_M_PrepSfMod,ASExElMcOc,ECmirror,2
EM_M_CrThWaSolid,EMCrThWlSl,ECshsolid,1
EM_M_RefPlnFrmCoord,MDCRfPlCrS,ECcoords,0
EM_M_DlFea,MDDlFt,ECeditfea,0
EM_M_MdXHPar,EMMdXHPar,COci,0,0,,"modxhatch"
