# $Id: makefile,v 1.2 2001/03/31 19:56:46 ahundiak Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdppl/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/03/31 19:56:46  ahundiak
#	ah
#	
#	Revision 1.1.1.1  2001/01/04 21:09:02  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  14:51:04  pinnacle
# rep bin w/txt
#
# Revision 1.2  1995/11/16  05:05:08  pinnacle
# Replaced: vdppl/makefile for:  by ksundar for vds.240
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	11/16/95	Sundar		mkmkppl is replace by "ksh $VDS/etc/bin/
#					mkmkppl" during Solaris port.
#
# -------------------------------------------------------------------

TGT = vdppl

# include ${VDS_PATH}/etc/makefiles/ppl_only.h

target:

clean:
	@rm -f pplmkfile *.e
