# Do not alter this SPC information: $Revision: 1.3.3.1 $
!include $(RISDEVDIR)\risums\nt\build\defines.nt

fast: clean $(LIBDIR)\I9RISU.dll

# Update the export and dll RISUMS.lib and/or I9RISU.dll
$(LIBDIR)\I9RISU.dll: I9RISUMS.def $(RISUMS_LIB_OBJS) $(RISLIB_RESOURCES)
	@echo.
	@echo 	RISUMS_LIB_OBJS  -to-   $@
	@if exist $(LIBDIR)\RISUMS.lib del $(LIBDIR)\RISUMS.lib
	@if exist $(LIBDIR)\RISUMS.exp del $(LIBDIR)\RISUMS.exp
#Create Import Library
    @$(implib) @<<
-machine:$(CPU)
-def:I9RISUMS.def
$(RISUMS_LIB_OBJS)
$(RISLIB_RESOURCES)
-out:$(LIBDIR)\RISUMS.lib
<<NOKEEP
#Create DLL
	@$(link) @<<
$(linkdebug)
-base:0x60770000
-dll
-entry:_CRT_INIT$(DLLENTRY)  
-out:$(LIBDIR)\I9RISU.dll 
$(LIBDIR)\RISUMS.exp $(guilibsdll) $(RISUMS_LIB_OBJS) $(RISLIB_RESOURCES)
<<NOKEEP
	@del $(LIBDIR)\RISUMS.exp

clean:
	@echo "deleting DLL in $(LIBDIR) directory"
	@-del $(LIBDIR)\I9RISU.dll
