#include "OMminimum.h"
#include "igetypedef.h"
#include "igrtypedef.h"
#include "igr.h"
#include "gr.h"
#include "dimsrc.h"

#template struct DMkeypt_str DMkeypt_tmp
#template struct DMkeyseg_str DMkeyseg_tmp
#template struct DM2ptseg_str DM2ptseg_tmp
#template struct DMaxis_str DMaxis_tmp
#template struct DMradcen_str DMradcen_tmp
#template struct DMtanpt_str DMtanpt_tmp
#template struct DMintpt_str DMintpt_tmp
#template struct DMmidpt_str DMmidpt_tmp
#template struct DMptdist_str DMptdist_tmp
#template struct DMarc_str DMarc_tmp
#template struct DMcenpt_str DMcenpt_tmp
#template struct DMedgept_str DMedgept_tmp
#template struct DMedgeseg_str DMedgeseg_tmp
#template struct DMpt_str DMpt_tmp
#template struct DMln_str DMln_tmp
