#!/bin/ksh
alias ls=ls
DESIGN=VDDESIGN
DETAIL=VDDETAIL

if [ -f pan.cmd ]
then
  rm pan.cmd
fi

echo "create pan.tbl" 
#
# Creation of VDS / SMAN icons.
#

ls EM* VD* SM* > pan.list
for file in `cat pan.list`
do
 print '^"'$file'",'$file',COci,0,0,,"Blank"' >> pan.cmd
done
rm pan.list

# print 

if [ -f pan.cmd ]
then
  cp pan.cmd ${VDS}/config/cmd_tbl/pan.tbl
  rm pan.cmd
fi
