#include "DMcmd.h"
DMC_M_DMLnStc,DMPScLnDm,COdmplace,0
DMC_M_DMLnStr,DMPSrLnDm,COdmplace,1
DMC_M_DMSmDia,DMPSyDmDm,COdmplace,2
DMC_M_DMLnPar,DMPSnPrDm,COdmplace,3
DMC_M_DMCrDia,DMPCrDmDm,COdmplace,4
DMC_M_DMLnDia,DMPLnDmDm,COdmplace,5
DMC_M_DMAnStc,DMPScAnDm,COdmplace,6
DMC_M_DMAnStr,DMPSrAnDm,COdmplace,7
DMC_M_DMRd,DMPRdDm,COdmplace,8
DMC_M_DMRdDia,DMPRdDmDm,COdmplace,9
DMC_M_DMLnCoo,DMPCrLnDm,COdmplace,10
DMC_M_DMCnLn,DMPCn,COdmplace,11
DMC_M_DMAdMsTGr,DMAdMsTGr,COdmplace,100
DMC_M_DMMeasAxis,DMSMsAx,COci,0,0,,"COdmplan"
DMC_M_DMStDmPrKy,DMStDmPrKy,COci,0,0,,"COdmkey"
DMC_M_DMSStDmPt,DMSStDmPt,COci,0,0,,"COsetstk"
"dm",DMxx,COci,0,0,,"COdmkey"
DMC_M_DMDsDmEnFr,DMDsDmEnFr,COci,0,0,,"COdspenv"
DMC_M_DMDsDmPrFr,DMDsDmPrFr,COci,0,0,,"COdsploc"
DMC_M_DMEdDm,DMEdDm,COci,0,0,,"COedtdim"
DMC_M_UpDmGr,DMUpDmGr,COci,0,0,,"COupdgrp"
DMC_M_DMMdDmGm,DMMdDmGm,COci,0,0,,"COmdgeom"
DMC_M_DMOfDmTx,DMOfDmTx,COci,0,0,,"COofftxt"
DMC_M_TogTer,DMTgTr,COci,0,0,,"COtogter"
DMC_M_RpTr,DMRpTr,COchgter,0
DMC_M_DMCpDim,DMCpDm,COdmcopy,0
DMC_M_DMPTxLd,DMPTxLd,COanplace,20
DMC_M_DMPLdTxBl,DMPLdTxBl,COanplace,21
DMC_M_DMAdLdLn,DMAdLdLn,COanplace,22
DMC_M_DMPFtCnFr,DMPFtCnFr,COanplace,23
DMC_M_DMPDtFr,DMPDtFr,COanplace,24
DMC_M_DMEdFtCnFr,DMEdAn,COgtedit,25
DMC_M_HdDm,DMHdDm,COdimonoff,0
DMC_M_ShDm,DMShDm,COdimonoff,1
DMC_M_TgDmNmVl,DMTgDmNmVl,COdimonoff,2
DMC_M_Retrieve,DMRtDm,COdimonoff,3
DMC_M_DMCmDM,DMCmDm,COdimonoff,4
DMC_M_DMAtDm,DMAtDm,COci,0,0,,"COchgpar"
DMC_M_DMSwDm,DMSwDm,COci,0,0,,"COvwswap"
DMC_M_PlWlSy,DMPlWlSy,COweld,25
DMC_M_DMPlSrTxSy,DMPlSrTxSy,COsurf,26
DMC_M_DMTgDmMd,DMTgDmMd,COci,0,0,,"COtogmode"
