#include "grcmd.h"
#include "execcmd.h"
GRC_M_DfLnStl,GRDfLnSt,COdfls,0
GRC_M_ModVwPar,GRShVPr,COvwchar,0
GRC_M_ChLyLcEl,GRChLyLcEl,COlocly,0
GRC_M_EdtLy,GREdLy,COedtly,0
GRC_M_SetActLayNmLayers,GRSALy,COactly,0
GRC_M_EdtSavVws,GRRvSvV,COedtsv,0
^GRC_M_VwAxLk1,GRSlPnOnVC,COaxlocks,0
^GRC_M_DbAxLk1,GRSlPnOnWr,COaxlocks,1
^GRC_M_DbAxLk,GRSlPnOnWr,COaxlocks,1
^GRC_M_VwAxLk,GRSlPnOnVC,COaxlocks,0
GRC_M_3DPt,GRSl3DPn,COaxlocks,2
GRC_M_AtchClrTbl,GRAtClTb,COcolors,0
GRC_M_SvClrTbl,GRSvClTb,COcolors,1
GRC_M_CvtPersParl,GRCPsPrTPl,COdynsetvw,10
GRC_M_CvtParlPers,GRCPlPrTPs,COdynsetvw,11
GRC_M_ModVwVol,GRMdVVl,COdynsetvw,6
GRC_M_SetDstBetwRefGrd,GRSDsMjGrD,COgrid,0
GRC_M_SetNumGrdPerRefGrd,GRSMnGrDvM,COgrid,1
GRC_M_DpDstBetwRefGrd,GRShDsMjGr,COgrid,2
GRC_M_DpNumGrdPerRefGrd,GRShMnGrDv,COgrid,3
GRC_M_GrdLk,GRTgGrLc,COgrid,4
GRC_M_GrdOnOff,GRTgGrDs,COgrid,5
GRC_M_Fit,GRFtV,COgrid,6
GRC_M_UnitLockDef,GRSUnRnOf,COgrid,10
GRC_M_UnitLockOff,GRTrOfUnLc,COgrid,8
GRC_M_UnitLockOn,GRTrOnUnLc,COgrid,9
GRC_M_Ur,GRSUnRnOf,COgrid,10
^GRC_M_BelOnOff,GRBelOnOff,COceocmds,0
GRC_M_DlyOnOff,GRTgDl,COmiscl,1
GRC_M_LysOff,GRTrOfLy,COmiscl,4
GRC_M_Off,GRTrOfLy,COmiscl,4
GRC_M_Of,GRTrOfLy,COmiscl,4
GRC_M_LysOn,GRTrOnLy,COmiscl,5
GRC_M_On,GRTrOnLy,COmiscl,5
GRC_M_SetVwRot,GRSVRt,COviewmnpl,4
GRC_M_Vi,GRSVRt,COviewmnpl,4
GRC_M_RecalSavVw,GRRtSvV,COviewmnpl,2
GRC_M_SavVw,GRSvV,COviewmnpl,0
GRC_M_Sv,GRSvV,COviewmnpl,0
GRC_M_AliVw,GRAlV,COviewmnpl,5
^GRC_M_ZmIn,GRZmInV,COviewmnpl,6
^GRC_M_ZmOut,GRZmOtV,COviewmnpl,7
GRC_M_RotVwDfnAx,GRRtVAbAx,COviewmnpl,8
GRC_M_RotVwPtKyVal,GRRtVAbPnK,COviewmnpl,9
GRC_M_Rv,GRRtVAbPnK,COviewmnpl,9
GRC_M_RotVwDfn3Pt,GRRtV3Pn,COviewmnpl,10
GRC_M_SetActDep,GRSZDp,COwndmnpl,0
GRC_M_Az,GRSZDp,COwndmnpl,0
GRC_M_WinAr,GRCVAr,COwnarea,0
GRC_M_CpWin,GRCpV,COswapcopy,1
GRC_M_CrtWin,GRCrV,COwndmnpl,3
GRC_M_WinCen,GRCVCn,COwndmnpl,4
GRC_M_DpActDep,GRShZ,COwndmnpl,5
GRC_M_DpDpDep,GRShDp,COwndmnpl,6
GRC_M_DpVwVol,GRShVVl,COwndmnpl,7
GRC_M_SetDpDep,GRSVDsDp,COwndmnpl,8
GRC_M_Dp,GRSVDsDp,COwndmnpl,8
GRC_M_SetVwVol,GRSVVl,COwndmnpl,9
GRC_M_WinOn,GRTrOnV,COwndmnpl,10
GRC_M_WinOff,GRTrOfV,COwndmnpl,11
GRC_M_RenmeWin,GRRnV,COwndmnpl,12
GRC_M_WinScr,GRMvVCn,COpan,0
GRC_M_SwpWin,GRSwV,COswapcopy,0
GRC_M_UpdWin,GRUpV,COwndmnpl,15
^GRC_M_ViewDyn,GRCVDy,COdynamics
GRC_M_RecalPt,GRRcPn,COrclpnt
GRC_M_CFlMdE,GRCFlMdE,COfillobj
GRC_M_SetWinShp,GRStWnSh,COSetWinShp,0
^GRC_M_TogPerBh,GRTgPrBh,COTogPerBh,0
GRC_M_PlcLnActAng,GRPL,COnpt,67
GRC_M_PlcFillet,GRPFl,COnpt,49
^GRC_M_PlcFillet,Z1PFl,COnpt,49
GRC_M_PlcAngBis3Pt,GRPAnBs3Pn,COnpt,78
GRC_M_PlcArcCenter,GRPArCn,COnpt,28
GRC_M_PlcArcCntRad,GRPArCnR,COnpt,29
GRC_M_PlcBlockDiag,GRPBlDgPn,COnpt,16
^GRC_M_PlcBlockDiag,Z1PBlDgPn,COnpt,16
GRC_M_PlcCir3Pts,GRPCr3Pn,COnpt,25
GRC_M_PlcCcirCentRad,GRPCnCrCnR,COnpt,1
GRC_M_PlcCirDiaPts,GRPCrDmPn,COnpt,13
GRC_M_PlcCirTanEleCen,GRPCTnT1EC,COnpt,1
GRC_M_DelVertex,GRDlVr,COnpt,24
GRC_M_DPT,GRDltVwPt,COnpt,102,0,1
GRC_M_PlcEllByBlock,GRPElBl,COnpt,84
GRC_M_PlcEllByRotblk,GRPElRtBl,COnpt,85
GRC_M_PlcEllAxis,GRPElAx,COnpt,4
GRC_M_PlcEllCent,GRPElCn,COnpt,5
GRC_M_PlcEqSpcPtsEle,GRPEqPnAlE,COnpt,58
GRC_M_Ext1EleToInt,GRExETIn,COnpt,54
GRC_M_Ext2EleToInt,GREx2ETIn,COnpt,55
GRC_M_PlcHalfEll,GRPHlElAx,COnpt,2
GRC_M_PlcHorLn,GRPHrL,COnpt,65
GRC_M_PlcInfLn,GRPInL,COnpt,48
GRC_M_InsVertex,GRInVr,COnpt,35
GRC_M_PlcLinTerm,GRPLTr,COnpt,119
GRC_M_PlcLnMinDis2Ele,GRPLMnDsBt,COnpt,75
GRC_M_PlcLnSeg,GRPLSg,COnpt,14
GRC_M_PlcLnSegTan2Ele,GRPLSgTnT2,COnpt,14
GRC_M_PlcLnString,GRPLn,COnpt,14
GRC_M_PlcFilletMan,GRPFlMnTr,COnpt,49
GRC_M_ModEle,GRMdE,COnpt,21
GRC_M_MoveSeg,GRMvSg,COnpt,51
GRC_M_MsDist2Pts,GRMDsBt2Pn,COmeasure,46
GRC_M_MsLenAlongEle,GRMLnAlE,COmeasure,42
GRC_M_MsAreaEle,GRMArE,COmeasure,44
GRC_M_MsCumDist,GRMCmDs,COmeasure,46
GRC_M_MsDiamEle,GRMDm,COmeasure,45
GRC_M_MsLenOfEle,GRMLnE,COmeasure,47
GRC_M_MsDistProj,GRMsPtProj,COmeasure,40
GRC_M_MsRadOfEle,GRMRE,COmeasure,43
GRC_M_PlcNsidePoly,GRPNsPl,COnpt,76
GRC_M_PlcOrthLn,GRPOrLn,COnpt,14
GRC_M_PlcOrthPoly,GRPOrPl,COnpt,14
GRC_M_PartDel,GRPrDlE,COnpt,50
GRC_M_PlcPoint,GRPPn,COnpt,20
GRC_M_PlcPolygon,GRPPl,COnpt,64
GRC_M_PT,GRAbsWldPt,COnpt,103,0,1
GRC_M_PtAlongEle,GRSlPnDsAl,COnpt,105
GRC_M_PtDstBt2Pts,GRSlPnDsBt,COnpt,99,0,1
GRC_M_PlcQrtEll,GRPQrElAx,COnpt,3
GRC_M_PlcRotBlk,GRPRtBl,COnpt,17
GRC_M_SplitEle,GRSpE,COnpt,23
GRC_M_PlcTenPt,GRPTnPn,COnpt,88,0,1
GRC_M_PlcVertline,GRPVrL,COnpt,66
GRC_M_HiliteName,GRHiLtEl,COnpt,0
GRC_M_Remove,GRRnE,COnpt,115
GRC_M_Rm,GRRnE,COnpt,115
GRC_M_XY,GRSlPnKyn,COcoord,0,0,1
GRC_M_CArTCr,GRCArTCr,COnpt,0
GRC_M_CArTDgCm,GRCArTDgCm,COnpt,0
GRC_M_ModAxOfConEle,GRCAxCn,COnpt,37
GRC_M_SetDefDir,GRCDr,COnpt,111,0,1
GRC_M_Cd,GRCDr,COnpt,111,0,1
GRC_M_SetChDirPath,GRCDrPt,COnpt,112
GRC_M_Cdpath,GRCDrPt,COnpt,112
GRC_M_CreateDir,GRCrDr,COnpt,113
GRC_M_Mkdir,GRCrDr,COnpt,113
GRC_M_DelDir,GRDlDr,COnpt,116
GRC_M_Rmdir,GRDlDr,COnpt,116
GRC_M_ExArAn,GRExArAn,COnpt,0
GRC_M_FragmentEle,GRFrE,COnpt,63
GRC_M_GnEqSpPts,GRGnEqSPAE,COnpt,0
GRC_M_GnPtsAlEl,GRGnPnAESp,COnpt,0
GRC_M_MsSwAngOfEle,GRMSwAnE,COmeasure,41
GRC_M_MoveDir,GRMvdir,COnpt,0
GRC_M_PlcArcTnTECD,GRPATnTECD,COnpt,123
GRC_M_PlcAngBis2Ln,GRPAnBsBtE,COnpt,56
GRC_M_PlcArcRad2Pt,GRPArR2Pn,COnpt,30
GRC_M_PlcArcRaTanPT,GRPArRPnTn,COnpt,30
GRC_M_PlcCirTanEleDia,GRPCTnT1ED,COnpt,13
GRC_M_PlcCirTnTECD,GRPCTnTECD,COnpt,121
GRC_M_PlcCirTan3Els,GRPCrTnT3E,COnpt,25
GRC_M_PlcNSPolyMpSide,GRPNsPlMdS,COnpt,76
GRC_M_PlcPlanLnStrg,GRPPlLn,COnpt,14
GRC_M_PlcPerpBis,GRPPrBs,COnpt,57
GRC_M_PSyOv,GRPSyOv,DEnpt,0
GRC_M_DlSyOv,GRDrSnSyOv,DEnpt,0
GRC_M_RvSyOv,GRRvSyOv,DEnpt,0
GRC_M_SetActCSTyp,GRSCrSyTy,COnpt,98,0,1
^GRC_M_SetVar,GRSVr,COnpt,97,0,1
GRC_M_CurPtFrm,GRShCrPn,COnpt,100
GRC_M_ShoDefDir,GRShDr,COnpt,114,0,1
GRC_M_Pwd,GRShDr,COnpt,114,0,1
GRC_M_Shownm,GRShNmEl,COnpt,117
^GRC_M_ShowVar,GRShVr,COnpt,96,0,1
GRC_M_MvElVec,GRMvEAlVc,COexp,0
GRC_M_GnMtxPts,GRGnMtPn,COnpt,0
GRC_M_GnPolPts,GRGnPlArPn,COnpt,0
GRC_M_MsAngLn,GRMAnL,COmeasure,60
GRC_M_MsMinDist2Ele,GRMMnDsBt2,COmeasure,83
GRC_M_MsDistPtEle,GRMDsBtPnE,COmeasure,120
GRC_M_MsDistBtPts,GRMDsBtPn,COmeasure,46
^GRC_M_MsDistBtPts,Z1MDsBtPn,COmeasure,46
GRC_M_RvAngRd,GRRvAnRdUn,COmeasure,0
GRC_M_RvLinRd,GRRvLnRdUn,COmeasure,0
GRC_M_MsAng3Pts,GRMAn3Pn,COmeasure,52
GRC_M_MsAng2Pts,GRMAn2Pn,COmeasure,59
GRC_M_MsAng2Ln,GRMAnBt2L,COmeasure,61
GRC_M_MsAng2PtsAx,GRMAnBt2Pn,COmeasure,108
GRC_M_MsAngLnAx,GRMAnBtLAr,COmeasure,107
GRC_M_DI,GRSlPnDsDr,COnpt,104,0,1
GRC_M_DistDir,GRSlPnDsDr,COnpt,104,0,1
GRC_M_DL,GRSlDlPIWC,COcoord,0,0,1
GRC_M_DX,GRSlDlPIV,COnpt,101,0,1
GRC_M_ChTxtCs,GRCTxChSp,COchgtxattr,3
GRC_M_ChTxtFt,GRCTxFn,COchgtxattr
GRC_M_ChTxtHt,GRCTxHg,COchgtxattr,4
GRC_M_ChTxtJust,GRCTxJs,COchgtxattr,1
GRC_M_ChTxtLs,GRCTxLSp,COchgtxattr,2
GRC_M_ChTxtSz,GRCTxSz,COchgtxattr,6
GRC_M_ChTxtWd,GRCTxWd,COchgtxattr,5
GRC_M_CurSelSet,GRDfSlSt,COgrpevent,0
GRC_M_DelFt,GRDlFn,COdelfnt
GRC_M_EdtTxt,GREdTx,COedittext,0
^GRC_M_EdtTxt,Z1EdTx,COedittext,0
GRC_M_EleClpInFnc,GRSlEClInF,COgrpevent,2
GRC_M_EleClpOutFnc,GRSlEClOtF,COgrpevent,5
GRC_M_EleCurFl,GRSlAlE,COgrpevent,0
GRC_M_EleInFnc,GRSlEInFn,COgrpevent,0
GRC_M_EleInOvlFnc,GRSlEInOvF,COgrpevent,1
GRC_M_EleIndSel,GRSlEInSl,COgrpevent,0
GRC_M_EleLy,GRSlEOnLy,COgrpevent,0
GRC_M_EleOutFnc,GRSlEOtFn,COgrpevent,3
GRC_M_EleOutOvlFnc,GRSlEOtOvF,COgrpevent,4
GRC_M_EleOvlFnc,GRSlEOvFn,COgrpevent,6
GRC_M_EleSym,GRSlESy,COgrpevent,0
GRC_M_EleVw,GRSlEInV,COgrpevent,0
GRC_M_EmTxOff,GRTrOfEmTx,COdpemptytx,0
GRC_M_EmTxOn,GRTrOnEmTx,COdpemptytx,1
GRC_M_FlFnc,GRCpFnE,COgrpevent,4
GRC_M_PlcPyFnc,GRPPlFn,COplfence,64
GRC_M_PlcRctFnc,GRPRcFn,COplfence,16
GRC_M_RepFt,GRRpFn,COrplfnt
GRC_M_ReplTx,GRRpTx,COedittext,1
GRC_M_RetFt,GRRtFn,COretfnt
GRC_M_RevAvailFnts,GRRvFn,COrevfnt,1
GRC_M_RevFntsFile,GRRvFnInFl,COrevfnt,0
GRC_M_SetADP,GRSDrPr,COsetadp
GRC_M_SvEl,GRSvEl,COsaveelem,0
GRC_M_TxFrmFile,GRSlTxFrAS,COtxfrmfile
GRC_M_TxFrmTxEl,GRSlTxFrTx,COtxfrmtxel
GRC_M_FncPlEle,GRFncPlEle,COgrpevent,0
GRC_M_PlcTxt,GRPTx,COtext,0
^GRC_M_PlcTxt,Z1PTx,COtext,0
GRC_M_PlcVITxt,GRPVInTx,COtext,1
GRC_M_PlcFitTxt,GRPFtTx,COtext,2
GRC_M_PlcVIFitTxt,GRPVInFtTx,COtext,3
GRC_M_CpTxFlJf,GRCpTxFlJs,COcptxfljf,0
GRC_M_SetActInsFt,GRStAcInFt,COci,0,0,,"setinsfnt"
GRC_M_CvtTxPly,GRCTxtPol,COplytext,0
GRC_M_SetRasBordOn,RSTOnCBDP,COrlocks,5,0,1
GRC_M_SetRasBordOff,RSTOfCBDP,COrlocks,6,0,1
GRC_M_SetRasAutoDefOn,RSTrOnAtCn,COrlocks,9,0,1
GRC_M_SetRasAutoDefOff,RSTrOfAtCn,COrlocks,10,0,1
GRC_M_SvTxTAsF,GRSvTxTAsF,COsvtxasfl,1
GRC_M_SetActDir,GRCCrDr,COattr,3,0,1
GRC_M_SetAD,GRCCrDr,COattr,3,0,1
^GRC_M_SetBoreLoc,GRTgBrLc,COattr,5,0,1
GRC_M_SetAppProjOn,GRTrOnApPr,COattr,7,0,1
GRC_M_SetAppProjOff,GRTrOfApPr,COattr,9,0,1
GRC_M_SetAbsMeaOn,GRTrOnAbMs,COattr,11,0,1
GRC_M_SetAbsMeaOff,GRTrOfAbMs,COattr,13,0,1
GRC_M_DynAllCur,GRTgDyMdAl,COattr,21,0,1
GRC_M_DynOnOff,GRTgDyMdIn,COattr,19,0,1
GRC_M_TrOnRFLc,GRTrOnRFLc,COattr,23,0,1
GRC_M_TrOfRFLc,GRTrOfRFLc,COattr,25,0,1
GRC_M_CFlMdFl,GRCFlMdFl,COattr,27,0,1
GRC_M_CTxFlMdF,GRCTxFlMdF,COattr,29,0,1
GRC_M_SetAA,GRSAn,COattr,256,0,1
GRC_M_SetActAng,GRSAn,COattr,256,0,1
GRC_M_SetActAng2Pt,GRSAn2Pn,COattr,16777216
GRC_M_SetActAng3Pt,GRSAn3Pn,COattr,33554432
GRC_M_SetActSc3Pt,GRSSc3Pn,COattr,67108864
GRC_M_SetCO,GRSCl,COattr,16,0,1
GRC_M_SetActCo,GRSCl,COattr,16,0,1
GRC_M_SetWT,GRSWg,COattr,32,0,1
GRC_M_SetActWt,GRSWg,COattr,32,0,1
GRC_M_SetST,GRSSt,COattr,64,0,1
GRC_M_SetActSt,GRSSt,COattr,64,0,1
GRC_M_SetActLy,GRSLy,COattr,128,0,1
GRC_M_SetLV,GRSLy,COattr,128,0,1
GRC_M_SetLY,GRSLy,COattr,128,0,1
GRC_M_SetSC,GRSSc,COattr,1,0,1
GRC_M_SetActSc,GRSSc,COattr,1,0,1
GRC_M_SetAS,GRSSc,COattr,1,0,1
GRC_M_SetXS,GRSXSc,COattr,2,0,1
GRC_M_SetActXsc,GRSXSc,COattr,2,0,1
GRC_M_SetYS,GRSYSc,COattr,4,0,1
GRC_M_SetActYsc,GRSYSc,COattr,4,0,1
GRC_M_SetZS,GRSZSc,COattr,8,0,1
GRC_M_SetActZsc,GRSZSc,COattr,8,0,1
GRC_M_SetMA,GRSAnMsUn,COattr,134217728,0,1
GRC_M_SetActUnAngMs,GRSAnMsUn,COattr,134217728,0,1
GRC_M_SetMD,GRSDsMsUn,COattr,268435456,0,1
GRC_M_SetActUnDisMs,GRSDsMsUn,COattr,268435456,0,1
GRC_M_SetMAR,GRSArMsUn,COattr,536870912,0,1
GRC_M_SetActArMs,GRSArMsUn,COattr,536870912,0,1
GRC_M_SetAP,GRSArPtDl,COattr,8388608,0,1
GRC_M_SetActArPatDlta,GRSArPtDl,COattr,8388608,0,1
GRC_M_SetEP,GRSEdPtDl,COattr,4194304,0,1
GRC_M_SetActEdgPatDlta,GRSEdPtDl,COattr,4194304,0,1
GRC_M_LstEleNme,GRCrLsNmE,COcpattr,93
GRC_M_CrtAuxDrwVw,GRCrAxDrV,COdetail,2
GRC_M_CrtPrnDrwVw,GRCrPrDrV,COdetail,5
GRC_M_RefFlLyOff,GRTrOfLyRf,COdetail,8
^GRC_M_MdlVwLyOff,GRTrOfRfFl,COdetail,0
GRC_M_RefFlLyOn,GRTrOnLyRf,COdetail,9
GRC_M_DtcMdl,GRDtMdFrDr,COdetail,6
GRC_M_ChgDrwVwSc,GRCDrVSc,COdetail,11
GRC_M_ScRefFl,GRScRfFl,COdetail,12
GRC_M_DrpDrwVwAlgn,GRDrDrVAl,COdetail,7
GRC_M_SetActDrwVw,GRSDrVSh,COdetail,13
GRC_M_ReAlgnDrwVw,GRAlDrV,COdetail,0
GRC_M_AdCmTPl,GRAdCmTPl,COpal,2
GRC_M_CrPl,GRCrPl,COpal,0
GRC_M_DlPl,GRDlPl,COpal,PALDEL
GRC_M_DlCmFrPl,GRDlCmFrPl,COpal,3
GRC_M_SvPlTFl,GRSvPlTFl,COpal,4
GRC_M_CrPartsLst,GRCrPrLs,COpart,5
GRC_M_UpdPtsLst,GRUpPrLs,COpart,7
GRC_M_SavePtData,GRSvPrDt,COpart,4
GRC_M_PlPart,GRPlPr,COpart,3
GRC_M_AddPtToPtLst,GRAdPrTPrL,COpart,6
GRC_M_PrjEl,GRPrEl,COproj,0
GRC_M_PrjPt,GRPrPn,COproj,0
GRC_M_SetRgMem,GRSetRMem,COrattr,1,0,1
GRC_M_SetRCM,GRSetRMem,COrattr,1,0,1
GRC_M_SetRFG,RSSCnFrCl,COrattr,2,0,1
GRC_M_SetRgForCo,RSSCnFrCl,COrattr,2,0,1
GRC_M_SetRBG,RSSBcCl,COrattr,3,0,1
"IGE_RETRIEVE_OPTIONS",GRRtOpFr,COretco,0,0,1
GRC_M_AttRef,GRAtRfFl,COref,0
GRC_M_DetFil,GRDtRfFl,COref,0
GRC_M_StFnE,GRStFnE,COstrfnc,1
GRC_M_MdClpD,GRMdClPlDp,COref,0
GRC_M_DrpRFS,GRDrRfFlSy,COref,0
GRC_M_CreatePart,GRCrPr,COpart,0
GRC_M_SetFT,GRSTxFn,COattr,512,0,1
^GRC_M_SetFT,Z1STxFn,COattr,512,0,1
GRC_M_SetActTxtFt,GRSTxFn,COattr,512,0,1
^GRC_M_SetActTxtFt,Z1STxFn,COattr,512,0,1
GRC_M_SetFrcFt,GRSFrFn,COattr,1024,0,1
GRC_M_SetAscFt,GRSASFn,COattr,4096,0,1
GRC_M_SetTX,GRSTxSz,COattr,16384,0,1
^GRC_M_SetTX,Z1STxSz,COattr,16384,0,1
GRC_M_SetTS,GRSTxSz,COattr,16384,0,1
^GRC_M_SetTS,Z1STxSz,COattr,16384,0,1
GRC_M_SetActTxtSz,GRSTxSz,COattr,16384,0,1
^GRC_M_SetActTxtSz,Z1STxSz,COattr,16384,0,1
GRC_M_SetTW,GRSTxWd,COattr,65536,0,1
GRC_M_SetActTxtWd,GRSTxWd,COattr,65536,0,1
GRC_M_SetTH,GRSTxHg,COattr,32768,0,1
GRC_M_SetActTxtHt,GRSTxHg,COattr,32768,0,1
GRC_M_SetCS,GRSTxChSp,COattr,131072,0,1
GRC_M_SetActTxtCs,GRSTxChSp,COattr,131072,0,1
GRC_M_SetLS,GRSTxLSp,COattr,262144,0,1
GRC_M_SetActTxtLs,GRSTxLSp,COattr,262144,0,1
GRC_M_SetTJ,GRSTxJs,COattr,8192,0,1
GRC_M_SetActTxtJust,GRSTxJs,COattr,8192,0,1
GRC_M_CopySymb,GRCpSy,COcpattr,91
GRC_M_CopyTxAttr,GRCpTxPr,COcpattr,92
GRC_M_CrPlFrFl,GRCrPlFrFl,COpal,1
GRC_M_EdPart,GREdPr,COpart,1
GRC_M_RevPt,GRRvPr,COpart,2
GRC_M_CrtDrwVw,GRCrDrV,COdetail,4
GRC_M_AtcMdlDrwVw,GRAtMdTDrV,COdetail,1
GRC_M_CreDrwSht,GRCrDrSh,COdetail,3
GRC_M_RvDrwVw,GRRvDrV,COdetail,15
GRC_M_RvRefFl,GRRvRfFl,COdetail,14
GRC_M_RvEdtDrwSht,GRRvDrShSt,COdetail,10
GRC_M_ShowEle,GRRvE,COreviewele,0
GRC_M_CreFont,GRCrFn,COci,0,0,0,"GRCrFnMn"
GRC_M_CnvtoIGDS,GRCnMcDsFl,COcvigeigds
GRC_M_CnvtoEMS,GRCnIGFlMc,COcvigdsige
GRC_M_CnvIGDSCelLib,GRCnIGClLb,COcvtclsl
GRC_M_DfnCor3Pt,GRPCrSy3Pn,COcsdefine,1
GRC_M_DfnCorPlEle,GRPCrSyPlE,COcsdefine,3
GRC_M_DfnCorVwAl,GRPCrSyFrV,COcsdefine,2
GRC_M_SetDefCorSys,GRSCrSy,COcsdefault,1
GRC_M_RevCS,GRRvCrSy,COcsreview
GRC_M_CSDisOnOff,GRTgCrSyDs,COcstoggle
GRC_M_PtAngFr,GRSlPnAnFr,COevgen,1
GRC_M_PtAngTo,GRSlPnAnT,COevgen,2
GRC_M_PtCen,GRSlPnCn,COevgen,3
GRC_M_PtEnd,GRSlPnEn,COevgen,4
GRC_M_PtInscPt,GRSlPnIn,COevgen,5
GRC_M_PtKyPt,GRSlPnKyp,COevgen,6
GRC_M_PtMidPt,GRSlPnMd,COevgen,7
GRC_M_PtPrjPt,GRSlPnPrPn,COevgen,8
GRC_M_PtPrpFr,GRSlPnPrFr,COevgen,9
GRC_M_PtPrpTo,GRSlPnPrT,COevgen,10
GRC_M_PtTgtFr,GRSlPnTnFr,COevgen,11
GRC_M_PtTgtTo,GRSlPnTnT,COevgen,12
GRC_M_TenKyPtSnp,GRSlTnPnKy,COevgen,13
GRC_M_PnSnPn,GRPnSnPn,COevgen,14
GRC_M_Drop,GRDrGr,COdrop
GRC_M_DrpCel,GRDrCl,COdrop
GRC_M_AddEleGrGrp,GRAdETGrGr,COggadd
GRC_M_CrtAddGrGrp,GRCrGrGr,COggcreate
^GRC_M_CrtAddGrGrp,Z1CrGrGr,COggcreate
GRC_M_RmEleGrGrp,GRDrEFrGrG,COggremove
^GRC_M_RmEleGrGrp,Z1DrEFrGrG,COggremove
GRC_M_Del,GRDlE,COchange,1
GRC_M_Undelete,GRUnE,COchange,2
GRC_M_UndelOnOff,GRTgUn,COchange,3
GRC_M_ChEleSym,GRCSy,COchange,4
GRC_M_ChEleCo,GRCCl,COchange,5
GRC_M_ChEleLy,GRCLy,COchange,6
GRC_M_ChEleSt,GRCSt,COchange,7
GRC_M_ChEleWt,GRCWg,COchange,8
GRC_M_ChEleNm,GRCENm,COchange,9
GRC_M_Mv,GRCENm,COchange,9
GRC_M_EleDspOn,GRTrOnEDs,COchange,10
GRC_M_EleDspOff,GRTrOfEDs,COchange,11
GRC_M_EleLocOn,GRTrOnELc,COchange,12
GRC_M_EleLocOff,GRTrOfELc,COchange,13
GRC_M_CpChLy,GRCpChLy,COchange,15
GRC_M_CpEPr,GRCpPr,COcpparal,14
GRC_M_Move,GRMvE,COmanip,1
GRC_M_Cp,GRCpE,COmanip,2
GRC_M_Align,GRAlE,COmanip,3
GRC_M_CpAlign,GRCpAlE,COmanip,4
GRC_M_MirVer,GRMrEAbVrA,COmanip,5
GRC_M_CpMirVer,GRCpMrEAbV,COmanip,6
GRC_M_MirHor,GRMrEAbHrA,COmanip,7
GRC_M_CpMirHor,GRCpMrEAbH,COmanip,8
GRC_M_MirLn,GRMrEAbAx,COmanip,9
GRC_M_CpMirLn,GRCpMrEAbA,COmanip,10
GRC_M_RotActAng,GRRtE,COmanip,11
GRC_M_CpRotActAng,GRCpRtE,COmanip,12
GRC_M_RotAx,GRRtEAbAx,COmanip,13
GRC_M_CpRotAx,GRCpRtEAbA,COmanip,14
GRC_M_Rot3Pts,GRRtE3Pn,COmanip,15
GRC_M_CpRot3Pts,GRCpRtE3Pn,COmanip,16
GRC_M_ScActSc,GRScE,COmanip,17
GRC_M_CpScActSc,GRCpScE,COmanip,18
GRC_M_Sc3Pts,GRScE3Pn,COmanip,19
GRC_M_CpSc3Pts,GRCpScE3Pn,COmanip,20
GRC_M_SubPlot,GRSbPlFl,COplot,1
GRC_M_QueSts,GRShPlQSt,COplot,2
GRC_M_CrePlot,GRCrPlRq,COplot,3
GRC_M_PatEleAr,GRPArPt,COpattern,0
GRC_M_PatEleEdg,GRPEdPt,COpattern,1
GRC_M_DfnActCel,GRSClDf,COdefactsm
^GRC_M_DfnActCel,Z1SClDf,COdefactsm
GRC_M_DfnActCelLib,GRAtClLb,COdefsymlib
GRC_M_RvCelLib,GRRvClDf,COrevcell,0
GRC_M_CrtCel,GRCrClDf,COsdcreate
GRC_M_RenCelLib,GRRnClDf,COsdrename
GRC_M_CnvSymCel,GRCnSyTCl,COsmtocl
GRC_M_PlcCel,GRPCl,COsymplace
GRC_M_PlcGrGrp,GRPGrGr,COsymplace,2
^GRC_M_PlcGrGrp,Z1PGrGr,COsymplace,2
GRC_M_PlcSym,GRPSy,COsymplace,1
^GRC_M_PlcSym,Z1PSy,COsymplace,1
GRC_M_PlcVISym,GRPVInSy,COsymplace,3
GRC_M_RepOccCel,GRRpClGl,COreplace,0
GRC_M_RepAllCel,GRRpAlClGl,COreplace,0
GRC_M_RepAllSym,GRRpAlSyGl,COreplace,0
GRC_M_RepOccSym,GRRpSyGl,COreplace,0
GRC_M_RepSngOccSym,GRRpSyIn,COreplace,0
GRC_M_DelCelLib,GRDlClDf,COreplace,0
GRC_M_DrpSymSymb,GRDrSySy,COreplace,0
GRC_M_TgAutoAcc,GRTgAtAc,COci,0,0,,"autoaccept"
GRC_M_AutoAccOn,GRAtAcOn,COci,0,0,,"autoaccept 1"
GRC_M_AutoAccOff,GRAtAcOf,COci,0,0,,"autoaccept 0"
GRC_M_GenSet,GRGenSet,COgenset
GRC_M_RvESlCr,GRRvESlCr,COlocelig
GRC_M_LcElFm,GRLcElFm,COlocelig
GRC_M_MpEvGn,GREvGnBt,COci,0,0,,"evgenmap"
GRC_M_TgAs,GRTgAs,COci,0,0,,"assocmode"
GRC_M_CscdWn,GRCscWn,COci,0,0,,"cascade"
GRC_M_TlWn,GRTlWn,COci,0,0,,"tile"
GRC_M_Clps,GRClps,COci,0,0,,"collapse"
GRC_M_MaxWn,GRMxWn,COci,0,0,,"MaxWin"
GRC_M_ResWn,GRRstWn,COci,0,0,,"RestoreWin"
^"Z xqt yrv",Blank,COci,0,0,,"blank"
GRC_M_SetActPixTol,GRSAcPxTl,COci,0,0,,"pixel"
GRC_M_SetPix,GRSAcPxTl,COci,0,0,,"pixel"
GRC_M_PlTexAlEl,GRPTxAlEl,COtxalel,0
GRC_M_StsDspFrm,GRStFr,COci,0,0,,"StatusDis"
^"cc",COcc,COcc,0
^GRC_M_RotVwArEyPt,GRRtVwEyPn,COroteye,0
GRC_M_RotVwAbUpVc,GRRtVwUpVe,COrotcoi,0
^GRC_M_Tilt,GRTl,COtilt,0
GRC_M_ChPerspAng,GRChPrAn,COvwangle
GRC_M_Zoom,GRZm,COzoom,0
GRC_M_PCrCEPnD,GRPCrCEPnD,COnpt,1
GRC_M_PCrDmKCP,GRPCrCnDm,COnpt,1
GRC_M_PCr2PnDm,GRPCr2PnDm,COnpt,26
GRC_M_DirCmdsForm,GRShDrCmFr,COci,0,0,,"dcf"
^GRC_M_DirCmdsForm,Z1ShDrCmFr,COci,0,0,,"dcf"
GRC_M_AdjMenus,GRAdMn,COci,0,0,,"AdjustMenu"
GRC_M_SrchForNm,GRFnNm,FIlstform,0
GRC_M_Find,GRFnNm,FIlstform,0
GRC_M_LstDirCon,GRShPrLs,FIlstform,1
GRC_M_Lst,GRShPrLs,FIlstform,1
GRC_M_GetCmd,GRMGetCmd,COgetcmd,0
EXC_M_AtPnMn,EXAtPnMn,COci,1,0,,"exswapmenu"
EXC_M_AtBrMn,EXAtBrMn,COci,3,0,,"exswapmenu"
GRC_M_NB,GRNtBk,COci,0,0,,"nb"
GRC_M_NB2,GRNtBk,COci,0,0,,"nb"
GRC_M_CrLcPl,GRCrLcPl,COci,0,0,,"hpgl"
GRC_M_SbLcPl,GRSbLcPl,COplot,5
GRC_M_SwitchProducts,GRSwPr,COci,0,0,,"switchprod"
GRC_M_SSOptions,GRSmSk,COnpt,0
GRC_M_ChgRefAtt,GRCRfFlAt,COci,0,0,,"GRChRfAt"
GRC_M_DisVieDyn,GRDsVwDy,DPvd,0
^GRC_M_IniMrkVw,GRInMrVw,DPvd_mv,3,512,1
GRC_M_MrkTmpVie,GRMrTmVw,DPvd_mv,0,0,1
GRC_M_RstView,GRRsVw,DPvd_rv,0,0,1
GRC_M_RedWins,GRRdWn,DPvd_rdwn,0,0,0
GRC_M_SetDisTol,GRSDsTl,DPdsp_tol,0,0,0
GRC_M_TogDisLst,GRTgDsLs,DPvd_tdl,0,0,0
GRC_M_PlcArc3Pts,GRPAr3Pn,COnpt,27
GRC_M_ToggleSSLock,GRTgSmSk,CEO_LOCATE,0
GRC_M_SetTxtParams,GRStTxPr,COci,0,0,,"driveform GRTextParam"
GRC_M_ExtEle,IDExEDyn,COnpt,22
GRC_M_ZAnalyzeElem,GRZAnEl,COci,0,0,,"COanalyze"
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
0x088991be,GRApndRcrd,RAPcobCO,0
0x088991ae,GRStrtRcrd,RAPcobCO,0
0x088991b6,GRStopRcrd,RAPcobCO,0
0x08899206,GRShRc,RAPcobCO,0
