void FTR_enter () {}
void NFT_init () {}
void NFT_ftr_search () {}
void NFT_delete_item () {}
void NFT_delete_entry () {}
void NFT_index () {}
void NFT_start_group () {}
void NFT_add_file () {}
void NFT_get_keywords () {}
void whence () {}
