/************************************************************************/
/* PURPOSE:    Provides the standard GETOPT Include definitions         */
/* -----                                                                */
/* COMMENTS:   none                                                     */
/************************************************************************/

extern char    *optarg;
extern short   opterr;
extern short   optind;

