# $Id: makefile,v 1.2 2001/05/09 15:47:06 ylong Exp $ 

#/***************************************************************************
# * I/VDS
# *
# * File:        smframe/ppl/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.2  2001/05/09 15:47:06  ylong
# *      *** empty log message ***
# *
# *      Revision 1.1.1.1  2001/01/04 21:07:35  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1997/12/18  19:05:28  pinnacle
# SurfaceFrame
#
# *
# * History:
# *      MM/DD/YY  AUTHOR DESCRIPTION
# *      12/17/97  ah     Creation
# ***************************************************************************/
TGT = smfrappl

include ${VDS_PATH}/etc/makefiles/ppl_only.h
