/* Form Labels */

#define          LOGIN_FORM            100
#define          SEARCH_FORM           200
#define          LOCAL_FILES_FORM      300
#define          SORT_FORM             400
#define          PART_FORM             500
#define          SEED_FORM             510
#define          DEFINE_ASSY_FORM      600
#define          ASSEMBLY_FORM         700
#define          SINGLE_LIST_FORM      800
#define          MCF_LIST_FORM         900
#define          CAT_OPERATIONS_FORM   150
#define          CATALOG_NAME_FORM     250
#define          CATALOG_ATTR_FORM     350
#define		 DESIGN_FORM	       450
#define          DYNAMIC_ATTR_FORM     550
#define          REPLACE_PART_FORM     650
#define          PART_LIST_FORM        750
#define          TOPDOWN_FORM          850
#define          REPORT_FORM           950
#define          COPY_FILE_FORM        960
#define          PARAMETRIC_FORM       120
#define          DESIGN_OPTIONS_FORM   220
#define          ACTIVE_PART_FORM      320
#define          BOM_CONTENTS_FORM     420
#define          BOM_LIST_FORM         520
#define          SEARCH_OPTIONS_FORM   710
#define          SORT_OPTIONS_FORM     810
#define          FILE_LIST_FORM        910
#define          ASSY_OPTIONS_FORM     620
#define          PARTS_LIST_FORM       720
#define          PARAMETRIC_CATALOG_FORM 820
#define          CHANGE_SYMBOLOGY_FORM 920
#define          PARAMETRIC_PARTS_FORM 930
#define          DESIGN_PARTS_FORM     940
#define          PART_FILE_LIST_FORM   630
#define          CANCEL_LIST_FORM      640
#define          WHERE_USED_FORM       660
#define          DEFINE_LIB_FORM       970
#define          ORIGIN_LIST_FORM      980
#define          CLASS_CAT_FORM        680
#define          ASSEMBLY_DISPLAY_FORM 870
#define          FLAG_FORM             880
#define          MOVE_STATE_FORM       890
#define          SEARCH_FORMAT         110
#define          REV_ASSY_FORM         130
#define          ATTR_VALUE_FORM       140
#define          ACTIVE_PART           160
