# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:57 cvs Exp $  

#/***************************************************************************
# * I/VDS
# *
# * File:        vdbro/imp/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:07:57  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1997/10/29  17:14:06  pinnacle
# ah Creation
#
# *
# * History:
# *      MM/DD/YY  AUTHOR  DESCRIPTION
# *      10/29/97  ah      added header
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdibro.m
	grmakemake vdibro.m mkfile


