#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:08:03 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdct4/imp/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:08:03  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1999/06/29  18:26:28  pinnacle
# ct
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/28/99  ah      creation
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdict4imp.m
	grmakemake vdict4imp.m mkfile
