#/* $Id: makefile,v 1.3 2001/04/24 20:40:04 jdsauby Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdat/post/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.3  2001/04/24 20:40:04  jdsauby
# *      Post table timestamp  CR 4474
# *
# *      Revision 1.2  2001/01/11 21:06:42  art
# *      sp merge
# *
# *      Revision 1.1.1.1  2001/01/04 21:07:43  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1998/01/09  22:04:14  pinnacle
# AssyTree
#
# *
# * History:
# *      MM/DD/YY  AUTHOR  DESCRIPTION
# *      01/09/98  ah      creation
# *
# ***************************************************************************/

TGT = vdiatpost

include ${VDS_PATH}/etc/makefiles/lib_only.h
