all: \
	directories \
	_BTREE \
	_DIR \
	_GROUP

directories:
	@if not exist $(TARGET)\om\IGRdir\lib mkdir $(TARGET)\om\IGRdir\lib
	@if not exist $(TARGET)\om\IGRdir\btree mkdir $(TARGET)\om\IGRdir\btree
	@if not exist $(TARGET)\om\IGRdir\dir mkdir $(TARGET)\om\IGRdir\dir
	@if not exist $(TARGET)\om\IGRdir\group mkdir $(TARGET)\om\IGRdir\group

_BTREE: $(TARGET)\om\IGRdir\btree\makefile
	@cd $(TARGET)\om\IGRdir\btree
	@cd
	@$(MAKE)

$(TARGET)\om\IGRdir\btree\makefile: $(EXNUC)\om\IGRdir\btree\btree.m
	cd $(EXNUC)\om\IGRdir\btree
	$(MAKEMAKE) btree.m $(TARGET)\om\IGRdir\btree\makefile

_DIR: $(TARGET)\om\IGRdir\dir\makefile
	@cd $(TARGET)\om\IGRdir\dir
	@cd
	@$(MAKE)

$(TARGET)\om\IGRdir\dir\makefile: $(EXNUC)\om\IGRdir\dir\dir.m
	cd $(EXNUC)\om\IGRdir\dir
	$(MAKEMAKE) dir.m $(TARGET)\om\IGRdir\dir\makefile

_GROUP: $(TARGET)\om\IGRdir\group\makefile
	@cd $(TARGET)\om\IGRdir\group
	@cd
	@$(MAKE)

$(TARGET)\om\IGRdir\group\makefile: $(EXNUC)\om\IGRdir\group\group.m
	cd $(EXNUC)\om\IGRdir\group
	$(MAKEMAKE) group.m $(TARGET)\om\IGRdir\group\makefile
