
 typedef int (* function_ptr)();
extern int DM$13_angular_roots_attr();
extern int DM$13_coord_roots_attr();
extern int DM$13_get_roots_attr();
extern int DM$13_linear_roots_attr();
extern int DM$13_radial_roots_attr();
extern int DM$action_handler();
extern int DM$active_values();
extern int DM$add_angular_field();
extern int DM$add_angular_text();
extern int DM$add_annot_char();
extern int DM$add_blanks_to_text();
extern int DM$add_char_str();
extern int DM$add_dimension_field();
extern int DM$add_dual_field();
extern int DM$add_format_string();
extern int DM$add_label_field();
extern int DM$add_seperator();
extern int DM$add_symbol_char();
extern int DM$add_symbol_text();
extern int DM$add_tolerance_symbol();
extern int DM$ancestry_valid();
extern int DM$ang_compute_proj_line();
extern int DM$annotdyn();
extern int DM$atof();
extern int DM$broadcast();
extern int DM$broadcast_subgraph();
extern int DM$car_pos();
extern int DM$change_node();
extern int DM$change_text_mode();
extern int DM$chg_to_grp();
extern int DM$clean_data();
extern int DM$clear_cache();
extern int DM$comp_obj();
extern int DM$compute_ang_limits();
extern int DM$compute_angular_text();
extern int DM$compute_dim_string();
extern int DM$compute_dim_text();
extern int DM$compute_disp_char_posn();
extern int DM$compute_endpt();
extern int DM$compute_object();
extern int DM$compute_prefix();
extern int DM$compute_single_end();
extern int DM$compute_single_start();
extern int DM$compute_suffix();
extern int DM$compute_symbol_text();
extern int DM$compute_tol_limits();
extern int DM$compute_tol_middle();
extern int DM$compute_tol_up_low();
extern int DM$compute_valid_index();
extern int DM$conv_13();
extern int DM$conv_cenline();
extern int DM$conv_cpx();
extern int DM$conv_dim();
extern int DM$conv_file();
extern int DM$conv_gpar();
extern int DM$conv_gplan();
extern int DM$conv_gt();
extern int DM$conv_gt_text();
extern int DM$conv_leader();
extern int DM$conv_lpar();
extern int DM$conv_lplan();
extern int DM$conv_src();
extern int DM$conv_status();
extern int DM$conv_tole();
extern int DM$conv_txbln();
extern int DM$conv_txldr();
extern int DM$conv_txldr_text();
extern int DM$convert_form_value();
extern int DM$copy_dimension();
extern int DM$copy_roots();
extern int DM$create_dim_param();
extern int DM$create_dmplan();
extern int DM$create_lplan();
extern int DM$create_root();
extern int DM$dat_cmpx_feet_print();
extern int DM$dat_cmpx_print();
extern int DM$dat_elem_feet_print();
extern int DM$dat_elem_print();
extern int DM$dat_environ_print();
extern int DM$dat_fields_dump();
extern int DM$dat_local_print();
extern int DM$decacc();
extern int DM$deci_dimension();
extern int DM$default_dim_stan();
extern int DM$delete_components();
extern int DM$delete_dimension();
extern int DM$delete_expr();
extern int DM$delete_text();
extern int DM$dim_stan();
extern int DM$dimension_dynamics();
extern int DM$display_dimension();
extern int DM$dual_above_end();
extern int DM$dual_above_middle();
extern int DM$dual_above_start();
extern int DM$dynamics();
extern int DM$end_dim();
extern int DM$extend_curve();
extern int DM$extend_points();
extern int DM$feet_str();
extern int DM$fill_plan_info();
extern int DM$first_compute();
extern int DM$fld_fil();
extern int DM$form_to_internal();
extern int DM$fraacc();
extern int DM$get_active_just();
extern int DM$get_annot_txt_info();
extern int DM$get_axis_info();
extern int DM$get_best_window();
extern int DM$get_cache_data();
extern int DM$get_cnv_factor();
extern int DM$get_coord_text_info();
extern int DM$get_dim13_symb();
extern int DM$get_dim_param();
extern int DM$get_dim_plane();
extern int DM$get_dimn_string_val();
extern int DM$get_direction();
extern int DM$get_first_13();
extern int DM$get_frac_index();
extern int DM$get_graph();
extern int DM$get_gt_labels();
extern int DM$get_just_pt();
extern int DM$get_keyin_index();
extern int DM$get_mea_trak();
extern int DM$get_meas_axis();
extern int DM$get_module_info();
extern int DM$get_neighbour();
extern int DM$get_option();
extern int DM$get_option_count();
extern int DM$get_param_info();
extern int DM$get_parents();
extern int DM$get_plan_from_pretend();
extern int DM$get_plan_mgr();
extern int DM$get_plus_minus_flag();
extern int DM$get_possible_posn();
extern int DM$get_prefix_suffix_val();
extern int DM$get_source_obj();
extern int DM$get_super();
extern int DM$get_text_info();
extern int DM$get_tol_symbol_char();
extern int DM$give_dim13_info();
extern int DM$give_feet_info();
extern int DM$give_template_info();
extern int DM$group_13();
extern int DM$init_dim_params();
extern int DM$init_drawing();
extern int DM$init_glob();
extern int DM$inquire_hilite();
extern int DM$insert_text();
extern int DM$internal_to_keyboard();
extern int DM$invoke_dynamics();
extern int DM$invoke_txdynamics();
extern int DM$is_comp_crv();
extern int DM$is_complex();
extern int DM$is_dim_in_rtree();
extern int DM$is_tol_sym_exists();
extern int DM$keyboard_to_internal();
extern int DM$list_keyins();
extern int DM$load_cache();
extern int DM$locate();
extern int DM$locate_dynamics();
extern int DM$make_alter_text();
extern int DM$make_annot_text();
extern int DM$make_chamfer_text();
extern int DM$make_fields();
extern int DM$make_grgrp();
extern int DM$make_tol_symbol();
extern int DM$map_font();
extern int DM$map_gadget_value();
extern int DM$map_tol_symbol();
extern int DM$mat_diff();
extern int DM$merge_complex();
extern int DM$merge_senv();
extern int DM$mod_andyn();
extern int DM$mod_graph_batch_cp();
extern int DM$modify_annot();
extern int DM$notify_disconnect();
extern int DM$notify_form();
extern int DM$place_angular();
extern int DM$place_annotation();
extern int DM$place_cirdia();
extern int DM$place_lindia();
extern int DM$place_radial();
extern int DM$place_sglpara();
extern int DM$place_stack_linear();
extern int DM$preproc_presuf();
extern int DM$process_keyin();
extern int DM$process_keyin_FORM_DISPLAY();
extern int DM$process_keyin_FORM_ENVIRON();
extern int DM$process_keyin_FORM_LOCAL();
extern int DM$process_keyin_NOT_ON_FORM();
extern int DM$project_points();
extern int DM$put_by_value();
extern int DM$put_dim_param();
extern int DM$replace_cap();
extern int DM$replace_dim();
extern int DM$replace_tol_sym();
extern int DM$retrieve_font();
extern int DM$return_dim_field();
extern int DM$select_sector();
extern int DM$set_dim_stan();
extern int DM$set_dyn_flag();
extern int DM$skip_symbol();
extern int DM$split_cmpx();
extern int DM$split_elem();
extern int DM$split_senv();
extern int DM$start_str();
extern int DM$strcat();
extern int DM$strequ();
extern int DM$strip();
extern int DM$strncpy();
extern int DM$supress_digit();
extern int DM$text_box();
extern int DM$text_processing();
extern int DM$tol_end();
extern int DM$tol_lim_end();
extern int DM$tol_limit_center();
extern int DM$tol_limit_start();
extern int DM$tol_middle_start();
extern int DM$tol_up_low_center();
extern int DM$tol_up_low_end();
extern int DM$tol_up_low_start();
extern int DM$txt_conv_fact();
extern int DM$undo_text_string();
extern int DM$update_complex();
extern int DM$update_event();
extern int DM$updt_disp_chars();
extern int DM$upper_to_lower();
extern int MA$TH_compute_plan_info();
extern int MA$TH_get_box_points();
extern int MA$TH_get_box_pt_upar();
extern int MA$TH_intersect_box_line();
extern int MA$TH_line_break();
extern int MA$TH_line_extend();
extern int MA$TH_proj_along_vector();
extern int MA$TH_ptdelta();
extern int MA$TH_rotate_vector();
function_ptr DM13_angular_roots_attr=DM$13_angular_roots_attr;
function_ptr DM13_coord_roots_attr=DM$13_coord_roots_attr;
function_ptr DM13_get_roots_attr=DM$13_get_roots_attr;
function_ptr DM13_linear_roots_attr=DM$13_linear_roots_attr;
function_ptr DM13_radial_roots_attr=DM$13_radial_roots_attr;
function_ptr DMaction_handler=DM$action_handler;
function_ptr DMactive_values=DM$active_values;
function_ptr DMadd_angular_field=DM$add_angular_field;
function_ptr DMadd_angular_text=DM$add_angular_text;
function_ptr DMadd_annot_char=DM$add_annot_char;
function_ptr DMadd_blanks_to_text=DM$add_blanks_to_text;
function_ptr DMadd_char_str=DM$add_char_str;
function_ptr DMadd_dimension_field=DM$add_dimension_field;
function_ptr DMadd_dual_field=DM$add_dual_field;
function_ptr DMadd_format_string=DM$add_format_string;
function_ptr DMadd_label_field=DM$add_label_field;
function_ptr DMadd_seperator=DM$add_seperator;
function_ptr DMadd_symbol_char=DM$add_symbol_char;
function_ptr DMadd_symbol_text=DM$add_symbol_text;
function_ptr DMadd_tolerance_symbol=DM$add_tolerance_symbol;
function_ptr DMancestry_valid=DM$ancestry_valid;
function_ptr DMang_compute_proj_line=DM$ang_compute_proj_line;
function_ptr DMannotdyn=DM$annotdyn;
function_ptr DMatof=DM$atof;
function_ptr DMbroadcast=DM$broadcast;
function_ptr DMbroadcast_subgraph=DM$broadcast_subgraph;
function_ptr DMcar_pos=DM$car_pos;
function_ptr DMchange_node=DM$change_node;
function_ptr DMchange_text_mode=DM$change_text_mode;
function_ptr DMchg_to_grp=DM$chg_to_grp;
function_ptr DMclean_data=DM$clean_data;
function_ptr DMclear_cache=DM$clear_cache;
function_ptr DMcomp_obj=DM$comp_obj;
function_ptr DMcompute_ang_limits=DM$compute_ang_limits;
function_ptr DMcompute_angular_text=DM$compute_angular_text;
function_ptr DMcompute_dim_string=DM$compute_dim_string;
function_ptr DMcompute_dim_text=DM$compute_dim_text;
function_ptr DMcompute_disp_char_posn=DM$compute_disp_char_posn;
function_ptr DMcompute_endpt=DM$compute_endpt;
function_ptr DMcompute_object=DM$compute_object;
function_ptr DMcompute_prefix=DM$compute_prefix;
function_ptr DMcompute_single_end=DM$compute_single_end;
function_ptr DMcompute_single_start=DM$compute_single_start;
function_ptr DMcompute_suffix=DM$compute_suffix;
function_ptr DMcompute_symbol_text=DM$compute_symbol_text;
function_ptr DMcompute_tol_limits=DM$compute_tol_limits;
function_ptr DMcompute_tol_middle=DM$compute_tol_middle;
function_ptr DMcompute_tol_up_low=DM$compute_tol_up_low;
function_ptr DMcompute_valid_index=DM$compute_valid_index;
function_ptr DMconv_13=DM$conv_13;
function_ptr DMconv_cenline=DM$conv_cenline;
function_ptr DMconv_cpx=DM$conv_cpx;
function_ptr DMconv_dim=DM$conv_dim;
function_ptr DMconv_file=DM$conv_file;
function_ptr DMconv_gpar=DM$conv_gpar;
function_ptr DMconv_gplan=DM$conv_gplan;
function_ptr DMconv_gt=DM$conv_gt;
function_ptr DMconv_gt_text=DM$conv_gt_text;
function_ptr DMconv_leader=DM$conv_leader;
function_ptr DMconv_lpar=DM$conv_lpar;
function_ptr DMconv_lplan=DM$conv_lplan;
function_ptr DMconv_src=DM$conv_src;
function_ptr DMconv_status=DM$conv_status;
function_ptr DMconv_tole=DM$conv_tole;
function_ptr DMconv_txbln=DM$conv_txbln;
function_ptr DMconv_txldr=DM$conv_txldr;
function_ptr DMconv_txldr_text=DM$conv_txldr_text;
function_ptr DMconvert_form_value=DM$convert_form_value;
function_ptr DMcopy_dimension=DM$copy_dimension;
function_ptr DMcopy_roots=DM$copy_roots;
function_ptr DMcreate_dim_param=DM$create_dim_param;
function_ptr DMcreate_dmplan=DM$create_dmplan;
function_ptr DMcreate_lplan=DM$create_lplan;
function_ptr DMcreate_root=DM$create_root;
function_ptr DMdat_cmpx_feet_print=DM$dat_cmpx_feet_print;
function_ptr DMdat_cmpx_print=DM$dat_cmpx_print;
function_ptr DMdat_elem_feet_print=DM$dat_elem_feet_print;
function_ptr DMdat_elem_print=DM$dat_elem_print;
function_ptr DMdat_environ_print=DM$dat_environ_print;
function_ptr DMdat_fields_dump=DM$dat_fields_dump;
function_ptr DMdat_local_print=DM$dat_local_print;
function_ptr DMdecacc=DM$decacc;
function_ptr DMdeci_dimension=DM$deci_dimension;
function_ptr DMdefault_dim_stan=DM$default_dim_stan;
function_ptr DMdelete_components=DM$delete_components;
function_ptr DMdelete_dimension=DM$delete_dimension;
function_ptr DMdelete_expr=DM$delete_expr;
function_ptr DMdelete_text=DM$delete_text;
function_ptr DMdim_stan=DM$dim_stan;
function_ptr DMdimension_dynamics=DM$dimension_dynamics;
function_ptr DMdisplay_dimension=DM$display_dimension;
function_ptr DMdual_above_end=DM$dual_above_end;
function_ptr DMdual_above_middle=DM$dual_above_middle;
function_ptr DMdual_above_start=DM$dual_above_start;
function_ptr DMdynamics=DM$dynamics;
function_ptr DMend_dim=DM$end_dim;
function_ptr DMextend_curve=DM$extend_curve;
function_ptr DMextend_points=DM$extend_points;
function_ptr DMfeet_str=DM$feet_str;
function_ptr DMfill_plan_info=DM$fill_plan_info;
function_ptr DMfirst_compute=DM$first_compute;
function_ptr DMfld_fil=DM$fld_fil;
function_ptr DMform_to_internal=DM$form_to_internal;
function_ptr DMfraacc=DM$fraacc;
function_ptr DMget_active_just=DM$get_active_just;
function_ptr DMget_annot_txt_info=DM$get_annot_txt_info;
function_ptr DMget_axis_info=DM$get_axis_info;
function_ptr DMget_best_window=DM$get_best_window;
function_ptr DMget_cache_data=DM$get_cache_data;
function_ptr DMget_cnv_factor=DM$get_cnv_factor;
function_ptr DMget_coord_text_info=DM$get_coord_text_info;
function_ptr DMget_dim13_symb=DM$get_dim13_symb;
function_ptr DMget_dim_param=DM$get_dim_param;
function_ptr DMget_dim_plane=DM$get_dim_plane;
function_ptr DMget_dimn_string_val=DM$get_dimn_string_val;
function_ptr DMget_direction=DM$get_direction;
function_ptr DMget_first_13=DM$get_first_13;
function_ptr DMget_frac_index=DM$get_frac_index;
function_ptr DMget_graph=DM$get_graph;
function_ptr DMget_gt_labels=DM$get_gt_labels;
function_ptr DMget_just_pt=DM$get_just_pt;
function_ptr DMget_keyin_index=DM$get_keyin_index;
function_ptr DMget_mea_trak=DM$get_mea_trak;
function_ptr DMget_meas_axis=DM$get_meas_axis;
function_ptr DMget_module_info=DM$get_module_info;
function_ptr DMget_neighbour=DM$get_neighbour;
function_ptr DMget_option=DM$get_option;
function_ptr DMget_option_count=DM$get_option_count;
function_ptr DMget_param_info=DM$get_param_info;
function_ptr DMget_parents=DM$get_parents;
function_ptr DMget_plan_from_pretend=DM$get_plan_from_pretend;
function_ptr DMget_plan_mgr=DM$get_plan_mgr;
function_ptr DMget_plus_minus_flag=DM$get_plus_minus_flag;
function_ptr DMget_possible_posn=DM$get_possible_posn;
function_ptr DMget_prefix_suffix_val=DM$get_prefix_suffix_val;
function_ptr DMget_source_obj=DM$get_source_obj;
function_ptr DMget_super=DM$get_super;
function_ptr DMget_text_info=DM$get_text_info;
function_ptr DMget_tol_symbol_char=DM$get_tol_symbol_char;
function_ptr DMgive_dim13_info=DM$give_dim13_info;
function_ptr DMgive_feet_info=DM$give_feet_info;
function_ptr DMgive_template_info=DM$give_template_info;
function_ptr DMgroup_13=DM$group_13;
function_ptr DMinit_dim_params=DM$init_dim_params;
function_ptr DMinit_drawing=DM$init_drawing;
function_ptr DMinit_glob=DM$init_glob;
function_ptr DMinquire_hilite=DM$inquire_hilite;
function_ptr DMinsert_text=DM$insert_text;
function_ptr DMinternal_to_keyboard=DM$internal_to_keyboard;
function_ptr DMinvoke_dynamics=DM$invoke_dynamics;
function_ptr DMinvoke_txdynamics=DM$invoke_txdynamics;
function_ptr DMis_comp_crv=DM$is_comp_crv;
function_ptr DMis_complex=DM$is_complex;
function_ptr DMis_dim_in_rtree=DM$is_dim_in_rtree;
function_ptr DMis_tol_sym_exists=DM$is_tol_sym_exists;
function_ptr DMkeyboard_to_internal=DM$keyboard_to_internal;
function_ptr DMlist_keyins=DM$list_keyins;
function_ptr DMload_cache=DM$load_cache;
function_ptr DMlocate=DM$locate;
function_ptr DMlocate_dynamics=DM$locate_dynamics;
function_ptr DMmake_alter_text=DM$make_alter_text;
function_ptr DMmake_annot_text=DM$make_annot_text;
function_ptr DMmake_chamfer_text=DM$make_chamfer_text;
function_ptr DMmake_fields=DM$make_fields;
function_ptr DMmake_grgrp=DM$make_grgrp;
function_ptr DMmake_tol_symbol=DM$make_tol_symbol;
function_ptr DMmap_font=DM$map_font;
function_ptr DMmap_gadget_value=DM$map_gadget_value;
function_ptr DMmap_tol_symbol=DM$map_tol_symbol;
function_ptr DMmat_diff=DM$mat_diff;
function_ptr DMmerge_complex=DM$merge_complex;
function_ptr DMmerge_senv=DM$merge_senv;
function_ptr DMmod_andyn=DM$mod_andyn;
function_ptr DMmod_graph_batch_cp=DM$mod_graph_batch_cp;
function_ptr DMmodify_annot=DM$modify_annot;
function_ptr DMnotify_disconnect=DM$notify_disconnect;
function_ptr DMnotify_form=DM$notify_form;
function_ptr DMplace_angular=DM$place_angular;
function_ptr DMplace_annotation=DM$place_annotation;
function_ptr DMplace_cirdia=DM$place_cirdia;
function_ptr DMplace_lindia=DM$place_lindia;
function_ptr DMplace_radial=DM$place_radial;
function_ptr DMplace_sglpara=DM$place_sglpara;
function_ptr DMplace_stack_linear=DM$place_stack_linear;
function_ptr DMpreproc_presuf=DM$preproc_presuf;
function_ptr DMprocess_keyin=DM$process_keyin;
function_ptr DMprocess_keyin_FORM_DISPLAY=DM$process_keyin_FORM_DISPLAY;
function_ptr DMprocess_keyin_FORM_ENVIRON=DM$process_keyin_FORM_ENVIRON;
function_ptr DMprocess_keyin_FORM_LOCAL=DM$process_keyin_FORM_LOCAL;
function_ptr DMprocess_keyin_NOT_ON_FORM=DM$process_keyin_NOT_ON_FORM;
function_ptr DMproject_points=DM$project_points;
function_ptr DMput_by_value=DM$put_by_value;
function_ptr DMput_dim_param=DM$put_dim_param;
function_ptr DMreplace_cap=DM$replace_cap;
function_ptr DMreplace_dim=DM$replace_dim;
function_ptr DMreplace_tol_sym=DM$replace_tol_sym;
function_ptr DMretrieve_font=DM$retrieve_font;
function_ptr DMreturn_dim_field=DM$return_dim_field;
function_ptr DMselect_sector=DM$select_sector;
function_ptr DMset_dim_stan=DM$set_dim_stan;
function_ptr DMset_dyn_flag=DM$set_dyn_flag;
function_ptr DMskip_symbol=DM$skip_symbol;
function_ptr DMsplit_cmpx=DM$split_cmpx;
function_ptr DMsplit_elem=DM$split_elem;
function_ptr DMsplit_senv=DM$split_senv;
function_ptr DMstart_str=DM$start_str;
function_ptr DMstrcat=DM$strcat;
function_ptr DMstrequ=DM$strequ;
function_ptr DMstrip=DM$strip;
function_ptr DMstrncpy=DM$strncpy;
function_ptr DMsupress_digit=DM$supress_digit;
function_ptr DMtext_box=DM$text_box;
function_ptr DMtext_processing=DM$text_processing;
function_ptr DMtol_end=DM$tol_end;
function_ptr DMtol_lim_end=DM$tol_lim_end;
function_ptr DMtol_limit_center=DM$tol_limit_center;
function_ptr DMtol_limit_start=DM$tol_limit_start;
function_ptr DMtol_middle_start=DM$tol_middle_start;
function_ptr DMtol_up_low_center=DM$tol_up_low_center;
function_ptr DMtol_up_low_end=DM$tol_up_low_end;
function_ptr DMtol_up_low_start=DM$tol_up_low_start;
function_ptr DMtxt_conv_fact=DM$txt_conv_fact;
function_ptr DMundo_text_string=DM$undo_text_string;
function_ptr DMupdate_complex=DM$update_complex;
function_ptr DMupdate_event=DM$update_event;
function_ptr DMupdt_disp_chars=DM$updt_disp_chars;
function_ptr DMupper_to_lower=DM$upper_to_lower;
function_ptr MATH_compute_plan_info=MA$TH_compute_plan_info;
function_ptr MATH_get_box_points=MA$TH_get_box_points;
function_ptr MATH_get_box_pt_upar=MA$TH_get_box_pt_upar;
function_ptr MATH_intersect_box_line=MA$TH_intersect_box_line;
function_ptr MATH_line_break=MA$TH_line_break;
function_ptr MATH_line_extend=MA$TH_line_extend;
function_ptr MATH_proj_along_vector=MA$TH_proj_along_vector;
function_ptr MATH_ptdelta=MA$TH_ptdelta;
function_ptr MATH_rotate_vector=MA$TH_rotate_vector;
