.PRECIOUS: $(MODEL)\src_lib\EMSdpbI.obj

.SUFFIXES: .lib .I .c .obj

CC = cl386

ECHO = d:\ingr\exnuc\bin\execho

LINKOPT = -subsystem:console -entry:mainCRTStartup

SRC = .

OPPFLAGS =  \
	-I$(MODEL)\include \
	-I$(EXNUC)\include \
	-I$(GRNUC)\include \
	-I$(BS)\include \
	-I$(OM)\spec \
	-I$(GRNUC)\spec \
	-I$(MODEL)\spec \
	-I$(EXNUC)\spec \
	-I$(SRC)

opp = $(EXNUC)\bin\opp

omcpp = $(EXNUC)\bin\omcpp

IPATH =  \
	-I$(MODEL)\include \
	-I$(EXNUC)\include \
	-I$(GRNUC)\include \
	-I$(BS)\include

MOPT = -D_M_IX86=300 -Di386=1


# Object files 

imp_objects = \
	EMdpbform.obj \
	EMdpbi.obj

objects = \
	$(imp_objects) 


# src group targets

objects_TARGET = $(MODEL)\src_lib\EMSdpbI.obj

$(objects_TARGET): $(objects)
	@$(ECHO)
	coff -lib $(DEBUGTYPE) -out:$(MODEL)\src_lib\EMSdpbI.obj @Mobjects
	@if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\tdir /n $(MODEL)\src_lib\EMSdpbI.obj"
	@dir /n $(MODEL)\src_lib\EMSdpbI.obj
	@$(ECHO)

EMdpbform.obj : \
	$(SRC)\EMdpbform.I \
	c:\mstools\h\stddef.h \
	$(OM)\spec\Root.S \
	$(OM)\spec\global_class.S \
	$(MODEL)\spec\EMSdpb.S \
	$(GRNUC)\include\EMmsg_obj.h \
	$(MODEL)\include\EMS.h \
	c:\mstools\h\tchar.h \
	d:\ingr\shamrock\include\fi.h \
	d:\ingr\shamrock\include\fidyn.h \
	d:\ingr\shamrock\include\shampub.h \
	c:\mstools\h\winbase.h \
	c:\mstools\h\wingdi.h \
	c:\mstools\h\stdarg.h \
	c:\mstools\h\winuser.h \
	c:\mstools\h\winnls.h \
	c:\mstools\h\winmm.h \
	c:\mstools\h\wincon.h \
	c:\mstools\h\winver.h \
	c:\mstools\h\winreg.h \
	c:\mstools\h\winnetwk.h \
	c:\mstools\h\cderr.h \
	c:\mstools\h\commdlg.h \
	c:\mstools\h\winnt.h \
	c:\mstools\h\windef.h \
	c:\mstools\h\dde.h \
	c:\mstools\h\ddeml.h \
	c:\mstools\h\dlgs.h \
	c:\mstools\h\drivinit.h \
	c:\mstools\h\lzexpand.h \
	c:\mstools\h\mmsystem.h \
	c:\mstools\h\nb30.h \
	c:\mstools\h\ole.h \
	c:\mstools\h\rpcdcep.h \
	c:\mstools\h\rpcdce.h \
	c:\mstools\h\rpcnsi.h \
	c:\mstools\h\rpcnterr.h \
	c:\mstools\h\excpt.h \
	c:\mstools\h\winerror.h \
	c:\mstools\h\rpc.h \
	c:\mstools\h\shellapi.h \
	c:\mstools\h\winperf.h \
	c:\mstools\h\winsock.h \
	c:\mstools\h\winspool.h \
	c:\mstools\h\winsvc.h \
	c:\mstools\h\windows.h \
	d:\ingr\shamrock\include\FI.h \
	c:\mstools\h\math.h \
	c:\mstools\h\string.h \
	$(BS)\include\bserr.h \
	$(BS)\include\bsconic.h \
	$(GRNUC)\include\igr.h \
	$(BS)\include\bstypes.h \
	$(BS)\include\bsdefs.h \
	$(BS)\include\bs.h \
	$(BS)\include\bsparameters.h \
	$(GRNUC)\include\godef.h \
	$(GRNUC)\include\dp.h \
	$(GRNUC)\include\dpmacros.h \
	$(GRNUC)\include\sunlimits.h \
	$(GRNUC)\include\go.h \
	$(GRNUC)\include\griodef.h \
	$(GRNUC)\include\grio.h \
	$(GRNUC)\include\igrdp.h \
	$(GRNUC)\include\gr.h \
	$(GRNUC)\include\grdpbdef.h \
	$(GRNUC)\include\grdpb.h \
	$(GRNUC)\include\grdpbmacros.h \
	$(EXNUC)\include\msdef.h \
	d:\ingr\shamrock\include\mi.h \
	d:\ingr\shamrock\include\ms.h \
	$(EXNUC)\include\UMS.h \
	$(EXNUC)\include\exms.h \
	$(EXNUC)\include\msmacros.h \
	$(BS)\include\maerr.h \
	$(GRNUC)\include\lcdef.h \
	$(GRNUC)\include\lc.h \
	$(GRNUC)\include\lcmacros.h \
	$(MODEL)\include\EMSellpsd.h \
	$(EXNUC)\include\OMerrordef.h \
	$(EXNUC)\include\OMprimitives.h \
	$(EXNUC)\include\OMcluster.h \
	$(EXNUC)\include\OMmacros.h \
	$(MODEL)\include\EMSasnucdef.h \
	$(MODEL)\include\EMSasnuc.h \
	$(MODEL)\include\EMSasdef.h \
	$(EXNUC)\include\DIdef.h \
	$(EXNUC)\include\DItypedef.h \
	$(GRNUC)\include\parametric.h \
	$(GRNUC)\include\dimdef.h \
	$(GRNUC)\include\dim.h \
	$(GRNUC)\include\dimsrc.h \
	$(GRNUC)\include\dimplan.h \
	$(GRNUC)\include\diminfo.h \
	$(MODEL)\include\EMSas.h \
	$(MODEL)\include\REgenbs.h \
	$(MODEL)\include\ems_m_inc.h \
	$(GRNUC)\include\griomacros.h \
	$(EXNUC)\include\exfi.h \
	$(EXNUC)\include\ex.h \
	$(EXNUC)\include\exmacros.h \
	$(EXNUC)\include\exdef.h \
	$(MODEL)\include\emsdef.h \
	$(MODEL)\include\EMSreleased.h \
	$(MODEL)\include\EMSlogic.h \
	$(MODEL)\include\EMSmsgassist.h \
	$(MODEL)\include\EMSmsgnumdef.h \
	$(MODEL)\include\EMSmsgdef.h \
	$(MODEL)\include\EMSerrordef.h \
	$(GRNUC)\include\EMSdpb.h \
	$(EXNUC)\include\OMlimits.h \
	$(EXNUC)\include\OMtypes.h \
	$(EXNUC)\include\OMminimum.h \
	$(EXNUC)\include\igrtypedef.h \
	$(EXNUC)\include\igetypedef.h \
	$(EXNUC)\include\igewindef.h \
	$(EXNUC)\include\igewindow.h \
	$(EXNUC)\include\igewinmacros.h \
	c:\mstools\h\stdio.h

EMdpbi.obj : \
	$(SRC)\EMdpbi.I \
	c:\mstools\h\stddef.h \
	$(EXNUC)\include\OMprimitives.h \
	$(OM)\spec\Root.S \
	$(OM)\spec\global_class.S \
	$(EXNUC)\include\OMerrordef.h \
	$(MODEL)\include\EMSreleased.h \
	$(MODEL)\include\EMSlogic.h \
	$(MODEL)\include\EMSmsgassist.h \
	$(MODEL)\include\EMSmsgnumdef.h \
	$(MODEL)\include\EMSmsgdef.h \
	$(MODEL)\include\EMSerrordef.h \
	$(GRNUC)\include\EMSdpb.h \
	$(MODEL)\spec\EMSdpb.S \
	$(GRNUC)\include\dp.h \
	$(GRNUC)\include\EMmsg_obj.h \
	$(EXNUC)\include\igetypedef.h \
	$(GRNUC)\include\godef.h \
	$(GRNUC)\include\gr.h \
	$(GRNUC)\include\igrdp.h \
	$(GRNUC)\include\sunlimits.h \
	$(EXNUC)\include\DIdef.h \
	$(GRNUC)\include\go.h \
	$(MODEL)\include\EMS.h \
	c:\mstools\h\tchar.h \
	d:\ingr\shamrock\include\fi.h \
	d:\ingr\shamrock\include\fidyn.h \
	d:\ingr\shamrock\include\mi.h \
	d:\ingr\shamrock\include\shampub.h \
	c:\mstools\h\winbase.h \
	c:\mstools\h\wingdi.h \
	c:\mstools\h\stdarg.h \
	c:\mstools\h\winuser.h \
	c:\mstools\h\winnls.h \
	c:\mstools\h\winmm.h \
	c:\mstools\h\wincon.h \
	c:\mstools\h\winver.h \
	c:\mstools\h\winreg.h \
	c:\mstools\h\winnetwk.h \
	c:\mstools\h\cderr.h \
	c:\mstools\h\commdlg.h \
	c:\mstools\h\winnt.h \
	c:\mstools\h\windef.h \
	c:\mstools\h\dde.h \
	c:\mstools\h\ddeml.h \
	c:\mstools\h\dlgs.h \
	c:\mstools\h\drivinit.h \
	c:\mstools\h\lzexpand.h \
	c:\mstools\h\mmsystem.h \
	c:\mstools\h\nb30.h \
	c:\mstools\h\ole.h \
	c:\mstools\h\rpcdcep.h \
	c:\mstools\h\rpcdce.h \
	c:\mstools\h\rpcnsi.h \
	c:\mstools\h\rpcnterr.h \
	c:\mstools\h\excpt.h \
	c:\mstools\h\winerror.h \
	c:\mstools\h\rpc.h \
	c:\mstools\h\shellapi.h \
	c:\mstools\h\winperf.h \
	c:\mstools\h\winsock.h \
	c:\mstools\h\winspool.h \
	c:\mstools\h\winsvc.h \
	c:\mstools\h\windows.h \
	d:\ingr\shamrock\include\FI.h \
	$(GRNUC)\include\GMdef.h \
	$(GRNUC)\include\nddef.h \
	$(GRNUC)\include\GMhcode.h \
	$(GRNUC)\include\GMlist.h \
	$(GRNUC)\include\GM.h \
	$(GRNUC)\include\GMmacros.h \
	$(GRNUC)\include\ndmacros.h \
	$(GRNUC)\include\grdpbdef.h \
	$(GRNUC)\include\grdpbmacros.h \
	c:\mstools\h\stdio.h \
	c:\mstools\h\string.h \
	$(EXNUC)\include\exdef.h \
	$(EXNUC)\include\OMlimits.h \
	$(EXNUC)\include\OMtypes.h \
	$(EXNUC)\include\OMminimum.h \
	$(EXNUC)\include\exfi.h \
	$(EXNUC)\include\ex.h \
	$(EXNUC)\include\exmacros.h \
	$(GRNUC)\include\igr.h \
	$(BS)\include\bstypes.h \
	$(BS)\include\bserr.h \
	$(EXNUC)\include\igrtypedef.h \
	$(BS)\include\bsparameters.h \
	$(MODEL)\include\emsdef.h

$(imp_objects):
	@if not "$(@D)" == "" if not "$(@D)" == "." if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\tcd $(@D)"
	@if not "$(@D)" == "" if not "$(@D)" == "." cd $(@D)
	@if "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(SRC)\$(@:.obj=.I) -> $(@:.obj=.c)"
	@if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $(@:.obj=.I)"
	@$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $(@:.obj=.I)
	@if "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(@:.obj=.c) -> $(@)"
	@if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(CC) $(COPT) $(IPATH) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $(@F:.obj=.c)"
	@$(CC) $(COPT) $(IPATH) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $(@F:.obj=.c)
	@if "$(DEBUGAMOUNT)" == "" if "$(VERBOSE_RULES)" == "" $(ECHO) "\\tremoving $(@:.obj=.c)"
	@if "$(DEBUGAMOUNT)" == "" if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\tdel/q $(@F:.obj=.c)"
	@if "$(DEBUGAMOUNT)" == "" del/q $(@F:.obj=.c)
	@if not "$(DEBUGAMOUNT)" == "" if "$(VERBOSE_RULES)" == "" $(ECHO) "\\tleaving $(@:.obj=.c)"
	@$(ECHO) 

.I.obj:
	@if "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$< -> $*.c"
	@if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $<"
	@$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $<
	@if "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$*.c -> $*.o"
	@if "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(CC) $(COPT) $(IPATH) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c"
	@$(CC) $(COPT) $(IPATH) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c
	@if "$(DEBUGAMOUNT)" == "" if "$(VERBOSE_RULES)" == "" $(ECHO) "\\tremoving $*.c"
	@if "$(DEBUGAMOUNT)" == "" if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\tdel/q $*.c"
	@if "$(DEBUGAMOUNT)" == "" del/q $*.c
	@if not "$(DEBUGAMOUNT)" == "" if "$(VERBOSE_RULES)" == "" $(ECHO) "\\tleaving $*.c"
	@$(ECHO) 

.c.obj:
	@if "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$< -> $*.obj"
	@if not "$(VERBOSE_RULES)" == "" $(ECHO) "\\t$(CC) $(COPT) $(IPATH) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c"
	@$(CC) $(COPT) $(IPATH) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c
	@$(ECHO) 



