#/* $Id: makefile,v 1.2 2001/01/17 19:53:11 ramarao Exp $  */

#/***************************************************************************
# * I/STRUCT
# *
# * File:        isdp/struct/vsapis/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.2  2001/01/17 19:53:11  ramarao
# *      *** empty log message ***
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 01/16/01  RR      File Creation
# ***************************************************************************/

TGT = vsapis

include ${STRUCT}/etc/makefiles/lib_only.h
