# Do not alter this SPC information: $Revision: 1.8.4.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt
RIS_PRODUCT=RISAPP
IS_RISSRV=NOT_RISSRV
RM_EXE_DIR=risapp\setup32\bin\$(BINDIR)
RMPROD_DIR=risapp\setup32\removent
!include $(RISDEVDIR)\riscli\setup32\rmprod\makefile.mak
