# $Id: makefile,v 1.1 2001/05/07 13:16:52 paul_noel Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdfile/ppl/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1  2001/05/07 13:16:52  paul_noel
#	Inital Creation File Browser
#	
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	05/01/01	pn		mkmkppl 
#
# -------------------------------------------------------------------

TGT = vdifileppl

include ${VDS_PATH}/etc/makefiles/ppl_only.h
