# $Id: makefile,v 1.2 2001/05/17 17:31:26 ramarao Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vddraw/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/05/17 17:31:26  ramarao
#	Added VDdrwGm20 and VDdrwGm30 macros.
#	
#	Revision 1.1.1.1  2001/01/04 21:08:38  cvs
#	Initial import to CVS
#	
# OPE
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	12/01/94	adz		creation date
#
# -------------------------------------------------------------------

TGT = vddrawimp

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o *.c
