# $Id: makefile,v 1.2 2001/05/12 22:09:27 ylong Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdpen/macros/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/05/12 22:09:27  ylong
#	CR5209, TR5109
#	
#	Revision 1.1.1.1  2001/01/04 21:08:58  cvs
#	Initial import to CVS
#	
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

TGT = penmacros

include ${VDS_PATH}/etc/makefiles/ppl_only.h
