# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:22 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/cimacros/wireframe/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:07:22  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:52:02  pinnacle
# rep bin w/txt
#
# Revision 1.3  1995/09/26  21:17:10  pinnacle
# Replaced: cimacros/wireframe/imp/makefile for:  by sundar for vds.240
#
# Revision 1.2  1995/09/25  21:16:38  pinnacle
# Replaced: cimacros/wireframe/imp/makefile for:  by sundar for vds.240
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target: mkfile
	grmake -r -k -f mkfile

mkfile: cimac_wrf.m
	grmakemake cimac_wrf.m mkfile
