/* ###################   APOGEE COMPILED   ################## */
class specification EMSdimdtm1 (2:0) of ASnode, EMSdimdtm;

/*
 * The function of this class is to provide the ability for objects to
 * connect to this object using the notification channel. The parent class
 * EMSdimdtm does not have this ability.
 *
 * History
 *  Creation : PP : 02/27/93
 */

override GRvg;

end specification EMSdimdtm1;
