SRC
$(MODEL)/src_tol/imp
OPP
$(EXTARG)/bin/opp
OMCPP
$(EXTARG)/bin/omcpp
INCLUDE
$(INGRHOME)/include
$(XINC)
$(GRNUC)/ingrsys
$(MODEL)/include
$(EXNUC)/include
$(GRNUC)/include
$(GRNUC)/src/assoc/include_priv
$(BS)/include
$(BS)/include/prototypes
#if defined (XGL)
$(XGLHOME)/include
$(XGLHOME)/include/xgl
#endif
SPEC
$(EXNUC)/spec
$(GRNUC)/spec
$(MODEL)/spec
LIB
$(MDTARG)/src_lib/EMStolI.o
SOURCE
ECtoli.I
ECworstoli.I
