#/* $Id: makefile,v 1.3 2001/04/12 14:04:45 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdxml/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.3  2001/04/12 14:04:45  ahundiak
# *      ah
# *
# *      Revision 1.2  2001/01/11 21:30:18  art
# *      sp merge
# *
# Revision 1.1  2000/04/25  16:20:48  pinnacle
# ah
#
# Revision 1.1  1999/04/21  20:01:14  pinnacle
# xml
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 04/21/99  ah      creation
# * 01/11/01  ah      sp merge
# ***************************************************************************/

TGT = vdixml
include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o
	@rm -f VDxmlBsp.c VDpdfChr.c VDpdfVerify.c VDxml.c VDpdf.c VDhttp.c
	@rm -f VDdxf.c VDpdfAttrs.c VDxmlDom.c
