#!/bin/ksh
# Do not alter this line: $Revision: 1.1.54.1 $
if [ `uname` = 'SunOS' ] ; then \
	sts=$(/usr/5bin/ln -f $* 2>&1 | grep -v 'identical' | grep -v 'File exists')
fi
if [ `uname` = 'CLIX' ] ; then \
	sts=$(/bin/ln -f $* 2>&1 | grep -v 'identical' | grep -v 'File exists')
fi
if [ `uname` = 'rissmp' ] ; then \
	sts=$(/bin/ln -f $* 2>&1 | grep -v 'identical' | grep -v 'File exists')
fi
if [ "$sts" ]; then
	echo $sts
	exit 1
fi
exit 0
