#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:09:32 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vexml/makefile
# *
# * Description: 
# *
# * Dependencies:
# *
# * Revision History:
# * $Log: makefile,v $
# * Revision 1.1.1.1  2001/01/04 21:09:32  cvs
# * Initial import to CVS
# *
# Revision 1.1  2000/03/31  17:06:38  pinnacle
# ah
#
# Revision 1.1  2000/03/24  15:49:10  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 03/08/00  ah      Creation
# *
# ***************************************************************************/
target: mkfile
	grmake -r -k -f mkfile

mkfile:	vdivexml.m
	grmakemake vdivexml.m mkfile


