# $Id: makefile,v 1.2 2001/07/28 20:07:14 ad Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdannot/func/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/07/28 20:07:14  ad
#	*** empty log message ***
#	
#	Revision 1.1.1.1  2001/01/04 21:07:41  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:21:26  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	07/28/01	adz		New makefile
# -------------------------------------------------------------------

TGT = vdannotfc

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o *.c

