# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:57 cvs Exp $

#***********************************************************************
# I/VDS
#
# File:         vdmeasure/imp/makefile
#
# Description:
#
# Dependencies:
#
# Revision History
#       $Log: makefile,v $
#       Revision 1.1.1.1  2001/01/04 21:08:57  cvs
#       Initial import to CVS
#
# Revision 1.1  1997/05/08  15:38:18  pinnacle
# rep bin w/txt
#
# Revision 1.2  1997/03/12  17:18:32  pinnacle
# Replaced: vdmeasure/imp/makefile for:  by v241_int for vds.241
#
# Revision 1.1  1996/11/08  21:50:28  pinnacle
# Created: vdmeasure/imp/makefile by v241_int for vds.241
#
#
# History:
#       MM/DD/YY        AUTHOR          DESCRIPTION
#       11/08/96        mf              creation date
#
#***********************************************************************

target:	mkfile
	grmake -r -k -f mkfile 

mkfile: vdmeasimp.m
	grmakemake vdmeasimp.m mkfile
