#include "machine.h"
#include <signal.h>
#include <errno.h>
#include "NFMerrordef.h"
#include "DEBUG.h"
#include "ERR.h"
#include "CVTstruct.h"

extern struct CVTglobal_st CVTglobal ;

long CVTinit_signal_handler ()
{
     long 	 status;
     void 	 CVTsignal_handler();
     static char *fname = "CVTinit_signal_handler";

     _NFMdebug ((fname, "ENTER\n"));

     /* Initial CVT signal handler to accept SIGTERM and SIGINT (Ctrl-C) */

     if (signal(SIGTERM, CVTsignal_handler) == SIG_ERR)
     {
         status = NFM_E_FAILURE;
         _NFMdebug ((fname, 
		"Signal for SIGTERM failed : errno <%d> : status <0x%.8x>\n", 
	 	   errno, status));
         return (status);
     } 

     if (signal(SIGINT, CVTsignal_handler) == SIG_ERR)
     {
         status = NFM_E_FAILURE;
         _NFMdebug ((fname, 
		"Signal for SIGINT failed : errno <%d> : status <0x%.8x>\n", 
		   errno, status));
         return (status);
     } 

     /* Ignore other signals generated by keyboard input. */

     if (signal(SIGQUIT, SIG_IGN) == SIG_ERR)
     {
         status = NFM_E_FAILURE;
         _NFMdebug ((fname, 
		"Signal for SIGQUIT failed : errno <%d> : status <0x%.8x>\n", 
		   errno, status));
         return (status);
     } 
     if (signal(SIGHUP, SIG_IGN) == SIG_ERR)
     {
         status = NFM_E_FAILURE;
         _NFMdebug ((fname, 
		"Signal for SIGHUP failed : errno <%d> : status <0x%.8x>\n", 
		   errno, status));
         return (status);
     } 
     if (signal(SIGTSTP, SIG_IGN) == SIG_ERR)
     {
         status = NFM_E_FAILURE;
         _NFMdebug ((fname, 
		"Signal for SIGTSTP failed : errno <%d> : status <0x%.8x>\n", 
		   errno, status));
         return (status);
     } 
     
     CVTglobal.NFM_STOP_CONVERT = FALSE; 
     _NFMdebug ((fname, "Successful Completion\n"));
     return (NFM_S_SUCCESS);
}


void CVTsignal_handler(sig)
int sig;
{
     static char *fname = "CVTsignal_handler";
   
     _NFMdebug ((fname, "ENTER\n"));
     _NFMdebug ((fname, "Signal Received <%d>\n", sig));

     CVTglobal.NFM_STOP_CONVERT = TRUE;

     _NFMdebug ((fname, "EXIT\n"));
}
