# $Id: makefile,v 1.4 2001/10/17 20:40:09 hans Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:        vdannot/dim/makefile
#
# Description:
#
# Dependencies:
#
# Revision History:
#      $Log: makefile,v $
#      Revision 1.4  2001/10/17 20:40:09  hans
#      Modifications for CR# MP5368
#
#      Revision 1.3  2001/01/23 13:44:51  build
#      makefile typo
#
#      Revision 1.2  2001/01/19 23:18:49  jayadev
#      *** empty log message ***
#
#      Revision 1.1.1.1  2001/01/04 21:07:40  cvs
#      Initial import to CVS
#
# Revision 1.1  1997/05/08  15:21:20  pinnacle
# rep bin w/txt
#
# Revision 1.2  1996/01/10  19:14:30  pinnacle
# Replaced: vdannot/dim/makefile for:  by jwfrosch for vds.240
#
#
# History:
#	MM/DD/YYYY	AUTHOR	DESCRIPTION
#
# -------------------------------------------------------------------

TGT = vdiannotdim
TGT_PPL = ppldim

include ${VDS_PATH}/etc/makefiles/lib_ppl.h
