# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	12/21/94	adz		add new functions.
#
# -------------------------------------------------------------------

target:	mkfile
	grmake -r -k -f mkfile

mkfile: vdproot.m
	grmakemake -i $$CPUTYPE.mk vdproot.m mkfile
