#include "PDUris_incl.h"

#define PDMS_DUP_UNIQUE_INDEX        RIS_E_DUPLICATE_VALUE
#define PDMS_NO_SUCH_ATTRIBUTE       RIS_E_ATTR_NOT_FOUND
#define PDMS_ATTRIBUTE_EXISTS        RIS_E_ATTR_EXISTS
#define PDMS_NO_SUCH_TABLE           206
#define PDMS_TABLE_EXISTS            310


