binaries: \
	directories \
	_CCD \
	_EXSP

directories:
	@if not exist $(TARGET)\trans\ccd mkdir $(TARGET)\trans\ccd
	@if not exist $(TARGET)\trans\sp_proc mkdir $(TARGET)\trans\sp_proc

_CCD: $(TARGET)\trans\ccd\makefile
	@$(ECHO) "\\n\\tMaking ccd ..."
	@cd $(TARGET)\trans\ccd
	@cd
	@$(MAKE)

$(TARGET)\trans\ccd\makefile: $(EXNUC)\trans\ccd\ccd.m
	cd $(EXNUC)\trans\ccd
	$(MAKEMAKE) ccd.m $(TARGET)\trans\ccd\makefile

_EXSP: $(TARGET)\trans\sp_proc\makefile
	@$(ECHO) "\\n\\tMaking sp_proc ..."
	@cd $(TARGET)\trans\sp_proc
	@cd
	@$(MAKE)

$(TARGET)\trans\sp_proc\makefile: $(EXNUC)\trans\sp_proc\sp_proc.m
	cd $(EXNUC)\trans\sp_proc
	$(MAKEMAKE) sp_proc.m $(TARGET)\trans\sp_proc\makefile
