#/* $Id: makefile,v 1.4 2001/04/03 16:46:30 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdctx/c/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.4  2001/04/03 16:46:30  ahundiak
# *      ah
# *
# *      Revision 1.3  2001/01/14 16:07:35  art
# *      sp merge
# *
# *      Revision 1.1  2001/01/14 16:02:29  art
# *      sp merge
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 12/12/00  ah      creation
# ***************************************************************************/

TGT = vdictxc

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o
