#include "ECcmd.h"
EM_M_ChmfEdg,EMChEd,ECchamfered,2,
EM_M_ChmfVtx,EMChVr,ECchamfered,3,
EM_M_CompTree,EMCmStTr,ECcomptree,0,
EM_M_CreSelSurSolBoo,EMCSSrSlBl,ECspbool,2
^EM_M_ExtSurSolInt,EMExSrSlTI,ECspbool,1
^EM_M_DebugReadGeom,EMRdGm,ECdebugEd,13
^EM_M_DebugWriteGeom,EMWrGm,ECdebugEd,6
^EM_M_DebugEditGeom,EMEdGm,ECdebugEd,3
EM_M_FrTrNd,EMUnStTrSp,ECselundo,0
EM_M_LctIntmdNd,EMLcInNd,ECselundo,2
EM_M_LiftFaceWithDraft,EMLfFcDrAn,ECdlift,0,
EM_M_LiftFace,EMLfFc,ECdlift,1,
EM_M_MkeAndLftFce,EMCrLfFc,ECfastlift,0
EM_M_MakeFace,EMCrFc,ECmkface,1,
EM_M_MkMrgdSrf,EMPMrSr,ECmerge,3,
EM_M_ManupVarCur,EMMnVrCv,EClawcv,0
EM_M_MrgSrfs,EMMrSr,ECmerge,2,
EM_M_MvNdsOnSrf,EMMvNdOnSr,ECmvpls,1,
EM_M_MvPoleonSurface,EMMvPlOnSr,ECmvpole,1,
EM_M_MvMnyPlsOnSrf,EMMvMnPOnS,ECmvpls,0,
EM_M_PlaceBoss,EMPBs,ECplpocket,1,
EM_M_PlaceCntrBoreHole,EMPCb,ECcounterpt,1
EM_M_PlaceCntrSinkHole,EMPCs,ECcounterpt,0
EM_M_PlaceDraftedSolid,EMPDrSl,ECdraft,1
EM_M_PlaceDraftedSurf,EMPDrSr,ECdraft,0
EM_M_PlaceHole,EMPlHl,ECplhole,0
EM_M_PlacePocket,EMPPc,ECplpocket,0,
EM_M_PlacTuSol,EMPSlTb,ECtubesur,1,
EM_M_PlacTbSrf,EMPTb,ECtubesur,0,
EM_M_ReplcTrNd,EMRpTrNd,ECselundo,1
EM_M_RndEdg,EMRnEd,ECround,0,
EM_M_SolProSftoPl,EMPSlPrSrP,ECslprjsfpl,0,
^EM_M_SplitSurface,EMSpSr,ECsplit,1,
^EM_M_StitchTwoEdges,EMStEd,ECstitch,0,
EM_M_TrimSurSolInt,EMTrSrSlTI,ECspbool,0
EM_M_UndoState,EMUnStTr,ECdprundo,0
EM_M_DeleteSurfaceBoundary,EMDlSrBn,ECdelbnd,0
EM_M_0001,EMPSlBx2Pn,ECconstruct,1,
EM_M_0002,EMPBx4Pn,ECconstruct,2,
EM_M_0003,EMPSlBx4Pn,ECconstruct,3,
EM_M_0004,EMPCnAxR,ECconstruct,4,
EM_M_0005,EMPSlCnAxR,ECconstruct,5,
EM_M_0006,EMPCyAxR,ECconstruct,6,
EM_M_0007,EMPSlCyAxR,ECconstruct,7,
EM_M_0008,EMPTrAxCnR,ECconstruct,8,
EM_M_0009,EMPSlTrAxC,ECconstruct,9,
EM_M_0010,EMPSlRgECy,ECconstruct,10,
EM_M_0011,EMPSlRgECn,ECconstruct,11,
EM_M_0012,EMPElFcAxL,ECconstruct,12,
EM_M_0013,EMPElCnAxR,ECconstruct,13,
EM_M_0014,EMPSl4Fc4V,ECconstruct,14,
EM_M_0015,EMPSl5Fc5V,ECconstruct,15,
EM_M_0016,EMPSl5Fc6V,ECconstruct,16,
EM_M_0017,EMPSl6Fc7V,ECconstruct,17,
EM_M_0018,EMPSl6Fc8V,ECconstruct,18,
EM_M_0019,EMPRcPl3Pn,ECconstruct,19,
EM_M_0020,EMPPrPl3Pn,ECconstruct,20,
EM_M_0021,EMPSlRgAnW,ECconstruct,21,
EM_M_0026,EMPSpCnR,ECconstruct,26,
EM_M_0027,EMPSlSpCnR,ECconstruct,27,
EM_M_0028,EMPSlElFcA,ECconstruct,28,
EM_M_0029,EMPSlElCnA,ECconstruct,29,
EM_M_0030,EMPRgElCy,ECconstruct,30,
EM_M_0031,EMPRgElCn,ECconstruct,31,
EM_M_0037,EMExPrSr,ECconstruct,37,
EM_M_0038,EMPSrRv,ECconstruct,38,
EM_M_0039,EMPSlRv,ECconstruct,39,
EM_M_0043,EMPSr3Bn,ECconstruct,43,
EM_M_0044,EMPSr4Bn,ECconstruct,44,
EM_M_0045,EMPOfSr,ECcsoffset,45,
EM_M_0046,EMPBS2SUIC,ECconstruct,46,
EM_M_0047,EMPBS2SUNC,ECblnd2srf,47,
EM_M_0048,EMPFlSr,ECfilletsf1,48,
EM_M_0049,EMPPlTnSr,ECconstruct,49,
EM_M_0050,EMPPlTnCr,ECconstruct,50,
EM_M_0058,EMPSrPl,ECfitsur,58,
EM_M_0061,EMPSrDrFtC,ECfitsur,61,
EM_M_0060,EMPSrLsSqF,ECfitsur,60,
EM_M_0059,EMPSrDrFtL,ECfitsur,59,
EM_M_0062,EMPSrThNtC,ECfitsur,62,
EM_M_0074,EMInOrSr,ECmodify,74,
EM_M_0076,EMPSlCpSrP,ECmodify,76,
EM_M_0082,EMExSrPl,ECmodify,82,
EM_M_0083,EMPSrPr,ECconstruct,83,
EM_M_0084,EMPSlPr,ECplsolproj,84,
EM_M_0088,EMAl2Sr,ECalign,88,
EM_M_0090,EMCnBsSrBz,ECmodify,90,
EM_M_0091,EMInKnl,ECmodify,91,
EM_M_0092,EMPRlSr,ECruledsur,92,
EM_M_0094,EMPPlNrTCr,ECconstruct,94,
EM_M_0095,EMPSkSrNrS,COplcsknrm,0,
EM_M_0096,EMPSkSr,ECplcskinsf,0
EM_M_0097,EMPSkSl,ECplcskinsf,1
EM_M_0098,EMImSrBn,COimpbnd,0,
EM_M_0100,EMInPlSvSd,COintplane,2,
EM_M_0104,EMPCmE,ECmkcompsf,0,
EM_M_0105,EMPBlSr,ECblndnsrf,105
EM_M_0108,EMMdSrSh,ECmodify,108
^EM_M_0109,EMPSlOfSr,ECconstruct,109
EM_M_0114,EMRdSrDt,ECmodify,114
EM_M_0117,EMPFtSr,ECfitsur,117
^EM_M_HollDiffSfSl,EMHlDfE,ECboolean,11
EM_M_SetSevLv,EMSSvLv,ECgift,1,0,1
^EM_M_UnionSfSlDis,EMCrDsUnE,ECboolean,6
EM_M_ShDjRg,ECjbk1,ECrmDjRg,1
EM_M_RmDjRg,ECjbk2,ECrmDjRg,2
EM_M_SplSurfWSurf,EMSpSrSlSr,ECboolean,16
EM_M_PlAngPrtSf,EMSsunit7,ECconstruct,203
EM_M_AnalyzeInterference,MDAnIn,ECintf,0
EM_M_AnalyzeIntfXsec,MDAnInACs,ECintf,1
EM_M_AnalyzeIntfBxsec,MDAnInBCs,ECintf,2
EM_M_PlOfstCrvNortoSrf,EMPOfCNrTS,ECscoffset,0
EM_M_PlaceSlot,EMPlSlOnS,ECplslot,0
EM_M_PlaceFlange,EMPlFl,ECplflange,0
EM_M_PlaceGroove,EMPlGr,ECplflange,1
EM_M_MkTnEd,MDMrTnEd,ECmarktan,0
EM_M_TgTnEdDs,MDTgTnEdDs,ECtantog,0
EM_M_PlaceProtrusion,EMPlPr,ECridge,2
EM_M_PlaceCutout,EMPlCt,ECridge,3
EM_M_UniteSurfaces,EMUnSr,ECmgsf,0
^EM_M_DlSfFea,EMDlSrFt,ECdelgralp,0
EM_M_AddDraft,EMAdDr,ECaddraft,0
EM_M_EnableReadOnlyDtl,EMEnRdOnDt,COci,0,0,,"ReadOnlyDtl"
EM_M_RndMan,EMRnMn,ECmarchfil,0
GRC_M_PlcLnActAng,EMPL,ECwireframe,67
GRC_M_PlcAngBis2Ln,EMPAnBsBtE,ECwireframe,56
GRC_M_PlcAngBis3Pt,EMPAnBs3Pn,ECwireframe,78
GRC_M_PlcArcTnTECD,EMPATnTECD,ECwireframe,123
GRC_M_PlcArcCenter,EMPArCn,ECwireframe,28
GRC_M_PlcArcRad2Pt,EMPArR2Pn,ECwireframe,30
GRC_M_PlcArcCntRad,EMPArCnR,ECwireframe,29
GRC_M_PlcArcRaTanPT,EMPArRPnTn,ECwireframe,30
GRC_M_PCr2PnDm,EMPCr2PnDm,ECwireframe,26
GRC_M_PlcCir3Pts,EMPCr3Pn,ECwireframe,25
GRC_M_PlcCirTnTECD,EMPCTnTECD,ECwireframe,121
GRC_M_PCrCEPnD,EMPCrCEPnD,ECwireframe,1
GRC_M_PlcCcirCentRad,EMPCnCrCnR,ECwireframe,1
GRC_M_PlcCirDiaPts,EMPCrDmPn,ECwireframe,13
GRC_M_PCrDmKCP,EMPCrCnDm,ECwireframe,1
GRC_M_PlcCirTan3Els,EMPCrTnT3E,ECwireframe,25
GRC_M_PlcCirTanEleCen,EMPCTnT1EC,ECwireframe,1
GRC_M_PlcCirTanEleDia,EMPCTnT1ED,ECwireframe,13
GRC_M_PlcLnMinDis2Ele,EMPLMnDsBt,ECwireframe,75
GRC_M_PlcLnSegTan2Ele,EMPLSgTnT2,ECwireframe,14
GRC_M_PlcPerpBis,EMPPrBs,ECwireframe,57
GRC_M_PlcPoint,EMPPn,ECwireframe,20
GRC_M_PlcVertline,EMPVrL,ECwireframe,66
GRC_M_PlcNsidePoly,EMPNsPl,ECwireframe,76
GRC_M_PlcNSPolyMpSide,EMPNsPlMdS,ECwireframe,76
GRC_M_PlcHorLn,EMPHrL,ECwireframe,65
GRC_M_PlcLnSeg,EMPLSg,ECwireframe,14
GRC_M_PlcArcEndPts,IDPAr3Pn,ECwireframe,27
EM_M_CrPattern,EMCrPt,ECfepattern,0
EM_M_SaveElement,MDSvEl,ECsplitpart,0
EM_M_PlaceRib,EMPlRb,ECrib,1
EM_M_PlcsecSurf,EMPlSrCrSc,ECprfsksf,0
EM_M_PrAsCrSr,EMPrAsCrSr,ECpacos,0,
EM_M_PlAsOfCr,EMPlAsOfCr,ECplasofcv,0,
EM_M_TrElBn,EMTrElBn,ECtrim1,0
EM_M_Tr2ElIn,EMTr2ElIn,ECtrim2,0
EM_M_PlBl2Cr,EMPlBl2Cr,ECblendcv,0
EM_M_PBS2S,EMPS2S,ECblendsf,0
EM_M_AnalyzABS,EMAnAdSr,ECtpanaly,0
EM_M_AddMtl,EMAddMtl,ECridge,2 
EM_M_RmMtl,EMRmMtl,ECridge,3
EM_M_AsCvMd,EMAsCrMd,ECascvmd,0
EM_M_AsCrCrLs,EMAsCrCr,ECascrcr,0
EM_M_PlAsSkSr,HDCrbu2,ECplcskin,0
EM_M_PlAsSkSl,HDCrbu3,ECplcskin,1
EM_M_PlcrsecSurf,HDCrbu1,ECprfsksf,0
EM_M_DelSecSol,EMDScSl,CODelSecSol,0
EM_M_UpdVE,EMUpdVE,COUpdVE,0
