# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:37 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/smspace/bnd/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:07:37  cvs
#	Initial import to CVS
#	
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target: mkfile
	grmake -r -k -f mkfile 

mkfile : smspacebnd.m
	grmakemake smspacebnd.m mkfile

clean:
	@rm -f mkfile *.o *.c

