#/* $Id: makefile,v 1.1 2001/04/12 14:38:23 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdgeom2/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/04/12 14:38:23  ahundiak
# *      ah
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 04/12/01  ah      creation
# ***************************************************************************/

TGT = vdigeom2

include ${VDS_PATH}/etc/makefiles/lib_only.h
