[
n_catalogname(char[12])=cabinet
n_catalogdesc(char[100])=I/VDS Equipment Catalog
n_cofilename(char[14])=equip/VSEQUIP
n_itemdesc(char[40])=equipment
v_product(char[10])=EQUIPMENT
v_dynamictbl(char[18])=EQUIP_DYNAMIC
v_schdyntbl(char[18])=SCH_EQP_DYNAMIC
v_cittbl(char[18])=EQUIP_CIT
v_pplfile(char[12])=equip_ppl
p_level1(char[40])=EQUIPMENT
p_d1|cs(referential)=cs
p_c1|soft_env_clear(double)=Soft Envelope Clearance[3]
p_c2|front_clear(double)=Front Clearance[15]
p_v1|eqp_number(char[20])=Equipment Number[0]
p_v2|eqp_descr(char[40])=Equipment Description[Equip]
p_v3|apprv_stat(char[40])=Approval Status[NA]
p_v4|constr_stat(char[8])=Construction Status[NEW]
p_v5|no_mto_flag(char[1])=MTO Flag[N]
p_v6|chg_no(integer)=Change Number[0]
p_v7|weight_grp(integer)=Weight Group[0]
p_v8|comp_note(char[40])=Component Remarks[No Remarks]
p_u0|n_itemname(char[32])=Part Number
p_u0|n_itemrev(char[15])=Part Revision
p_u0|n_itemdesc(char[40])=Part Description
p_u0|n_creator(char[14])=CREATED BY
p_u0|n_creationdate(char[10])=Part Creation Date
p_u0|p_parttype(char[1])=Part Type
p_u0|wet_weight(double)=wet_weight
p_u0|eqp_type(char[12])=eqp_type
p_u0|heat_disp(double)=heat_disp
p_u0|mlx(double)=moment of inertia
p_u0|mly(double)=moment of inertia
p_u0|mlz(double)=moment of inertia
p_f0|n_cofilename(char[14])=Local File Name
]
