/* Do not alter this SPC information: $Revision: 1.2.3.1 $ */
/*
**	NAME:							ristoken.h
**	AUTHORS:						David Michal
**	CREATION DATE:					03/16/
**	ABSTRACT:
**		The header file for any routine that uses RIS tokens	
**	
**	REVISION HISTORY:
*/
 
#define RIS_TOK_ADD                    1
#define RIS_TOK_ALIAS_NAME             2
#define RIS_TOK_ALL                    3
#define RIS_TOK_ALTER                  4
#define RIS_TOK_ALTER_SCHEMA           5
#define RIS_TOK_ALTER_TABLE            6
#define RIS_TOK_AND                    7
#define RIS_TOK_ANSI                   8
#define RIS_TOK_ANY                    9
#define RIS_TOK_APPROX_NUM_LIT         10
#define RIS_TOK_ARCH                   11
#define RIS_TOK_ARRAY_SPEC_LIST        12
#define RIS_TOK_AS                     13
#define RIS_TOK_ASC                    14
#define RIS_TOK_ASGN                   15
#define RIS_TOK_ASYNC                  16
#define RIS_TOK_ASYNC_ID               17
#define RIS_TOK_ASYNC_ID_LIST          18
#define RIS_TOK_ATTR                   19
#define RIS_TOK_AUTHORIZATION          20
#define RIS_TOK_AUTH_ID                21
#define RIS_TOK_AUTO                   22
#define RIS_TOK_AUTOCOMMIT             23
#define RIS_TOK_AUTORENAME             24
#define RIS_TOK_AVG                    25
#define RIS_TOK_BEGIN                  26
#define RIS_TOK_BEGIN_DECLARE          27
#define RIS_TOK_BETWEEN                28
#define RIS_TOK_BETWEEN_AND            29
#define RIS_TOK_BLANK                  30
#define RIS_TOK_BLANKSTRIP             31
#define RIS_TOK_BUFFER                 32
#define RIS_TOK_BUFFER_SIZE            33
#define RIS_TOK_BUFFER_TIMEOUT         34
#define RIS_TOK_BY                     35
#define RIS_TOK_CHAR                   36
#define RIS_TOK_CHARACTER              37
#define RIS_TOK_CHAR_STR_LIT           38
#define RIS_TOK_CLEAR                  39
#define RIS_TOK_CLOSE                  40
#define RIS_TOK_CLOSE_SCHEMA           41
#define RIS_TOK_COLON                  42
#define RIS_TOK_COLUMN_DEF             43
#define RIS_TOK_COLUMN_DEF_LIST        44
#define RIS_TOK_COLUMN_LIST            45
#define RIS_TOK_COL_NAME               46
#define RIS_TOK_COMMA                  47
#define RIS_TOK_COMMIT                 48
#define RIS_TOK_COMPLETION             49
#define RIS_TOK_CONNECT                50
#define RIS_TOK_CONST                  51
#define RIS_TOK_CONTINUE               52
#define RIS_TOK_COUNT                  53
#define RIS_TOK_CREATE                 54
#define RIS_TOK_CREATE_INDEX           55
#define RIS_TOK_CREATE_SCHEMA          56
#define RIS_TOK_CREATE_TABLE           57
#define RIS_TOK_CREATE_VIEW            58
#define RIS_TOK_CURRENT                59
#define RIS_TOK_CURRENT_TIMESTAMP      60
#define RIS_TOK_CURSOR                 61
#define RIS_TOK_CURSOR_NAME            62
#define RIS_TOK_C_CHAR_STR_LIT         63
#define RIS_TOK_DATABASE               64
#define RIS_TOK_DATETIME               65
#define RIS_TOK_DAY                    66
#define RIS_TOK_DB2                    67
#define RIS_TOK_DBNAME                 68
#define RIS_TOK_DB_TYPE_LIST           69
#define RIS_TOK_DEBUG                  70
#define RIS_TOK_DEC                    71
#define RIS_TOK_DECIMAL                72
#define RIS_TOK_DECLARE                73
#define RIS_TOK_DECLARE_SCHEMA         74
#define RIS_TOK_DECLARE_SUPERSCHEMA    75
#define RIS_TOK_DECLARE_TABLE          76
#define RIS_TOK_DECLARE_VIEW           77
#define RIS_TOK_DEFAULT                78
#define RIS_TOK_DEFAULT_SCHEMA         79
#define RIS_TOK_DEFINE                 80
#define RIS_TOK_DEFINENAME             81
#define RIS_TOK_DELETE                 82
#define RIS_TOK_DESC                   83
#define RIS_TOK_DESCRIBE               84
#define RIS_TOK_DESCRIBE_INPUT         85
#define RIS_TOK_DESCRIBE_OUTPUT        86
#define RIS_TOK_DESCRIPTOR             87
#define RIS_TOK_DESC_NAME              88
#define RIS_TOK_DIR                    89
#define RIS_TOK_DISTINCT               90
#define RIS_TOK_DIV                    91
#define RIS_TOK_DNP                    92
#define RIS_TOK_DOT                    93
#define RIS_TOK_DOUBLE                 94
#define RIS_TOK_DROP                   95
#define RIS_TOK_DROP_INDEX             96
#define RIS_TOK_DROP_SCHEMA            97
#define RIS_TOK_DROP_TABLE             98
#define RIS_TOK_DROP_VIEW              99
#define RIS_TOK_ELSE                   100
#define RIS_TOK_ENABLE                 101
#define RIS_TOK_END                    102
#define RIS_TOK_ENDIF                  103
#define RIS_TOK_END_DECLARE            104
#define RIS_TOK_ENFORCE                105
#define RIS_TOK_ENV                    106
#define RIS_TOK_EQ                     107
#define RIS_TOK_ERROR                  108
#define RIS_TOK_EXACT_NUM_LIT          109
#define RIS_TOK_EXCLUDE                110
#define RIS_TOK_EXCLUSIVE              111
#define RIS_TOK_EXEC                   112
#define RIS_TOK_EXECUTE                113
#define RIS_TOK_EXECUTE_IMMEDIATE      114
#define RIS_TOK_EXISTS                 115
#define RIS_TOK_EXTERN                 116
#define RIS_TOK_FEATURE                117
#define RIS_TOK_FETCH                  118
#define RIS_TOK_FILENAME               119
#define RIS_TOK_FLOAT                  120
#define RIS_TOK_FOR                    121
#define RIS_TOK_FORCE                  122
#define RIS_TOK_FOUND                  123
#define RIS_TOK_FROM                   124
#define RIS_TOK_FULL                   125
#define RIS_TOK_GATEWAY                126
#define RIS_TOK_GE                     127
#define RIS_TOK_GO                     128
#define RIS_TOK_GOTO                   129
#define RIS_TOK_GRANT                  130
#define RIS_TOK_GRANTEE_LIST           131
#define RIS_TOK_GRANT_CONNECT          132
#define RIS_TOK_GRANT_ON_TABLE         133
#define RIS_TOK_GRANT_RESOURCE         134
#define RIS_TOK_GRANT_SCHEMA           135
#define RIS_TOK_GROUP                  136
#define RIS_TOK_GROUP_BY               137
#define RIS_TOK_GT                     138
#define RIS_TOK_HAVING                 139
#define RIS_TOK_HOST_IDENT             140
#define RIS_TOK_HOST_LU                141
#define RIS_TOK_HOST_PROGRAM           142
#define RIS_TOK_HOST_TYPE_SPEC_LIST    143
#define RIS_TOK_HOST_VAR               144
#define RIS_TOK_HOST_VAR_DEF           145
#define RIS_TOK_HOST_VAR_LIST          146
#define RIS_TOK_HOUR                   147
#define RIS_TOK_IDENT                  148
#define RIS_TOK_IFDEF                  149
#define RIS_TOK_IFDEFNAME              150
#define RIS_TOK_IFNDEF                 151
#define RIS_TOK_IFNDEFNAME             152
#define RIS_TOK_IMMEDIATE              153
#define RIS_TOK_IN                     154
#define RIS_TOK_INCLUDE                155
#define RIS_TOK_INDEX                  156
#define RIS_TOK_INDEX_NAME             157
#define RIS_TOK_INDICATOR              158
#define RIS_TOK_INFORMIX               159
#define RIS_TOK_INGRES                 160
#define RIS_TOK_INITIAL                161
#define RIS_TOK_INITIAL_TIMEOUT        162
#define RIS_TOK_INPUT                  163
#define RIS_TOK_INSERT                 164
#define RIS_TOK_INT                    165
#define RIS_TOK_INTEGER                166
#define RIS_TOK_INTERVAL               167
#define RIS_TOK_INTO                   168
#define RIS_TOK_IS                     169
#define RIS_TOK_LBRACK                 170
#define RIS_TOK_LE                     171
#define RIS_TOK_LIKE                   172
#define RIS_TOK_LIST                   173
#define RIS_TOK_LOCK                   174
#define RIS_TOK_LOCK_TABLES            175
#define RIS_TOK_LONG                   176
#define RIS_TOK_LPAREN                 177
#define RIS_TOK_LT                     178
#define RIS_TOK_MAJOR                  179
#define RIS_TOK_MAX                    180
#define RIS_TOK_MIN                    181
#define RIS_TOK_MINUTE                 182
#define RIS_TOK_MODE                   183
#define RIS_TOK_MODIFY                 184
#define RIS_TOK_MONTH                  185
#define RIS_TOK_MSSQL                  186
#define RIS_TOK_MUL                    187
#define RIS_TOK_NE                     188
#define RIS_TOK_NETWORK                189
#define RIS_TOK_NET_PROTOCOL           190
#define RIS_TOK_NODE                   191
#define RIS_TOK_NON_ANSI               192
#define RIS_TOK_NOT                    193
#define RIS_TOK_NOT_FOUND              194
#define RIS_TOK_NOT_NULL               195
#define RIS_TOK_NO_VERIFY              196
#define RIS_TOK_NT                     197
#define RIS_TOK_NULL                   198
#define RIS_TOK_NULL_NODE              199
#define RIS_TOK_OF                     200
#define RIS_TOK_OFF                    201
#define RIS_TOK_ON                     202
#define RIS_TOK_ONLY                   203
#define RIS_TOK_OPEN                   204
#define RIS_TOK_OPEN_SCHEMA            205
#define RIS_TOK_OPTION                 206
#define RIS_TOK_OR                     207
#define RIS_TOK_ORACLE                 208
#define RIS_TOK_ORDER                  209
#define RIS_TOK_ORDER_BY               210
#define RIS_TOK_OS                     211
#define RIS_TOK_OS400                  212
#define RIS_TOK_OSTYPE                 213
#define RIS_TOK_OSUSER                 214
#define RIS_TOK_OUTPUT                 215
#define RIS_TOK_PARAMETER              216
#define RIS_TOK_PARAM_LIST             217
#define RIS_TOK_PARTIAL                218
#define RIS_TOK_PASSWORD               219
#define RIS_TOK_PLUS                   220
#define RIS_TOK_PORT                   221
#define RIS_TOK_PRECISION              222
#define RIS_TOK_PREPARE                223
#define RIS_TOK_PRIMARY                224
#define RIS_TOK_PRIVILEGES             225
#define RIS_TOK_PRIVILEGE_LIST         226
#define RIS_TOK_PUBLIC                 227
#define RIS_TOK_QUESTION               228
#define RIS_TOK_RBRACK                 229
#define RIS_TOK_RDB                    230
#define RIS_TOK_REAL                   231
#define RIS_TOK_REDECLARE              232
#define RIS_TOK_REDECLARE_SUPERSCHEMA  233
#define RIS_TOK_REGISTER               234
#define RIS_TOK_REMOTE                 235
#define RIS_TOK_REPLACE                236
#define RIS_TOK_REPORT                 237
#define RIS_TOK_REPORT_ERROR           238
#define RIS_TOK_REPORT_SS_ERROR        239
#define RIS_TOK_RESOURCE               240
#define RIS_TOK_RESPONSE               241
#define RIS_TOK_RESPONSE_INTERVAL      242
#define RIS_TOK_REVOKE                 243
#define RIS_TOK_REVOKE_CONNECT         244
#define RIS_TOK_REVOKE_ON_TABLE        245
#define RIS_TOK_REVOKE_RESOURCE        246
#define RIS_TOK_REVOKE_SCHEMA          247
#define RIS_TOK_RIS_BLOB               248
#define RIS_TOK_RIS_DICT_DBNAME        249
#define RIS_TOK_RIS_LU                 250
#define RIS_TOK_RIS_TEXT               251
#define RIS_TOK_ROLLBACK               252
#define RIS_TOK_RPAREN                 253
#define RIS_TOK_SCHEMA                 254
#define RIS_TOK_SCHEMA_LIST            255
#define RIS_TOK_SCHEMA_SPEC_LIST       256
#define RIS_TOK_SECOND                 257
#define RIS_TOK_SECONDARY              258
#define RIS_TOK_SECTION                259
#define RIS_TOK_SECURE                 260
#define RIS_TOK_SELECT                 261
#define RIS_TOK_SELECT_EXPR            262
#define RIS_TOK_SELECT_SELECT          263
#define RIS_TOK_SEMICOLON              264
#define RIS_TOK_SERVER                 265
#define RIS_TOK_SET                    266
#define RIS_TOK_SET_MODE               267
#define RIS_TOK_SET_TRANSACTION        268
#define RIS_TOK_SHARE                  269
#define RIS_TOK_SHORT                  270
#define RIS_TOK_SIGNED                 271
#define RIS_TOK_SIZE                   272
#define RIS_TOK_SMALLINT               273
#define RIS_TOK_SOME                   274
#define RIS_TOK_SQL                    275
#define RIS_TOK_SQLCODE                276
#define RIS_TOK_SQLDA                  277
#define RIS_TOK_SQLDS                  278
#define RIS_TOK_SQLERROR               279
#define RIS_TOK_STAR_LIST              280
#define RIS_TOK_STATIC                 281
#define RIS_TOK_STMT_ID                282
#define RIS_TOK_STRIP                  283
#define RIS_TOK_STRUCT                 284
#define RIS_TOK_SUB                    285
#define RIS_TOK_SUM                    286
#define RIS_TOK_SUPERSCHEMA            287
#define RIS_TOK_SWAP                   288
#define RIS_TOK_SYBASE                 289
#define RIS_TOK_TABLE                  290
#define RIS_TOK_TABLES                 291
#define RIS_TOK_TABLE_LIST             292
#define RIS_TOK_TABLE_NAME             293
#define RIS_TOK_TCP                    294
#define RIS_TOK_TEST                   295
#define RIS_TOK_TEST_COND              296
#define RIS_TOK_TIMEOUT                297
#define RIS_TOK_TIMESTAMP              298
#define RIS_TOK_TIMESTAMP_LIT          299
#define RIS_TOK_TO                     300
#define RIS_TOK_TOLERANCE              301
#define RIS_TOK_TRANSACTION            302
#define RIS_TOK_UCHAR                  303
#define RIS_TOK_UINT                   304
#define RIS_TOK_ULONG                  305
#define RIS_TOK_UNARYMINUS             306
#define RIS_TOK_UNDECLARE              307
#define RIS_TOK_UNDECLARE_SCHEMA       308
#define RIS_TOK_UNDECLARE_SUPERSCHEMA  309
#define RIS_TOK_UNDECLARE_TABLE        310
#define RIS_TOK_UNDECLARE_VIEW         311
#define RIS_TOK_UNDEF                  312
#define RIS_TOK_UNDEFNAME              313
#define RIS_TOK_UNION                  314
#define RIS_TOK_UNION_ALL_SELECT       315
#define RIS_TOK_UNION_SELECT           316
#define RIS_TOK_UNIQUE                 317
#define RIS_TOK_UNIX                   318
#define RIS_TOK_UNSIGNED               319
#define RIS_TOK_UNSUPPORTED            320
#define RIS_TOK_UPDATE                 321
#define RIS_TOK_USER                   322
#define RIS_TOK_USHORT                 323
#define RIS_TOK_USING                  324
#define RIS_TOK_USING_DICT_OWNER       325
#define RIS_TOK_USR_NAME               326
#define RIS_TOK_VALUES                 327
#define RIS_TOK_VALUE_EXPR_LIST        328
#define RIS_TOK_VAR                    329
#define RIS_TOK_VAR_NAME               330
#define RIS_TOK_VERIFICATION           331
#define RIS_TOK_VERIFY                 332
#define RIS_TOK_VERSION                333
#define RIS_TOK_VIEW                   334
#define RIS_TOK_VIRTUAL                335
#define RIS_TOK_VMS                    336
#define RIS_TOK_VOLATILE               337
#define RIS_TOK_WAIT                   338
#define RIS_TOK_WHENEVER               339
#define RIS_TOK_WHERE                  340
#define RIS_TOK_WITH                   341
#define RIS_TOK_WORK                   342
#define RIS_TOK_XNS                    343
#define RIS_TOK_YEAR                   344
#define RIS_TOK_CHAR_STR_LIT_STB       345

