# $Id: makefile,v 1.1 2001/08/13 14:38:55 jdsauby Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/emsfixes/nfm/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	06/10/01	jds		creation
# -------------------------------------------------------------------

TGT = vdnfm

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o

