/* $Id: VLunwMgr.S,v 1.1.1.1 2001/01/04 21:11:43 cvs Exp $  */

/*************************************************************************
 * I/LOFT
 *
 * File:        src/unwext/VLunwMgr.S
 *
 * Description: Specification file for Unwrap Manager Object.
 *
 * Dependencies:
 *
 * Revision History:
 *      $Log: VLunwMgr.S,v $
 *      Revision 1.1.1.1  2001/01/04 21:11:43  cvs
 *      Initial import to CVS
 *
# Revision 1.1  1998/04/30  10:32:50  pinnacle
# LOFT 2.5.1
#
# Revision 1.1  1997/10/28  15:30:04  pinnacle
# Created: src/unwext/VLunwMgr.S by rchennup for loft
#
 *
 * History:
 *      MM/DD/YY   AUTHOR       DESCRIPTION
 *      10/28/97   Rama Rao     File Creation
 *************************************************************************/


class specification VLunwMgr(1:0) of GRcmpowner;

instance VLunwMgr
{
	/*
	 * None.
	 */
};

end specification VLunwMgr;
