# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:57 cvs Exp $

#***********************************************************************
# I/VDS
#
# File:         vdmeasure/func/makefile
#
# Description:
#
# Dependencies:
#
# Revision History
#       $Log: makefile,v $
#       Revision 1.1.1.1  2001/01/04 21:08:57  cvs
#       Initial import to CVS
#
# Revision 1.1  1997/05/08  15:38:12  pinnacle
# rep bin w/txt
#
# Revision 1.2  1997/03/12  17:17:24  pinnacle
# Replaced: vdmeasure/func/makefile for:  by v241_int for vds.241
#
# Revision 1.1  1996/11/08  21:52:30  pinnacle
# Created: vdmeasure/func/makefile by v241_int for vds.241
#
#
# History:
#       MM/DD/YY        AUTHOR          DESCRIPTION
#       11/08/96        mf              creation date
#
#***********************************************************************



target:	mkfile
	grmake -r -k -f mkfile 

mkfile: vdmeasfc.m
	grmakemake vdmeasfc.m mkfile
