#define ECsM_Insert_Pole	   "Insert pole without changing shape"
#define ECsP_Identify_Curve 	   "Identify curve"
#define ECsP_Acc_Rej_Curve  	   "Accept/reject"
#define ECsP_Curve_Not_Found 	   "Curve not found"
#define ECsP_Input_Pt_On_Polygon   "Input point on polygon"
#define ECsS_Invalid_Input 	   "Invalid input"
#define ECsS_PntNotOnPolygon	   "point not on polygon"

#define ECsM_Place_Plane_Tan_Sf	   "Place plane tangent to surface"
#define ECsP_Identify_Surface 	   "Identify surface"
#define ECsP_Acc_Rej_Surface  	   "Accept/reject"
#define ECsP_Surface_Not_Found 	   "Surface not found"
#define ECsP_Input_Pt_On_Surface   "Input point on surface"
#define ECsP_Keyin_Length	   "Key in length"
#define ECsP_Keyin_Width	   "Key in width"
#define ECsP_Processing		   "Processing..."
#define ECsS_Invalid_Length	   "length must be greater than 0.0"
#define ECsS_Invalid_Width	   "width must be greater than 0.0"
#define ECsS_Plane_Not_Constructed "plane not constructed"
#define ECsP_Input_Pt_On_Curve     "Input point on curve"

#define ECsM_Place_Plane_Tan_Cv	   "Place plane tangent to curve"

#define ECsM_Place_Skining_Surface "Place skinning surface"
#define ECsP_Id_Crs1		   "Identify cross-section 1"
#define ECsP_Id_Trc1_At_St	   "Identify trace 1 at starting pt"
#define ECsP_Id_Crs2_Or_Move 	   "Identify cross-section 2/move-on"
#define ECsP_Id_Trc2_At_St_Or_Move "Identify trace 2 at starting pt/move-on"
#define ECsP_Is_Crs_Sec_On_Site	   "Is cross-section on site? y/n [n]"
#define ECsP_Is_Scaling_Desired    "Is scaling desired? y/n [n]"
#define ECsP_Input_Ref_Pnt1	   "Input reference point 1"
#define ECsP_Input_Ref_Pnt2	   "Input reference point 2"
#define ECsP_Input_Xvec_Pnt	   "Input x-vector point"
#define ECsP_Input_Yvec_Pnt	   "Input y-vector point"
#define ECsS_Surf_Not_Constructed  "surface not constructed"
#define ECsS_Crss_Not_In_Same_Wn   "cross sections not in same window"
