#/* $Id: makefile,v 1.1 2001/07/23 16:32:40 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdval/x3/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/07/23 16:32:40  ahundiak
# *      ah
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 07/20/01  ah      creation
# ***************************************************************************/

TGT = vdivalx3
include ${VDS_PATH}/etc/makefiles/lib_only.h
