# $Id: makefile,v 1.2 2001/04/03 16:27:16 anand Exp $  */

#--------------------------------------------------------------------------
#
#  I/ROUTE
#
#  File:        isdp/route/vrconsco/makefile
#
#  Description:
#
#  Dependencies:
#
#  Revision History:
#       $Log: makefile,v $
#       Revision 1.2  2001/04/03 16:27:16  anand
#       Changed $ROUTE to $ROUTE_PATH for service pack.
#
#
#  History:
#  MM/DD/YY  AUTHOR  DESCRIPTION
#  --------  ------  -----------
#  01/17/01  Anand   File Creation
#
#--------------------------------------------------------------------------

TGT = vrconsco

include ${ROUTE_PATH}/etc/makefiles/slic_n_lib.h
