<TP>forms
:Using Forms:
Many commands use forms that gather information used by
the command.  A form contains items called gadgets.  A
gadget is a portion of a form that gathers and displays
information from and to the user of the command.

<S>Form Descriptions<T>

The following sections briefly describe the forms used in
I/PDM.  The forms are illustrated and described in greater
detail later in the manual.  Many of the forms contain the
Control Bar buttons that have already been described.  Those
buttons will not be described in the form descriptions.

<XR>login  Login to PDM<T> --- This form logs into I/PDM server and
environment.

<XR>list  List<T> --- This form displays information you request when you
select a list button.  There are two types of List<T> forms: Single
Column Field<T> and Multi-column Field<T>.

<XR>local_files  PDM/PDU<T> --- This form is the main menu for I/PDM-PDU
commands.

<XR>seed_form  New File Creation<T> --- This form appears when you select the
Retrieve for Design<T> button on the PDM/PDU<T> form to retrieve a
part that has never been checked in.  The form lets you add a
reference seed file to a part.

<XR>Create_cat1  Catalog Operations<T> --- This form lets you perform different
catalog operations on different catalogs displayed on the list
on the form.

<XR>create_cat2  Catalog Attribute<T> --- This form appears when you select the
Require Attributes Display<T> or User Define Attributes<T> options
from the Catalog Name<T> form.  The forms lets you change the
synonyms of the required attributes, add user defined
attributes, and assign protections, defaults, ranges for
validation, and list of values.

<XR>part_form  Part Operation<T> --- This form lets you perform specific part
operations.  This form appears in four modes: New, Similar,
Change,<T> and Review<T>.

<XR>part_listing  Part Listing<T> --- This forms lists parts found during a search
when performing assembly design.

<XR>parmoper  Parametric Parts Operations<T> --- This form lets you perform
operations on parametric parts.

<XR>MOAddPart  Parametric Attributes<T> --- This form lets you assign values to
attributes for  parametric parts.

<XR>def_lib  Define Support Library<T> --- This form lets you define support
libraries to use for parametric part operations.

<XR>MOPartSelec2  Part Selection<T> --- This form lets you perform part operations
such as Place Part<T> and Replace Part<T>, as well as search for
parts in the database.

<XR>search_options  Name<T> --- This form lets you load previously saved search
criteria or save new search criteria.

<XR>sort  Sort Parts<T> --- This form lets you sort the results from a
search before the catalog or part listing is displayed.

<XR>sort_options  Load Sort Conditions<T> --- This form lets you load previously
saved sort conditions.

<XR>ssort  Save Sort Conditions<T> --- This form lets you save new sort
conditions.

<XR>where_used  Part Relationship Criteria<T> --- This form lets you display
where a selected part is used in an assembly or what parts
are contained in the selected part.

<XR>cancel_list  Cancel Part Check Out<T> --- This form lets you cancel the
checkout of a part.

<XR>design_form  Design Operations<T> --- This form accesses to all commands
relative to building an assembly.

<XR>placeOpt  Placement Option<T> --- This form appears when you select the
Placement Options<T> button on the Part Selection<T> form and lets
you determine how a part is placed.

<XR>topdown  Identify Part<T> --- This form is displayed during a topdown
assembly design and lets you identify an existing part to
associate with a collection of graphic elements.

<XR>Dynamic  Dynamic Attribute Information<T> --- This form lets you place
dynamic attributes when executing the Place Part<T> and
Replace Part<T> commands.

<XR>define_assy  Define/Modify Assembly Structure<T> --- This form lets you
define and modify the structure of an assembly.

<XR>report_form  Reports<T> --- This form lets you define and generate reports.

<XR>reportgen  Define Report Format<T> --- This form lets you define the
format for reports.

<XR>bom_contents  BOM Contents/Mapping<T> --- This form lets you define and
modify the BOM contents and BOM mapping.

<ETP>
<TP>login
:Login to PDM Form:
The login form appears when I/PDU is invoked and is used to
log into the I/PDM environment.

<S>Form Fields ---<T>

<S>Username<T>

This field displays the I/PDM username for the user logging
into an I/PDM database.

<S>Password<T>

This field displays the password for the I/PDM username.

<S>Environment<T>

This field displays the I/PDM operating environment being
used. You can key in an environment name or select from a list
that is generated by tapping the List<T> button next to this field.

At the end of the session, the information entered on the form
is written to a file called .refresh.dat<T> which is located in the
directory from which I/PDU was invoked.  To connect to the
same environment the next time you log in, key in only the
password.

<ETP>
<TP>list
:List Forms:
Any list that you generate in I/PDM will be displayed in either
a Single Column Field List<T> form or a Multi-column Field List<T>
form.  After the list has been reviewed, these forms can be
dismissed by selecting the Quit<T> button on the forms.

<H>Single Column Field List Form<T><T>

The Single Column Field List<T> appears when you select the List<T>
button next to a field.  It will contain only the name of what
you are listing.  For example, if you select the List<T> button next
to a Catalog<T> field, the list will contain only catalog names.

<S>Form Fields ---<T>

<S>Scroll Bar<T>

This bar allows you to scroll forward and backward through a
list that does not fit within the fixed size of the list form.

<H>Multi-Column Field List Form<T><T>

The Multi-column Field List<T> form lets you review information
on parts in the I/PDM database and perform operations on
them.  The following illustrates and describes the
Multi-column Field List<T> form.

<S>Form Fields ---<T>

<S>Scroll Bar<T>

This bar allows you to scroll forward and backward through a
list that does not fit within the fixed size of the list form.  The
scroll bars at the bottom of the form let you scroll forward and
backward through fields that do not fit within the form.

<ETP>
<TP>local_files
:PDM/PDU Form:
The PDM/PDU<T> form appears after you log in and is the main
menu for I/PDM and I/PDU commands. This is the form from
which I/PDM-PDU operations are initiated. The form has three
sections:

1.   Top section --- This section contains information about the
     current project, catalog, or part.  It also displays the name
     of the user and the server and environment in which the
     user is working.

2.   Middle section --- This section displays any lists.

3.   Bottom section --- This section contains command buttons
     used to operate on the selected parts in the middle section
     or part in the top section.

1.   Logout<T> logs you out of I/PDM.

2.   The Help<T> button activates on-line Help.

3.   The Convert to Window<T> button converts the form to a
     window. Converting the form to a window lets you perform
     actions in other windows while the form is displayed.

4.   The Restore<T> button restores the form to its original state.

5.   This field displays the name for the project you are
     working on.  You can use the List<T> button beside this field to
     view a complete list of projects.  If the list contains only
     one project, the value will be automatically loaded into the
     field.

6.   This field displays the name for the catalog you are
     working on.  You can use the List<T> button beside this field to
     display a complete list of catalog classifications.  You can
     then select the appropriate classification from the list
     which will return either a lower classification or a list of
     catalogs inside the classification.  If there are no
     classifications, a complete list of catalogs will be
     displayed.  If the list contains only one catalog, the value
     will be automatically loaded into the field.  If the project
     name is defined, the list will contain only catalogs mapped
     to the project.

7.   This field displays the part number for the part you want to
     operate on.  You can use the List<T> button beside this field to
     view a complete list of parts.  If the list contains only one
     part, the value will be automatically loaded into the field.
     You must have a valid catalog name in the Catalog<T> field to
     get a list of parts.

8.   This field displays the revision for the current part.  You
     can use the List<T> button beside this field to view a complete
     list of revisions for the part.  If the list contains only one
     revision for the part, the value will be automatically loaded
     into the field.  You must have a valid catalog name and part
     name to get a list of part revisions.

9.   This field displays the local filename for the current part.
     You can use the List<T> button beside this field to view a
     complete list of files for the part.  If the list contains only
     one filename, the value will be automatically loaded into
     the field.  An I/PDM part can have multiple files.

10.  This field displays the description for the current part.

11.  This field displays the I/PDM username used to log in.  This
     is a read-only field.

12.  This field displays the name of the operating environment
     that you selected to work in when you logged into I/PDM.
     This is a read-only field.

13.  This area displays lists of parts and files.  The area is
     multi-selectable.  Whenever a part is selected, it is written
     to the Part Selection<T> area and overwrites the data in this
     area.

14.  This area contains the commands that let you list parts
     and files.

     -  List Parts In Catalog<T> button --- This button displays a list of
        parts in the catalog displayed in the Part Selection<T> area.
        <XR>PDShLsPrIn  Show List of Parts In Catalog<T>

     -  List of Local Files<T> button --- This button displays a list of
        files based on the list criteria defined in the Local File List
        Type<T> field.

        <XR>PDShLsLcFl Show List of Local Files<T>

     -  List Part Structure<T> button --- This button shows the
        complete assembly structure for the current part that is
        in the Part Selection<T> area.  The list is displayed in the List
        of Part/Files<T> area of the PDM/PDU<T> form.  You can select
        any of the parts from this structure list for file operations.

     -  List Where Used<T> button --- This button displays a list of
        where the identified part is directly used.  The list may
        include assemblies, drawings, or NC files.

     -  Search for Parts<T> button --- This button invokes the Part
        Selection<T> form.

15.  This field sets the list criteria for a list of user files.  The
     default criteria is All Local Files<T> which shows all local files
     that have been checked out, copied, or copied for
     reference.  You can toggle the list criteria to Checked In<T> to
     show all files that have been checked in by the user in the
     past or Checked Out<T> to show all files that you currently
     have checked out.

16.  This area contains the file operation commands.

     -  Retrieve for Design<T> button --- This retrieves the part in the
        Part Selection<T> area and opens the file for design.

        If only one part is selected:

        a.   The file for the selected part is automatically checked
             out if not already checked out.

        b.   The file is activated in EMS for design.

        If more than one part is selected:

        a.   All files are checked out, if not already checked out.

        b.   A save/restore form displays a list of the checked out
             files for you to select which one should be opened for
             design.

        c.   Checking off this form deletes the list and redisplays
             the PDM/PDU<T> form.

        If the parts being retrieved has never been checked in,
        the New File Creation<T> form appears.  This form is
        discussed in the section New File Creation<T> Form.

        <XR>PDChOtAcPr  Retrieve for Design<T>

     -  Check In<T> button --- This button checks in the part in the
        Part Selection<T> area or the parts that are selected in the
        List of Parts/Files<T> area.  Check in from the List of
        Parts/Files<T> area allows you to check in multiple files at
        one time.

        <XR>PDChInPr  Check In Part<T>

     -  Retrieve for Review<T> button --- This button creates a copy
        of the files of the selected parts in the local directory.
        Parts may be selected in the Part Selection<T> area or the
        List of Parts/Files<T> area.  You can copy multiple files at one
        time by selecting parts in the List of Parts/Files<T> area.

        If only one part is selected:

        a.   The file for the part is automatically copied to local if
             the current version is not already local.

        b.   The file is then activated in EMS for design review.

             <S>Note:<T>

             This file is read-only and cannot be modified. <F>
             „<T>

        If more than one part is selected:

        a.   All files are copied to local as required.

        b.   A save/restore form then shows a list of the parts for
             you to select which part to enter for review.

        c.   Checking off the form deletes the list and redisplays
             the PDM/PDU<T> form.

        <XR>PDCpFlTLc  Retrieve for Review<T>

     -  Delete Local File<T> button --- This button lets you delete the
        files that have been copied to local and updates the local
        file manager information.  The command also deletes the
        selected checked-out files and then changes the
        database entry to cancel the checkout.  A pop-up form
        verifies that the files should be deleted.

        <XR>PDDlLcFl  Delete Local File<T>

17.  This area lets you invoke non-file related commands.

     -  Catalogs<T> button --- This button activates the Catalog
        Operations<T> form that lets you perform catalog-related
        commands.

     -  Reports<T> button --- This button activates the Reports<T> form
        that lets you perform report related operations such as
        definition  and modification of reporting formats,
        generation of reports such as BOM, parts lists and list of
        parts in catalog.

     -  Parts<T> button --- This button activates the Part Operations<T>
        form that lets you perform part-related commands.

     -  Assembly Structure<T> button --- This button activates the
        Define/Modify Assembly Structure<T> form that lets you
        define a new assembly structure or modify an existing
        assembly structure.

     -  Parametric Part<T> button --- This button activates the
        Parametric Part Operations<T> form that lets you perform
        part operations on parametric parts.

<ETP>
<TP>seed_form
:New File Creation Form:
The New File Creation<T> form appears when you select the
Retrieve for Design<T> button on the PDM/PDU<T> form to retrieve a
part that has never been checked in.  This form lets you add a
reference seed file to a part.  The form can be executed by
selecting the Exit and Save<T> button on the form after all
information has been added to the form.

<S>Form Fields ---<T>

<S>Seed File Toggle<T>

This toggle indicates the source of the seed file.  If the toggle
is set to Default EMS Seed File<T>, the system uses the default
seed file.  If the toggle is set to User Define Seed File<T>, the Seed
File<T> palette appears along with a Search<T> button that lets you
select a file to be used as the seed file.

<S>Seed File Palette<T>

This palette appears when the Seed File<T> toggle is set to User
Define Seed File<T> and lets you add the existing seed file.

<S>Catalog Field<T>

This field displays the catalog containing the existing part
that is associated with the seed file you wish to add.  You can
select the List<T> button next to this field to display a list of all
catalogs found in the database.

<S>Part Number Field<T>

This field displays the existing part that is associated with the
seed file you wish to add.  You can select the List<T> button next
to this field to display a list of all parts found in the catalog
displayed in the Catalog<T> field.

<S>Revision Field<T>

This field displays the revision for the part displayed in the
Part Number<T> field.  You can select the List<T> button next to this
field to display a list of all revisions for the part displayed in
the Part Number<T> field.

<S>Filename Field<T>

This field displays the file associated with the selected part
and revision.  You can select the List<T> button next to this field
to display a list of all files associated with the selected part
and revision.

<S>Description Field<T>

This field displays the description for the selected part and
revision.

<S>Search Button<T>

This button displays the Part Selection<T> form and lets you
search for a specific part.

<S>Note:<T>

If you select the Exit<T> button at the top of this form, the
Retrieve for Design<T> is cancelled. <F> „<T>

<ETP>
<TP>Create_cat1
:Catalog Operations Form:
The Catalog Operations<T> form appears when you select the
Catalog<T> button on the PDM/PDU<T> form.  This form has two
modes of operation:

1.   New<T> --- This mode lets you add a new catalog.

2.   Change<T> --- This mode lets you change or modify existing
     catalogs.

<S>New Mode<T>

The New<T> mode of the Catalog Operations<T> form is used to add
new catalogs.  The new catalog can be created from scratch,
or copied from an existing catalog.  These catalogs will be
used to store information about parts, drawings, assemblies.
When adding new catalogs, I/PDM gives you the ability to
group similar catalogs based on similarities and then
separate them based on their differences.  This is known as
classifications<T>. Because catalog classifications group similar
catalogs, they can be very helpful when searching for a
particular part from the catalogs.  I/PDM does not require you
to classify catalogs, but it can be a very powerful tool in
effectively managing a large amount of data.  If you choose to
use classifications, you should define the proper
classifications before creating catalogs.

The form contains different fields based on the mode in which
you are working.

<S>Form Fields ---<T>

<S>New Button<T>

This button invokes the New<T> mode of operation for the
Catalog Operations<T> form.

<S>Catalog Name Field<T>

This field contains the name for the catalog being added.  If a
catalog is keyed in, it is validated for length and valid
characters.

<S>Description Field<T>

This field contains the description for the catalog being
added.

<S>ACL Field<T>

This field contains the ACL for the catalog being added.  This
information can be keyed in.  For more information on ACLs,
refer to Access Control Lists<T> in this manual.

<S>Catalog Classification Palette<T>

This palette is used to add classifications for grouping
catalogs. It is very important that catalogs be properly
classified when created. If a classification does not exist for a
catalog, you should create one before adding the new
catalog.

The following steps describe how to add a classification.

1.   Enter a data point inside the Catalog Classification<T>
     palette.

     A small subform displays an entry,<T> new category<T>, followed
     by a list of available classifications.  If no classifications
     exists,<T> new category<T> is the only entry listed on the
     subform.<T>

2.   If no classifications exist or the desired classification
     does not exist:

     a.   Select the new category<T> entry from the list.

          The cursor appears in the<T> Catalog Classification<T> palette.<T>

     b.   Key in the name of the classification and press
          <Return>.

     c.   Add any lower level classifications that might be
          needed.

     d.   After you have added the desired classifications, enter
          the information for the catalog to be added.

     If the desired classification already exists:

     a.   Highlight the desired classification name from the list.

          The list disappears and the classification name appears
          in the<T> Catalog Classification<T> palette.<T>

     b.   Proceed to enter the information for the catalog to be
          added.

<S>Default Usage ID Field<T>

This field appears when you are creating a parametric
catalog.  The field lets you enter a usage id for all parts in a
parametric catalog placed in an assembly.

<S>Template Catalog Field<T>

This field is used is create a new catalog based on the
attributes of an existing catalog.  You can enter the name of
the existing catalog that you wish to copy in this field.  When
you select the List<T> button next to the field, a list of existing
catalogs appears.  When you highlight the catalog in the list
to be copied, the list disappears and the catalog name
appears in this field.

<S>Catalog Type Toggle<T>

This toggle indicates the type of catalog to be created.  The
possible values for this toggle are Standard<T> and Parametric<T>.

<S>Change Mode<T>

The Change<T> mode of the Catalog Operations<T> is used to make
changes to existing catalogs.  When catalogs are changed,
they can be assigned to a new classification.  This form is
also used to delete existing catalogs.

<S>Form Fields ---<T>

<S>Change Button<T>

This button invokes the Change<T> mode of operation for the
Catalog Operations<T> form.

<S>Catalog Name Field<T>

This field contains the name for the catalog being changed.
You can enter the catalog name by key-in or select it from a
list generated by the List<T> button next to the Catalog Name<T>
field.

<S>Description Field<T>

This field contains the description for the catalog being
changed.

<S>Catalog Classification Palette<T>

In Change<T> mode, this palette displays the classification to
which the catalog being changed belongs.

<S>Catalog Type Toggle<T>

This toggle is not active in Change<T> mode.

<S>Delete Catalog Button<T>

This button becomes active in Change<T> mode and lets you
delete the existing catalog if no parts exist.

<S>Update Class Button<T>

This button becomes active in Change<T> mode and lets you add
an existing catalog to a classification.  The catalog can be
added to an existing classification or a new classification.

<ETP>
<TP>create_cat2
:Catalog Attributes Form:
The Catalog Attributes<T> form appears when you select the Exit
and Save<T> button on the Catalog Operations<T> form and lets you
change the synonyms of the required attributes, add user
defined attributes and assign protections.  The choices
expressed in this form are actually used when parts are added
to the catalog.

<S>Form Fields ---<T>

<S>Static Button<T>

This button identifies the static attributes that will be added
to the catalog.  These attributes are added as columns to the
catalog table in the database.  Values for static attributes are
defined when adding parts.

<S>Dynamic Button<T>

This button identifies the dynamic attribute that will be added
to the catalog.  Dynamic attributes receive values when the
part is placed in an assembly.

<S>Dynamic Table Field<T>

This field appears when you select the Dynamic<T> button at the
top of the form to add dynamic attributes.  The table defaults
to y_<catalog><T> where <catalog> represents the catalog
being created.  You can use the default or key in another
value.

Dynamic attribute tables can be shared among several
catalogs.  The following steps describe how this is done.

1.   Create a catalog with the necessary attributes.

2.   Create another catalog that requires the same dynamic
     attributes and place the dynamic attribute table name in
     the Dynamic Attribute Table<T> field.

3.   Once you have entered the table name in the field, select
     the Exit and Save<T> button on the form.  The attribute does
     not have to be added again.

<S>Palette for Attribute Listing<T>

This palette lists the static or dynamic attributes that will be
added to the catalog.  This list will be updated when adding a
part to this catalog.  You can change the order of these
attributes by entering a data point in the Order<T> field, deleting
the value, and keying in the new value. The rows will then be
resequenced.

<S>Attribute Definition Palette<T>

This palette contains the options available for defining
catalog attributes.

<S>Range Button<T>

This toggle gives the option to define either a range of values
or a list of possible values for the attribute selected from the
Listing<T> area or an attribute you are adding to the list.  These
values must be entered prior to adding or changing the
attribute.  If an attribute is selected in the Listing<T> field, the
values listed are associated with the selected attribute. After
you select this button, enter the minimum and maximum
range values in the Minimum Value<T> and Maximum Value<T> fields.

<S>List Button<T>

This button displays a list of possible values for the attribute.
You can also use the list to add possible values for the
attribute.

<S>Function Button<T>

This button lets you assign a function to the attribute value.
When you select the Function<T> button, a Function<T> field is
displayed in which you key in the PPL function name.  I/PDM
looks locally for the function and makes sure that it is unique.
If the function is not local, I/PDU looks for it in the function
storage area.

<S>Minimum Value<T>

The field where you enter the minimum value for the range of
values for an attribute.

<S>Maximum Value<T>

The field where you enter the maximum value for range of
values for an attribute.

<S>Listing Area<T>

The field displays when you select the List<T> or Function<T> button
to display a list of possible values for the attribute or
function.

<S>Protections Palette<T>

These toggles let you set protections for the attributes.

<S>Read Toggle<T>

This toggle lets you give the user read access to this attribute.
For new attributes, it is defaulted to Yes.

<S>Write Toggle<T>

This toggle lets you give the user write access to this
attribute.  For new attributes, the toggle is set to Yes. The Yes
value lets you assign values to this attribute when adding a
part to the catalog.

<S>Update Toggle<T>

This toggle lets you give the user update access to this
attribute.  For example, when performing Change Part<T> you
can update information on an existing part in this catalog.
For new attributes, the toggle is set to Yes.

<S>Input Required Toggle<T>

This toggle lets you identify whether users are required to
enter values for the attributes when adding a part to the
catalog or modifying part information.  For new attributes,
the toggle is set to No.

<S>Attribute Information Palette<T>

This palette displays information about attributes to be added
or changed.

<S>Attribute Name Field<T>

This field lets you key in an attribute name to be added.  When
you key in an attribute name, the name is validated.  If the
attribute name is not valid, an error message is returned and
the field is cleared. This field is also used to change an
attribute name.

<S>Datatype Field<T>

This field lets you key in the datatype for the attribute to be
added.  This field is also used to change an attribute datatype,
(increasing or decreasing the size of a character datatype).
For more information on data types, refer to the RIS Reference
Manual DNA0032<T>.

<S>Synonym Field<T>

This field lets you key in the synonym for the attribute to be
added. This field is also used to change an attribute synonym.

<S>Default Value Field<T>

This field lets you key in the default value for the attribute to
be added.  This field is also used to change the default value
for an attribute.  This value will be displayed at add part time.

<S>Attribute Commands Palette<T>

This palette contains commands that let you perform
operations on catalog attributes.

<S>Show System Attributes Toggle<T>

This toggle indicates if the system attributes will be displayed
when this form appears.

<S>Add Attribute Button<T>

This button lets you add the attribute keyed in the Attribute
Name<T> field.  You must have all toggles set and range or list
values set before you add the attribute.  The command lets
you key in the order, synonym, and default value for the
attribute. After you add the attribute, its name appears in the
attribute name column in the attribute multi-column list.

<S>Change Attribute Button<T>

This button lets you change the selected attributes.  You can
change synonym or size for the datatype on required
attributes.

<S>Note:<T>

When this form is checked off, the Catalog Operations<T> form
reappears. <F> „<T>

<ETP>
<TP>part_form
:Part Operations Form:
The Part Operations<T> form appears when you select the Parts<T>
button on the PDM/PDU<T> form.  This form lets you add a new
part from nothing or start from an existing part, change an
existing part, or review information on an existing part.  The
form has four modes to perform these operations:

1.   New<T> --- This mode lets you add a new part from scratch. For
     related information, see the following topic:<T> New Mode<T>.

     <ST>newmode  New Mode<T>

2.   Similar<T> --- This mode lets you add a new part by starting
     from an existing part.  For related information, see the
     following topic:<T> Similar Mode<T>.

     <ST>part_form.sm Similar Mode<T>

3.   Change<T> --- This mode lets you change or delete an existing
     part. For related information, see the following topic:<T>
     Change Mode<T>.

     <ST>changemode  Change Mode<T>

4.   Review<T> --- This mode lets you review information of an
     existing part and delete files. For related information, see
     the following topic:<T> Review Mode<T>.

     <ST>revmode  Review Mode<T>

<ETP>
<TP>newmode
:New Mode:
The New<T> mode of the Part Operations<T> form lets you add new
parts to the selected catalog.  The form lets you add the
information for the new part and execute the Add Part<T>
command by selecting the Add<T> button.

<S>Form Fields ---<T>

<S>New Button<T>

This button activates the New<T> mode.

<S>Similar Button<T>

This button activates the Similar<T> mode.

<S>Change Button<T>

This button activates the Change<T> mode.

<S>Review Button<T>

This button activates the Review<T> mode.

<S>New Part Palette<T>

This palette displays the information about the part being
added.

<S>Project Field<T>

This field displays the name of the project to which you are
adding a part.  You can use the List<T> button beside this field to
view a complete list of projects.

If a catalog name is entered before a project name is keyed in,
the system will check to see if the catalog is mapped to the
project name that is entered.  If the catalog is not mapped to
the project, the system will display an error.  If a catalog is
entered when the list button next to the Project<T> field is
selected, the system will list any projects to which the
catalog is mapped.  If the catalog is not mapped to any
projects, an error message will appear.

<S>Catalog Field<T>

This field displays the name of the catalog to which you are
adding a part.  You can use the List<T> button beside this field to
view a complete list of catalogs.  If you are using catalog
classifications, the List<T> button displays a list of valid
classifications.  You can select the appropriate classification
to display a list of catalogs within the classification.

When a catalog name is entered, the catalog attributes are
displayed in the  Part Attribute Value<T> area.  When a catalog
name is entered, the Part Number, Revision, Part Type<T> and
Description<T> fields are blanked out.

<S>Part Number Field<T>

This field displays the part number for the part you are
adding.  You can use the List<T> button beside this field to view a
complete list of parts.

<S>Revision Field<T>

This field displays the revision for the part you are adding.
The revision must be keyed in.

<S>Part Type Field<T>

This field displays the part type for the part you are adding.
By default the system places a "G<T>" in this field to indicate a
graphic part.  The following is a list of valid part types:
<F>

G            Graphic
N            Non-graphic
M            Macro
D            Drawings<T>
<S>Description Field<T>

This field is where you key the description for the part you are
adding.

<S>Part Attribute Values Palette<T>

This palette displays the write only attributes and values for
the catalog selected.  The attribute column is read only, but
the value column allows data entry.  Attributes that are
prefixed by an asterisk *<T> indicates that there is a list of
possible values for the attribute.  You can view this list by
tapping the middle mouse button on the attribute name.

<S>New File Information Palette<T>

This palette displays file information about the part.  This
palette contains the following fields:

<X>õ<T>   Description<T> --- Displays the description of the reference
     file for the part.

<X>õ<T>   Local Filename<T> --- Displays the name of the reference file
     stored on the local working area.

<X>õ<T>   Storage Filename<T> --- Displays the name under which the
     file is stored on the permanent storage area.  If this field is
     left blank, the system generates a unique filename for
     storage.

<X>õ<T>   File Type<T> --- Displays the file type for the reference file.

<S>Storage Area Field<T>

This field displays the storage area for the local files when
they are checked in.  You can use the List<T> button beside this
field to view a complete list of storage areas.  If there is only
one storage area, the List<T> button will not be displayed.

<S>ACL Information Palette<T>

This palette displays a state name, workflow, and ACL for the
new part.

<S>State Name Field<T>

This field displays the state name for the new part.  Since the
part is new, the state name will always be the first or creation
state.  This field is non-selectable to prevent you from
changing the state name for the part without using the Move
To Next State<T> button.

<S>Workflow Field<T>

This field displays the workflow for the current catalog.  If the
catalog is not mapped, the value defaults to
PDM_PART_WORKFLOW.<T>

<S>ACL Name Field<T>

This field displays the ACLs for the current catalog.  You can
use the List<T> button to display a list of all valid ACLs.  The
system defaults to PDM_PART_ACL.<T>

<S>Part Operation Buttons<T>

These buttons invoke the part operations command.  In the
New<T> mode all commands except the Add<T>  and Search<T>
commands are disabled.

<S>Add Button<T>

This button invokes the Add Part<T> command after you have
loaded the new part information.

<XR>PDAdPr  Add Part<T>

<S>Search Button<T>

This button invokes the Part Selection<T> form and lets you
search for a particular part in the current catalog.

<ETP>
<TP>part_form.sm
:Similar Mode:
The Similar<T> mode of the Part Operations<T> form lets you create
new parts that are similar to existing parts based on
information about existing parts.

<S>Form Fields ---<T>

<S>Existing Part Palette<T>

This palette contains information about an existing part.

<S>Project Field<T>

This field displays the name of the project containing the
existing part.  You can use the List<T> button beside this field to
view a complete list of projects.

<S>Catalog Field<T>

This field displays the name of the catalog containing the
existing part.  You can use the List<T> button beside this field to
view a complete list of catalogs.  If you are using catalog
classifications, the List<T> button displays a list of valid
classifications.  You can select the appropriate classification
to display a list of catalogs within the classification.

<S>Part Number Field<T>

This field displays the part number for the existing part that is
similar to the new part.  You can use the List<T> button beside
this field to view a complete list of parts.

If no values appear in the Existing Part<T> palette when a part
number is entered, the system searches all catalogs for a
catalog that contains the part number.  If only one catalog
exists, the system displays the information about the part.  If
more than one catalog exists, the system displays a list of
catalogs that contain the part number.  After a catalog is
selected, the information about the latest revision of the part
appears in the Existing Part<T> palette.

If no values appear in the Existing Part<T> palette when the List<T>
button next to the Part Number<T> is selected, a message
displays stating that a catalog must be chosen before a list of
parts can be displayed.

If a catalog name is displayed in the Existing Part<T> palette
when a part number is entered, the system checks to see if
the catalog contains the part number.  If the catalog does not
contain the part number, you are given the option to search all
catalogs for the part number.  If you want to search all
catalogs, the Part Selection<T> form appears to let you conduct
the search.  If the search determines that the part number
does not exist, a message is displayed and the Part Number<T>
field is cleared.  If catalogs exist, they will be displayed the
same way as described previously.

If a catalog name is entered when the List<T> button next to the
Part Number<T> field is selected, a list of parts in the catalog is
displayed.  If the catalog contains no parts, a message is
displayed.

<S>Revision Field<T>

This field displays the revision for the existing part that is
similar to the new part.  This field defaults to the latest or
only revision when a part number or description is entered.

If a description or part number is displayed when a revision is
entered, the system determines if the catalog contains a part
number with the specified revision.  If the part number and
revision exists, the revision is displayed.  If not, a message is
displayed stating the revision is not found.

If a description or part number is displayed when the List<T>
button next to the Revision<T> field is selected, the system
displays a list of revisions for the entered part number based
on the entered catalog.  If no other revisions exist, a message
is displayed.

<S>Part Type Field<T>

This field displays the part type for the existing part.  You can
use the List<T> button beside this field to view a complete list of
part types.  The following is a list of possible part types:
<F>

G            Graphic
N            Non-graphic
M            Macro
D            Drawings<T>
<S>Description Field<T>

This field displays the description for the existing part.

<S>New Part Palette<T>

This palette contains the same part information as in the
Existing Part<T> area except for the revision<T> which is blank.

<S>Project Field<T>

This field displays the name of the project to which you are
adding the part.  You can use the List<T> button beside this field
to view a complete list of projects.

<S>Catalog Field<T>

This field displays the name of the catalog to which you are
adding the part.  You can use the List<T> button beside this field
to view a complete list of catalogs.

<S>Part Number Field<T>

This field displays the part number for the part you are
adding.  You can use the List<T> button beside this field to view a
complete list of parts.

Before a part number can be entered, a valid catalog name
must appear in the Catalog<T> field.

<S>Revision Field<T>

This field displays the revision for the part you are adding.
Since this is a new part, there is no List<T> button next to the
Revision<T> field.

<S>Part Type Field<T>

This field displays the part type for the part you are adding.
You can use the List<T> button beside this field to view a
complete list of part types.  By default the system places a "G<T>"
in the field to indicate a graphic part.

<S>Description Field<T>

This field displays the description for the part you are adding.

<S>Part Attribute Values Palette<T>

This palette contains the write-only attributes and values for
those attributes common to the existing part.  The attribute<T>
column is read-only and the value<T> column allows data entry.
Attributes that are prefixed by an *<T> indicates that there is a
list of possible values for the attribute.  You can view this list
by tapping the middle mouse button on the attribute name.

<S>New File Information Palette<T>

This palette displays the file information about the part
displayed in the Existing Part<T> palette.  All columns in this field
allow data entry.  If the part type is "G<T>", a local filename is
required.  This palette contains the following fields:

<X>õ<T>   Copy/Do Not Copy Toggle<T> --- This toggle appears if you the
     existing part is checked in.  If you set the toggle to Copy<T>,
     the existing local file name appears in the Local Filename<T>
     field.  When you select the Add<T> button, this local filename
     will be associated with the new part.  If the toggle is set to
     Do Not Copy<T>, you will not associate a reference file with
     the new part.

<X>õ<T>   Checkin/Do Not Checkin Toggle<T> --- This toggle indicates if
     the new part will be checked in.

<X>õ<T>   Description<T> --- Displays the description of the reference
     file for the part.

<X>õ<T>   Local Filename<T> --- Displays the name of the reference file
     stored on the local working area.

<X>õ<T>   Storage Filename<T> --- Displays the name under which the
     file is stored on the permanent storage area.  If this field is
     left blank, the system generates a unique filename for
     storage.

<X>õ<T>   File Type<T> --- Displays the file type for the reference file.

<S>Storage Area Field<T>

This field displays the storage area for the new file.  You can
use the List<T> button beside this field to view a complete list of
storage areas.

<S>ACL Information Palette<T>

This palette displays a state name, workflow, and ACL for the
existing part.

<S>State Name Field<T>

This field displays the state name for the part displayed in the
Existing Part<T> palette.

<S>Workflow Field<T>

This field displays the workflow for the current catalog.  If the
catalog is not mapped, the value defaults to
PDM_PART_WORKFLOW<T>

<S>ACL Name Field<T>

This field displays the ACLs for the current catalog.  You can
use the List<T> button to display all valid ACLs.

<S>Part Operations Buttons<T>

These buttons invoke the part operations commands.  All
commands except the Add<T> and Search<T> commands are
disabled during Similar<T> mode.

<S>Add Button<T>

This button invokes the Add Part<T> command after part
information for the new part has been added.

<S>Search Button<T>

This button invokes the Part Selection<T> form and lets you
search for a particular part in the current catalog.

<XR>PDAdPr  Add Part<T>

<ETP>
<TP>changemode
:Change Mode:
The Change<T> mode of the Part Operations<T> form lets you change
existing parts.

<S>Form Fields ---<T>

<S>Existing Part Palette<T>

This palette contains information about an existing part.

<S>Project Field<T>

This field displays the name of the project containing the part
you are changing.  You can use the List<T> button beside this field
to view a complete list of projects.

<S>Catalog Field<T>

This field displays the name of the catalog to which you are
adding a part.  You can use the List<T> button beside this field to
view a complete list of catalogs.  If you are using catalog
classifications, the List<T> button displays a list of valid
classifications.  You can select the appropriate classification
to display a list of catalogs within the classification.

<S>Part Number Field<T>

This field displays the part number for the part you are
changing.  You can use the List<T> button beside this field to view
a complete list of parts.

<S>Revision Field<T>

This field displays the revision for the part you are changing.

<S>Part Type Field<T>

This field displays the part type for the part you are changing.
You can use the List<T> button beside this field to view a
complete list of part types.  The following is a list of possible
part types:
<F>

G            Graphic
N            Non-graphic
M            Macro
D            Drawings<T>
<S>Description Field<T>

This field displays the description for the part you are
changing.

<S>Part Attributes Values Palette<T>

This palette contains the update-only attributes and values
for the catalog selected in the Existing Part<T> palette.  The
attribute<T> column is read-only.  The value<T> column allows data
entry.  Attributes that are prefixed by an asterisk *<T> indicates
that there is a list of possible values for the attribute.  You can
view this list by tapping the middle mouse button on the
attribute name.

<S>File Information Palette<T>

This palette contains file information for both the existing
files and new files.

<S>Existing Files<T>

This palette displays the file information associated with the
part selected in the Existing Part<T> palette.  All columns in this
gadget allow data entry. This palette contains the following
fields:

<X>õ<T>   Description<T> --- Displays the description of the reference
     file for the part.

<X>õ<T>   Local Filename<T> --- Displays the name of the reference file
     stored on the local working area.

<X>õ<T>   Storage Filename<T> --- Displays the name under which the
     file is stored on the permanent storage area.  If this field is
     left blank, the system generates a unique filename for
     storage.

<X>õ<T>   File Type<T> --- Displays the file type for the reference file.

<S>New Files<T>

This palette displays the description, local filename, storage
filename, and file type for the new file.

<S>Storage Area Field<T>

This field displays the storage area for the filename if the
existing part is checked in.  You can use the List<T> button beside
this field to view a complete list of storage areas.  If there is
only one storage area, the List<T> button will not be displayed.

<S>ACL Information Palette<T>

This field displays the state name, workflow, and ACL name
for the existing part in non-selectable fields.  The information
contained in this palette cannot be changed.

<S>State Name Field<T>

This field displays the state name for the existing part.  This
field is non-selectable to prevent you from changing the state
name for the part without using the Move to Next State<T>
button.

<S>Workflow Field<T>

This field displays the workflow for the current catalog.
Since you working with a part that exists, this field is
non-selectable to prevent you from changing the value in this
field.

<S>ACL Name Field<T>

This field displays the ACL for the current catalog.  Since you
are working with a part that exists, this field is non-selectable
to prevent you from changing the value in this field.

<S>Move to Next State Button<T>

This button displays the Possible State Transitions<T> form. This
form gives the possible state transitions a part can make
according to the selected and the state the part is in at the
time of the command selection.

<XR>PDApPr  Approve Part<T>

<S>Part Operations Buttons<T>

These buttons invoke the part related commands that can be
used in Change<T> mode.

<S>Change/Add Files Button<T>

This button lets you change the existing files or add new files
for the part in the Existing Part<T> palette through the Part
Attribute Values<T> palette and Existing File Information<T> palette.

<XR>PDCPr  Change Part<T>

<S>Add to Project Button<T>

This button lets you add the review part to a project.

<XR>PDAdPrPj  Add Part To Project<T>

<S>Flag/Cancel Flag Button<T>

This button lets you flag or cancel the flag for an archive,
backup, delete, or restore for the part in the Existing Part<T>
palette. When you select this button, a palette appears
containing a toggle and four buttons.  The Flag/Cancel Flag<T>
toggle indicates if the flag is being set or cancelled for the
part displayed in the Existing Part<T> palette.   The four buttons,
Archive, Restore, Backup,<T> and Delete<T> indicate the utility to be
performed on the part displayed in the Existing Part<T> palette.

<XR>PDCnFlAr Cancel Flag for Archive<T>
<XR>PDCnFlBc Cancel Flag for Backup<T>
<XR>PDCnFlDl Cancel Flag for Delete<T>
<XR>PDCnFlRs Cancel Flag for Restore<T>
<XR>PDFlPrAr Flag Part for Archive<T>
<XR>PDFlPrBc Flag Part for Backup<T>
<XR>PDFlPrDl Flag Part for Delete<T>
<XR>PDFlPrRs Flag Part for Restore<T>

<S>Search Button<T>

This button invokes the Part Selection<T> form and lets you
search for a part.

<S>Delete Button<T>

This button invokes the Delete Part<T> command and lets you
delete the current part in the Existing Part<T> palette or a number
of parts simultaneously that were searched for, displayed,
and selected from the Part Listing<T> palette.

<XR>PDDlPr  Delete Part<T>

<S>Where Used Button<T>

This button lets you show where the part is used in an
assembly.

<ETP>
<TP>revmode
:Review Mode:
The Review<T> mode lets you review a part's attributes.

<S>Form Fields ---<T>

<S>Existing Part Field<T>

This field contains information about an existing part.

<S>Part Attributes Values Field<T>

This field contains the read only attributes and values for the
catalog selected in the Existing Part<T> palette.  The attribute<T>
and value<T> column are both read only.  Attributes that are
prefixed by an asterisk *<T> indicates that there is a list of
possible values for the attribute.  You can view this list by
tapping the middle mouse button on the attribute name.

<S>Existing File Information Field<T>

This field displays information for the file associated with the
part selected in the Existing Part<T> palette.  All columns in this
field are read-only.  You can select one or more rows for
deleting files.  This palette contains the following fields:

<X>õ<T>   Description<T> --- Displays the description of the reference
     file for the part.

<X>õ<T>   Local Filename<T> --- Displays the name of the reference file
     stored on the local working area.

<X>õ<T>   Storage Filename<T> --- Displays the name under which the
     file is stored on the permanent storage area.  If this field is
     left empty, the system generates a unique filename for
     storage.

<X>õ<T>   File Type<T> --- Displays the file type for the reference file.

<S>Storage Area Field<T>

This field displays the storage area for the filename.

<S>ACL Information Field<T>

This field displays the state name, workflow, and ACL name
for the existing part in non-selectable fields.

<S>State Name Field<T>

This field displays the state name for the existing part.  This
field is non-selectable to prevent you from changing the state
name for the part without using the Move to Next State<T>
button.

<S>Workflow Field<T>

This field displays the workflow for the current catalog.
Since you are working with a part that exists, this field is
non-selectable to prevent you from changing the value in this
field.

<S>ACL Name Field<T>

This field displays the ACL for the current catalog.  Since you
are working with a part that exists, this field is non-selectable
to prevent you from changing the value in this field.

<S>Move to Next State Button<T>

This command displays the Possible State Transitions<T> form.
This form gives the possible state transition a part can make
according to the selected workflow and the state the part is
in at the time of the command selection.

<S>Part Operations Buttons<T>

The Delete Files<T> is the only button active in Review<T> mode.

<S>Delete Files Button<T>

This button lets you delete files associated with a part.
Select the files in the Existing File Information<T> palette to be
deleted and select the Delete Files<T> button.  If the part is
checked in, no files can be deleted.

<ETP>
<TP>part_listing
:Part List Form:
There are two forms that display a list of parts.  You can
display these forms by selecting the List<T> button next to the
Part<T> field and by selecting the List of Parts in Catalog<T> from the
PDM/PDU<T> form.  The form that appears depends on which
button is selected.

<H>List of Parts<T><T>

<H>List of Parts/Files<T><T>

The following illustrates the List of Parts/Files<T> form that
appears when the List of Parts/Files<T> button on the PDM/PDU<T>
form is selected.

<ETP>
<TP>parmoper
:Parametric Parts Operations Form:
This form appears when you select the Parametrics<T> button
from the Management<T> palette of the PDM/PDU<T> form and lets
you perform operations on parametric parts.

<S>New Button<T>

This button activates the New<T> mode of the form and lets you
add new parametric parts.

<S>Change Button<T>

This button activates the Change<T> mode of the form and lets
you change existing parametric parts.

<S>Project Field<T>

This field displays the project that contains the part.  You can
use the List<T> button next to this field to display a list of
available projects.

<S>Catalog Field<T>

This field displays the catalog that contains the part.

<S>Description Field<T>

This field displays the description of the catalog.

<S>Classification Buttons<T>

These buttons display the classification levels for the
catalogs.  For example, L1<T> means classification level one.

<S>Spreadsheet Operations Buttons<T>

These buttons let you perform spreadsheet operations.

<S>Add Row With Defaults Button<T>

This button automatically adds a row to the spreadsheet and
inputs all of the defaults.  You must enter any attributes that
do not have defaults.

<S>Add Rows From Search Button<T>

This button activates the Part Selection<T> form and lets you
select rows to be entered in the spreadsheet.  These rows can
be selected by a search.  The rows are ented in the
spreadsheet when you execute the Run<T> button on the Part
Selection<T> form.

<S>Copy Row Button<T>

This button copies the highlighted row in the spreadsheet to
the bottom of the list in the spreadsheet.  This lets you change
one or two parameters in the addition of a series of standard
parts.

<S>Clear Row Button<T>

This button lets you clear all data from a selected row in the
spreadsheet.

<S>Multi-column Field Spreadsheet<T>

The multi-column field spreadheet is a horizontal display of
the part attributes and their values.  The spreadsheet displays
only the attributes that have write<T> privileges.

<S>Part Commands palette<T>

This palette contains buttons that let you activate parametric
part commands.

<S>Add Button<T>

This button adds the rows in the spreadsheet to the catalog.
It does not add a row that has the same part number and
revision.  Once the parts are added, the spreadsheet is
cleared.

<S>Change Button<T>

This button changes all the rows that are currently displayed
in the main spreadsheet for the catalog.  The change uses the
part and revision to know which row to change.  Once the
parts are changed, the spreadsheet is cleared.

<S>Delete Button<T>

This button deletes all the rows that are currently displayed in
the main spreadsheet for the catalog.  The deletes uses the
part and revision to know which row to delete.  Once the
parts are deleted, the spreadsheet is cleared.

<S>Move to Next State Button<T>

This button moves the identified part to its next state.

<ETP>
<TP>MOAddPart
:Parametric Attributes Form:
The Parametric Attributes<T> form appears when you select the
Exit and Save<T> button from the Catalog Operations<T> form when
adding a parametric catalog.  This form lets you add
parametric attributes to the catalog.  After you have entered
the information on this form and selected the Exit and Save<T>
button the Catalog Attributes<T> form appears.

<S>Form Fields ---<T>

<S>Catalog Field<T>

This field displays the name of the parametric catalog.

<S>Description Field<T>

This field displays the description for the parametric catalog.

<S>Checkin Macro Library Toggle<T>

This toggle indicates if the macro library will be checked in.
The default is Yes<T>.

<S>Macro Library Field<T>

This field displays the name of the macro part containing the
macro displayed in the Macro Name<T> field.

<S>Macro Name Field<T>

This field displays the name of the macro containing the
parameters needed for creating the catalog.

<S>Sketch File Name Field<T>

This field displays the name of a sketch file.

<S>Attribute Listing Palette<T>

This palette displays the attributes for the catalog.

<S>Define Source Libraries Button<T>

This button displays the Define Support Library<T> form.

<ETP>
<TP>def_lib
:Define Support Libraries Form:
The Define Support Libraries<T> form appears when you select
the Define Source Libraries<T> button on the Parametric
Attributes<T> form.

<S>Form Fields ---<T>

<S>Library Field<T>

This field displays name of the library containing the macro
library file.

<S>Description Field<T>

This field describes the library displayed in the Library<T> field.

<S>Support Libraries Palette<T>

This palette contains information about the support libraries.

<S>Delete Button<T>

This button lets you delete an existing support library.

<S>Library Selection Palette<T>

This palette contains information about the library being
added as a support library.

<S>Catalog Field<T>

This field displays the catalog that contains the macro library
being added as a support library.

<S>Description Field<T>

This field displays the description of the catalog displayed in
the Catalog<T> field.

<S>Add Button<T>

This button lets you add a new support library.

<ETP>
<TP>MOPartSelec2
:Part Selection Form:
The Part Selection<T> form lets you perform part operations such
as Place Part<T> and Replace Part<T>, as well as perform searches
for parts, in the database.  You can search for a part in a single
catalog or in a number of catalogs in the database.  The form
is invoked in several ways.  It appears when you select the
Search for Parts<T> button from the PDM/PDU<T> form, the Place
Part<T> button or Replace Part<T> button from the Design Operations<T>
form, or the Search<T> button that appears on several forms.

<S>Form Fields ---<T>

<S>Project Field<T>

This field lets you limit the search for selected parts to those
that belong to the indicated project.  Selecting this field
displays a list of all projects.  You can then select the project
from this list.

<S>Catalog Field<T>

This field contains the name of the catalog when you are
limiting the search to a single catalog.

<S>Description Field<T>

This field contains the description of the catalog displayed in
the Catalog<T> field.

<S>Classification Buttons<T>

This button performs several functions.  Selecting this button
invokes a list that displays the entries, Common Attributes,
Display Catalogs<T>, and a list of classifications and catalogs at
this level.

Highlighting Common Attributes<T> displays a list of common
attributes at this classification level.

Highlighting the Display Catalogs<T> displays a list of all
catalogs in the database.

Highlighting a classification invokes another list that displays
the entries, Common Attributes, Display Catalogs<T>, and a list of
classifications and catalogs at this level. You can continue to
select the classification until you get to the level containing
the desired catalog.

<S>Static Attr/Dynamic Attr Toggle<T>

This toggle indicates the attribute type on which the search
will be conducted.  If the toggle is set to Static Attr<T> the
system searches on the static attributes defined on the
Catalog Attributes<T> form.  If the toggle is set to Dynamic Attr<T>
the system searches on the dynamic attributes defined on the
Catalog Attributes<T> form.

<S>Replace All/Replace One Toggle<T>

This toggle appears on the form only when the Replace Part<T>
on the Design Operations<T> form is selected and lets you
replace all occurrences or a single occurrence of the selected
part.

<S>Show Graphics Button<T>

This button displays the graphic file for the selected part.

<S>Search Button<T>

This button executes a search based on the search criteria
displayed in the attribute listing palette at the bottom on the
form.  You can conduct searches based on new criteria or on
previously defined criteria.

<S>Placement Options Button<T>

This button displays the Placement Options<T> form.

<S>Expand Listing Button<T>

This button invokes the Expanded Listing<T> form, which displays
a detailed list of the values returned from executing a search.

<S>Selected Value Palette<T>

Use the Minus<T> and Plus<T> buttons to scroll through the parts to
locate a specific part.  The field between these buttons tells
the number of parts found in the search.

<S>Selection Criteria Palette<T>

This palette contains buttons used in search and sort
operations. Before selecting any of these buttons, you must
select the Convert to Permanent Window<T> button at the top of
this form.

<S>Load Button<T>

This button lets you load previously defined search criteria.
When you select this button a subform appears that lets you
enter the name of the previously defined search criteria.

<S>Save Button<T>

This button lets you save search criteria.  When you select this
button a subform appears that lets you enter the name to save
the new search criteria.

<S>Sort Button<T>

This button invokes the Sort Parts<T> form that lets you define
sort conditions for the results of the search.

<S>Part Relation Button<T>

This button displays the Part Relationship Criteria<T> form.

<ETP>
<TP>search_options
:Name Form:
This form appears when you select the Load<T> button or Save<T>
button on the Part Selection<T> form. When invoked with the
Load<T> button, the form lets you load a previously defined
search criteria.  When invoked with the Save<T> button, the form
lets you save new search criteria.  The following illustrates
the Name<T> form and describes the gadgets on the form.

<S>Form Fields ---<T>

<S>Name Field<T>

This field lets you key in the name for the previously defined
criteria or the name for saving the new search criteria.

<ETP>
<TP>sort
:Sort Parts Form:
The Sort Parts<T> form appears when you select the Sort<T> button
on the Part Selection<T> form and lets you sort the results from a
search before the catalog/part listing is displayed.

<S>Form Fields ---<T>

<S>Part Sort Conditions Field<T>

This palette contains rows of empty fields that allow you to
enter the attribute on which the parts will be sorted.  You can
select the List<T> button next to the field to display a list of
attributes for the part.  When you highlight an attribute from
this list, the list disappears and the highlighted attribute
appears in the field.  You can use multiple attributes when
defining the sort criteria.

<S>Load Sort Conditions Button<T>

This button invokes the Load Sort Conditions<T> form that lets
you load previously defined sort conditions.

<S>Save Button<T>

This button invokes the Save Sort Conditions<T> form that lets
you save sort conditions for parts.

<ETP>
<TP>sort_options
:Load Sort Conditions Form:
This form appears when you select the Load Sort Conditions<T>
button on the Sort Parts/Catalogs<T> form and lets you load
previously defined sort criteria.

<S>Form fields ---<T>

<S>Sort Conditions Field<T>

This field displays previously defined sort conditions for
catalogs.

<ETP>
<TP>ssort
:Save Sort Conditions Form:
This form appears when you select the Save<T> button on the
Sort Parts<T> form and lets you save sort conditions for parts.

<S>Form Fields ---<T>

<S>Sort Conditions Field<T>

This field contains the name to which the sort conditions will
be saved.

<ETP>
<TP>where_used
:Part Relationship Criteria Form:
The Part Relationship Criteria<T> form appears when you select
the Part Relation<T> button on the Part Selection<T> form.  This form
lets you search for a part that is:

<X>õ<T>   a child of the selected part.

<X>õ<T>   a parent of the selected part.

This can be used to find all drawings in a drawing catalog that
reference a selected part.

<S>Select only parts that... toggle<T>

This toggle indicates if the list will display a parent or child of
the selected part.   If the toggle is set to contain the part
below<T>., the list will display all parent parts that contain the
selected part.  If the toggle is set to are contained in the
assembly below.<T>, the list will display all children parts that
are contained in the selected part.

<S>Project Field<T>

This field displays the project to which the selected part
belongs.  The List<T> button next to the field displays a list of all
projects.

<S>Catalog Field<T>

This field displays the catalog that contains the selected part.
The List<T> button next to the field displays a list of all catalogs.
If a project name is displayed in the Project<T> field when the List<T>
button next to the Catalog<T> field is selected, the list will
display only the catalogs that belong to the displayed project.

<S>Part Number Field<T>

This field displays the part number for the selected part. The
List<T> button next to the field displays a list of all parts in the
catalog displayed in the Catalog<T> field.  A valid catalog name
must appear in the Catalog<T> field before the List<T> button can be
used to display a list of parts.

<S>Revision Field<T>

This field displays the revision for the selected part. The List<T>
button next to the field displays a list of all revisions for the
part displayed in the Part Number<T> field.  A valid part number
must appear in the Part Number<T> field before the List<T> button
can be used to display a list of revisions.

<S>Description Field<T>

This field displays the description for the selected part.

<ETP>
<TP>cancel_list
:Cancel Part Check Out Form:
The Cancel Part Check Out<T> form appears when you select the
Delete Local Files<T> button on the PDM/PDU<T> form to delete
multiple local files.  The form displays a highlighted list of all
parts that are checked out.  You can select the Exit and Save<T>
button on the form to cancel the checkout of these parts.  You
can unhighlight any of the parts that you want to remained
checked out to the local workstation.

<S>Form Fields ---<T>

<S>Listing Palette<T>

This palette contains information about the parts that are
checked out.

<ETP>
<TP>design_form
:Design Operations Form:
The Design Operations<T> form appears when a part is opened
for design when the Retrieve for Design<T> button is selected
from the PDM/PDU<T> form.  The form lets you access all
commands relative to building an assembly design.  This form
is persistent during the design session, but can be collapsed
by the user.  The form is collapsed if command that displays
the entire design.

<S>Form Fields ---<T>

<S>Save & Exit Button<T>

This button lets you save the active file and exit the design
session.  When you select this button, the system will prompt
Save and Exit Design with (y/n) [y]?<T>.  Exiting this form
redisplays the PDM/PDU<T> form.

<S>Save, Exit & Checkin Button<T>

This button lets you save the active file, exit the design
session, and check in the file.  The system will prompt Exit,
Save and Checkin (y/n) [y]?<T>. Exiting this form redisplays the
PDM/PDU<T> form.

<XR>PDDcChInPr  Save, Exit & Checkin<T>

<S>Exit Without Save Button<T>

This button lets you exit the design session without saving
the active file.  When you select this button, the system will
prompt Exit Design Without Save (y/n) [y]?<T>. Exiting this form
redisplays the PDM/PDU<T> form.

<S>Active Part Information Palette<T>

This palette displays information about the active part.

<S>Catalog Field<T>

This read-only field displays the name of the catalog that
contains the active part.

<S>Part Number Field<T>

This read-only field displays the part number for the active
part.

<S>Revision Field<T>

This read-only field displays the revision for the active part.

<S>Filename<T>

This read-only field displays the name of the attached design
file for the active part.

<S>Display Part Pointers Toggle<T>

This toggle determines if the part pointer for the part will be
displayed when the part is placed.  The two options are Off<T>
and On<T>.

<S>Design Commands Palette<T>

This palette contains the command buttons used in design
operations.

<S>Place Part Button<T>

This button invokes the Part Selection<T> form.  After the part
has been selected, the Place Part<T> command begins the part
placement procedure.

<XR>PDPPr  Place Part<T>

<S>Define Origin Button<T>

This button defines an origin in the currently active design
file.  You are prompted to enter the view name and identify
the point to place the origin.  The default viewname is
PDUview<T>.

<XR>PDDfOr  Define Origin<T>

<S>Highlight Part Button<T>

This button highlights an existing part in an assembly.  When
the button is selected, the system prompts, Identify Part<T>.  At
this point, you can graphically locate a part or get a
save/restore form that lists the first level part occurrences.
This command allows multiple part selection.  The first list
displayed will contain only first-level parts.

<XR>PDLcRvPr  Highlight Part<T>

<S>Replace Part Button<T>

This button invokes the Part Selection<T> form.  The form invoked
by this button looks much like the form invoked with the Place
Part<T> button.  However, this form contains two additional
toggles, Static Attr/Dynamic Attr<T> and Replace All/Replace One<T>.
For more information on these toggles, see Part Selection
Form<T>.

<XR>PDRpPr  Replace Part<T>

<S>Delete Origin Button<T>

This button invokes the Delete Origin<T> command and lets you
delete the origin for a part.  When the button is selected, the
system prompts, Identify Part<T>.  At this point, you can
graphically locate a part or display a save/restore form that
lists the first level part occurrences.

<XR>PDDlOr  Delete Origin<T>

<S>Reports Button<T>

This button activates the Reports<T> form which lets you define
the format for reports and then create and display the report.

<S>Copy Part Button<T>

This button lets you copy a part pointer.  When the button is
selected, the system prompts, Identify Part<T>.  At this point, you
can graphically locate a part or get a save/restore form that
lists the first level part occurrences.

<XR>PDCpPr  Copy Part<T>

<S>Attach Button<T>

This button attaches a part's graphics by identifying the part's
pointer in the current active design file.  The part's file must
be checked in at least once or an error message is displayed
in the message area indicating the file must be checked in
first.  When the button is selected, the system prompts,
Identify Part<T>.  At this point, you can graphically locate a part
or get a save/restore form that lists the first level part
occurrences.  The list will contain detached graphic parts
that have reference file attachments.  The list allows multiple
first-level part selection.

<XR>PDAtPr  Attach Part<T>

<S>Topdown Design Button<T>

This button invokes the Topdown Design<T> command, which
allows you to design the assembly in one file and then break
the assembly into smaller parts.  The new part will be
incorporated into the database. The assembly must be the
active part.  The Design Operations<T> form will be erased when
the command is invoked.

<S>Delete Part Button<T>

This button deletes the part occurrence.  When the button is
selected, the system prompts, Identify Part<T>.  At this point, you
can graphically locate a part or get a save/restore form that
lists the first level part occurrences.  The list allows multiple
first-level part selection.

<XR>PDDlPrPt  Delete Part Pointer<T>

<S>Detach Button<T>

This button detaches the part's graphics by identifying the
part pointer in the current active design.  When the button is
selected, the system prompts, Identify Part<T>.  At this point, you
can graphically locate a part or get a save/restore form that
lists the first level part occurrences.   This list that is
displayed will only contain only attached graphic parts which
have reference file attachments.  The list allows multiple
first-level part selection.

<XR>PDDtPr  Detach Part<T>

<S>Position Part<T>

This button lets you position graphics parts in an assembly
structure.

<XR>PDUPoPr  Position Part<T>

<ETP>
<TP>placeOpt
:Placement Options Form:
The Placement Options<T> form appears when you select the
Placement Options<T> button from the Part Selection<T> form and
lets you determine how a part will be placed.  This form will
be different for graphic parts and parametric parts.  The
settings on this form will be saved from the last setting used in
the design setting.

<S>Form Fields ---<T>

<S>Positioned by Field<T>

This field appears only when placing graphic parts and
displays how the part will be placed.  Graphic parts can be
placed by:

1.   view alignment

2.   three points

3.   coordinate system

<S>Usage ID Field<T>

This field appears only when placing graphic parts and
displays the usage id for the part.  A unique usage id is
generated by default.

<S>Include in Structure Field<T>

This field indicates whether to include the part in an
assembly structure.  If you place a data point in the field to
place a checkmark in the field, the part will be included in the
structure.  The system checks the value of this field at
placement and replacement time.  If you want the part
included in the structure, you must enter a data point in the
field before executing either of these commands.

<S>Include in BOM Field<T>

This field indicates whether to include the part in the BOM.  If
you enter a data point in the field, the part will be included in
a BOM.  The system checks the value of this field at
placement and replacement time. If you want the part
included in a BOM, you must enter a data point in the field
before executing either of these commands.

<S>Explode Part Field<T>

This field indicates if you wish to explode the part in a BOM.
Exploding the part shows the subassemblies that make up the
part.  If you enter a data point in the field, the part will be
exploded in a BOM.  The system checks the value of this field
at placement and replacement time. If you want the part
exploded in a BOM, you must enter a data point in the field
before executing  either of these commands.

<S>Depth Field<T>

This field contains the level to which the assembly is to be
exploded. The default is set to the maximum level of the
assembly.

<S>Attach Part Field<T>

This field indicates if the part model file is to be attached as a
reference file at part placement time.  If you enter a data
point in the field, the part is attached after it is placed.

<S>Display Dynamic Attribute Form Field<T>

This field indicates if the Dynamic Attribute<T> form is displayed
at placement and replacement time.  If you enter a data point
in the field, the Dynamic Attribute<T> form will be displayed.

<S>Placement Type Field<T>

This field appears only when placing parametric parts and
indicates the type of placement.  The possible values are:

1.   construction

2.   symbol

3.   drop

<S>Usage ID Field<T>

This field appears only when placing graphic parts and
displays the usage id for the part.  A unique usage id is
generated by default.

<S>Include in Structure Field<T>

This field indicates whether to include the part in an
assembly structure.  If you place a data point in the field to
place a checkmark in the field, the part will be included in the
structure.  The system checks the value of this field at
placement and replacement time.  If you want the part
included in the structure, you must enter a data point in the
field before executing either of these commands.

<S>Include in BOM Field<T>

This field indicates whether to include the part in the BOM.  If
you enter a data point in the field, the part will be included in
a BOM.  The system checks the value of this field at
placement and replacement time. If you want the part
included in a BOM, you must enter a data point in the field
before executing either of these commands.

<S>Explode Part Field<T>

This field indicates if you wish to explode the part in a BOM.
Exploding the part shows the subassemblies that make up the
part.  If you enter a data point in the field, the part will be
exploded in a BOM.  The system checks the value of this field
at placement and replacement time. If you want the part
exploded in a BOM, you must enter a data point in the field
before executing  either of these commands.

<S>Depth Field<T>

This field contains the level to which the assembly is to be
exploded. The default is set to the maximum level of the
assembly.

<S>Display Dynamic Attribute Form Field<T>

This field indicates if the Dynamic Attribute<T> form is displayed
at placement and replacement time.  If you enter a data point
in the field, the Dynamic Attribute<T> form will be displayed.

<S>Automatic Part Selection Field<T>

This field lets you automatically select parts while creating a
parametric assembly.

<S>Default Layer Toggle<T>

This toggle indicates whether the part will use the Active<T> or
Default<T> layer.  The system defaults to the Default<T> layer.

<S>Default Color Toggle<T>

This toggle indicates whether the part will use the Active<T> or
Default<T> color.  The system defaults to the Default<T> color.

<S>Default Style Toggle<T>

This toggle indicates whether the part will use the Active<T> or
Default<T> style.  The system defaults to the Default<T> style.

<S>Default Weight Toggle<T>

This toggle indicates whether the part will use the Active<T> or
Default<T> weight.  The system defaults to the Default<T> weight.

<ETP>
<TP>topdown
:Identify Part Form:
The Identify Part<T> is displayed during the execution sequence
of a topdown assembly design.  Before identifying graphics in
the active file that need to be saved as a part, this form lets
you specify a part that already exists in the database with
which the saved graphics will be associated.

<S>Note:<T>

The fields of this form behave like the Part Selection<T> fields in
existing part mode of the Part Operations<T> form. <F> „<T>

<S>Form Fields ---<T>

<S>Catalog Field<T>

This field lets you key in or select an existing catalog.  You
can use the List<T> button beside this field to view a complete list
of catalogs.

<S>Part Number Field<T>

This field lets you key in or select an existing part.  You can
use the List<T> button beside this field to view a complete list of
existing parts.

<S>Revision Field<T>

The field lets you key in or select an existing revision of a
part.  You can use the List<T> button beside this field to view a
complete list of revisions for the existing part.

<S>Filename Field<T>

This field lets you key in or select an existing filename for a
part.  You can use the List<T> button beside this field to view a
complete list of filenames for the existing part.

<S>Description Field<T>

This field contains the description for the existing part.

<S>Search Button<T>

This button invokes the Part Selection<T> form.

<ETP>
<TP>Dynamic
:Dynamic Attribute Information Form:
The Dynamic Attribute Information<T> form lets you assign values
for dynamic attributes during the Place Part<T> and Replace Part<T>
commands. The form is displayed depending on the Display
Dynamic Attribute Form<T> toggle on the Placement Options<T> form
during Place Part<T> or Replace Part<T>.

<S>Form Fields ---<T>

<S>View Name Field<T>

This field lets you enter a view name or select a view name
from a list.  If there are no views associated with this part,
then the field is not displayed.  You can use the List<T> button
next to this field to display a complete list of view names for
the part.

<S>Quantity Field<T>

This field lets you enter the quantity of the part being placed.
The default is 1<T>.

<S>Usage Id Field<T>

This field lets you specify a usage_id for the part.  The
usage_id is displayed on the part pointer.  A unique usage_id
is generated by default.  The default is <catalog> <part>
<revision> <instance#>.

<S>Tag Number Field<T>

This field lets you see the tag number for the part.  This field is
read only and is automatically generated.

<S>Alt Tag Number Field<T>

This field lets you give an alternate tag number for the part.
The field is not defaulted, but the entered alternate tag
number is checked for uniqueness.  For more information on
alternate tag numbers see Assemblies<T> in this document.

<S>User-Defined Attributes Field<T>

This field lets you give values for any user-defined dynamic
attributes for this part.  If there are no user-defined dynamic
attributes associated with this part, the field is not displayed.
Attributes that are prefixed by an * indicates that there is a
list of possible values for the attribute. You can view this list
by tapping the attribute name with the mouse button.  All
values entered are validated according to datatype.

<ETP>
<TP>define_assy
:Define/Modify Assembly Structure:
The Define/Modify Assembly Structure<T> form appears when
you select the Assembly Structure<T> button from the PDM/PDU<T>
form and lets you define and modify non-graphic assembly
structures.

<S>Form Fields ---<T>

<S>Assembly Selection Palette<T>

This palette contains information about the current assembly.

<S>Project Field<T>

The field displays the project containing the assembly if the
assembly is mapped to a project.  You can use the List<T> button
next to this field to display a complete list of projects.  If a
catalog name is entered before a project name is keyed in, the
system will check to see if the catalog is mapped to the
project name that is entered.  If the catalog is not mapped to
the project, the system will display an error.  If a catalog is
entered when the list button next to the Project<T> field is
selected, the system will list any projects to which the
catalog is mapped.  If the catalog is not mapped to any
projects, an error message will appear.

<S>Catalog Field<T>

This field displays the name of the catalog containing the
active part. You can use the List<T> button beside this field to
view a complete list of catalogs.  If you are using catalog
classifications, the List<T> button displays a list of valid
classifications.  You can select the appropriate classification
to display a list of catalogs within the classification.

<S>Part Number Field<T>

This field displays the part number of the assembly part being
worked on.

<S>Revision Field<T>

This field displays the revision for the part number being
worked on.

<S>Description Field<T>

This field displays the description for the assembly being
worked on.  This field is read-only.

<S>Part Selection Palette<T>

This palette contains information about the parts being added
to the assembly.

<S>Key in Part/Select from List Toggle<T>

If the toggle is set to Key in Part<T> you can key in the part name
to be added to the structure.  If the toggle is set to Select from
List<T>, a list of parts to select from appears.

<S>Catalog Field<T>

This field contains the catalog for the part being added to the
assembly.

<S>Part Number Field<T>

This field contains the part number for the part being added to
the assembly.

<S>Revision Field<T>

This field contains the revision for the part being added to the
assembly.

<S>Description Field<T>

This field contains the description for the part being added to
the assembly.

<S>Assembly Structure Palette<T>

This palette displays the assembly structure of the assembly
in the Assembly Selection<T> area.

<S>Delete Button<T>

This button lets you delete a part from the assembly.  You
must highlight the part in the assembly structure to be
deleted and select the Delete<T> button to delete the part.

<S>Search Button<T>

This button invokes the Part Selection<T> form and sets the Key
in Part/Select From List<T> toggle to Select From List<T>.  The search
returns a list of parts from which the assembly can be
created.

<S>Place Button<T>

This button lets you place a part in the assembly without
bringing the assembly up in a design file.  The part to be
placed must be displayed in the Part Selection<T> fields.

<S>Placement Options Button<T>

This button invokes the Placement Options<T> form.

<ETP>
<TP>report_form
:Reports Form:
The Reports<T> form appears when you select the Reports<T> button
on the PDM/PDU<T> form and gives access to the commands
associated with reports.  This form can also be accessed
through several of the I/PDM-PDU forms.

<S>Form Fields ---<T>

<S>Mode Selection Palette<T>

This palette contains buttons that indicate the type of report.

<S>BOM Button<T>

This button is the default active button when you enter the
form.  This button also lets you create a BOM report that
displays the bill of materials for the assembly.

<S>Exploded BOM Button<T>

This button lets you create an Exploded Bill of Material.  This
report shows the exploded assembly structure.

<S>Summary Atomic Parts Button<T>

This button lets you create a Summary of Atomic Parts report,
which shows the atomic parts in an assembly.

<S>Parts List Button<T>

This button lets you create a report that lists the parts in an
assembly.

<S>Parts in Catalog Button<T>

This button lets you create a report that lists the parts in a
catalog.

<S>Catalogs in Database Button<T>

This button lets you create a report that lists the catalogs in a
database.

<S>Where Used Immediate Button<T>

This button lets you create a report that lists where the
specified part is used immediately.

<S>Where Used Highest Lvl Button<T>

This button lets you create a report that lists where the
specified part is used at the highest level.

<S>Report Format Name Field<T>

This field contains the name of the current report format for
the type of report being created.  You can use the List<T> button
next to this field to display a complete list of formats for the
type of report being created.

<S>Add Button<T>

This button lets you add a new report format.  Before
selecting this button, enter the name for the format in the
Report Format Name<T> field.

<XR>PDDfBOLsFr Define BOM List Format<T>
<XR>PDDfBOPrLs Define Parts List Format<T>
<XR>PDDfCtLsFr Define Catalog In Database List Format<T>
<XR>PDDfWhUsAs Define Where Used Immediate List Format<T>
<XR>PDDfWhUsHL Define Where Used at Highest Level List Format<T>

<S>Modify Button<T>

This button lets you modify an existing report format.  Before
selecting this button, enter the name for the format in the
Report Format Name<T> field.

<S>Delete Button<T>

This button lets you delete an existing report format.  Before
selecting this button, enter the name for the format in the
Report Format Name<T> field.

<XR>PDDlBOLsFr Delete BOM List Format<T>
<XR>PDDlBOPrLs Delete Parts List Format<T>
<XR>PDDlCtLsFr Delete Catalog In Database List Format<T>
<XR>PDDlWhUsAs Delete Where Used Immediate List Format<T>
<XR>PDDlWhUsHL Delete Where Used at Highest Level List Format<T>

<S>Import RIS Button<T>

This button lets you import an existing RIS report template.

<S>Part Selection Palette<T>

This palette contains information about the parts being added
to the report.

<S>Part Selection/Existing BOM Selection Toggle<T>

This toggle lets you create a BOM from parts selected from a
list or from an existing BOM.  If the toggle is set to Part
Selection<T>, you can enter information about the part or
catalog to be used in the report in the fields displayed below
this toggle.  If the toggle is set to Existing BOM Selection<T>, a
list displaying information about an existing BOM appears
below the toggle.  From the list, you can select the
information used in the report.

<S>Catalog Field<T>

This field displays the catalog being used in the report
generation. You can use the List<T> button next to this field to see
a complete list of catalogs.

<S>Part Number Field<T>

This field displays the part number being used in the report
generation. You can use the List<T> button next to this field to see
a complete list of parts found in the catalog displayed in the
Catalog<T> field.

<S>Revision Field<T>

This field displays the revision for the part displayed in the
Part Number<T> field.  You can use the List<T> button next to this
field to see a complete list of revisions for the displayed part.

<S>Description Field<T>

This field displays the description for the part appearing in the
Part Number<T> field.

<S>Search Button<T>

This button invokes the Part Selection<T> form.

<S>Print Options Palette<T>

This palette lets you define a print format for the report.

<S>Don't Save To File/Save To File Toggle<T>

Setting the toggle to Save to File<T> displays the Output Filename<T>
that lets you enter a file name for storing the report in ASCII
format.

<S>Output Filename Field<T>

This field contains the filename containing the print format
for the report.

<S>Create Button<T>

This button lets you create a report based on the list format
appearing in the Report Format Name<T> field and the part
displayed in the Part Selection<T> palette.

<XR>PDCrBOPrLs Create Parts List<T>
<XR>PDCrBOSmPr Create Summary Atomic Parts<T>
<XR>PDCrWhUsAs Create BOM Where Used Immediate<T>
<XR>PDCrWhUsHL Create BOM Where Used at Highest Level<T>

<S>Display Existing Report Button<T>

This button becomes active when the Don't Save To File/Save
To File<T> toggle is set to Save To File<T> and lets you display the
report found in the Output Filename<T> field to the screen.

<S>BOM Mapping Button<T>

This button invokes the BOM Contents/Mapping<T> form and lets
you map attributes for the report.

<ETP>
<TP>reportgen
:Define Report Format Form:
This form appears when you select the Add<T> button on the
Reports<T> form and lets you define the report format.

<S>Note:<T>

The form defaults with the Insert<T> button on which lets you
add attributes to the format. <F> „<T>

<S>Form Fields ---<T>

<S>Insert Button<T>

This button lets you enter an attribute on the format line.

<S>Delete Button<T>

This button lets you delete input from the format line.

<S>Replace Button<T>

This button lets you replace input on the format line.

<S>Column Definition Palette<T>

This palette lets you create and change the column headings
of the report.

<S>Column Header Field<T>

This field contains the column headings for the report.  The
value defaults to the synonym for the attribute, but a new
value can be keyed in.

<S>Attribute Field<T>

This field contains the attribute synonym for the attribute in
the database.  You can key in this value or select from a list
that appears when you select the List<T> button next to the field.

<S>Format Field<T>

This field lets you key in the number of decimal places for a
decimal valued attribute.

<S>Justification Buttons<T>

These button let you set the justification for the column to
Left, Center,<T> or Right<T>.  The default is Left<T>.

<S>Selected Field Width Slide<T>

This slide lets you set the field width.  The value defaults to
the datatype value.  You can also key in the field width in the
field to the left of the slider.

<S>Column Options<T>

These toggles let you perform options on the columns of the
report.

<S>Don't Sort On Attribute/Sort On Attribute Toggle<T>

This toggle lets you sort the report based on attributes.

<S>Subtotal Toggle<T>

This button lets you subtotal a column on the report.  The
default is No<T>.

<S>Total Toggle<T>

This button lets you total a column on the report.  The default
is No<T>.

<S>Report Options Palette<T>

This palette lets you specify the width and length of the
report.

<S>Report Width Field<T>

This field displays the width of the report.

<S>Report Length Field<T>

This field displays the length of the report.

<S>Template Library Field<T>

This field lets you enter the name of an existing format to be
used.

<ETP>
<TP>bom_contents
:BOM Contents/Mapping Form:
The BOM Contents/Mapping<T> form appears when you select
the BOM Mapping<T> button on the Reports<T> form and lets you
map user-defined attributes to BOM attributes or change to
existing attributes.  The system automatically maps BOM
attributes to catalogs with the same name.  This form lets you
map those attributes that are not automatically mapped and
to add new BOM attributes.

<S>Form Fields ---<T>

<S>BOM Attribute Field<T>

This field displays the attribute names for the BOM.  The
maximum attribute size is 40 characters (A-Z, 0-9, or
underbar) and must start with a lowercase letter.  The
attribute name cannot have an underbar(_) as the second
character.

<S>Data Type Field<T>

This field displays the data type for the BOM attribute.

<S>Synonym Field<T>

This field displays the synonym for the BOM attribute.  The
synonym is the name that appears on the BOM.  The synonym
may contain spaces and uppercase letters.  The maximum
size for a synonym is 40 characters, although only 26
characters are displayed in the form.

<S>Mapping Palette<T>

This palette displays the catalog attribute that is be mapped
to the BOM attribute.  You can map the BOM attributes by
entering the information in the fields of this palette and
selecting the Map Attribute<T> button.

<S>BOM Attribute Field<T>

This field displays the BOM attribute to be mapped.  You can
use the List<T> button next to this field to display a complete list
of BOM attributes.

<S>Catalog Name Field<T>

This field displays the current catalog.  You can use the List<T>
button beside this field to view a complete list of catalogs.  If
you are using catalog classifications, the List<T> button displays
a list of valid classifications.  You can select the appropriate
classification to display a list of catalogs within the
classification.

<S>Catalog Attribute Field<T>

This field displays the catalog attribute to be mapped.  You
can use the List<T> button next to this field to display a complete
list of attributes contained in the catalog displayed in the
Catalog<T> field.

<S>Map Attribute Button<T>

This button maps the BOM attribute to the corresponding
catalog attribute.  The information in the Mapping<T> palette
must be complete before the Map Attribute<T> button is selected.

<S>Attribute Information Palette<T>

This palette displays information about the BOM attribute to
be added. You can add BOM attributes by entering information
in the fields of this palette and selecting the Add Attribute<T>
button.

<S>BOM Attribute Field<T>

This field displays the BOM attribute being added.

<S>Data Type Field<T>

This field displays the data type of the BOM attribute being
mapped.

<S>Synonym Field<T>

This field displays the synonym of the BOM attribute being
mapped.

<S>Add Attribute Button<T>

This button adds attributes to the BOM.  You must enter
information in the fields of this palette before selecting the
Add Attribute<T> button.

<ETP>
