<TP>PDRpPr
:Replace Part:
This command lets you replace or edit one or all occurrences
of a part in the active design file.  Edit Part<T> lets you change or
add dynamic attribute values to the previously placed part.

<S>Before Using This Command<T>

An assembly part is retrieved and open for design.

<S>Operating Sequence --- Replace Part<T>

1.   Select the Replace Part<T> button on the Design Operations<T>
     form.

     Identify Part...or move-on for list<T>

2.   Place a data point on the part to replace.

                                              OR

     Select the right mouse button to select a part from
           the List of Parts<T> form and select the Save and Exit<T>
     button.

     The Part Selection<T> form appears.

3.   Use the Part Selection<T> form to search for the part to be
     used as the replacement part.  For more information, see
     the Define Search Criteria<T> command.

4.   Set the Replace All/Replace One<T> toggle to Replace All<T> to
     replace all occurrence of the part.

                                              OR

     Set the Replace All/Replace One<T> toggle to Replace
           One<T> to only replace the one selected occurrence of the
     part.

5.   Save and exit the Part Selection<T> form and save the
     changes.

<S>Note:<T>

     If the part has multiple views, a form will display the list of
     views for the part.  You can highlight the view that should
     be replaced. <F>„<T>

     The part is replaced and the Design Operations<T> form
     reappears.

<S>Operating Sequence --- Edit Part<T>

1.   Select the Replace Part<T> button on the Design Operations<T>
     form.

     Identify Part...or move-on for list<T>

2.   Place a data point on the part to replace.

                                              OR

     Select the right mouse button to select a part from
           the List of Parts<T> form and select the Save and Exit<T>
     button.

     The Part Selection<T> form appears.

3.   Set the Static Attr/Dynamic Attr<T> toggle to Dynamic Attr<T>.

     A list of dynamic attributes is displayed on the form.

4.   Change or add values to the desired dynamic attributes.

5.   Save and exit the Part Selection<T> form.

     The Design Operations<T> form is redisplayed.


<ETP>
<TP>PDChOtAcPr
:Retrieve for Design:
This command retrieves a file from its storage location and
opens it for design.

<S>Before Using This Command<T>

The name of the part to be checked out and opened for design
must appear in the Part Selection<T> area of the PDM/PDU<T> form.
This can be done by key-in or by selecting the part from a list.
A list can be generated by selecting the List<T> button next to the
Part Number<T> field of by selecting the List of Parts<T> button on
the PDM/PDU<T> form or highlighting the part in the List of
Parts/Files<T> palette on the PDM/PDU<T> form.

<S>Operating Sequence<T>

1.   Select the Retrieve for Design<T> button from the File
     Operations<T> palette on the PDM/PDU<T> form.

     The part's graphic file and all attached reference files are
     sent form the storage location to the workstation and
     opened for design.  The Design Operations<T> form is
     displayed.

<S>Note:<T>

     If you select several parts to retrieve, a form appears after
     all files are local.  You can select which part you want to
     open for design.  If you do not want to select a file, you can
     dismiss the form. <F>„<T>


<ETP>
<TP>PDCpFlTLc
:Retrieve for Review:
This command lets you copy a file or a list of files to your
workstation any time after the initial checkin of that file.

There are several situations for which you could use this
command.  You might simply want to review a file without
any intentions of modifying it.  You could use this command to
copy the file to your workstation and view its graphics.
Because you did not check it out, there is no need for you to
check it back in.  As a matter of fact, you cannot<T> check it in
without creating new part information for it.

<S>Before Using This Command<T>

I/PDM lets you copy a single file or a list of files locally.  If you
want to copy a single file local, the name of the part you want
to copy must appear in the Part Selection<T> palette of the
PDM/PDU<T> form.  If you want to copy a list of files locally, the
files must appear in the List of Parts/Files<T> palette or selected
form the List of Parts/Files<T> palette on the PDM/PDU<T> form.

The file to be copied may or may not be local to the user's
storage area.  I/PDM takes appropriate steps depending on
the file's location.  If the file to be copied is not local, the file
is copied to the local storage area.  If the file is local to the
user's storage area, I/PDM compares version of the file to the
version stored on the server.

<S>Operating Sequence<T>

1.   Enter the part information for the file to be copied local in
     the Part Selection<T> palette of the PDM/PDU<T> form by key-in or
     from a list of files.  If you want to copy more than one file
     locally, highlight those files.

2.   Select the Retrieve for Review<T> button on the File
     Operations<T> palette of the PDM/PDU<T> form.

     The part's graphic file is copied to the local workstation
     and the Part Listing<T> form is displayed.

3.   Select the part from the list that you want to retrieve for
     review.

     The read-only file is brought into design and the Design
     Operations<T> form is displayed.


<ETP>
