[
n_catalogname(char[12])=exjoin
n_catalogdesc(char[100])=I/VDS Parametric Catalog
n_cofilename(char[14])=VRmacro
p_s1|units_set(smallint)=units_set
p_o2|cp0(macro)=cp0
p_o3|cp1(macro)=cp1
p_d4|ref(referential)=ref
p_s5|ff(double)=ff
p_s7|d1(double)=d1
p_s8|b1(double)=b1
p_s9|f1(double)=f1
p_u0|n_itemname(char[32])=Part Number
p_u0|n_itemrev(char[15])=Part Revision
p_u0|n_itemdesc(char[40])=Part Description
p_u0|n_creator(char[14])=CREATED BY
p_u0|n_creationdate(char[10])=Part Creation Date
p_u0|p_parttype(char[1])=Part Type
p_u0|dry_wt(double)=dry_wt
p_u0|wet_wt(double)=wet_wt
p_u0|oper_wt(double)=oper_wt
p_u0|cog_x(double)=cog_x
p_u0|cog_y(double)=cog_y
p_u0|cog_z(double)=cog_z
p_u0|opcog_x(double)=opcog_x
p_u0|opcog_y(double)=opcog_y
p_u0|opcog_z(double)=opcog_z
p_u0|surf_area(double)=surf_area
p_f0|n_cofilename(char[14])=Local File Name
]
