# $Id: makefile,v 1.1.1.1 2001/01/04 21:13:06 cvs Exp $

# -------------------------------------------------------------------
# I/ROUTE
#
# File:		vrris/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:13:06  cvs
#	Initial import to CVS
#	
# Revision 1.1  1996/03/06  18:24:54  pinnacle
# Created: vrris/makefile by azuurhou for route240
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	03/06/96	adz		make system dependent makefiles.
#
# -------------------------------------------------------------------

target:
	grmake -rkf make_"`uname -s`"
