# Do not alter this SPC information: $Revision: 1.43.3.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt
!include setupenv.nt

share: test cleanall remove_dir remsc_dir interop_dir csource_dir bldcui_dir local_copy gen_lyt local_copy_setup gen_inf

share_noclean: test remove_dir remsc_dir interop_dir csource_dir bldcui_dir local_copy gen_lyt local_copy_setup gen_inf

utility: test gen_lyt local_copy_setup gen_inf

remove_dir:
	@echo.
	@echo	Making $@ files ...
	@cd $(RIS_REMOVE_DIR)
	@mk
	@cd $(RIS_SETUP_DIR)
	@echo	Finished making $@ files

remsc_dir:
	@echo.
	@echo	Making $@ files ...
	@cd $(RIS_REMSC_DIR)
	@mk
	@cd $(RIS_SETUP_DIR)
	@echo	Finished making $@ files

interop_dir:
	@echo.
	@echo	Making $@ files ...
	@cd $(RIS_INTEROP_DIR)
	@mk
	@cd $(RIS_SETUP_DIR)
	@echo	Finished making $@ files

csource_dir:
	@echo.
	@echo	Making $@ setup files ...
	@cd $(RIS_CSOURCE_DIR)
	@mk 
	@cd $(RIS_SETUP_DIR)
	@echo	Finished making $@ files

bldcui_dir:
	@echo.
	@echo	Making $@ setup files ...
	@cd $(RIS_BLDCUI_DIR)
	@mk 
	@cd $(RIS_SETUP_DIR)
	@echo	Finished making $@ files

local_copy:
	@echo.
	@-mkdir	$(PROD_SHARE_DIR)
	@-mkdir	$(PROD_SHARE_DIR)\shared
	@-mkdir	$(RIS_PROD_SHARE_DIR)
	@-mkdir	$(RIS_PROD_SHARE_DIR)\bin
	@-mkdir	$(RIS_PROD_SHARE_DIR)\lib
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\forms
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\help
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\messages
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\messages\src
	@echo Deleting all files under $(PROD_SHARE_DIR) ...
	@del /s /q $(PROD_SHARE_DIR)\*.*

	@echo Substituting macros in files.
#Share component layout file
	@perl -p -e "s/!maj_min!/$(RIS_MAJ).$(RIS_MIN)/g" \
		csource\rissetup.lyt > $(RIS_PROD_SHARE_DIR)\rissetup.lyt
	@perl -p -e "s/!maj_min!/$(RIS_MAJ).$(RIS_MIN)/g;s/!PRODINDEX!/003168/g" \
		csource\rispack.lyt > $(RIS_PROD_SHARE_DIR)\rispack.lyt
	@perl -p -e "s/!maj_min!/$(RIS_MAJ).$(RIS_MIN)/g" \
		manifest.txt > $(RIS_PROD_SHARE_DIR)\manifes1.txt

	@echo Executing perl scripts.
	@set RIS_PROD_SHARE_DIR=$(RIS_PROD_SHARE_DIR)
#	@perl readme.pl       # edits the readme.txt file adding version and date
        @perl makeprod.pl RISCLI
	@echo Copying files.
	@copy bin\$(BINDIR)\rissetup.lib \
		$(RIS_PROD_SHARE_DIR)\rissetup.lib
	@copy csource\rissetup.h \
		$(RIS_PROD_SHARE_DIR)\rissetup.h
	@copy bin\$(BINDIR)\risrem.lib \
		$(RIS_PROD_SHARE_DIR)\risrem.lib
	@copy remove\risrem.h \
		$(RIS_PROD_SHARE_DIR)\risrem.h

	@copy extdlls\i9shamr1.dll $(PROD_SHARE_DIR)\shared
	@copy $(SHAMROCKDIR)\shared\i9shamr2.dll $(PROD_SHARE_DIR)\shared

	@copy extdlls\i9ums1.dll $(PROD_SHARE_DIR)\shared
	@copy $(UMSDIR)\shared\i9ums2.dll $(PROD_SHARE_DIR)\shared
	@copy $(RISDEVDIR)\risums\nt\lib\nt\i9risu.dll $(PROD_SHARE_DIR)\shared

	@copy $(RISDEVDIR)\riscli\doc\keyword.doc \
		$(RIS_PROD_SHARE_DIR)\config\english\help\keyword.doc

	@copy $(RISDEVDIR)\riscli\doc\rissql.hlp \
		$(RIS_PROD_SHARE_DIR)\config\english\help\rissql.hlp
	@copy $(RISDEVDIR)\riscli\doc\rissql.ind \
		$(RIS_PROD_SHARE_DIR)\config\english\help\rissql.ind

	@copy $(RISDEVDIR)\riscli\doc\ftengine.dll \
		$(RIS_PROD_SHARE_DIR)\config\english\help\ftengine.dll
	@copy $(RISDEVDIR)\riscli\doc\ftui.dll \
		$(RIS_PROD_SHARE_DIR)\config\english\help\ftui.dll
	@copy $(RISDEVDIR)\riscli\doc\mvapi.dll \
		$(RIS_PROD_SHARE_DIR)\config\english\help\mvapi.dll

	@copy $(RISDEVDIR)\risutl\config\english\help\risutl.hlp \
		$(RIS_PROD_SHARE_DIR)\config\english\help\risutl.hlp
	@copy $(RISDEVDIR)\risutl\config\english\help\risutl.ind \
		$(RIS_PROD_SHARE_DIR)\config\english\help\risutl.ind

	@copy $(RISDEVDIR)\risutl\config\english\help\rislist.hlp \
		$(RIS_PROD_SHARE_DIR)\config\english\help\rislist.hlp

	@copy $(RISDEVDIR)\riscli\setup32\bin\$(BINDIR)\risintop.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risintop.exe

	@copy $(RISDEVDIR)\riscli\bin\$(BINDIR)\riscli.exe \
		$(RIS_PROD_SHARE_DIR)\bin\riscli.exe

	@copy $(RISDEVDIR)\riscli\bin\$(BINDIR)\risupgrd.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risupgrd.exe

	@copy $(RISDEVDIR)\riscom\bin\$(BINDIR)\ristcpsr.exe \
		$(RIS_PROD_SHARE_DIR)\bin\ristcpsr.exe

	@copy $(VC20_DIR)\msvcrt20.dll \
		$(RIS_PROD_SHARE_DIR)\lib\msvcrt20.dll

	@copy $(VC20_DIR)\ctl3d32.dll \
		$(RIS_PROD_SHARE_DIR)\lib\ctl3d32.dll

	@copy $(RISDEVDIR)\riscli\ntextlib\I9ris.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9ris.dll

	@copy $(RISDEVDIR)\riscli\ntextlib\I9risfm.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9risfm.dll

	@copy $(RISDEVDIR)\riscli\ntextlib\I9rislu.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9rislu.dll


	@copy $(RISDEVDIR)\riscli\ntextlib\I9ris5.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9ris5.dll

	@copy $(RISDEVDIR)\riscli\ntextlib\I9risfm5.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9risfm5.dll

	@copy $(RISDEVDIR)\riscli\ntextlib\I9rislu5.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9rislu5.dll


	@copy $(RISDEVDIR)\risapp\lib\$(BINDIR)\I9ris6.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9ris6.dll

	@copy $(RISDEVDIR)\risutl\lib\$(BINDIR)\I9risfm6.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9risfm6.dll

	@copy $(RISDEVDIR)\risutl\lib\$(BINDIR)\I9rislu6.dll \
		$(RIS_PROD_SHARE_DIR)\lib\I9rislu6.dll

	@copy $(RISDEVDIR)\risutl\resource\risicon.dll $(RIS_PROD_SHARE_DIR)\lib

	@copy $(RISDEVDIR)\riscom\config\langs \
		$(RIS_PROD_SHARE_DIR)\config\langs

	@copy $(RISDEVDIR)\riscom\config\english\messages\net.txt \
		$(RIS_PROD_SHARE_DIR)\config\english\messages\src\net.txt

	@copy $(RISDEVDIR)\riscom\config\english\messages\ris.txt \
		$(RIS_PROD_SHARE_DIR)\config\english\messages\src\ris.txt

	@copy $(RISDEVDIR)\risutl\config\english\messages\utl.txt \
		$(RIS_PROD_SHARE_DIR)\config\english\messages\src\utl.txt

	@copy $(RISDEVDIR)\riscom\config\english\messages\net.msg \
		$(RIS_PROD_SHARE_DIR)\config\english\messages\net.msg

	@copy $(RISDEVDIR)\riscom\config\english\messages\ris.msg \
		$(RIS_PROD_SHARE_DIR)\config\english\messages\ris.msg

	@copy $(RISDEVDIR)\risutl\config\english\messages\utl.msg \
		$(RIS_PROD_SHARE_DIR)\config\english\messages\utl.msg

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risalsch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risalsc4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risaltab.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risalta4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\riscrsch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\riscrsc4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\riscrtab.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\riscrta4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risdadef.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risdade4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risdb2pa.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risdb2p4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risdbs.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risdb4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risdebug.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risdebu4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risdrsch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risdrsc4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risdrtab.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risdrta4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgabou.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgabo4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgi4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgopts.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgopt4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgparm.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgpar4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgpswd.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgpsw4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgset.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgse4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgshow.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgsho4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgshtr.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgsht4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgsrch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgsrc4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgtran.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgtra4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risgutls.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risgutl4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risinex.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risine4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\rislocli.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\rislocl4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risnodin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risnodi4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risschfl.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risschf4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risschin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risschi4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risschmg.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risschm4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risschpa.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risschp4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\risset.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\risse4.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION4)\ristabin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\ristabi4.frm



	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risaltab.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risaltab.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\riscrsch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\riscrsch.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\riscrtab.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\riscrtab.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdadef.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdadef.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdb2pa.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdb2pa.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdbs.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdbs.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdebug.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdebug.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdicac.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdicac.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdrsch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdrsch.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risdrtab.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risdrtab.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risexcl.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risexcl.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgabou.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgabou.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgin.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgopts.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgopts.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgparm.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgparm.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgpswd.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgpswd.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgset.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgset.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgshow.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgshow.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgshtr.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgshtr.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgsrch.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgsrch.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgtran.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgtran.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risguspw.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risguspw.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risgutls.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risgutls.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risincl.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risincl.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\rislocli.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\rislocli.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risnodin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risnodin.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risosusr.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risosusr.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risschac.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risschac.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risschdf.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risschdf.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risschfl.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risschfl.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risschin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risschin.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risschmg.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risschmg.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risschpa.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risschpa.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\risset.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\risset.frm

	@copy $(RISDEVDIR)\risutl\config\english\forms\$(BINDIR)\$(RIS_FORMS_VERSION)\ristabin.frm \
		$(RIS_PROD_SHARE_DIR)\config\english\forms\$(RIS_FORMS_VERSION)\ristabin.frm

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risgui.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risgui.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risbatch.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risbatch.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risclnsr.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risclnsr.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risdcode.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risdcode.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risdtype.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risdtype.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\rislod.exe \
		$(RIS_PROD_SHARE_DIR)\bin\rislod.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\rliclist.exe \
		$(RIS_PROD_SHARE_DIR)\bin\rliclist.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\rismgr.exe \
		$(RIS_PROD_SHARE_DIR)\bin\rismgr.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risplbck.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risplbck.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risrecrd.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risrecrd.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risrun.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risrun.exe

	@copy $(RISDEVDIR)\risutl\bin\$(BINDIR)\risunlod.exe \
		$(RIS_PROD_SHARE_DIR)\bin\risunlod.exe


gen_lyt:
	@-mkdir	$(RIS_SETUP_DIR)\compress
	@del /s/q $(LOCAL_DIR)
	@copy $(RIS_SETUP_DIR)\bin\$(BINDIR)\remove.exe  $(RIS_PROD_SHARE_DIR)\bin
	@copy $(RIS_SETUP_DIR)\32ssetup.txt  $(RIS_PROD_SHARE_DIR)
	@echo.
	@echo	Making risshare.lyt file in $(LOCAL_DIR) ...
	@echo HEADER> risshare.lyt
	@echo SRC = $(PROD_SHARE_DIR)>> risshare.lyt
	@echo WRITEABLE = 0 >> risshare.lyt
        @echo DISKLABEL = FILES >> risshare.lyt
	@echo FILES>> risshare.lyt
	@perl -p -e "s/!maj_min!/$(RIS_MAJ).$(RIS_MIN)/g;s/!maj-min!/$(RIS_MAJ)$(RIS_MIN)/g" \
		csource\locfiles.lyt >> risshare.lyt
#	@type csource\locfiles.lyt  >> risshare.lyt
	@type $(RIS_PROD_SHARE_DIR)\rissetup.lyt  >> risshare.lyt
	@echo REMOVE>> risshare.lyt
	@echo	Finished making risshare.lyt file in $(LOCAL_DIR)

local_copy_setup: $(COPY_SETUP_FILES)
	@!copy $** $(PROD_SHARE_DIR)

gen_inf:
	@cd ris
#	@-"$(NT_SETUP_DIR)\setup32\disklay\dsklayt2" ..\risshare.lyt $(LOCAL_DISK1_DIR)\risshare.inf /kN /f /v /cC:\tmp\deliv /d$(LOCAL_DIR)
#	@-"$(NT_SETUP_DIR)\setup32\disklay\dsklayt2" ..\risshare.lyt $(LOCAL_DISK1_DIR)\risshare.inf /k144 /f /v /c$(RIS_SETUP_DIR)\compress /d$(LOCAL_DIR) /w1
	@-dsklayt2 ..\risshare.lyt $(LOCAL_DISK1_DIR)\risshare.inf /f /c$(RIS_SETUP_DIR)\compress /d$(LOCAL_DIR) /w1
	@cd $(RIS_SETUP_DIR)
	@set RIS_SETUP_DIR=$(RIS_SETUP_DIR)
	@set RIS_PROD_SHARE_DIR=$(RIS_PROD_SHARE_DIR)
	@set LOCAL_DIR=$(LOCAL_DIR)
	@perl diskidrp.pl        # disk id replace
	@del /Q risshare.lyt 2>NUL

cleanall: mksubdirs cleanobjs cleanbin cleansetup

mksubdirs:
	@echo Making subdirs
	@-mkdir $(RIS_REMOVE_DIR)\$(OBJDIR)
	@-mkdir $(RIS_CSOURCE_DIR)\$(OBJDIR)
	@-mkdir $(RIS_BLDCUI_DIR)\$(OBJDIR)
        @-mkdir $(RIS_REMSC_DIR)\$(OBJDIR)
        @-mkdir $(RIS_INTEROP_DIR)\$(OBJDIR)
        @-mkdir bin
	@-mkdir bin\$(BINDIR)
	@-mkdir	$(PROD_SHARE_DIR)
	@-mkdir	$(PROD_SHARE_DIR)\shared
	@-mkdir	$(RIS_PROD_SHARE_DIR)
	@-mkdir	$(RIS_PROD_SHARE_DIR)\lib
	@-mkdir	$(RIS_PROD_SHARE_DIR)\bin
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\help
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\forms
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\forms\v5forms
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\messages
	@-mkdir	$(RIS_PROD_SHARE_DIR)\config\english\messages\src
	@-mkdir	$(LOCAL_DIR)
	@-mkdir $(RIS_SETUP_DIR)\compress
	@-mkdir $(RIS_SETUP_DIR)\deliv
	@echo	Finished making $@ files

cleanobjs:
	@echo Deleting the obj dirs
	@del /Q $(RIS_REMOVE_DIR)\$(OBJDIR)\*.* 2>NUL
        @cd $(RIS_CSOURCE_DIR)
        nmake -f makefile.nt clean
        @cd ..
        @cd $(RIS_BLDCUI_DIR)
        nmake -f makefile.nt clean
        @cd ..

cleanbin:
	@echo Deleting the bin dir
	@del /Q bin\$(BINDIR)\*.* 2>NUL

cleansetup:
	@echo Deleting $(PROD_SHARE_DIR)
	@-rmdir /s /q $(PROD_SHARE_DIR)\*.* 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config\english\messages\src 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config\english\messages 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config\english\help 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config\english\forms\v5forms 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config\english\forms 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config\english 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\config 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\lib 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR)\bin 2>NUL
	@-rmdir	$(RIS_PROD_SHARE_DIR) 2>NUL
	@-rmdir	$(PROD_SHARE_DIR)\shared 2>NUL
	@-rmdir	$(PROD_SHARE_DIR) 2>NUL

	@echo Deleting $(LOCAL_DIR)
	@del /s/q $(LOCAL_DIR)\*.* 2>NUL
	@del /s/q $(RIS_SETUP_DIR)\deliv\*.* 2>NUL
	@echo Deleting compressed directory
	@del /s/q $(RIS_SETUP_DIR)\compress\*.* 2>NUL

test:
!IF "$(SETUPSDK_DIR)" == ""
!ERROR SETUPSDK_DIR must be set to the location where SetupSDK is located.
!ENDIF
