#!/bin/ksh
####
#   Remove all files that get created by running integ/build.sh that we do not
# want to be checked in.  The should only be files that get created during the
# build process.
#   Using netbeans you can inspect for new files that have been created in a
# project.  The name will be displayed in green (at least for Netbeans 6.8).
# If additional files other than what are named here need to be deleted,
# possibly as additional features are added to the build, please add them to
# the script for deletion prior to checkin.
#   If ever the files being deleted here end up being placed in the $ISDP_TARGET
# directories instead of $ISDP_SOURCE, as they are now, they should be removed
# from this script.
####

if [ "$GRNUC" = "" ] ; then
    if [ "$ISDP_SOURCE" = "" ] ; then
        echo '$ISDP_SOURCE is not set.  Please set up your environment with ISDP_SOURCE or GRNUC first.'
        exit 1
    else
        GRNUC=$ISDP_SOURCE/grnuc
    fi
fi

echo "Cleaning selected files from $GRNUC/include directory..."
cd $GRNUC/include
rm -i AScmd.h ASmsg.h DMcmd.h DMmsg.h cctcmd.h cctmessage.h cicmd.h cimessage.h
rm -i grclasses.h grcmd.h grmsg.h lcmsg.h plotcmd.h pltmessage.h

echo "Cleaning selected files from $GRNUC/src/pplsrc/src directory..."
cd $GRNUC/src/pplsrc/src
rm -i cidb.c

echo "Cleaning all files from $GRNUC/config/command directory..."
rm -f $GRNUC/config/commands/*

echo "Cleaning all .msg files from $GRNUC/config/english/messages/src directory..."
rm -f $GRNUC/config/english/messages/*.msg

echo "Cleaning all files from $GRNUC/spec directory..."
rm -f $GRNUC/spec/*
