#!/bin/ksh

setup_c100()
{
	print
	print "\tMaking c100 $*"

	export IFDEF_FLAG="-Dunix -D__clipper__"

	export CC="acc -ansi -O3 -Atarg=c100 -Dunix -D__cpu_c100__ -D_INGR_EXTENSIONS"
	# clipper defined "__unix__", but not "unix"; so define it.
	export LINK="acc -Atarg=c100 -L/usr/lib/c100"

	export TARGET="c100"
	export OBJDIR="obj_c100"
	export LIBDIR="c100"
	export BINDIR="c100"

	export DNPOBJ="netdnp.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxns.o"
	export XNSOBJ_2="netwrapx.o"

	export MATHLIB=-lmath
	export SYS_LIB="-lprot -lmalloc -lc_s -lc"
	export IX_LIB="-lix"
	export LD_LIB="-lld"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB="-lbsd"
	export XNS_LIB="-linc -lnsl_s"
	export HELP_LIB="-lhlibEV -lmalloc -lc_s"
	export XHELP_LIB="-lhlib -lX11_s -lmalloc -lc_s"
	export FORMS_LIB="-lforms_s -ltools_s $MATHLIB -lhelp"
	export XFORMS_LIB="/usr/ip32/xformsdp/xfi/lib/c100/libXFI.a -lXFS_s -lX11_s $MATHLIB -lbsd"
}

setup_c400()
{
	print
	print "\tMaking c400 $*"

	export IFDEF_FLAG="-Dunix -D__clipper__"

	export CC="acc -ansi -O3 -Atarg=c400 -Dunix -D__cpu_c400__ -D_INGR_EXTENSIONS"
	# clipper defined "__unix__", but not "unix"; so define it.
	export LINK="acc -Atarg=c400 -L/usr/lib/c400"

	export TARGET="c400"
	export OBJDIR="obj_c400"
	export LIBDIR="c400"
	export BINDIR="c400"

	export DNPOBJ="netdnp.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxns.o"
	export XNSOBJ_2="netwrapx.o"

	export MATHLIB=-lmath
	export SYS_LIB="-lprot -lmalloc -lc_s -lc"
	export IX_LIB="-lix"
	export LD_LIB="-lld"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB="-lbsd"
	export XNS_LIB="-linc -lnsl_s"
	export HELP_LIB="-lhlibEV -lmalloc -lc_s"
	export XHELP_LIB="-lhlib -lX11_s -lmalloc -lc_s"
	export FORMS_LIB="-lforms_s -ltools_s $MATHLIB -lhelp"
	export XFORMS_LIB="/usr/ip32/xformsdp/xfi/lib/c400/libXFI.a  -lXFS_s -lX11_s $MATHLIB"
}

setup_sco()
{
	print
	print "\tMaking sco $*"

	export IFDEF_FLAG="-Dunix -Dsco"

	export CC="cc -Dunix -Dsco -O -K -M3 -quiet -W3"   
	export LINK="cc"

	export TARGET="sco"
	export OBJDIR="obj_sco"
	export LIBDIR="sco"
	export BINDIR="sco"

	export DNPOBJ="netdnpdm.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxnsdm.o"
	export XNSOBJ_2="netdum.o"

	# -lprot and -lx are for C2 routines; crypt is for crypt routines
	export SYS_LIB="-lprot -lx -lmalloc -lcrypt_d -lc_s -lc"
	export LD_LIB="-lld"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB="-lsocket"
	export XNS_LIB=""
}

setup_sun()
{
	print
	print "\tMaking SunOS 4.x $*"

	export IFDEF_FLAG="-Dunix -Dsun"

	export CC='acc -Dunix -Dsun -O2 -PIC -Xa -I/usr/5include'
	export LINK="acc -PIC -L/usr/5lib -L/usr/openwin/lib"

	export TARGET="sun"
	export OBJDIR="obj_sun"
	export LIBDIR="sun"
	export BINDIR="sun"

	export DNPOBJ="netdnpdm.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxnsdm.o"
	export XNSOBJ_2="netdum.o"

	export SYS_LIB="-lc"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB=""
	export XNS_LIB=""

	export XHELP_LIB="-lhlib -lX11 -lc"
	export XFORMS_LIB="-lX11 -lXFI -lXFS"
}

setup_Sol2()
{
	print
	print "\tMaking Solaris/SPARC $*"

	export IFDEF_FLAG="-Dunix -D__Sol2__"

	export CC='cc -Dunix -Usun -D__Sol2__ -Xc -KPIC -xO1'
	# Comment above line & uncomment next line to compile with debug.
	# export CC='cc -Dunix -Usun -D__Sol2__ -Xc -KPIC -g -xsb'
	export LINK='cc -KPIC'

	export TARGET="Sol2"
	export OBJDIR="obj_Sol2"
	export LIBDIR="Sol2"
	export BINDIR="Sol2"

	export DNPOBJ="netdnpdm.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxnsdm.o"
	export XNSOBJ_2="netdum.o"

	export SYS_LIB="-lmalloc -lw -lc"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB="-lsocket -lnsl"
	export XNS_LIB=""

	export XHELP_LIB="-lhlib -lX11 -lw -lc"
	export XFORMS_LIB="-lX11 -lXFI -lXFS -lm"
}

setup_Soli()
{
	print
	print "\tMaking Solaris/INTEL $*"

	export IFDEF_FLAG="-Dunix -DSoli"

	export CC='cc -Di386 -D__i386 -xnolib -Dunix -Usun -DSoli -Xc -KPIC -xO4'
	export LINK='cc -KPIC -xnolib -x486'

	export TARGET="Soli"
	export OBJDIR="obj_Soli"
	export LIBDIR="Soli"
	export BINDIR="Soli"

	export DNPOBJ="netdnpdm.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxnsdm.o"
	export XNSOBJ_2="netdum.o"

	export SYS_LIB="-lmalloc -lw -laio -lc -lm"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB="-lnsl -lsocket"
	export XNS_LIB=""

	export XHELP_LIB="-lhlib -lX11 -lw -lc"
	export XFORMS_LIB="-lX11 -lXFI -lXFS -lm"
}

setup_hpux()
{
	print
	print "\tMaking HP-UX $*"

	export IFDEF_FLAG="-Dunix -D__hpux__"

	export CC='cc -O -Dunix -D__hpux__ -Ae'
	export LINK='cc -L/usr/lib/X11R5'

	export TARGET="hpux"
	export OBJDIR="obj_hpux"
	export LIBDIR="hpux"
	export BINDIR="hpux"

	export DNPOBJ="netdnpdm.o"
	export LU62OBJ="netl62dm.o"
	export TCPOBJ_1="nettcp.o"
	export TCPOBJ_2="netwrapt.o"
	export XNSOBJ_1="netxnsdm.o"
	export XNSOBJ_2="netdum.o"

	export SYS_LIB="-lmalloc -lc -lV3 -lsec"
	export DNP_LIB=""
	export LU62_LIB=""
	export TCP_LIB="-lbsdipc -lBSD -lnet"
	export XNS_LIB=""

	export XHELP_LIB="-lhlib -lX11 -lV3 "
	export XFORMS_LIB="-lX11 /usr/ip32/xformsdp/xfi/lib/hp9000/libXFI.a /usr/lib/X11R5/libX11.sl -lm"
}

setup_sun_for_clipper()
{
	print "\tMaking sun_for_clipper $*"
	export TARGET="sun"
	export OBJDIR="obj_sun"
	export LIBDIR="sun"
	export BINDIR="sun"
}

setup_Sol2_for_clipper()
{
	print "\tMaking Sol2_for_clipper $*"
	export TARGET="Sol2"
	export OBJDIR="obj_Sol2"
	export LIBDIR="Sol2"
	export BINDIR="Sol2"
}

setup_Soli_for_clipper()
{
	print "\tMaking Soli_for_clipper $*"
	export TARGET="Soli"
	export OBJDIR="obj_Soli"
	export LIBDIR="Soli"
	export BINDIR="Soli"
}

setup_hpux_for_clipper()
{
	print "\tMaking hpux_for_clipper $*"
	export TARGET="hpux"
	export OBJDIR="obj_hpux"
	export LIBDIR="hpux"
	export BINDIR="hpux"
}

case $1 in
	"c100")
		shift
		setup_c100 $* ;;

	"c400")
		shift
		setup_c400 $* ;;

	"sco")
		shift
		setup_sco $* ;;

	"sun")
		if [ `uname -s` = "SunOS" ] 
		then 
			shift; setup_sun $*
		else
			setup_sun_for_clipper
		fi ;;

	"Sol2")
		if [ `uname -s` = "SunOS" -a `uname -p` = "sparc" ]
		then 
			shift; setup_Sol2 $*
		else
			setup_Sol2_for_clipper
		fi ;;

	"Soli")
		if [ `uname -s` = "SunOS" -a `uname -m` = "i86pc" ]
		then 
			shift; setup_Soli $*
		else
			setup_Soli_for_clipper
		fi ;;	

	"hpux")
		if [ `uname -s` = "HP-UX" ] 
		then 
			shift; setup_hpux $*
		else
			setup_hpux_for_clipper
		fi ;;

	*)
		case $(uname -s) in
		"CLIX")
			case $(inqcpuid) in
				"C100"|"C300") setup_c100 $* ;;
				"C400") setup_c400 $* ;;
				*)	print "Unknown CPU id"
					exit 1 ;;
			esac ;;
		"rissmp")
			setup_sco $* ;;
		"SunOS")
			if uname -p >/dev/null 2>&1
			then
				case $(uname -p) in
					"sparc") setup_Sol2 $* ;;
					"i386") setup_Soli $* ;;
					*)	print "Unknown System"
						exit 1 ;;
				esac
			else
				setup_sun $*
			fi ;;
		"HP-UX")
			setup_hpux $* ;;
		*)
			print "Unknown Platform"
			exit 1 ;;
		esac ;;
esac

export MK_CALLED=1
make $*

