# $Id: makefile,v 1.3 2001/04/18 13:20:12 ahundiak Exp $

# *************************************************************************
# I/LOFT
#
#  File:        src/vlisms/makefile
#
#  Description:
#
#  Dependencies:
#
#  Revision History:
#       $Log: makefile,v $
#       Revision 1.3  2001/04/18 13:20:12  ahundiak
#       ah
#
#       Revision 1.2  2001/01/18 17:55:32  art
#       ah
#
# Revision 1.4  2000/11/27  20:26:08  pinnacle
# ah
#
# Revision 1.3  2000/10/15  13:36:54  pinnacle
# ah
#
# Revision 1.2  2000/04/25  17:01:42  pinnacle
# ah
#
#
#  History:
#  MM/DD/YY  AUTHOR  DESCRIPTION
#  04/25/00  ah	     Add ppl
# ************************************************************************/

TGT     = vlisms
TGT_PPL = pplvlisms

include ${LOFT_PATH}/etc/makefiles/lib_ppl.h
