# $Id: makefile,v 1.1.1.1 2001/01/04 21:09:32 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdvvol/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:09:32  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:47:06  pinnacle
# rep bin w/txt
#
# Revision 1.2  1994/12/07  00:48:26  pinnacle
# Replaced:  vdvvol/imp/makefile r#
#
# Revision 1.1  1994/12/06  20:39:06  pinnacle
# Created:   vdvvol/imp/makefile r#
#
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdvvolimp.m
	grmakemake vdvvolimp.m mkfile
