# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:38 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:		vddraw/struct/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:08:38  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:32:12  pinnacle
# rep bin w/txt
#
# Revision 1.1  1995/08/16  14:51:48  pinnacle
# Created: vddraw/struct/makefile by azuurhou for vds.240
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	08/12/95	adz		creation date
#
# -------------------------------------------------------------------

target: mkfile 
	grmake -r -k -f mkfile

mkfile : vddrawstr.m
	grmakemake vddrawstr.m mkfile

