#/* $Id: makefile,v 1.2 2001/04/03 12:57:20 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vds/vdct1/set/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.2  2001/04/03 12:57:20  ahundiak
# *      makefile
# *
# *      Revision 1.1  2001/01/12 15:14:11  art
# *      sp merge
# *
# Revision 1.4  2000/09/20  21:10:00  pinnacle
# js
#
# Revision 1.2  2000/07/17  20:54:22  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 01/12/01  ah      sp merge
# * 04/03/01  ah      Use template
# ***************************************************************************/

TGT = vdict1tree

include ${VDS_PATH}/etc/makefiles/lib_only.h
