all: \
	directories \
	_SRC

directories:
	@if not exist $(TARGET)\message\lib mkdir $(TARGET)\message\lib
	@if not exist $(TARGET)\message\src mkdir $(TARGET)\message\src

_SRC: $(TARGET)\message\src\makefile
	@cd $(TARGET)\message\src
	@cd
	@$(MAKE)

$(TARGET)\message\src\makefile: $(EXNUC)\message\src\message.m
	cd $(EXNUC)\message\src
	$(MAKEMAKE) message.m $(TARGET)\message\src\makefile
