#/* $Id: makefile,v 1.2 2001/04/03 16:46:11 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdctx/om/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.2  2001/04/03 16:46:11  ahundiak
# *      ah
# *
# *      Revision 1.1  2001/01/14 16:09:04  art
# *      sp merge
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 12/12/00  ah      creation
# ***************************************************************************/

TGT = vdictxom

include ${VDS_PATH}/etc/makefiles/lib_only.h

