# Do not alter this SPC information: $Revision: 1.1.54.1 $
BASE_NAME=network
UNUSED_EXCEPTIONS=\
	makefile\
	makefile.nt\
	makefile.dos\
	makeout\
	make.vax\
	readme\
	nonfuncs

include ../build/maketplt
