#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:07:57 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdbuf/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:07:57  cvs
# *      Initial import to CVS
# *
# Revision 1.1  2000/02/25  17:23:52  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 02/17/00  ah      Creation
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdibuf.m
	grmakemake vdibuf.m mkfile
