#/* $Id: makefile,v 1.1.2.1 2003/12/11 14:16:42 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vds/vdnfm/list/makefile
# *
# * Description: List nfm enviroments Utility
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 02/21/05  ah      creation
# ***************************************************************************/

TGT = list

target: mkfile 
	grmake -r -k -f mkfile

mkfile : ${TGT}.m
	grmakemake ${TGT}.m mkfile

