#/* $Id: makefile,v 1.1 2001/10/16 15:37:56 jdsauby Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vds/vdqry/func/makefile
# *
# * Description: 
# *
# * Dependencies:
# *
# * Revision History:
# * $Log: makefile,v $
# * Revision 1.1  2001/10/16 15:37:56  jdsauby
# * JTS MP CR 5536
# *
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 10/08/01  js      Creation
# ***************************************************************************/

TGT     = vdiqryfunc
TGT_PPL     = vdiqryppl

include ${VDS_PATH}/etc/makefiles/lib_ppl.h

