objects:\
	directories \
	_ACTIONS \
	_CEO \
	_STATE \
	_TRANS \
	_UTIL \
	_SHFN \
	$(TARGET)\icob\lib\give_vers.obj

binaries:\
	directories \
	_SLI

directories:
	@if not exist $(TARGET)\icob\lib mkdir $(TARGET)\icob\lib
	@if not exist $(TARGET)\icob\actions mkdir $(TARGET)\icob\actions
	@if not exist $(TARGET)\icob\ceo mkdir $(TARGET)\icob\ceo
	@if not exist $(TARGET)\icob\state mkdir $(TARGET)\icob\state
	@if not exist $(TARGET)\icob\trans mkdir $(TARGET)\icob\trans
	@if not exist $(TARGET)\icob\util mkdir $(TARGET)\icob\util
	@if not exist $(TARGET)\icob\shfn mkdir $(TARGET)\icob\shfn
	@if not exist $(TARGET)\icob\sli mkdir $(TARGET)\icob\sli

_ACTIONS: $(TARGET)\icob\actions\makefile
	@cd $(TARGET)\icob\actions
	@cd
	@$(MAKE)

_CEO: $(TARGET)\icob\ceo\makefile
	@cd $(TARGET)\icob\ceo
	@cd
	@$(MAKE)

_STATE: $(TARGET)\icob\state\makefile
	@cd $(TARGET)\icob\state
	@cd
	@$(MAKE)

_TRANS: $(TARGET)\icob\trans\makefile
	@cd $(TARGET)\icob\trans
	@cd
	@$(MAKE)

_UTIL: $(TARGET)\icob\util\makefile
	@cd $(TARGET)\icob\util
	@cd
	@$(MAKE)

_SHFN: $(TARGET)\icob\shfn\makefile
	@cd $(TARGET)\icob\shfn
	@cd
	@$(MAKE)

_SLI: $(TARGET)\icob\sli\makefile
	@cd $(TARGET)\icob\sli
	@cd
	@$(MAKE)

$(TARGET)\icob\lib\give_vers.obj:
	@$(ECHO) "give_cob_version (){ return $(COB_VER_D); }" > $(TARGET)\icob\lib\give_vers.c
	@cd $(TARGET)\icob\lib
	$(CC) -c $(COPT) $(IPATH) $(DOPT) $(DOPT1) $(DOPT2) $(TARGET)\icob\lib\give_vers.c

$(TARGET)\icob\actions\makefile: $(EXNUC)\icob\actions\actions.m
	cd $(EXNUC)\icob\actions
	$(MAKEMAKE) actions.m $(TARGET)\icob\actions\makefile

$(TARGET)\icob\ceo\makefile: $(EXNUC)\icob\ceo\ceo.m
	cd $(EXNUC)\icob\ceo
	$(MAKEMAKE) ceo.m $(TARGET)\icob\ceo\makefile

$(TARGET)\icob\shfn\makefile: $(EXNUC)\icob\shfn\shfn.m
	cd $(EXNUC)\icob\shfn
	$(MAKEMAKE) shfn.m $(TARGET)\icob\shfn\makefile

$(TARGET)\icob\sli\makefile: $(EXNUC)\icob\sli\sli.m $(TARGET)\icob\sli\ytab.h
	cd $(EXNUC)\icob\sli
	$(MAKEMAKE) sli.m $(TARGET)\icob\sli\makefile

$(TARGET)\icob\sli\ytab.h:
	$(ECHO) > $@

$(TARGET)\icob\state\makefile: $(EXNUC)\icob\state\state.m
	cd $(EXNUC)\icob\state
	$(MAKEMAKE) state.m $(TARGET)\icob\state\makefile

$(TARGET)\icob\trans\makefile: $(EXNUC)\icob\trans\trans.m
	cd $(EXNUC)\icob\trans
	$(MAKEMAKE) trans.m $(TARGET)\icob\trans\makefile

$(TARGET)\icob\util\makefile: $(EXNUC)\icob\util\util.m
	cd $(EXNUC)\icob\util
	$(MAKEMAKE) util.m $(TARGET)\icob\util\makefile
