# $Id: makefile,v 1.1 2001/08/16 22:02:43 ylong Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdtbl/xml/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1  2001/08/16 22:02:43  ylong
#	Export table to xml
#	
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	08/02/01	ylong		first integration
# -------------------------------------------------------------------

TGT	= vditblxml

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile *.o *.c

