/* $Revision: 1.1 $ */
/* Function:	no_mcsl */

int ASInitX                            () { return (0); }
int ASEnterXFI                         () { return (0); }
int ASInitEnvironV                     () { return (0); }
int ASSetKbdBuf                        () { return (0); }
int ms_cmdfilter_function              () { return (0); }
int ASFilterFunc                       () { return (0); }
int quat_to_trans                      () { return (0); }
int ASEnterFI                          () { return (0); }
int ASSetGetFuncs                      () { return (0); }
int ms_application_id                  () { return (0); }
int ASLoadVLT                          () { return (0); }
int ms_menu_function                   () { return (0); }
int ms_terminate_function              () { return (0); }
int ASEnableEvents                     () { return (0); }
int process_multi_elements             () { return (0); }
int open_shared_mem                    () { return (0); }
int efdfpi                             () { return (0); }
int close_shared_mem                   () { return (0); }
int ASNullCmd                          () { return (0); }
int ASGetInput                         () { return (0); }
int ASExecCmd                          () { return (0); }
int get_ref_info                       () { return (0); }
int set_ref_info                       () { return (0); }
int txmtrx                             () { return (0); }
int tnmtrx                             () { return (0); }
int tndfpi                             () { return (0); }
int txdfpi                             () { return (0); }
int reload_cache                       () { return (0); }
int ms_execute_function                () { return (0); }
int ms_input_function                  () { return (0); }
int ms_command_term_function           () { return (0); }
int ms_execute_command                 () { return (0); }
int ms_validate_command                () { return (0); }
int ms_set_help_topic                  () { return (0); }
int ms_active_command                  () { return (0); }
int ms_command_terminate               () { return (0); }
int indfpi                             () { return (0); }  
int dispatch_asynch_request            () { return (0); } 
int clear_hilite                       () { return (0); } 
int usermsg                            () { return (0); } 
int dedfpi                             () { return (0); } 
int rdtcbasc                           () { return (0); } 
int ms_get_windows                     () { return (0); } 
int ms_return_windows                  () { return (0); } 
int wttcbasc                           () { return (0); } 
int locate_element                     () { return (0); } 
int locele                             () { return (0); } 
int wtdfpi                             () { return (0); } 
int rddfpi                             () { return (0); } 
int igds_size                          () { return (0); } 
int delete_element                     () { return (0); } 
int scan_fmt                           () { return (0); } 
int initialize_scan                    () { return (0); } 
int scan_file                          () { return (0); } 
int un_scan_fmt                        () { return (0); } 
int ms_queue_input                     () { return (0); } 
int add_hilite_element                 () { return (0); } 
int io_ulfopr                          () { return (0); } 
int io_ulfcri                          () { return (0); } 
int io_ulfget                          () { return (0); } 
int convert_double                     () { return (0); } 
int io_ulfcls                          () { return (0); } 

int prdfpi                             () { return (0); } 

