target: ../reports/BMB.sh \
	../reports/BMG.sh \
	../reports/BMN.sh \
	../reports/BMW.sh \
	../reports/BPG.sh \
	../reports/EQB.sh \
	../reports/EQN.sh \
	../reports/EQW.sh \
	../reports/HVB.sh \
	../reports/HVE.sh \
	../reports/HVN.sh \
	../reports/HVW.sh \
	../reports/NZB.sh \
	../reports/OVW.sh \
	../reports/PLB.sh \
	../reports/PLN.sh \
	../reports/PLW.sh \
	../reports/PPB.sh \
	../reports/PPD.sh \
	../reports/PPE.sh \
	../reports/PPN.sh \
	../reports/PPR.sh \
	../reports/PPV.sh \
	../reports/PPW.sh \
	../reports/RWB.sh \
	../reports/RWE.sh \
	../reports/RWN.sh \
	../reports/RWW.sh \
	../reports/CMB.sh \
	../reports/CMT.sh \
	../reports/print_file.sh \
	../reports/RPTexec.ksh

../reports/BMB.sh : BMB.sh
	    	    cp BMB.sh ../reports

../reports/BMG.sh : BMG.sh
	    	    cp BMG.sh ../reports

../reports/BMN.sh : BMN.sh
	    	    cp BMN.sh ../reports

../reports/BMW.sh : BMW.sh
	    	    cp BMW.sh ../reports

../reports/BPG.sh : BPG.sh
	    	    cp BPG.sh ../reports

../reports/EQB.sh : EQB.sh
	    	    cp EQB.sh ../reports

../reports/EQN.sh : EQN.sh
	    	    cp EQN.sh ../reports

../reports/EQW.sh : EQW.sh
	    	    cp EQW.sh ../reports

../reports/HVB.sh : HVB.sh
	    	    cp HVB.sh ../reports

../reports/HVE.sh : HVE.sh
	    	    cp HVE.sh ../reports

../reports/HVN.sh : HVN.sh
	    	    cp HVN.sh ../reports

../reports/HVW.sh : HVW.sh
	    	    cp HVW.sh ../reports

../reports/NZB.sh : NZB.sh
	    	    cp NZB.sh ../reports

../reports/OVW.sh : OVW.sh
	    	    cp OVW.sh ../reports

../reports/PLB.sh : PLB.sh
	    	    cp PLB.sh ../reports

../reports/PLN.sh : PLN.sh
	    	    cp PLN.sh ../reports

../reports/PLW.sh : PLW.sh
	    	    cp PLW.sh ../reports

../reports/PPB.sh : PPB.sh
	    	    cp PPB.sh ../reports

../reports/PPD.sh : PPD.sh
	    	    cp PPD.sh ../reports

../reports/PPE.sh : PPE.sh
	    	    cp PPE.sh ../reports

../reports/PPN.sh : PPN.sh
	    	    cp PPN.sh ../reports

../reports/PPR.sh : PPR.sh
	    	    cp PPR.sh ../reports

../reports/PPV.sh : PPV.sh
	    	    cp PPV.sh ../reports

../reports/PPW.sh : PPW.sh
	    	    cp PPW.sh ../reports

../reports/RWB.sh : RWB.sh
	    	    cp RWB.sh ../reports

../reports/RWE.sh : RWE.sh
	    	    cp RWE.sh ../reports

../reports/RWN.sh : RWN.sh
	    	    cp RWN.sh ../reports

../reports/RWW.sh : RWW.sh
	    	    cp RWW.sh ../reports

../reports/CMB.sh : CMB.sh
	    	    cp CMB.sh ../reports

../reports/CMT.sh : CMT.sh
	    	    cp CMT.sh ../reports

../reports/print_file.sh : print_file.sh
	    	           cp print_file.sh ../reports

../reports/RPTexec.ksh : RPTexec.ksh
	    	         cp RPTexec.ksh ../reports
