#/* $Id: makefile.1,v 1.1.1.1 2001/01/04 21:08:53 cvs Exp $ */

#/***************************************************************************
#* I/VDS
#*
#* File:        vds/vdloft/cmd/makefile
#*
#* Description:    make file for files in vds/vdloft/cmd.
#*
#* Dependencies:
#*
#* Revision History:
#*      $Log: makefile.1,v $
#*      Revision 1.1.1.1  2001/01/04 21:08:53  cvs
#*      Initial import to CVS
#*
# Revision 1.1  1998/04/29  16:27:20  pinnacle
# VDS 2.5.1
#
# Revision 1.1  1998/01/30  13:58:48  pinnacle
# ah
#
# Revision 1.1  1998/01/29  20:12:46  pinnacle
# TR_179702387: converted file from Loft to VDS
#
#*
#* History:
#*  MM/DD/YY  AUTHOR  DESCRIPTION
#*  01/23/98  ejm     TR:179702387, converted file from Loft to VDS
#***************************************************************************/

target:	sl \
	mkfile
	grmake -r -k -f mkfile

sl: ${VDS}/config/commands/VDRepSrf

${VDS}/config/commands/VDRepSrf: VDRepSrfCmd.S VDRepSrfCmd.sl \
        ${VDS}/include/SMmsg.h ${VDS}/include/SMcmd.h \
        ${VDS}/include/VDmsg.h ${VDS}/include/VDcmd.h
	slic -siTC -p${VDS}/spec VDRepSrfCmd.sl

mkfile: repsrf.m
	grmakemake repsrf.m mkfile
