# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:56 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vdmdlv/func/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:08:56  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:37:48  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/12/06  21:43:56  pinnacle
# Created:   vdmdlv/func/makefile r#
#
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdmdlvfc.m
	grmakemake vdmdlvfc.m mkfile

clean:
	@rm -f mkfile *.o *.c

