# (Originally) Microsoft Visual C++ Generated NMAKE File, Format Version 2.00

# TARGTYPE "Win32 (x86) Dynamic-Link Library" 0x0102
!include $(RISDEVDIR)\ristools\include\makeenv.nt
!include ..\setupenv.nt

################################################################################
# Begin Project
# PROP Target_Last_Scanned "Win32 Debug"
NT_SETUPDIR_BLDCUI = $(NT_SETUP_DIR)\csource\bldcui
RISSETUP_BLDCUI_OBJ = $(RISDEVDIR)\riscli\setup32\bldcui\obj_nt

MTL=MkTypLib.exe
!IFDEF BOUNDSCHECKER
CPP=bcompile.exe
!ELSE
CPP=cl.exe
!ENDIF
RSC=rc.exe -r
DLL_NAME=mscuistf
#NEW_DLL_NAME=rissc
NEW_DLL_NAME=ui0409c

IPATH=\
	 -I"$(NT_SETUP_DIR)\setup32" \
	 -I"$(NT_SETUP_DIR)\isdklib" \
	 -I..\..\..\riscom\internal \
         -I"$(NT_SETUP_DIR)\csource\bldcui" \
	 -I..\..\..\riscli\setup32\csource \
         -I..\..\..\riscli\setup32\remove \

OBJDIR=.\obj_nt

fast : $(CUISDK_OBJS) ..\bin\nt/$(NEW_DLL_NAME).dll

$(OBJDIR) : 
    if not exist $(OBJDIR)/nul mkdir $(OBJDIR)

# ADD BASE MTL /nologo /D "_DEBUG" /win32
# ADD MTL /nologo /D "_DEBUG" /win32
MTL_PROJ=/nologo /D "_DEBUG" /win32 
# ADD BASE CPP /nologo /MT /W3 /GX /Zi /YX /Od /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /FR /c
# ADD CPP /nologo /MT /W3 /GX /Zi /YX /Od /I "." /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /FR /QIfdiv-  /c
CPP_PROJ=/nologo /MT /W3 /GX /Zi /YX /Od /I "." $(IPATH) /D "RISCLI" /D "WIN32" /D\
 "_DEBUG" /D "_WINDOWS" /Fp$(OBJDIR)/"$(DLL_NAME).pch" /Fo$(OBJDIR)/\
 /Fd$(OBJDIR)/"$(DLL_NAME).pdb" /QIfdiv- /c 
CPP_PROJ2=/nologo /MT /W3 /GX /Zi /YX /Od /I "." $(IPATH) /D "RISCLI" /D "WIN32" /D\
 "_DEBUG" /D "_WINDOWS" /Fp$(OBJDIR)/"$(DLL_NAME).pch" \
 /Fd$(OBJDIR)/"$(DLL_NAME).pdb" /QIfdiv- /c 
CPP_OBJS=.\obj_nt/
# ADD BASE RSC /l 0x409 /d "_DEBUG"
# ADD RSC /l 0x409 /i ".." /d "_DEBUG"
RSC_PROJ=/l 0x409 /i ".." $(IPATH) -DRISCLI
BSC32=bscmake.exe
# ADD BASE BSC32 /nologo
# ADD BSC32 /nologo
BSC32_FLAGS=/nologo /o$(OBJDIR)/"$(DLL_NAME).bsc" 
BSC32_SBRS=


!IFDEF BOUNDSCHECKER
LINK32=bclink.exe -machine:$(CPU) -dll -entry:LibMain$(DLLENTRY) \
	/debug
!ELSE
LINK32=link.exe -machine:$(CPU) -dll -entry:LibMain$(DLLENTRY) 
!ENDIF
# ADD BASE LINK32 kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib /NOLOGO /SUBSYSTEM:windows /DLL /DEBUG /MACHINE:I386
# ADD LINK32 "$(NT_SETUP_DIR)\setup32\\mscomstf.lib" "$(NT_SETUP_DIR)\setup32\\msshlstf.lib" "$(NT_SETUP_DIR)\setup32\msuilstf.lib" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib /NOLOGO /SUBSYSTEM:windows /DLL /DEBUG /MACHINE:I386
LINK32_FLAGS="$(NT_SETUP_DIR)\setup32\mscomstf.lib" "$(NT_SETUP_DIR)\setup32\msshlstf.lib"\
 "$(NT_SETUP_DIR)\setup32\msuilstf.lib" "$(NT_SETUP_DIR)\isdklib\isdkdll.lib" \
 kernel32.lib user32.lib gdi32.lib winspool.lib version.lib msvcrt.lib \
 comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib /NOLOGO\
!IFDEF BOUNDSCHECKER
 /SUBSYSTEM:windows /DLL /INCREMENTAL:no /PDB:$(OBJDIR)/"$(DLL_NAME).pdb" \
!ELSE
 /SUBSYSTEM:windows /DLL /INCREMENTAL:yes /PDB:$(OBJDIR)/"$(DLL_NAME).pdb" \
!ENDIF
 /MACHINE:I386 /OUT:..\bin\nt\$(NEW_DLL_NAME).dll /IMPLIB:$(OBJDIR)/"$(DLL_NAME).lib" \
-def:$(DLL_NAME).def
DEF_FILE=$(DLL_NAME).def
LINK32_OBJS= \
	$(RISSETUP_BLDCUI_OBJ)\dlgproc3.obj \
	$(OBJDIR)/risdlog.res \
	$(OBJDIR)/risdlog.obj \

..\bin\nt/$(NEW_DLL_NAME).dll : $(OBJDIR)  $(DEF_FILE) $(LINK32_OBJS) $(OBJDIR)\$(DLL_NAME).exp
    @$(LINK32) $(LINK32_FLAGS) $(LINK32_OBJS)

.c{$(CPP_OBJS)}.obj:
   @$(CPP) $(CPP_PROJ) $<  

.cpp{$(CPP_OBJS)}.obj:
   @$(CPP) $(CPP_PROJ) $<  

.cxx{$(CPP_OBJS)}.obj:
   @$(CPP) $(CPP_PROJ) $<  

################################################################################
# Begin Group "Source Files"

################################################################################
# Begin Source File

SOURCE="$(NT_SETUPDIR_BLDCUI)\dlgproc3.c"
DEP_DLGPR=\
	"$(NT_SETUPDIR_SETUP32)\setupapi.h"\
	"$(NT_SETUPDIR_BLDCUI)\cui.h"

$(RISSETUP_BLDCUI_OBJ)\dlgproc3.obj : 
    @$(CPP) $(CPP_PROJ2) $(NT_SETUPDIR_BLDCUI)\dlgproc3.c /Fo$(RISSETUP_BLDCUI_OBJ)\dlgproc3.obj

# End Source File
################################################################################
# Begin Source File

SOURCE=.\risdlog.rc
DEP_DIALO=\
	$(OBJDIR)\cuirsc.res\
	"$(NT_SETUP_DIR)\csource\exver.h"

$(OBJDIR)/risdlog.res :  $(SOURCE)  $(DEP_DIALO) $(OBJDIR)
   @$(RSC) $(RSC_PROJ) /fo$(OBJDIR)/"risdlog.res" $(SOURCE)

# End Source File
################################################################################
# Begin Source File

SOURCE=.\cuirsc.rc
$(OBJDIR)\cuirsc.res :  
   $(RSC) $(RSC_PROJ)  /fo$(OBJDIR)/"cuirsc.res" $(SOURCE)

# End Source File
################################################################################
# Begin Source File

#SOURCE=.\cuivers.rc
#.\OBJ_NT\cuivers.res :  
#   $(RSC) $(RSC_PROJ)  -DRISCLI /fo.\OBJ_NT/"cuivers.res" $(SOURCE)

# End Source File
################################################################################
# Begin Source File

SOURCE=.\risdlog.c
DEP_DLGPRO=\
	"$(NT_SETUP_DIR)\setup32\setupapi.h" \
	"$(NT_SETUP_DIR)\csource\bldcui\cui.h"

$(OBJDIR)/risdlog.obj :  $(SOURCE)  $(DEP_DLGPRO) $(OBJDIR)

# End Source File
# End Group
# End Project
################################################################################
$(OBJDIR)\$(DLL_NAME).exp: $(DLL_NAME).def $(LINK32_OBJS)
	@echo.
	@echo	$?  -to-  $@
	@lib  -machine:$(CPU) \
	-def:$(DLL_NAME).def	\
	-out:$(@R).lib	\
	$(LINK32_OBJS)


clean:
        @-del/Q $(OBJDIR)\*.*
        @-del/Q $(OBJDIR)\$(DLL_NAME).exp
    
