#/* $Id: makefile,v 1.1 2001/01/10 18:04:41 art Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vditem/func/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/01/10 18:04:41  art
# *      sp merge
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  	DESCRIPTION
# * 07/06/00  Rama Rao  Creation
# * 01/10/01  ah        sp merge
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vditem.m
	grmakemake vditem.m mkfile


