
/*
$Author: hans $
$Revision: 1.1.1.1 $
$Date: 2001/12/17 22:40:57 $
$Locker:  $
*/

#ifndef VEcheform_include
#define VEcheform_include 1

/****** Defines for the field sizes of the Create Hidden Edges Form ******/

/* Size of hidden and visible level fields */
#define LEVEL_FIELD_SIZE	10

/* Size of symbology fields */
#define SYMB_FIELD_SIZE	8

/* Size of the reduction fields */
#define REDUCTION_FIELD_SIZE	32

#define VE_CHE_HIGH_RES_ROW 0
#define VE_CHE_MEDIUM_RES_ROW 1
#define VE_CHE_LOW_RES_ROW 2

#define VE_CHE_2D_ROW 0
#define VE_CHE_3D_ROW 1

#define VE_CHE_CHECK_BUTTON 1
#define VE_CHE_X_BUTTON	4
#define VE_CHE_STATUS_FIELD   10

#define VE_CHE_BACKGROUND_GROUP 70
#define VE_CHE_HIDDEN_LINE_DISP_GROUP 75
#define VE_CHE_HIGH_RES_GROUP 76
#define VE_CHE_REDUCTION_GROUP 71
#define VE_CHE_TRACING_GROUP 73
#define VE_CHE_GAPPING_GROUP 72
#define VE_CHE_TEXT_COPY_GROUP 74

#define VE_CHE_CPE_TEXT 41
#define VE_CHE_CHE_TEXT 11
#define VE_CHE_RESOLUTION_TEXT 25
#define VE_CHE_WINDOW_FIELD 13

#define VE_CHE_HIDDEN_LINE_DISP_TOG 14
#define VE_CHE_FENCE_CLIP_TOG 23
#define VE_CHE_TEXT_COPY_TOG 42
#define VE_CHE_CURVE_PROC_TOG 24
#define VE_CHE_TRACE_TOG 27
#define VE_CHE_REF_FILE_DISP_TOG 53
#define VE_CHE_GAPPING_TOG 31
#define VE_CHE_REDUCTION_TOG 35
#define VE_CHE_EXEC_MODE_TOG 54

#define VE_CHE_HID_COLOR_FIELD 19
#define VE_CHE_HID_STYLE_FIELD 20
#define VE_CHE_HID_WEIGHT_FIELD 21

#define VE_CHE_VIS_COLOR_FIELD 81
#define VE_CHE_VIS_STYLE_FIELD 82
#define VE_CHE_VIS_WEIGHT_FIELD 83

#define VE_CHE_GAPPING_DISTANCE_FIELD 33
#define VE_CHE_SURF_THRESHOLD_FIELD 38
#define VE_CHE_CURVE_THRESHOLD_FIELD 39
#define VE_CHE_VIS_LAYER_FIELD 47
#define VE_CHE_TEXT_LAYER_FIELD 48
#define VE_CHE_HID_LAYER_FIELD 49
#define VE_CHE_TRACE_TOL_FIELD 29
#define VE_CHE_RESULTS_NAME_FIELD 60
#define VE_CHE_SERVER_NAME_FIELD 61
#define VE_CHE_USER_NAME_FIELD 62
#define VE_CHE_PASSWORD_FIELD 63
#define VE_CHE_START_TIME_FIELD 64

#define VE_CHE_RESOLUTION_LIST 26
#define VE_CHE_DIMENSION_LIST 52

#define VE_CHE_HIDDEN_LINE_DISPLAY_TEXT 85

#endif
