SRC
$(MODEL)/src_dpr/funk
OPP
$(EXTARG)/bin/opp
OMCPP
$(EXTARG)/bin/omcpp
INCLUDE
$(INGRHOME)/include
#ifndef IRIX5
$(GRNUC)/unix_include/$(CPUTYPE)
#endif
$(XINC)
$(GRNUC)/ingrsys
$(MODEL)/include
$(EXNUC)/include
$(GRNUC)/include
$(BS)/include
$(BS)/include/prototypes
$(BS)/include/prototypes
#if defined (XGL)
$(XGLHOME)/include
$(XGLHOME)/include/xgl
#endif
SPEC
$(EXNUC)/spec
$(GRNUC)/spec
$(MODEL)/spec
LIB
$(MDTARG)/src_lib/EMSdprF.o
SOURCE
EFaddrmblsup.I
EFaddrmbool.I
EFaddrmsupp.I
EFallocmore.I
EFchan_funk.C
EFcontop.I
EFfixpcrel.I
EFflt_ed.I
EFget_roots.I
EFgetedarmu.C
EFgetlped.I
EFgetobjids.I
EFininflpinf.I
EFisancval.C
EFlft_funk.I
EFmgcoinc.I
EFotinflpinf.I
EFpfspbool.I
EFprtassoc.I
EFre_exec.I
EFribfeacons.I
EFrootbatch.I
EFrploneds.I
EFsetsfstate.I
EFshowpc.I
EFspboolsup.I
EFssiPrfmRm.I
EFsttr_func.I
EFtr2BoolSSI.C
EMaddrmfecns.I
EMcmprs_lps.I
EMcon_spl_ed.I
EMcon_usp_ed.I
EMfix_loops.I
EMmkpoles.I
EMrnd2cx1cv.I
EMrnd_filter.I
EMrndblnsupp.I
EMrndgenbln.I
EMrndgenfunc.I
EMrndgentrm.I
EMrndmemsupp.I
EMrndopensrf.I
EMrndrolbal.I
EMrndsngpch.I
EMrndsngtrm.I
EMrndsphbln.I
EMrndtantrm.I
EMrndtpint.I
EMrndvtxcnfg.I
EMselboolean.I
EMsfbool.I
EMsftrim.I
EFxtOpInfo.c
