#/* $Id: makefile,v 1.2 2001/11/09 15:08:39 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdsa/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.2  2001/11/09 15:08:39  ahundiak
# *      ah
# *
# *      Revision 1.1.1.1  2001/01/04 21:09:12  cvs
# *      Initial import to CVS
# *
# Revision 1.4  1998/04/10  21:58:04  pinnacle
# ah
#
# Revision 1.3  1998/04/09  14:27:04  pinnacle
# ah
#
# Revision 1.1  1998/04/02  21:27:28  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 03/30/98  ah      creation
# * 11/08/01  ah      New format
# ***************************************************************************/

TGT     = vdisa
TGT_PPL = pplsa

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile pplmkfile *.e *.o

