# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:29 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/etc/pplmacros/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:07:29  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  14:58:16  pinnacle
# rep bin w/txt
#
# Revision 1.2  1995/07/06  20:49:24  pinnacle
# Replaced: etc/pplmacros/makefile for:  by azuurhou for vds.240
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

.SUFFIXES: .u .e

target : COPPMmacro.e  COSMmacro.e   COVDSmacro.e COVDSdrw.e

.u.e:
	cci.here $<
	

