#/* $Id: makefile,v 1.3 2001/02/06 16:19:32 build Exp $  */

#/***************************************************************************
# * I/STRUCT
# *
# * File:        isdp/struct/vsgeom/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.3  2001/02/06 16:19:32  build
# *      Reverting to 1.1
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 01/16/01  RR      File Creation
# ***************************************************************************/

TGT = vsgeom

include ${STRUCT}/etc/makefiles/lib_only.h
