#!/bin/sh
# NAME
#       inqlgexist - check the existence of Looking Glass
#
# DESCRIPTION
#       This shell script tests the existence of Looking Glass by
#       first testing the existence of /usr/lib/.lgexists.  Then
#       the script checks to see if the source of .lgexists' symbolic
#       link exists.
#
# RETURN STATUS
#       If Looking Glass exists, inqlgexist returns 0.
#       If Looking Glass does not exist, inqlgexist returns 255.
#
#       1/16/91 cmd - made changes to support diskless installation

#       Test for existence of /usr/lib/.lgexists

DISKLESS_ROOT=""
[ "$ROOT" -a "$INSTALL_SHARED" -a "$VARDIR" ] && DISKLESS_ROOT=$ROOT

if [ -x /bin/sun -a /bin/sun ]
then
    if [ -h $DISKLESS_ROOT/usr/lib/.lgexists ]
    then
    #               Test for existence of actual file
        ls -L $DISKLESS_ROOT/usr/lib/.lgexists >/dev/null 2>&1
        if [ $? -eq 2 ]
        then
                exit 255
        else
                exit 0
        fi
    else
        exit 255
    fi
else
    if [ -L $DISKLESS_ROOT/usr/lib/.lgexists ]
    then
    #               Test for existence of actual file
        ls -L $DISKLESS_ROOT/usr/lib/.lgexists >/dev/null 2>&1
        if [ $? -eq 2 ]
        then
                exit 255
        else
                exit 0
        fi
    else
        exit 255
    fi
fi
