#/* $Id: makefile.1,v 1.1 2001/10/18 16:41:55 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdcdom/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile.1,v $
# *      Revision 1.1  2001/10/18 16:41:55  ahundiak
# *      ah
# *
# *      Revision 1.1  2001/05/02 15:07:25  ahundiak
# *      ah
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 04/23/01  ah      creation
# ***************************************************************************/

TGT = vdicdom

include ${VDS_PATH}/etc/makefiles/lib_only.h
