cci.sh detach_part.u
cci.sh create_part.u
cci.sh edit_part.u
cci.sh align_part.u
cci.sh attach_part.u
cci.sh locate_part.u
cci.sh def_origin.u
cci.sh update_bypt.u
cci.sh del_origin.u
cci.sh identify_prt.u 
cci.sh display_prt.u 
cci.sh get_rplprt.u 
cci.sh def_invisorg.u 
cci.sh del_part.u 
cci.sh copy_part.u 
cci.sh replace_part.u 
cci.sh update_bypt.u 
cci.sh topdown.u 
cci.sh cvt_file.u 
cci.sh cvt_pointer.u 
cci.sh cvt_origin.u 
cci.sh mac_attr.u 
cci.sh mac_list.u 
cci.sh get_atr_val.u
cci.sh import_ris.u
cci.sh position_prt.u
cci.sh put_queue.u
cci.sh dsp_prt_lst.u
cci.sh dsp_org_lst.u
cci.sh get_cs_id.u
cci.sh cvt_objspace.u
cci.sh clear_dbg.u
cci.sh post_dbg.u
cci.sh move_dbg.u
cci.sh copy_dbg.u
cci.sh copy_os.u
cci.sh send_dbg.u
cci.sh login.u
