# $Id: makefile,v 1.1 2001/07/23 16:32:23 ahundiak Exp $

# *************************************************************************
# I/VDS
#
#  File:        vdval/om/makefile
#
#  Description:
#
#  Dependencies:
#
#  Revision History:
#       $Log: makefile,v $
#       Revision 1.1  2001/07/23 16:32:23  ahundiak
#       ah
#
#
# History:
# MM/DD/YY  AUTHOR  DESCRIPTION
# 07/10/01  ah      Creation
# ************************************************************************/

TGT     = vdivalom
TGT_PPL = vdivalppl

include ${VDS_PATH}/etc/makefiles/lib_ppl.h


