# Do not alter this line: $Revision: 1.1.54.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt

EXES=\
	..\bin\$(TOOLSDIR)\because.exe\
	..\bin\$(TOOLSDIR)\cmpdir.exe\
	..\bin\$(TOOLSDIR)\get_prt.exe\
	..\bin\$(TOOLSDIR)\getfiles.exe\
	..\bin\$(TOOLSDIR)\line.exe\
	..\bin\$(TOOLSDIR)\mkhshtb.exe\
	..\bin\$(TOOLSDIR)\touchold.exe

all: $(EXES)

cleanup:
	@-del $(EXES) 2>NUL


.c{..\bin\$(TOOLSDIR)\}.exe:
	@echo.
	@echo 	$(@B).c   -to-   $@
	@echo 	Compiling with $(cc)
	@$(cc) $(cdebug) $(cflags) $(cvars) $(@B).c
	@echo 	Linking with $(link)
	@$(link) $(linkdebug) $(conflags) -out:$(@) $(@B).obj $(conlibs)
	@del $(@B).obj
