#/* $Id: makefile,v 1.3 2001/03/31 19:39:04 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vds/vdpdm/func/makefile
# *
# * Description: 
# *
# * Dependencies:
# *
# * Revision History:
# * $Log: makefile,v $
# * Revision 1.3  2001/03/31 19:39:04  ahundiak
# * ah
# *
# * Revision 1.2  2001/02/21 13:02:25  jdsauby
# * CR4088
# *
# * Revision 1.1  2001/02/12 21:26:02  jdsauby
# * Added for CR 4088
# *
# * Revision 1.2  2001/01/24 20:11:12  ahundiak
# * ah
# *
# * Revision 1.1  2001/01/11 21:48:41  art
# * sp merge
# *
# Revision 1.2  2000/09/20  21:08:34  pinnacle
# js
#
# Revision 1.3  2000/09/20  21:05:08  pinnacle
# js
#
# Revision 1.1  2000/07/27  15:13:14  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/29/99  ah      Creation
# * 01/11/01  ah      sp merge
# ***************************************************************************/

TGT     = vdpdmfunc
TGT_PPL = vdpdmfuncppl

include ${VDS_PATH}/etc/makefiles/lib_only.h

clean:
	@rm -f mkfile pplmkfile *.e *.o 

