# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:38 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vddraw/ve/make_sh/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:08:38  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:54:28  pinnacle
# rep bin w/txt
#
# Revision 1.2  1995/03/16  21:26:44  pinnacle
# Replaced: vddraw/ve/make_sh/makefile by azuurhou r#
#
# Revision 1.1  1995/03/16  21:22:20  pinnacle
# Created: vddraw/ve/make_sh/makefile by azuurhou r#
# rno
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target: mkfile 
	grmake -r -k -f mkfile

mkfile : vdvesh.m
	grmakemake vdvesh.m mkfile

clean:
	@rm -f mkfile *.o *.c

