# $Id: makefile.1,v 1.1 2002/04/18 16:31:28 ahundiak Exp $

# *************************************************************************
# I/VDS
#
#  File:        vdat/pcmk/makefile
#
#  Description:
#
#  Dependencies:
#
#  Revision History:
#       $Log: makefile.1,v $
#       Revision 1.1  2002/04/18 16:31:28  ahundiak
#       ah
#
#       Revision 1.3  2002/04/01 21:03:43  ahundiak
#       ah
#
#       Revision 1.2  2001/01/11 20:54:47  art
#       sp merge
#
# Revision 1.1  2000/06/27  17:34:38  pinnacle
# ah
#
#
# History:
# MM/DD/YY  AUTHOR  DESCRIPTION
# 06/27/00  ah	    Add ppl
# 01/11/01  ah      sp merge  
# ************************************************************************/

TGT     = vdiatpcmk
TGT_PPL = pplpcmk

include ${VDS_PATH}/etc/makefiles/lib_ppl.h

