# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:36 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vddetail/func/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:08:36  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:30:34  pinnacle
# rep bin w/txt
#
# Revision 1.1  1995/11/27  14:50:26  pinnacle
# Created: ./vddetail/func/makefile by azuurhou for vds.240
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------

target: mkfile
	grmake -r -k -f mkfile

mkfile : vddetlfnc.m
	grmakemake vddetlfnc.m mkfile

