#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:08:01 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdct/set/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:08:01  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1999/05/28  19:08:46  pinnacle
# ct
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/28/99  ah      creation
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdictset.m
	grmakemake vdictset.m mkfile

clean:
	@rm -f mkfile 8.o *.c

