#/* $Id: makefile,v 1.1 2001/05/24 19:02:09 ahundiak Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdbin/sp_pens/makefile
# *
# * Description: Spades Penetration Report Generator
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1  2001/05/24 19:02:09  ahundiak
# *      ah
# *
# *      Revision 1.1  2001/04/12 14:49:41  ahundiak
# *      ah
# *
# *
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 04/12/01  ah      creation
# ***************************************************************************/

TGT = sp_val

target: mkfile 
	grmake -r -k -f mkfile

mkfile : ${TGT}.m
	grmakemake ${TGT}.m mkfile

