all:\
	directories \
	_LIB \
	_SRC

directories:
	@if not exist $(TARGET)\package\bin mkdir $(TARGET)\package\bin
	@if not exist $(TARGET)\package\lib mkdir $(TARGET)\package\lib
	@if not exist $(TARGET)\package\src mkdir $(TARGET)\package\src

_LIB: $(TARGET)\package\lib\makefile
	@cd $(TARGET)\package\lib
	@cd
	$(MAKE)

$(TARGET)\package\lib\makefile: $(EXNUC)\package\lib\lib.m
	cd $(EXNUC)\package\lib
	$(MAKEMAKE) lib.m $(TARGET)\package\lib\makefile

_SRC: $(TARGET)\package\src\makefile
	@cd $(TARGET)\package\src
	@cd
	$(MAKE)

$(TARGET)\package\src\makefile: $(EXNUC)\package\src\src.m
	cd $(EXNUC)\package\src
	$(MAKEMAKE) src.m $(TARGET)\package\src\makefile
