# $Id $  */

#--------------------------------------------------------------------------
#
#  I/ROUTE
#
#  File:        isdp/route/vrtrace/makefile
#
#  Description:
#
#  Dependencies:
#
#  Revision History:
#       $Log $
#
#  History:
#  MM/DD/YY  AUTHOR  DESCRIPTION
#  --------  ------  -----------
#  01/17/01  Anand   File Creation
#
#--------------------------------------------------------------------------

TGT = vrtrace

include ${ROUTE}/etc/makefiles/lib_only.h
