# Do not alter this SPC information: $Revision: 1.17.3.1 $
!include $(RISDEVDIR)\ristools\include\makeenv.nt
!include ..\setupenv.nt

IPATH=	\
	-I$(RISDEVDIR)\riscli\setup32\remove \
	-I$(RISDEVDIR)\riscli\setup32\rmprod \
	-I$(RISDEVDIR)\riscom\internal \
	-I"$(NT_SETUP_DIR)\remove"  \
	-I"$(NT_SETUP_DIR)\csource" \
	-I"$(NT_SETUP_DIR)\csource\bldcui" \
	-I"$(NT_SETUP_DIR)\isdklib"

IPATH_RC=	\
		-I$(RISDEVDIR)\risutl\config\english\icons \
		-I$(RISDEVDIR)\riscom\internal \
		-I"$(NT_SETUP_DIR)\csource\bldcui"

#
# Be sure to remove the -DDONT_VERIFY tag below when building your
# procedure for real!
#
!if "$(DEBUG)" == "yes"
cflags = $(cflags) $(cdebug) $(cvars) -I"$(NT_SETUP_DIR)\setup32" -DDONT_VERIFY -DEBUG -nologo
lflags = $(ldebug)
!else
#cflags = $(cflags) $(cdebug) $(cvars) -I"$(NT_SETUP_DIR)\setup32" -DDONT_VERIFY -nologo
cflags = $(cflags) $(cdebug) $(cvars) -I"$(NT_SETUP_DIR)\setup32" -nologo
# lflags = $(guilflags)
!endif

OBJS=\
..\remove\$(OBJDIR)\ddeprog.obj \
..\remove\$(OBJDIR)\risrem.obj \
..\remove\$(OBJDIR)\ingrrmv.obj \
..\remove\$(OBJDIR)\rissrvc.obj \
..\remove\$(OBJDIR)\reglib.obj \
$(OBJDIR)\intrem.obj \
..\remove\$(OBJDIR)\rmlib.obj \
..\remove\$(OBJDIR)\srvctl.obj \
$(OBJDIR)\interop.res \
$(OBJDIR)\interop.obj


fast: ..\bin\$(BINDIR)\risintop.exe


..\bin\$(BINDIR)\risintop.exe: $(OBJS)  \
		..\bin\$(BINDIR)\risrem.lib \
		$(NT_SETUP_LIBS)
	@echo Making risintop.exe
	$(link) $(guiflags) -machine:i386 -out:$@ \
		$(OBJS) \
		$(NT_SETUP_LIBS) \
		"$(NT_SETUP_DIR)\csource\cingr.lib" \
		$(guilibsdll) \
		advapi32.lib \
		version.lib

$(OBJDIR)\interop.res: interop.rc \
		interop.h \
		intstg.h \
		intver.h \
		$(RISDEVDIR)\risutl\config\english\icons\interop.ico \
		$(RISDEVDIR)\riscom\internal\risver.h
	@echo.
	@echo	$**  -to-  $@
#	rc -DWIN32 -DRISINTOP -DNOT_RISSRV $(IPATH) -r \
#		-fo $(OBJDIR)\interop.res interop.rc
	$(rc) -r /l 0x409 $(rcvars) $(IPATH_RC) -DRISINTOP -DNOT_RISSRV \
		-fo $(OBJDIR)\interop.res $(cvars) interop.rc

$(OBJDIR)\interop.obj: interop.c \
	interop.h \
	..\remove\risrem.h \
	intrem.h \
	intstg.h \
	$(RISDEVDIR)\riscom\internal\risver.h
	@echo.
	@echo	$**  -to-  $@
	$(cc) $(cflags) -DRISINTOP -DNOT_RISSRV $(IPATH) interop.c
	@if exist $@ del $@
	@move $(@F) $@

$(OBJDIR)\intrem.obj: intrem.c \
	$(RISDEVDIR)\riscli\setup32\rmprod\ingrreg.h \
	..\remove\risrem.h \
	$(RISDEVDIR)\riscom\internal\risver.h \
	interop.h \
	intstg.h \
	intrem.h
        @echo Making intrem.obj
        $(cc) -c $(IPATH) $(cdebug) $(cflags) $(cvarsdll) -DRISINTOP -DNOT_RISSRV intrem.c
        @if exist $@ del $@
        @move $(@F) $(@)
