#/* $Id $  */

#/***************************************************************************
# * I/STRUCT
# *
# * File:        isdp/struct/vsbmcs/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log $
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 01/16/01  RR      File Creation
# ***************************************************************************/

TGT = vsbmcs

include ${STRUCT}/etc/makefiles/lib_only.h
