#define		G_INTER		101
#define		G_ORIGIN	39
#define		G_GEN_XAXIS	41
#define		G_XAXIS		44
#define		G_YAXIS		46

#define		G_INT_PLATE_OP0_TEXT	13
#define		G_INT_PLATE_OP1_TEXT	35
#define		G_INT_PLATE_OP2_TEXT	36
#define		G_INT_PLATE_OP3_TEXT	37

#define		G_INT_BEAM_OP0_TEXT	38
#define		G_INT_BEAM_OP1_TEXT	48
#define		G_INT_BEAM_OP2_TEXT	49
#define		G_INT_BEAM_OP3_TEXT	50

#define		G_YAXIS_OP0_TEXT	52
#define		G_YAXIS_OP1_0_TEXT	51
#define		G_YAXIS_OP1_1_TEXT	53
