#!/bin/sh
# This script creates the directories, required for building a new version of GRNUC
#
mkdir -p /usr2/grnuc34/archlib
mkdir -p /usr2/grnuc34/archlib/isl
mkdir -p /usr2/grnuc34/atp
mkdir -p /usr2/grnuc34/atp/GRSvEl
mkdir -p /usr2/grnuc34/atp/dp_macros
mkdir -p /usr2/grnuc34/atp/macros
mkdir -p /usr2/grnuc34/atp/macros/DelVertex
mkdir -p /usr2/grnuc34/atp/macros/FragmentEle
mkdir -p /usr2/grnuc34/atp/macros/GRMAn2Pn
mkdir -p /usr2/grnuc34/atp/macros/GRMAn3Pn
mkdir -p /usr2/grnuc34/atp/macros/GRMAnBt2L
mkdir -p /usr2/grnuc34/atp/macros/GRMAnBt2Pn
mkdir -p /usr2/grnuc34/atp/macros/GRMAnBtLAr
mkdir -p /usr2/grnuc34/atp/macros/GRMAnL
mkdir -p /usr2/grnuc34/atp/macros/GRMArE
mkdir -p /usr2/grnuc34/atp/macros/GRMCmDs
mkdir -p /usr2/grnuc34/atp/macros/GRMDm
mkdir -p /usr2/grnuc34/atp/macros/GRMDsBt2Pn
mkdir -p /usr2/grnuc34/atp/macros/GRMDsBtPn
mkdir -p /usr2/grnuc34/atp/macros/GRMDsBtPnE
mkdir -p /usr2/grnuc34/atp/macros/GRMLnAlE
mkdir -p /usr2/grnuc34/atp/macros/GRMLnE
mkdir -p /usr2/grnuc34/atp/macros/GRMMnDsBt2
mkdir -p /usr2/grnuc34/atp/macros/GRMRE
mkdir -p /usr2/grnuc34/atp/macros/GRMSwAnE
mkdir -p /usr2/grnuc34/atp/macros/GRMsPtProj
mkdir -p /usr2/grnuc34/atp/macros/GRMvEl
mkdir -p /usr2/grnuc34/atp/macros/GRPSyOv
mkdir -p /usr2/grnuc34/atp/macros/GRPlCr
mkdir -p /usr2/grnuc34/atp/macros/GRRvAnRdUn
mkdir -p /usr2/grnuc34/atp/macros/GRRvLnRdUn
mkdir -p /usr2/grnuc34/atp/macros/InsVertex
mkdir -p /usr2/grnuc34/atp/macros/ModAxOfCon
mkdir -p /usr2/grnuc34/atp/macros/ModEle
mkdir -p /usr2/grnuc34/atp/macros/MoveSeg
mkdir -p /usr2/grnuc34/atp/macros/PartDelete
mkdir -p /usr2/grnuc34/atp/macros/PlcArc3Pts
mkdir -p /usr2/grnuc34/atp/macros/PlcArcCenter
mkdir -p /usr2/grnuc34/atp/macros/PlcArcCntRad
mkdir -p /usr2/grnuc34/atp/macros/PlcArcRaTanPT
mkdir -p /usr2/grnuc34/atp/macros/PlcArcRad2Pt
mkdir -p /usr2/grnuc34/atp/macros/PlcArcTnTECD
mkdir -p /usr2/grnuc34/atp/macros/PlcBlockDiag
mkdir -p /usr2/grnuc34/atp/macros/PlcCcirCnRad
mkdir -p /usr2/grnuc34/atp/macros/PlcCir2PtRad
mkdir -p /usr2/grnuc34/atp/macros/PlcCir3Pts
mkdir -p /usr2/grnuc34/atp/macros/PlcCirCenRad
mkdir -p /usr2/grnuc34/atp/macros/PlcCirDiaPts
mkdir -p /usr2/grnuc34/atp/macros/PlcCirRadCen
mkdir -p /usr2/grnuc34/atp/macros/PlcCirTan3El
mkdir -p /usr2/grnuc34/atp/macros/PlcCirTnElCe
mkdir -p /usr2/grnuc34/atp/macros/PlcCirTnElDi
mkdir -p /usr2/grnuc34/atp/macros/PlcEqSpPtEle
mkdir -p /usr2/grnuc34/atp/macros/PlcFillet
mkdir -p /usr2/grnuc34/atp/macros/PlcFilletMan
mkdir -p /usr2/grnuc34/atp/macros/PlcHalfEll
mkdir -p /usr2/grnuc34/atp/macros/PlcNSPolyMp
mkdir -p /usr2/grnuc34/atp/macros/PlcNsidePoly
mkdir -p /usr2/grnuc34/atp/macros/PlcOrthPoly
mkdir -p /usr2/grnuc34/atp/macros/PlcPoint
mkdir -p /usr2/grnuc34/atp/macros/PlcPolygon
mkdir -p /usr2/grnuc34/atp/macros/PlcQrtEll
mkdir -p /usr2/grnuc34/atp/macros/PlcRotBlk
mkdir -p /usr2/grnuc34/atp/macros/PtAlongEle
mkdir -p /usr2/grnuc34/atp/macros/PtDstBt2Pts
mkdir -p /usr2/grnuc34/atp/macros/RAP
mkdir -p /usr2/grnuc34/atp/macros/SplitEle
mkdir -p /usr2/grnuc34/bin
mkdir -p /usr2/grnuc34/cc
mkdir -p /usr2/grnuc34/config
mkdir -p /usr2/grnuc34/config/dload
mkdir -p /usr2/grnuc34/config/dload/cmds
mkdir -p /usr2/grnuc34/config/dload/init
mkdir -p /usr2/grnuc34/config/dload/patch
mkdir -p /usr2/grnuc34/grnuc
mkdir -p /usr2/grnuc34/grnucdp
mkdir -p /usr2/grnuc34/grnucsrc
mkdir -p /usr2/grnuc34/include
mkdir -p /usr2/grnuc34/ingrsys
mkdir -p /usr2/grnuc34/lib
mkdir -p /usr2/grnuc34/lib/isl
mkdir -p /usr2/grnuc34/ppl
mkdir -p /usr2/grnuc34/ppl/bin
mkdir -p /usr2/grnuc34/proto_priv
mkdir -p /usr2/grnuc34/spec
mkdir -p /usr2/grnuc34/src
mkdir -p /usr2/grnuc34/src/IGRdir
mkdir -p /usr2/grnuc34/src/IGRdir/nb
mkdir -p /usr2/grnuc34/src/IGRdir/src
mkdir -p /usr2/grnuc34/src/apis
mkdir -p /usr2/grnuc34/src/apis/ref
mkdir -p /usr2/grnuc34/src/archlib
mkdir -p /usr2/grnuc34/src/archlib/cosrc
mkdir -p /usr2/grnuc34/src/archlib/grsrc
mkdir -p /usr2/grnuc34/src/assoc
mkdir -p /usr2/grnuc34/src/assoc/AStext
mkdir -p /usr2/grnuc34/src/assoc/absg_graph
mkdir -p /usr2/grnuc34/src/assoc/attrib
mkdir -p /usr2/grnuc34/src/assoc/ci_macro
mkdir -p /usr2/grnuc34/src/assoc/cisrc
mkdir -p /usr2/grnuc34/src/assoc/condit
mkdir -p /usr2/grnuc34/src/assoc/copara
mkdir -p /usr2/grnuc34/src/assoc/exec_node
mkdir -p /usr2/grnuc34/src/assoc/expression
mkdir -p /usr2/grnuc34/src/assoc/gopara
mkdir -p /usr2/grnuc34/src/assoc/include_priv
mkdir -p /usr2/grnuc34/src/assoc/macro
mkdir -p /usr2/grnuc34/src/assoc/macro_co
mkdir -p /usr2/grnuc34/src/assoc/nmacro
mkdir -p /usr2/grnuc34/src/assoc/nmacro_co
mkdir -p /usr2/grnuc34/src/assoc/node
mkdir -p /usr2/grnuc34/src/assoc/nodein
mkdir -p /usr2/grnuc34/src/assoc/source
mkdir -p /usr2/grnuc34/src/assoc/super_para
mkdir -p /usr2/grnuc34/src/assoc/symb_mac
mkdir -p /usr2/grnuc34/src/co
mkdir -p /usr2/grnuc34/src/co/adpco
mkdir -p /usr2/grnuc34/src/co/arc
mkdir -p /usr2/grnuc34/src/co/attrco
mkdir -p /usr2/grnuc34/src/co/cct
mkdir -p /usr2/grnuc34/src/co/cob
mkdir -p /usr2/grnuc34/src/co/coglobal
mkdir -p /usr2/grnuc34/src/co/cosup
mkdir -p /usr2/grnuc34/src/co/cr
mkdir -p /usr2/grnuc34/src/co/csco
mkdir -p /usr2/grnuc34/src/co/detailco
mkdir -p /usr2/grnuc34/src/co/displayco
mkdir -p /usr2/grnuc34/src/co/dpbco
mkdir -p /usr2/grnuc34/src/co/dvd
mkdir -p /usr2/grnuc34/src/co/event
mkdir -p /usr2/grnuc34/src/co/eventsco
mkdir -p /usr2/grnuc34/src/co/fenceco
mkdir -p /usr2/grnuc34/src/co/globalco
mkdir -p /usr2/grnuc34/src/co/grgrpco
mkdir -p /usr2/grnuc34/src/co/lineterm
mkdir -p /usr2/grnuc34/src/co/ln
mkdir -p /usr2/grnuc34/src/co/manipco
mkdir -p /usr2/grnuc34/src/co/meas
mkdir -p /usr2/grnuc34/src/co/misc
mkdir -p /usr2/grnuc34/src/co/mod
mkdir -p /usr2/grnuc34/src/co/palco
mkdir -p /usr2/grnuc34/src/co/partco
mkdir -p /usr2/grnuc34/src/co/plotco
mkdir -p /usr2/grnuc34/src/co/poly
mkdir -p /usr2/grnuc34/src/co/projco
mkdir -p /usr2/grnuc34/src/co/pt
mkdir -p /usr2/grnuc34/src/co/ptnco
mkdir -p /usr2/grnuc34/src/co/rattrco
mkdir -p /usr2/grnuc34/src/co/retco
mkdir -p /usr2/grnuc34/src/co/rfco
mkdir -p /usr2/grnuc34/src/co/sl
mkdir -p /usr2/grnuc34/src/co/smartco
mkdir -p /usr2/grnuc34/src/co/symbco
mkdir -p /usr2/grnuc34/src/co/textco
mkdir -p /usr2/grnuc34/src/co/toolco
mkdir -p /usr2/grnuc34/src/co/transco
mkdir -p /usr2/grnuc34/src/co/xhatch
mkdir -p /usr2/grnuc34/src/dcob
mkdir -p /usr2/grnuc34/src/dcob/ceo_gslocate
mkdir -p /usr2/grnuc34/src/dcob/ceo_locate
mkdir -p /usr2/grnuc34/src/dcob/spc
mkdir -p /usr2/grnuc34/src/dim
mkdir -p /usr2/grnuc34/src/dim/cisrc
mkdir -p /usr2/grnuc34/src/dim/dim_angular
mkdir -p /usr2/grnuc34/src/dim/dim_annot
mkdir -p /usr2/grnuc34/src/dim/dim_cenline
mkdir -p /usr2/grnuc34/src/dim/dim_co
mkdir -p /usr2/grnuc34/src/dim/dim_coord
mkdir -p /usr2/grnuc34/src/dim/dim_expr
mkdir -p /usr2/grnuc34/src/dim/dim_linear
mkdir -p /usr2/grnuc34/src/dim/dim_param
mkdir -p /usr2/grnuc34/src/dim/dim_plan
mkdir -p /usr2/grnuc34/src/dim/dim_radial
mkdir -p /usr2/grnuc34/src/dim/dim_root
mkdir -p /usr2/grnuc34/src/dim/dim_sgl
mkdir -p /usr2/grnuc34/src/dim/dim_src
mkdir -p /usr2/grnuc34/src/dim/dim_super
mkdir -p /usr2/grnuc34/src/dim/dim_text
mkdir -p /usr2/grnuc34/src/dim/dim_utils
mkdir -p /usr2/grnuc34/src/display
mkdir -p /usr2/grnuc34/src/display/dl
mkdir -p /usr2/grnuc34/src/display/dlist
mkdir -p /usr2/grnuc34/src/display/grdisplay
mkdir -p /usr2/grnuc34/src/display/grmodule
mkdir -p /usr2/grnuc34/src/display/grwindow
mkdir -p /usr2/grnuc34/src/display/stopsign
mkdir -p /usr2/grnuc34/src/font
mkdir -p /usr2/grnuc34/src/font/fontco
mkdir -p /usr2/grnuc34/src/font/fontmgr
mkdir -p /usr2/grnuc34/src/font/fontutil
mkdir -p /usr2/grnuc34/src/fontbuilder
mkdir -p /usr2/grnuc34/src/fontbuilder/bin
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/CF_src
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/EX_src
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/FF_src
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/FS_src
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/Flib_src
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/UT_src
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/include
mkdir -p /usr2/grnuc34/src/fontbuilder/fconv/lib
mkdir -p /usr2/grnuc34/src/fontbuilder/flib
mkdir -p /usr2/grnuc34/src/fontbuilder/ftbutil
mkdir -p /usr2/grnuc34/src/fontbuilder/notes
mkdir -p /usr2/grnuc34/src/fontbuilder/ppl
mkdir -p /usr2/grnuc34/src/fontbuilder/ppl/bin
mkdir -p /usr2/grnuc34/src/fontbuilder/ppl/cisrc
mkdir -p /usr2/grnuc34/src/gde
mkdir -p /usr2/grnuc34/src/gde/assocattr
mkdir -p /usr2/grnuc34/src/gde/cisrc
mkdir -p /usr2/grnuc34/src/gde/gdedriver
mkdir -p /usr2/grnuc34/src/go
mkdir -p /usr2/grnuc34/src/go/EMSstubs
mkdir -p /usr2/grnuc34/src/go/csgo
mkdir -p /usr2/grnuc34/src/go/detailgo
mkdir -p /usr2/grnuc34/src/go/dsgo
mkdir -p /usr2/grnuc34/src/go/fencego
mkdir -p /usr2/grnuc34/src/go/globalgo
mkdir -p /usr2/grnuc34/src/go/go1
mkdir -p /usr2/grnuc34/src/go/go3d
mkdir -p /usr2/grnuc34/src/go/gosup
mkdir -p /usr2/grnuc34/src/go/graphics
mkdir -p /usr2/grnuc34/src/go/grdglobal
mkdir -p /usr2/grnuc34/src/go/grgrpgo
mkdir -p /usr2/grnuc34/src/go/grsetgo
mkdir -p /usr2/grnuc34/src/go/lcobjgo
mkdir -p /usr2/grnuc34/src/go/ownergo
mkdir -p /usr2/grnuc34/src/go/palgo
mkdir -p /usr2/grnuc34/src/go/partgo
mkdir -p /usr2/grnuc34/src/go/ptngo
mkdir -p /usr2/grnuc34/src/go/ref
mkdir -p /usr2/grnuc34/src/go/rfsup
mkdir -p /usr2/grnuc34/src/go/so
mkdir -p /usr2/grnuc34/src/go/supfungo
mkdir -p /usr2/grnuc34/src/go/symbgo
mkdir -p /usr2/grnuc34/src/go/tablego
mkdir -p /usr2/grnuc34/src/go/test.so
mkdir -p /usr2/grnuc34/src/go/textgo
mkdir -p /usr2/grnuc34/src/go/transgo
mkdir -p /usr2/grnuc34/src/go/undogo
mkdir -p /usr2/grnuc34/src/go/vg
mkdir -p /usr2/grnuc34/src/grdpb
mkdir -p /usr2/grnuc34/src/grdpb/grdpb
mkdir -p /usr2/grnuc34/src/grio
mkdir -p /usr2/grnuc34/src/grio/expreval
mkdir -p /usr2/grnuc34/src/grio/forms
mkdir -p /usr2/grnuc34/src/grio/getevent
mkdir -p /usr2/grnuc34/src/grio/grio_sp
mkdir -p /usr2/grnuc34/src/grio/parse
mkdir -p /usr2/grnuc34/src/grio/units
mkdir -p /usr2/grnuc34/src/grio/uom
mkdir -p /usr2/grnuc34/src/grio/var
mkdir -p /usr2/grnuc34/src/lg
mkdir -p /usr2/grnuc34/src/lg/copyos
mkdir -p /usr2/grnuc34/src/lg/lastprod
mkdir -p /usr2/grnuc34/src/lg/options
mkdir -p /usr2/grnuc34/src/locate
mkdir -p /usr2/grnuc34/src/locate/locate
mkdir -p /usr2/grnuc34/src/pmenu
mkdir -p /usr2/grnuc34/src/pmenu/cisrc
mkdir -p /usr2/grnuc34/src/pop
mkdir -p /usr2/grnuc34/src/popen
mkdir -p /usr2/grnuc34/src/ppl
mkdir -p /usr2/grnuc34/src/ppl/cisrc
mkdir -p /usr2/grnuc34/src/pplsrc
mkdir -p /usr2/grnuc34/src/pplsrc/bin
mkdir -p /usr2/grnuc34/src/pplsrc/cci
mkdir -p /usr2/grnuc34/src/pplsrc/cci/SUNregex
mkdir -p /usr2/grnuc34/src/pplsrc/ciexpr
mkdir -p /usr2/grnuc34/src/pplsrc/cinotify
mkdir -p /usr2/grnuc34/src/pplsrc/com
mkdir -p /usr2/grnuc34/src/pplsrc/executor
mkdir -p /usr2/grnuc34/src/pplsrc/lib
mkdir -p /usr2/grnuc34/src/pplsrc/listener
mkdir -p /usr2/grnuc34/src/pplsrc/setup
mkdir -p /usr2/grnuc34/src/pplsrc/spec
mkdir -p /usr2/grnuc34/src/pplsrc/src
mkdir -p /usr2/grnuc34/src/pplsrc/user_data
mkdir -p /usr2/grnuc34/src/query
mkdir -p /usr2/grnuc34/src/query/parser
mkdir -p /usr2/grnuc34/src/query/sl
mkdir -p /usr2/grnuc34/src/rap
mkdir -p /usr2/grnuc34/src/rap/temp
mkdir -p /usr2/grnuc34/src/raster
mkdir -p /usr2/grnuc34/src/stubs
mkdir -p /usr2/grnuc34/src/stubs/perm
mkdir -p /usr2/grnuc34/src/stubs/temp
mkdir -p /usr2/grnuc34/src/transos
mkdir -p /usr2/grnuc34/src/util
mkdir -p /usr2/grnuc34/src/util/checkcmds
mkdir -p /usr2/grnuc34/src/util/find_msg
mkdir -p /usr2/grnuc34/src/util/genbarmenu
mkdir -p /usr2/grnuc34/src/util/gencmdtbl
mkdir -p /usr2/grnuc34/src/util/listref
mkdir -p /usr2/grnuc34/src/util/misc
mkdir -p /usr2/grnuc34/src/util/revasm
mkdir -p /usr2/grnuc34/src/util/root
mkdir -p /usr2/grnuc34/test
mkdir -p /usr2/grnuc34/test/commands
mkdir -p /usr2/grnuc34/test/commands/ASCrAEx
mkdir -p /usr2/grnuc34/test/commands/GRShDrCmFr
mkdir -p /usr2/grnuc34/test/grio
mkdir -p /usr2/grnuc34/test/grio/units
mkdir -p /usr2/grnuc34/test/grio/units/GRengmet.C
mkdir -p /usr2/grnuc34/test/lib
mkdir -p /usr2/grnuc34/test/strk
mkdir -p /usr2/grnuc34/tr
mkdir -p /usr2/grnuc34/tr/bin
mkdir -p /usr2/grnuc34/tr/config
mkdir -p /usr2/grnuc34/tr/config/english
mkdir -p /usr2/grnuc34/tr/config/english/forms
mkdir -p /usr2/grnuc34/tr/config/english/icons
mkdir -p /usr2/grnuc34/tr/config/message_source
mkdir -p /usr2/grnuc34/tr/grnuc
mkdir -p /usr2/grnuc34/tr/include
mkdir -p /usr2/grnuc34/tr/lib
mkdir -p /usr2/grnuc34/tr/makedir
mkdir -p /usr2/grnuc34/tr/makedir/oplclean
mkdir -p /usr2/grnuc34/tr/trret
mkdir -p /usr2/grnuc34/tr/trsav
mkdir -p /usr2/grnuc34/unix_include
mkdir -p /usr2/grnuc34/unix_include/c100
mkdir -p /usr2/grnuc34/unix_include/c100/sys
mkdir -p /usr2/grnuc34/unix_include/c400
mkdir -p /usr2/grnuc34/unix_include/c400/sys
mkdir -p /usr2/grnuc34/unix_include/isl
mkdir -p /usr2/grnuc34/unix_include/isl/X11
mkdir -p /usr2/grnuc34/unix_include/isl/sys
mkdir -p /usr2/grnuc34/unix_include/sgi
mkdir -p /usr2/grnuc34/unix_include/sgi/GL
mkdir -p /usr2/grnuc34/unix_include/sgi/X11
mkdir -p /usr2/grnuc34/unix_include/sgi/sys
mkdir -p /usr2/grnuc34/unix_include/sun5
mkdir -p /usr2/grnuc34/unix_include/sun5/X11
mkdir -p /usr2/grnuc34/unix_include/sun5/sys
mkdir -p /usr2/grnuc34/unix_include/sunzx
mkdir -p /usr2/grnuc34/unix_include/sunzx/X11
mkdir -p /usr2/grnuc34/unix_include/sunzx/sys
mkdir -p /usr2/grnuc34/userdata
