SRC
$(MODEL)/src_bound/imped
OPP
$(EXTARG)/bin/opp
OMCPP
$(EXTARG)/bin/omcpp
INCLUDE
$(INGRHOME)/include
$(XINC)
$(GRNUC)/ingrsys
$(MODEL)/include
$(EXNUC)/include
$(GRNUC)/include
$(BS)/include
$(BS)/include/prototypes
$(BS)/include/prototypes
#if defined (XGL)
$(XGLHOME)/include
$(XGLHOME)/include/xgl
#endif
SPEC
$(EXNUC)/spec
$(GRNUC)/spec
$(MODEL)/spec
LIB
$(MDTARG)/src_lib/EMSboundedI.o
SOURCE
EMedExecCvF.I
EMedTopInfo.I
EMed_change.I
EMed_config.I
EMed_tangent.I
EMedact.I
EMedarea.I
EMedbdryloc.I
EMedbotedg.I
EMedbstrmint.I
EMedchkbind.I
EMedchkcnvx.I
EMedchkprops.I
EMedchkslivr.I
EMedcncttone.I
EMedcntedg.I
EMedcoinceds.I
EMedcoined.I
EMedcomp_top.I
EMedconnect.I
EMedconstseg.I
EMeddbgdisp.I
EMeddelete.I
EMeddisplay.I
EMeddrop.I
EMeded_move.I
EMedextd_gm.I
EMedextnd.I
EMedfindcvtx.I
EMedgenl_pch.I
EMedget_pln.I
EMedget_tped.I
EMedgeteddef.I
EMedgetedg.I
EMedgetencmp.I
EMedgetlen.I
EMedgetloc.I
EMedgetmedge.I
EMedgetntedg.I
EMedgetobjin.I
EMedgetprops.I
EMedgetsfedg.I
EMedgetsfgm.I
EMedintcopy.I
EMedinternpt.I
EMedissplit.I
EMedkeypoint.I
EMedlocate.I
EMedmk_cmptl.I
EMedmkfcolcp.I
EMedmsc.I
EMedmsgchgp.I
EMedmypar.I
EMedobint.I
EMedoffpt.I
EMedpack.I
EMedpostproc.I
EMedpropty.I
EMedprtread.I
EMedptalong.I
EMedptcoinc.I
EMedputpy.I
EMedrefine.I
EMedreplace.I
EMedreverse.I
EMedrng_edgs.I
EMedrpaccmed.I
EMedset_typ.I
EMedsetprops.I
EMedsfintdat.I
EMedshnk_gm.I
EMedsnddumed.I
EMedspl_twin.I
EMedsplit.I
EMedsrfinfo.I
EMedstitch.I
EMedstrkpy.I
EMedtopoattr.I
EMedtreetrav.I
EMedtrmyours.I
EMedtstcls.I
EMedtstdegn.I
EMedtstrev.I
EMedtwinpar.I
EMedunsplit.I
EMedvalidate.I
EMedvld_prm.I
EMedvt_move.I
EMedvtx_srf.I
EMedvtxedges.I
EMedvtxsfs.I
EMedxyzendpt.I
EMedxyzobj.I
