
/*******
	This file should be used in place of hsurf_import.c to create
	a non-shared version of HSURF (hsurf.o) without having to 
	recompile the code.  The makfile that creates a non-shared
	library is hsurf.m.
*******/


#include <stdio.h>
#include "OMminimum.h"
#include "igrtypedef.h"

extern char	*sbrk();
extern int	getmemsize();
extern char	*getenv();
extern int	nlist();
extern int	mergeZbufferpixelblock();
extern int	putline16();
extern int	lseek();
extern int	GPSetOrthoViewVector();
extern IGRint	DPinq_buf_ptrs();
extern int	bgcolor();
extern int	Inq_displayed_vs();
extern int	Enter_SR();
extern int	Create_SR_area();
extern int	Clear_button_data();
extern int	Alert_box();
extern IGRboolean	BSprintbsps();
extern IGRboolean	BSprintbspc();
extern IGRboolean	BSfreesf();
extern IGRboolean	BSallocsf();
extern short	BSchangepar();
extern void	BScvarreval();
extern void	BScveval();
extern short	BSchrdlkts();
extern int	BSfndsfcsp();
extern short	BSsf_rev();
extern IGRboolean	BSxtractpar();
extern int	BSsfarrev1();
extern int	BSsfarrev0();
extern void	BSsfeval();
extern int	BSsfarrevnd();
extern int	Display_win();
extern int	Delete_SR_area();
extern int	Display_message();
extern int	Enable_events();
extern int	Erase_win();
extern int	Exit_SR();
extern int	Error_box();
extern int	GPEnableZbuffer();
extern int	GPDelete();
extern int	GPBsplineTol();
extern int	GPBsplineMaxPnts();
extern int	GPBsplineCurve();
extern int	GPBsplineTiler();
extern int	GPCreateWin();
extern int	GPSetZclip();
extern int	GPSetLightSource();
extern int	GPPutViewport();
extern int	GPPutMatrix();
extern int	GPInqStatus();
extern int	GPInitZbuffer();
extern int	GPFlushImageBuffer();
extern int	GPGetMatrix();
extern int	GPPolyFill3D();
extern int	GPLinestr3D();
extern int	GPPolyConstShd();
extern int	GPPolySmoothShd();
extern IGRint	GPResetMatrix();
extern int	GPSetDepthCueing();
extern int	GPSetScaleRatios();
extern int	GPSetPerspEyepoint();
extern int	GPSetShadeTable();
extern int	GPSetTransparency();
extern int	Get_button_data();
extern int	Get_keyin_data();
extern int	Inq_vs_info();
extern int	Inq_events();
extern int	Inq_screen_info();
extern int	allocef();
extern int	Read_SR_vlt();
extern int	Load_SR_vlt();
extern int	Inq_win_name();
extern int	Inq_win_region();
extern int	Inq_win_vs();
extern int	Load_symbol_file();
extern int	Mouseposition();
extern int	Loadvlt();
extern int	MSmessage();
extern int	MS_init();
extern int	MS_fix_type();
extern IGRboolean	MAtypemx();
extern IGRboolean	MAoptsxform();
extern IGRboolean	MA2ptdis();
extern IGRboolean	MAcrossvc();
extern IGRdouble	MAatan2();
extern IGRboolean	MAdotvc();
extern IGRboolean	MAinvmx();
extern IGRboolean	MAidmx();
extern IGRboolean	MAptalln();
extern IGRboolean	MAraddeg();
extern IGRboolean	MAptsxform();
extern IGRboolean	MAsincos();
extern int	MS_out_msg();
extern int	MS_onoff();
extern int	Process_keyin();
extern int	Wait_for_events();
extern int	Readvlt();
extern int	Set_win_name();
extern int	Set_keyin_buffer();
extern int	Set_keyboard_buffer();
extern int	UI_prompt();
extern int	UI_status();
extern int	Set_win_vs_swap();
extern int	_filbuf();
extern double	acos();
extern int	hidecursor();
extern int	enableplane();
extern int	drawsymbols();
extern int	blocksave_size();
extern int	blocksave();
extern int	blockrestore();
extern int	blendline();
extern int	blendarea();
extern int	chmod();
extern int	buffer_select();
extern char	*calloc();
extern double	cos();
extern int	close();
extern int	creat();
extern int	fgcolor();
extern int	fclose();
extern int	enter_db();
extern int	exit_db();
extern double	fabs();
extern int	flushbuffer();
extern int	fwrite();
extern long	ftell();
extern int	fseek();
extern int	fread();
extern int	fprintf();
extern int	fscanf();
extern void	free();
extern int	getline();
extern int	openbuffer();
extern int	inquire_vs();
extern void	hl_mark_line();
extern void	hl_display_edge();
extern int	inquire_window();
extern char	*malloc();
extern char	*memset();
extern char	*memcpy();
extern int	rectf();
extern int	polyf();
extern int	putblock();
extern int	printf();
extern char	*realloc();
extern int	putline();
extern int	putpixelblock();
extern int	showcursor();
extern void	sh_zbufshadeline();
extern void	sh_set_bright_edge_tol();
extern void	sh_linestr();
extern void	sh_set_trans_mode();
extern void	sh_set_dither_mode();
extern int	sh_set_delete_mode();
extern void	sh_set_zbuf();
extern void	sh_trap();
extern int	strlen();
extern char	*strcpy();
extern int	sprintf();
extern double	sin();
extern double	sqrt();
extern int	strcmp();
extern int	sscanf();
extern char	*strcat();
extern char	*strchr();
extern int	strspn();
extern int	strncmp();
extern char	*strncpy();
extern char	*tmpnam();
extern int	sleep();
extern int	texture();
extern int	write();
extern int	syscli();
extern long	times();
extern long	time();
extern int	uname();
extern double	pow();
extern int	EGSetZBufferMode();
extern int	EGSetZBuffer();
extern int	EGSetBaseColor();
extern int	EGPolyLine3();
extern int	EGCreateVC();
extern int	EGEvalViewMapMatrix3();
extern int	EGEvalViewOriMatrix3();
extern int	EGSetVCWindow();
extern int	EGSetLightSrcState();
extern int	EGSetLightSrcRep();
extern int	EGSetLightingMode();
extern int	EGSetNPCLimits();
extern int	EGSetViewRep();
extern int	EGSetViewport();
extern void	_EGInitRGB_();
extern int	IGEgetrgbvalue();
extern int	EGTriMeshData3();
extern int	EGSetRenderMethod();
extern int	EGSetNormReorientMode();
extern int	EGSetFaceCullingMode();
extern int	putline32();
extern IGRint	DPinq_buf_ptrs();
extern void	GRsetinqcolcal();
extern int	EGSetObjectProp();
extern int	load_exp_vlt();
extern IGRboolean	BSprptoncv();
extern void	BSsfarrevmt();
extern int	EGDeleteVC();
extern int	EGSetDepthCueMode();
extern int	EGSetDepthCueRep();
extern int	enabledata();
extern int	putlinedata();
extern int	Alloc_vlt();
extern int	IGEinq_term_info();
extern int	IGEreadresclr();
extern int	Inq_activevltno();
extern int	Inq_activevltno();
extern int	Inq_vlt_info();
extern int	Inq_vlt_type();
extern int	Load_allocated_vlt();
extern int	activevltno();
extern int	bgdata();
extern int	convertpixelblock();
extern int	fgdata();
extern int	EGInqViewRep();

/*--- Assign function pointers to point to actual function --------------*/

int	(*_hsurf_EGInqViewRep)()	= EGSetViewRep;
int	(*_hsurf_Alloc_vlt)()	= Alloc_vlt;
int	(*_hsurf_IGEinq_term_info)()	= IGEinq_term_info;
int	(*_hsurf_IGEreadresclr)()	= IGEreadresclr;
int	(*_hsurf_Inq_activevltno)()	= Inq_activevltno;
int	(*_hsurf_Inq_activevltno)()	= Inq_activevltno;
int	(*_hsurf_Inq_vlt_info)()	= Inq_vlt_info;
int	(*_hsurf_Inq_vlt_type)()	= Inq_vlt_type;
int	(*_hsurf_Load_allocated_vlt)()	= Load_allocated_vlt;
int	(*_hsurf_activevltno)()	= activevltno;
int	(*_hsurf_bgdata)()	= bgdata;
int	(*_hsurf_convertpixelblock)()	= convertpixelblock;
int	(*_hsurf_fgdata)()	= fgdata;
int	(*_hsurf_EGDeleteVC)()	= EGDeleteVC;
int	(*_hsurf_EGSetDepthCueMode)()	= EGSetDepthCueMode;
int	(*_hsurf_EGSetDepthCueRep)()	= EGSetDepthCueRep;
int	(*_hsurf_enabledata)()	= enabledata;
int	(*_hsurf_putlinedata)()	= putlinedata;
void	(*_hsurf_BSsfarrevmt)()	= BSsfarrevmt;
IGRboolean	(*_hsurf_BSprptoncv)()	= BSprptoncv;
int	(*_hsurf_load_exp_vlt)()	= load_exp_vlt;
int	(*_hsurf_EGSetObjectProp)()	= EGSetObjectProp;
void	(*_hsurf_GRsetinqcolcal)()	= GRsetinqcolcal;
IGRint	(*_hsurf_DPinq_buf_ptrs)()	= DPinq_buf_ptrs;
int	(*_hsurf_bgcolor)()	= bgcolor;
int	(*_hsurf_Inq_displayed_vs)()	= Inq_displayed_vs;
int	(*_hsurf_Enter_SR)()	= Enter_SR;
int	(*_hsurf_Create_SR_area)()	= Create_SR_area;
int	(*_hsurf_Clear_button_data)()	= Clear_button_data;
int	(*_hsurf_Alert_box)()	= Alert_box;
IGRboolean	(*_hsurf_BSprintbsps)()	= BSprintbsps;
IGRboolean	(*_hsurf_BSprintbspc)()	= BSprintbspc;
IGRboolean	(*_hsurf_BSfreesf)()	= BSfreesf;
IGRboolean	(*_hsurf_BSallocsf)()	= BSallocsf;
short	(*_hsurf_BSchangepar)()	= BSchangepar;
void	(*_hsurf_BScvarreval)()	= BScvarreval;
void	(*_hsurf_BScveval)()	= BScveval;
short	(*_hsurf_BSchrdlkts)()	= BSchrdlkts;
int	(*_hsurf_BSfndsfcsp)()	= BSfndsfcsp;
short	(*_hsurf_BSsf_rev)()	= BSsf_rev;
IGRboolean	(*_hsurf_BSxtractpar)()	= BSxtractpar;
int	(*_hsurf_BSsfarrev1)()	= BSsfarrev1;
int	(*_hsurf_BSsfarrev0)()	= BSsfarrev0;
void	(*_hsurf_BSsfeval)()	= BSsfeval;
int	(*_hsurf_BSsfarrevnd)()	= BSsfarrevnd;
int	(*_hsurf_Display_win)()	= Display_win;
int	(*_hsurf_Delete_SR_area)()	= Delete_SR_area;
int	(*_hsurf_Display_message)()	= Display_message;
int	(*_hsurf_Enable_events)()	= Enable_events;
int	(*_hsurf_Erase_win)()	= Erase_win;
int	(*_hsurf_Exit_SR)()	= Exit_SR;
int	(*_hsurf_Error_box)()	= Error_box;
int	(*_hsurf_GPEnableZbuffer)()	= GPEnableZbuffer;
int	(*_hsurf_GPDelete)()	= GPDelete;
int	(*_hsurf_GPBsplineTol)()	= GPBsplineTol;
int	(*_hsurf_GPBsplineMaxPnts)()	= GPBsplineMaxPnts;
int	(*_hsurf_GPBsplineCurve)()	= GPBsplineCurve;
int	(*_hsurf_GPBsplineTiler)()	= GPBsplineTiler;
int	(*_hsurf_GPCreateWin)()	= GPCreateWin;
int	(*_hsurf_GPSetZclip)()	= GPSetZclip;
int	(*_hsurf_GPSetLightSource)()	= GPSetLightSource;
int	(*_hsurf_GPPutViewport)()	= GPPutViewport;
int	(*_hsurf_GPPutMatrix)()	= GPPutMatrix;
int	(*_hsurf_GPInqStatus)()	= GPInqStatus;
int	(*_hsurf_GPInitZbuffer)()	= GPInitZbuffer;
int	(*_hsurf_GPFlushImageBuffer)()	= GPFlushImageBuffer;
int	(*_hsurf_GPGetMatrix)()	= GPGetMatrix;
int	(*_hsurf_GPPolyFill3D)()	= GPPolyFill3D;
int	(*_hsurf_GPLinestr3D)()	= GPLinestr3D;
int	(*_hsurf_GPPolyConstShd)()	= GPPolyConstShd;
int	(*_hsurf_GPPolySmoothShd)()	= GPPolySmoothShd;
IGRint	(*_hsurf_GPResetMatrix)()	= GPResetMatrix;
int	(*_hsurf_GPSetDepthCueing)()	= GPSetDepthCueing;
int	(*_hsurf_GPSetScaleRatios)()	= GPSetScaleRatios;
int	(*_hsurf_GPSetPerspEyepoint)()	= GPSetPerspEyepoint;
int	(*_hsurf_GPSetShadeTable)()	= GPSetShadeTable;
int	(*_hsurf_GPSetTransparency)()	= GPSetTransparency;
int	(*_hsurf_Get_button_data)()	= Get_button_data;
int	(*_hsurf_Get_keyin_data)()	= Get_keyin_data;
int	(*_hsurf_Inq_vs_info)()	= Inq_vs_info;
int	(*_hsurf_Inq_events)()	= Inq_events;
int	(*_hsurf_Inq_screen_info)()	= Inq_screen_info;
int	(*_hsurf_allocef)()	= allocef;
int	(*_hsurf_Read_SR_vlt)()	= Read_SR_vlt;
int	(*_hsurf_Load_SR_vlt)()	= Load_SR_vlt;
int	(*_hsurf_Inq_win_name)()	= Inq_win_name;
int	(*_hsurf_Inq_win_region)()	= Inq_win_region;
int	(*_hsurf_Inq_win_vs)()	= Inq_win_vs;
int	(*_hsurf_Load_symbol_file)()	= Load_symbol_file;
int	(*_hsurf_Mouseposition)()	= Mouseposition;
int	(*_hsurf_Loadvlt)()	= Loadvlt;
int	(*_hsurf_MSmessage)()	= MSmessage;
int	(*_hsurf_MS_init)()	= MS_init;
int	(*_hsurf_MS_fix_type)()	= MS_fix_type;
IGRboolean	(*_hsurf_MAtypemx)()	= MAtypemx;
IGRboolean	(*_hsurf_MAoptsxform)()	= MAoptsxform;
IGRboolean	(*_hsurf_MA2ptdis)()	= MA2ptdis;
IGRboolean	(*_hsurf_MAcrossvc)()	= MAcrossvc;
IGRdouble	(*_hsurf_MAatan2)()	= MAatan2;
IGRboolean	(*_hsurf_MAdotvc)()	= MAdotvc;
IGRboolean	(*_hsurf_MAinvmx)()	= MAinvmx;
IGRboolean	(*_hsurf_MAidmx)()	= MAidmx;
IGRboolean	(*_hsurf_MAptalln)()	= MAptalln;
IGRboolean	(*_hsurf_MAraddeg)()	= MAraddeg;
IGRboolean	(*_hsurf_MAptsxform)()	= MAptsxform;
IGRboolean	(*_hsurf_MAsincos)()	= MAsincos;
int	(*_hsurf_MS_out_msg)()	= MS_out_msg;
int	(*_hsurf_MS_onoff)()	= MS_onoff;
int	(*_hsurf_Process_keyin)()	= Process_keyin;
int	(*_hsurf_Wait_for_events)()	= Wait_for_events;
int	(*_hsurf_Readvlt)()	= Readvlt;
int	(*_hsurf_Set_win_name)()	= Set_win_name;
int	(*_hsurf_Set_keyin_buffer)()	= Set_keyin_buffer;
int	(*_hsurf_Set_keyboard_buffer)()	= Set_keyboard_buffer;
int	(*_hsurf_UI_prompt)()	= UI_prompt;
int	(*_hsurf_UI_status)()	= UI_status;
int	(*_hsurf_Set_win_vs_swap)()	= Set_win_vs_swap;
FILE	(*_hsurf__iob)[]	= _iob;
int	(*_hsurf__filbuf)()	= _filbuf;
double	(*_hsurf_acos)()	= acos;
int	(*_hsurf_hidecursor)()	= hidecursor;
int	(*_hsurf_enableplane)()	= enableplane;
int	(*_hsurf_drawsymbols)()	= drawsymbols;
int	(*_hsurf_blocksave_size)()	= blocksave_size;
int	(*_hsurf_blocksave)()	= blocksave;
int	(*_hsurf_blockrestore)()	= blockrestore;
int	(*_hsurf_blendline)()	= blendline;
int	(*_hsurf_blendarea)()	= blendarea;
int	(*_hsurf_chmod)()	= chmod;
int	(*_hsurf_buffer_select)()	= buffer_select;
char	*(*_hsurf_calloc)()	= calloc;
double	(*_hsurf_cos)()	= cos;
int	(*_hsurf_close)()	= close;
int	(*_hsurf_creat)()	= creat;
int	(*_hsurf_fgcolor)()	= fgcolor;
int	(*_hsurf_fclose)()	= fclose;
int	(*_hsurf_enter_db)()	= enter_db;
int	(*_hsurf_exit_db)()	= exit_db;
double	(*_hsurf_fabs)()	= fabs;
int	(*_hsurf_flushbuffer)()	= flushbuffer;
int	(*_hsurf_fwrite)()	= fwrite;
FILE	*(*_hsurf_fopen)()	= fopen;
long	(*_hsurf_ftell)()	= ftell;
int	(*_hsurf_fseek)()	= fseek;
int	(*_hsurf_fread)()	= fread;
int	(*_hsurf_fprintf)()	= fprintf;
int	(*_hsurf_fscanf)()	= fscanf;
void	(*_hsurf_free)()	= free;
int	(*_hsurf_getline)()	= getline;
int	(*_hsurf_openbuffer)()	= openbuffer;
int	(*_hsurf_inquire_vs)()	= inquire_vs;
void	(*_hsurf_hl_mark_line)()	= hl_mark_line;
void	(*_hsurf_hl_display_edge)()	= hl_display_edge;
int	(*_hsurf_inquire_window)()	= inquire_window;
char	*(*_hsurf_malloc)()	= malloc;
char	*(*_hsurf_memset)()	= memset;
char	*(*_hsurf_memcpy)()	= memcpy;
int	(*_hsurf_rectf)()	= rectf;
int	(*_hsurf_polyf)()	= polyf;
int	(*_hsurf_putblock)()	= putblock;
int	(*_hsurf_printf)()	= printf;
char	*(*_hsurf_realloc)()	= realloc;
int	(*_hsurf_putline)()	= putline;
int	(*_hsurf_putpixelblock)()	= putpixelblock;
int	(*_hsurf_read_nurb_curve)()	= 0;
int	(*_hsurf_read_nurb_surface)()	= 0;
int	(*_hsurf_showcursor)()	= showcursor;
void	(*_hsurf_sh_zbufshadeline)()	= sh_zbufshadeline;
void	(*_hsurf_sh_set_bright_edge_tol)()	= sh_set_bright_edge_tol;
void	(*_hsurf_sh_linestr)()	= sh_linestr;
void	(*_hsurf_sh_set_trans_mode)()	= sh_set_trans_mode;
void	(*_hsurf_sh_set_dither_mode)()	= sh_set_dither_mode;
int	(*_hsurf_sh_set_delete_mode)()	= sh_set_delete_mode;
void	(*_hsurf_sh_set_zbuf)()	= sh_set_zbuf;
void	(*_hsurf_sh_trap)()	= sh_trap;
int	(*_hsurf_strlen)()	= strlen;
char	*(*_hsurf_strcpy)()	= strcpy;
int	(*_hsurf_sprintf)()	= sprintf;
double	(*_hsurf_sin)()	= sin;
double	(*_hsurf_sqrt)()	= sqrt;
int	(*_hsurf_strcmp)()	= strcmp;
int	(*_hsurf_sscanf)()	= sscanf;
char	*(*_hsurf_strcat)()	= strcat;
char	*(*_hsurf_strchr)()	= strchr;
int	(*_hsurf_strspn)()	= strspn;
int	(*_hsurf_strncmp)()	= strncmp;
char	*(*_hsurf_strncpy)()	= strncpy;
char	*(*_hsurf_tmpnam)()	= tmpnam;
int	(*_hsurf_sys_sleep)()	= sleep;
int	(*_hsurf_texture)()	= texture;
int	(*_hsurf_sys_write)()	= write;
int	(*_hsurf_syscli)()	= syscli;
long	(*_hsurf_times)()	= times;
long	(*_hsurf_time)()	= time;
int	(*_hsurf_uname)()	= uname;

int	(*_hsurf_OM_GA_primitives)	= 0;
int	(*_hsurf_EMSsfimpbnd$EMget_subbs_method_index)	= 0;
int	(*_hsurf_OPP_EMSsfimpbnd_class_id)	= 0;
int	(*_hsurf_NULL_CHANNUM)	= 0;
int	(*_hsurf_NULL_OBJID)	= 0;
int	(*_hsurf_GRvg$GRgetsize_method_index)	= 0;
int	(*_hsurf_OPP_GRvg_class_id)	= 0;
int	(*_hsurf_GRvg$GRgetgeom_method_index)	= 0;
int	(*_hsurf_EMSsubbs$EMget_boundaries_method_index)	= 0;
int	(*_hsurf_OPP_EMSsubbs_class_id)	= 0;
int	(*_hsurf_GRgraphics$GRgetrang_method_index)	= 0;
int	(*_hsurf_OPP_GRgraphics_class_id)	= 0;
int	(*_hsurf_GRowner$GRget_number_components_method_index)	= 0;
int	(*_hsurf_OPP_GRowner_class_id)	= 0;
int	(*_hsurf_GRdpb_get)	= 0;
int	(*_hsurf_GRowner$GRget_components_method_index)	= 0;
int	(*_hsurf_GRvg$GRgetsymb_method_index)	= 0;
int	(*_hsurf_GRvg$GRgenabsg_method_index)	= 0;
int	(*_hsurf_OPP_EMScomposite_class_id)	= 0;
int	(*_hsurf_OPP_GRcompcurve_class_id)	= 0;
int	(*_hsurf_OPP_EMSsurface_class_id)	= 0;
int	(*_hsurf_OPP_GRflxown_class_id)	= 0;
int	(*_hsurf_OPP_GRclhdr_class_id)	= 0;
int	(*_hsurf_OPP_GRsmdfhdr_class_id)	= 0;
int	(*_hsurf_OPP_GRsmhdr_class_id)	= 0;
int	(*_hsurf_GRowner$GRget_matrix_method_index)	= 0;
int	(*_hsurf_OPP_ACcpx_class_id)	= 0;
int	(*_hsurf_GRgs_fun)	= 0;
char	*(*_hsurf_getenv)()	= getenv;
int	(*_hsurf_GRgetrefrange)	= 0;
int	(*_hsurf_GRgetreflevels)	= 0;
int	(*_hsurf_pow)	= pow;
int	(*_hsurf_GPSetOrthoViewVector)	= GPSetOrthoViewVector;
int	(*_hsurf_lseek)()	= lseek;
int	(*_hsurf_putline16)()	= putline16;

OMuword	(*_hsurf_EMSloopset$EMget_props_method_index)	= 0;
OMuword	(*_hsurf_OPP_EMSloopset_class_id)	= 0;
OMuword	(*_hsurf_OPP_AScontents_class_id)	= 0;
int	(*_hsurf_Create_win_no_border)()	= 0;
int	(*_hsurf_Delete_win)()	= 0;
OMuword	(*_hsurf_OM_Gw_current_OS)	= 0;
int	(*_hsurf_IGEconclrtab)()	= 0;
int	(*_hsurf_mergeZbufferpixelblock)()	= mergeZbufferpixelblock;
int	(*_hsurf_sys_nlist)()	= nlist;
int	(*_hsurf_DPget_frame_block)()	= 0;
OMuword	(*_hsurf_OPP_EMSsolid_class_id)	= 0;
int	(*_hsurf_getmemsize)()	= getmemsize;
char	*(*_hsurf_sbrk)()	= sbrk;
int	(*_hsurf_IGEstop)()	= 0;
void	(*_hsurf_IGEresetstop)()	= 0;
OMuword	(*_hsurf_OPP_EMSmassprop_class_id)	= 0;
int	(*_hsurf_EGSetZBufferMode)()	= EGSetZBufferMode;
int	(*_hsurf_EGSetZBuffer)()	= EGSetZBuffer;
int	(*_hsurf_EGSetBaseColor)()	= EGSetBaseColor;
int	(*_hsurf_EGPolyLine3)()	= EGPolyLine3;
int	(*_hsurf_EGCreateVC)()	= EGCreateVC;
int	(*_hsurf_EGSetVCWindow)()	= EGSetVCWindow;
int	(*_hsurf_EGEvalViewMapMatrix3)()	= EGEvalViewMapMatrix3;
int	(*_hsurf_EGEvalViewOriMatrix3)()	= EGEvalViewOriMatrix3;
int	(*_hsurf_EGSetLightSrcState)()	= EGSetLightSrcState;
int	(*_hsurf_EGSetLightSrcRep)()	= EGSetLightSrcRep;
int	(*_hsurf_EGSetLightingMode)()	= EGSetLightingMode;
int	(*_hsurf_EGSetNPCLimits)()	= EGSetNPCLimits;
int	(*_hsurf_EGSetViewRep)()	= EGSetViewRep;
int	(*_hsurf_EGSetViewport)()	= EGSetViewport;
void	(*_hsurf__EGInitRGB_)()	= _EGInitRGB_;
int	(*_hsurf_IGEgetrgbvalue)()	= IGEgetrgbvalue;
int	(*_hsurf_EGTriMeshData3)()	= EGTriMeshData3;
int	(*_hsurf_EGSetRenderMethod)()	= EGSetRenderMethod;
int	(*_hsurf_EGSetNormReorientMode)()	= EGSetNormReorientMode;
int	(*_hsurf_EGSetFaceCullingMode)()	= EGSetFaceCullingMode;
int	(*_hsurf_putline32)()	= putline32;

