[
n_catalogname=round_rod
n_itemname='RB1x0.924'
n_itemrev='aluminium'
n_itemdesc=''
n_creator='nfmadmin'
n_creationdate='04/28/90'
p_parttype='P'
Height=1.000000
n_cofilename='VSmacro'
]
[
n_catalogname=round_rod
n_itemname='RB2x3.695'
n_itemrev='aluminium'
n_itemdesc=''
n_creator='nfmadmin'
n_creationdate='04/28/90'
p_parttype='P'
Height=2.000000
n_cofilename='VSmacro'
]
