#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:07:57 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdbt/imp/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:07:57  cvs
# *      Initial import to CVS
# *
# Revision 1.3  1998/04/09  14:46:46  pinnacle
# ah
#
# Revision 1.1  1998/04/02  23:31:20  pinnacle
# ah
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 03/25/98  ah      creation
# *
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdibtimp.m
	grmakemake vdibtimp.m mkfile
