# $Id: makefile,v 1.1.1.1 2001/01/04 21:08:38 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vds/vddraw/ve/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:08:38  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:32:22  pinnacle
# rep bin w/txt
#
# Revision 1.1  1995/03/16  21:16:48  pinnacle
# Created: vddraw/ve/makefile by azuurhou r#
# rno
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	03/16/95	adz		New makefile
#	10/14/98	ah		Changed make to grmake for Sol 2.6
# -------------------------------------------------------------------

target:
	cd src ;	grmake 
	cd make_sh ;	grmake

