# $Id: makefile,v 1.2 2001/08/20 20:18:06 ad Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:	vdstartup/cmd/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.2  2001/08/20 20:18:06  ad
#	*** empty log message ***
#	
#	Revision 1.1.1.1  2001/01/04 21:09:23  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:43:32  pinnacle
# rep bin w/txt
#
# Revision 1.1  1994/11/14  22:42:32  pinnacle
# Create vds.240 from vds.232
#
# Revision 1.1  1994/11/08  16:07:00  pinnacle
# create vds.232
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#
# -------------------------------------------------------------------


TGT = vdstartcmd

include ${VDS_PATH}/etc/makefiles/lib_only.h
