.SUFFIXES: .S .I .c .o

CC = cc

LINKOPT =

SRC = .

OPPFLAGS =  \
	-I/opt/ingr/bspmathdp/include \
	-I/opt/ingr/bspmathdp/include/prototypes \
	-I/opt/ingr/exnucdp/include \
	-I/opt/ingr/grnucdp/include \
	-I/opt/ingr/pdu/include \
	-I/opt/ingr/nfmdp/include \
	-I/opt/ingr/modeldp/include \
	-I/export/home/isdp/isdp263_08/vds/include \
	-I/export/home/isdp/isdp263_08/vds/vdinclude \
	-I/opt/ingr/exnucdp/spec \
	-I/opt/ingr/grnucdp/spec \
	-I/opt/ingr/modeldp/spec \
	-I/opt/ingr/pdu/spec \
	-I/export/home/isdp/isdp263_08/vds/spec \
	-I$(SRC)

IPATH =  \
	-I/opt/ingr/bspmathdp/include \
	-I/opt/ingr/bspmathdp/include/prototypes \
	-I/opt/ingr/exnucdp/include \
	-I/opt/ingr/grnucdp/include \
	-I/opt/ingr/pdu/include \
	-I/opt/ingr/nfmdp/include \
	-I/opt/ingr/modeldp/include \
	-I/export/home/isdp/isdp263_08/vds/include \
	-I/export/home/isdp/isdp263_08/vds/vdinclude

opp = /opt/ingr/exnucdp/bin/opp

omcpp = /opt/ingr/exnucdp/bin/omcpp

MOPT = -Dsun=1 -D__sun__=1 -Di386=1 -D__i386=1 -D__i386__=1

ocfiles = $(EXTARG)/bin/ocfiles


# Object files 

spec_objects = \
	VDCmdStrtup.o

imp_objects = \
	VDCmdStrtupi.o \
	VDStrtupFnc.o

objects = \
	$(spec_objects) \
	$(imp_objects) 


# src group targets

objects_TARGET = /export/home/isdp/isdp263_08/vds/lib/vdstartcmd.o

$(objects_TARGET): $(objects)
	@echo 
	ld $(LDOPT) -r -o /export/home/isdp/isdp263_08/vds/lib/vdstartcmd.o $(objects)
	@if test -n "$(VERBOSE_RULES)"; then echo "\tls -ls /export/home/isdp/isdp263_08/vds/lib/vdstartcmd.o"; fi; ls -ls /export/home/isdp/isdp263_08/vds/lib/vdstartcmd.o; echo

objects_FAST: FASTstart $(objects) FASTfinish $(objects_TARGET)

VDCmdStrtup.o : \
	$(SRC)/VDCmdStrtup.S \
	/usr/include/sys/isa_defs.h \
	/usr/include/iso/stddef_iso.h \
	/usr/include/stddef.h \
	/opt/ingr/exnucdp/include/OMprimitives.h \
	/opt/ingr/exnucdp/spec/Root.S \
	/opt/ingr/exnucdp/include/OMerrordef.h \
	/opt/ingr/exnucdp/include/exdef.h \
	/opt/ingr/exnucdp/include/OMlimits.h \
	/opt/ingr/exnucdp/include/OMtypes.h \
	/opt/ingr/exnucdp/include/OMminimum.h \
	/opt/ingr/bspmathdp/include/igrtypedef.h \
	/opt/ingr/exnucdp/include/exfi.h \
	/opt/ingr/exnucdp/include/ex.h \
	/opt/ingr/exnucdp/include/igrtypedef.h \
	/opt/ingr/bspmathdp/include/msdef.h \
	/opt/ingr/exnucdp/include/exms.h \
	/opt/ingr/exnucdp/include/msdef.h \
	/opt/ingr/exnucdp/include/msmacros.h \
	/opt/ingr/exnucdp/spec/super_cmd.S

VDCmdStrtupi.o : \
	$(SRC)/VDCmdStrtupi.I \
	/opt/ingr/exnucdp/spec/Root.S \
	/opt/ingr/exnucdp/spec/super_cmd.S \
	/export/home/isdp/isdp263_08/vds/spec/VDCmdStrtup.S \
	/usr/include/sys/dirent.h \
	/usr/include/dirent.h \
	/opt/ingr/exnucdp/include/DItypedef.h \
	/opt/ingr/exnucdp/include/DIglob.h \
	/usr/include/malloc.h \
	/opt/ingr/exnucdp/include/DIprims.h \
	/opt/ingr/exnucdp/include/version.h \
	/opt/ingr/exnucdp/include/EXproduct.h \
	/opt/ingr/grnucdp/include/ciexecdef.h \
	/opt/ingr/grnucdp/include/ciexecmacros.h \
	/opt/ingr/exnucdp/include/ms.h \
	/opt/ingr/grnucdp/include/grlicense.h \
	/opt/ingr/grnucdp/include/GMhcode.h \
	/opt/ingr/grnucdp/include/GMlist.h \
	/opt/ingr/grnucdp/include/GM.h \
	/opt/ingr/grnucdp/include/GMmacros.h \
	/opt/ingr/grnucdp/include/ndmacros.h \
	/opt/ingr/grnucdp/include/acdef.h \
	/opt/ingr/grnucdp/include/acmacros.h \
	/opt/ingr/grnucdp/include/acrepdef.h \
	/opt/ingr/grnucdp/include/acrepmacros.h \
	/export/home/isdp/isdp263_08/vds/include/VDmsg.h \
	/export/home/isdp/isdp263_08/vds/include/vdprdmacros.h \
	/export/home/isdp/isdp263_08/vds/include/v_slcdef.h \
	/export/home/isdp/isdp263_08/vds/include/v_slc.h \
	/export/home/isdp/isdp263_08/vds/include/v_pplslc.h \
	/export/home/isdp/isdp263_08/vds/include/VDppl1.h \
	/export/home/isdp/isdp263_08/vds/include/VDpdmDef.h \
	/export/home/isdp/isdp263_08/vds/include/VDpdm.h \
	/export/home/isdp/isdp263_08/vds/include/v_.h \
	/opt/ingr/bspmathdp/include/igrdef.h \
	/export/home/isdp/isdp263_08/vds/include/dp.h \
	/opt/ingr/grnucdp/include/lcdef.h \
	/opt/ingr/grnucdp/include/lc.h \
	/export/home/isdp/isdp263_08/vds/include/v_cmd.h \
	/export/home/isdp/isdp263_08/vds/include/v_globals.h \
	/opt/ingr/bspmathdp/include/bsdbg.h \
	/export/home/isdp/isdp263_08/vds/include/VDmem.h \
	/export/home/isdp/isdp263_08/vds/include/v_miscmacros.h \
	/export/home/isdp/isdp263_08/vds/include/vIdbgmacros.h \
	/export/home/isdp/isdp263_08/vds/include/v_dbgmacros.h \
	/export/home/isdp/isdp263_08/vds/include/v_datamacros.h \
	/opt/ingr/grnucdp/include/exdate.h \
	/opt/ingr/grnucdp/include/exvers.h \
	/export/home/isdp/isdp263_08/vds/vdinclude/VDdebug.h \
	/usr/include/FI.h \
	/usr/include/FIdyn.h \
	/usr/include/MI.h \
	/usr/include/XFIproto_pub.h \
	/export/home/isdp/isdp263_08/vds/include/VX_FIproto.h \
	/export/home/isdp/isdp263_08/vds/include/VDfld.h \
	/usr/include/sys/va_list.h \
	/usr/include/stdio_impl.h \
	/usr/include/iso/stdio_iso.h \
	/usr/include/stdio.h \
	/export/home/isdp/isdp263_08/vds/include/standards.h \
	/usr/include/iso/stdlib_iso.h \
	/usr/include/sys/procset.h \
	/usr/include/sys/wait.h \
	/usr/include/stdlib.h \
	/usr/include/iso/math_iso.h \
	/usr/include/stdio_tag.h \
	/usr/include/sys/ieeefp.h \
	/usr/include/floatingpoint.h \
	/usr/include/math.h \
	/opt/ingr/exnucdp/include/OMerrordef.h \
	/opt/ingr/exnucdp/include/OMprimitives.h \
	/opt/ingr/exnucdp/include/OMcluster.h \
	/opt/ingr/exnucdp/include/OMmacros.h \
	/opt/ingr/exnucdp/include/igetypedef.h \
	/opt/ingr/grnucdp/include/grerr.h \
	/opt/ingr/grnucdp/include/growner.h \
	/opt/ingr/bspmathdp/include/maerr.h \
	/opt/ingr/bspmathdp/include/madef.h \
	/opt/ingr/grnucdp/include/godef.h \
	/opt/ingr/grnucdp/include/sunlimits.h \
	/opt/ingr/exnucdp/include/DIdef.h \
	/opt/ingr/grnucdp/include/go.h \
	/opt/ingr/exnucdp/include/exdef.h \
	/usr/include/X11/StringDefs.h \
	/usr/include/X11/CoreP.h \
	/usr/include/X11/CompositeP.h \
	/usr/include/X11/ConstrainP.h \
	/usr/include/X11/ObjectP.h \
	/usr/include/X11/RectObjP.h \
	/usr/include/X11/IntrinsicP.h \
	/usr/include/X11/extensions/multibuf.h \
	/usr/include/X11/extensions/transovl.h \
	/opt/ingr/exnucdp/include/wl.h \
	/usr/include/X11/Xmd.h \
	/usr/include/X11/X.h \
	/usr/include/iso/stddef_iso.h \
	/usr/include/stddef.h \
	/usr/include/X11/Xlib.h \
	/usr/include/X11/Xutil.h \
	/usr/include/X11/Xresource.h \
	/usr/include/X11/Xfuncproto.h \
	/usr/include/X11/Xw32defs.h \
	/usr/include/sys/resource.h \
	/usr/include/sys/auxv.h \
	/usr/include/sys/errno.h \
	/usr/include/sys/cred.h \
	/usr/include/vm/seg_enum.h \
	/usr/include/sys/kstat.h \
	/usr/include/sys/buf.h \
	/usr/include/sys/aio_req.h \
	/usr/include/sys/uio.h \
	/usr/include/sys/copyops.h \
	/usr/include/sys/watchpoint.h \
	/usr/include/sys/pcb.h \
	/usr/include/sys/msacct.h \
	/usr/include/sys/synch.h \
	/usr/include/sys/lwp.h \
	/usr/include/sys/klwp.h \
	/usr/include/sys/iso/signal_iso.h \
	/usr/include/vm/faultcode.h \
	/usr/include/sys/machsig.h \
	/usr/include/sys/siginfo.h \
	/usr/include/sys/ucontext.h \
	/usr/include/sys/machlock.h \
	/usr/include/sys/rwlock.h \
	/usr/include/sys/semaphore.h \
	/usr/include/sys/condvar.h \
	/usr/include/sys/t_lock.h \
	/usr/include/sys/signal.h \
	/usr/include/sys/thread.h \
	/usr/include/sys/timer.h \
	/usr/include/sys/segment.h \
	/usr/include/sys/utrap.h \
	/usr/include/sys/debug.h \
	/usr/include/sys/model.h \
	/usr/include/sys/refstr.h \
	/usr/include/sys/param.h \
	/usr/include/sys/id_space.h \
	/usr/include/sys/exacct_impl.h \
	/usr/include/sys/vmem.h \
	/usr/include/sys/kmem.h \
	/usr/include/sys/task.h \
	/usr/include/sys/proc.h \
	/usr/include/ia32/sys/reg.h \
	/usr/include/ia32/sys/stack.h \
	/usr/include/ia64/sys/stack.h \
	/usr/include/sys/stack.h \
	/usr/include/ia64/sys/reg.h \
	/usr/include/sys/reg.h \
	/usr/include/sys/regset.h \
	/usr/include/sys/user.h \
	/usr/include/sys/file.h \
	/usr/include/sys/time_std_impl.h \
	/usr/include/sys/stat_impl.h \
	/usr/include/sys/stat.h \
	/usr/include/sys/fcntl.h \
	/usr/include/fcntl.h \
	/usr/include/sys/unistd.h \
	/usr/include/unistd.h \
	/usr/include/sys/timeb.h \
	/usr/include/X11/Xos.h \
	/usr/include/X11/Xosdefs.h \
	/usr/include/ia32/sys/machtypes.h \
	/usr/include/ia64/sys/machtypes.h \
	/usr/include/sys/machtypes.h \
	/usr/include/sys/int_limits.h \
	/usr/include/sys/int_const.h \
	/usr/include/sys/int_fmtio.h \
	/usr/include/sys/inttypes.h \
	/usr/include/sys/mutex.h \
	/usr/include/iso/time_iso.h \
	/usr/include/sys/int_types.h \
	/usr/include/sys/types32.h \
	/usr/include/sys/time_impl.h \
	/usr/include/time.h \
	/usr/include/sys/time.h \
	/usr/include/sys/select.h \
	/usr/include/sys/types.h \
	/usr/include/sys/isa_defs.h \
	/usr/include/sys/feature_tests.h \
	/usr/include/iso/string_iso.h \
	/usr/include/string.h \
	/usr/include/strings.h \
	/usr/include/X11/Core.h \
	/usr/include/X11/Composite.h \
	/usr/include/X11/Constraint.h \
	/usr/include/X11/Object.h \
	/usr/include/X11/RectObj.h \
	/usr/include/X11/Intrinsic.h \
	/opt/ingr/exnucdp/include/exproto.h \
	/opt/ingr/exnucdp/include/exmacros.h \
	/opt/ingr/grnucdp/include/griodef.h \
	/opt/ingr/grnucdp/include/grio.h \
	/opt/ingr/exnucdp/include/OMlimits.h \
	/opt/ingr/exnucdp/include/OMtypes.h \
	/opt/ingr/exnucdp/include/OMminimum.h \
	/opt/ingr/exnucdp/include/exfi.h \
	/opt/ingr/exnucdp/include/ex.h \
	/opt/ingr/grnucdp/include/igrdp.h \
	/opt/ingr/grnucdp/include/gr.h \
	/opt/ingr/grnucdp/include/grdpbdef.h \
	/opt/ingr/grnucdp/include/grdpb.h \
	/opt/ingr/grnucdp/include/grdpbmacros.h \
	/opt/ingr/grnucdp/include/EMSdpb.h \
	/opt/ingr/grnucdp/include/grmacros.h \
	/export/home/isdp/isdp263_08/vds/include/parametric.h \
	/opt/ingr/grnucdp/include/ACrg_collect.h \
	/opt/ingr/grnucdp/include/ACattrib.h \
	/opt/ingr/exnucdp/include/igrtypedef.h \
	/opt/ingr/bspmathdp/include/msdef.h \
	/opt/ingr/exnucdp/include/exms.h \
	/opt/ingr/exnucdp/include/msdef.h \
	/opt/ingr/exnucdp/include/msmacros.h \
	/opt/ingr/bspmathdp/include/igrtypedef.h \
	/opt/ingr/bspmathdp/include/igr.h \
	/opt/ingr/bspmathdp/include/bstypes.h \
	/opt/ingr/bspmathdp/include/bserr.h \
	/opt/ingr/grnucdp/include/GMdef.h \
	/opt/ingr/grnucdp/include/nddef.h \
	/export/home/isdp/isdp263_08/vds/include/VDtypedef.h \
	/export/home/isdp/isdp263_08/vds/include/VDvla.h \
	/export/home/isdp/isdp263_08/vds/include/VDobj.h \
	/export/home/isdp/isdp263_08/vds/include/VDsa.h \
	/export/home/isdp/isdp263_08/vds/include/VDsaProto.h

VDStrtupFnc.o : \
	$(SRC)/VDStrtupFnc.I \
	/opt/ingr/exnucdp/spec/Root.S \
	/opt/ingr/exnucdp/spec/super_cmd.S \
	/export/home/isdp/isdp263_08/vds/spec/VDCmdStrtup.S \
	/usr/include/sys/dirent.h \
	/usr/include/dirent.h \
	/opt/ingr/exnucdp/include/DItypedef.h \
	/opt/ingr/exnucdp/include/DIglob.h \
	/usr/include/malloc.h \
	/opt/ingr/exnucdp/include/DIprims.h \
	/opt/ingr/exnucdp/include/version.h \
	/opt/ingr/exnucdp/include/EXproduct.h \
	/opt/ingr/grnucdp/include/ciexecdef.h \
	/opt/ingr/grnucdp/include/ciexecmacros.h \
	/opt/ingr/exnucdp/include/ms.h \
	/opt/ingr/grnucdp/include/grlicense.h \
	/opt/ingr/grnucdp/include/GMhcode.h \
	/opt/ingr/grnucdp/include/GMlist.h \
	/opt/ingr/grnucdp/include/GM.h \
	/opt/ingr/grnucdp/include/GMmacros.h \
	/opt/ingr/grnucdp/include/ndmacros.h \
	/opt/ingr/grnucdp/include/acdef.h \
	/opt/ingr/grnucdp/include/acmacros.h \
	/opt/ingr/grnucdp/include/acrepdef.h \
	/opt/ingr/grnucdp/include/acrepmacros.h \
	/export/home/isdp/isdp263_08/vds/include/VDmsg.h \
	/export/home/isdp/isdp263_08/vds/include/vdprdmacros.h \
	/export/home/isdp/isdp263_08/vds/include/v_slcdef.h \
	/export/home/isdp/isdp263_08/vds/include/v_slc.h \
	/export/home/isdp/isdp263_08/vds/include/v_pplslc.h \
	/export/home/isdp/isdp263_08/vds/include/VDppl1.h \
	/export/home/isdp/isdp263_08/vds/include/VDpdmDef.h \
	/export/home/isdp/isdp263_08/vds/include/VDpdm.h \
	/export/home/isdp/isdp263_08/vds/include/v_.h \
	/opt/ingr/bspmathdp/include/igrdef.h \
	/export/home/isdp/isdp263_08/vds/include/dp.h \
	/opt/ingr/grnucdp/include/lcdef.h \
	/opt/ingr/grnucdp/include/lc.h \
	/export/home/isdp/isdp263_08/vds/include/v_cmd.h \
	/export/home/isdp/isdp263_08/vds/include/v_globals.h \
	/opt/ingr/bspmathdp/include/bsdbg.h \
	/export/home/isdp/isdp263_08/vds/include/VDmem.h \
	/export/home/isdp/isdp263_08/vds/include/v_miscmacros.h \
	/export/home/isdp/isdp263_08/vds/include/vIdbgmacros.h \
	/export/home/isdp/isdp263_08/vds/include/v_dbgmacros.h \
	/export/home/isdp/isdp263_08/vds/include/v_datamacros.h \
	/opt/ingr/grnucdp/include/exdate.h \
	/opt/ingr/grnucdp/include/exvers.h \
	/usr/include/FI.h \
	/usr/include/FIdyn.h \
	/usr/include/MI.h \
	/usr/include/XFIproto_pub.h \
	/export/home/isdp/isdp263_08/vds/include/VX_FIproto.h \
	/export/home/isdp/isdp263_08/vds/include/VDfld.h \
	/usr/include/sys/va_list.h \
	/usr/include/stdio_impl.h \
	/usr/include/iso/stdio_iso.h \
	/usr/include/stdio.h \
	/export/home/isdp/isdp263_08/vds/include/standards.h \
	/usr/include/iso/stdlib_iso.h \
	/usr/include/sys/procset.h \
	/usr/include/sys/wait.h \
	/usr/include/stdlib.h \
	/usr/include/iso/math_iso.h \
	/usr/include/stdio_tag.h \
	/usr/include/sys/ieeefp.h \
	/usr/include/floatingpoint.h \
	/usr/include/math.h \
	/opt/ingr/exnucdp/include/OMerrordef.h \
	/opt/ingr/exnucdp/include/OMprimitives.h \
	/opt/ingr/exnucdp/include/OMcluster.h \
	/opt/ingr/exnucdp/include/OMmacros.h \
	/opt/ingr/exnucdp/include/igetypedef.h \
	/opt/ingr/grnucdp/include/grerr.h \
	/opt/ingr/grnucdp/include/growner.h \
	/opt/ingr/bspmathdp/include/maerr.h \
	/opt/ingr/bspmathdp/include/madef.h \
	/opt/ingr/grnucdp/include/godef.h \
	/opt/ingr/grnucdp/include/sunlimits.h \
	/opt/ingr/exnucdp/include/DIdef.h \
	/opt/ingr/grnucdp/include/go.h \
	/opt/ingr/exnucdp/include/exdef.h \
	/usr/include/X11/StringDefs.h \
	/usr/include/X11/CoreP.h \
	/usr/include/X11/CompositeP.h \
	/usr/include/X11/ConstrainP.h \
	/usr/include/X11/ObjectP.h \
	/usr/include/X11/RectObjP.h \
	/usr/include/X11/IntrinsicP.h \
	/usr/include/X11/extensions/multibuf.h \
	/usr/include/X11/extensions/transovl.h \
	/opt/ingr/exnucdp/include/wl.h \
	/usr/include/X11/Xmd.h \
	/usr/include/X11/X.h \
	/usr/include/iso/stddef_iso.h \
	/usr/include/stddef.h \
	/usr/include/X11/Xlib.h \
	/usr/include/X11/Xutil.h \
	/usr/include/X11/Xresource.h \
	/usr/include/X11/Xfuncproto.h \
	/usr/include/X11/Xw32defs.h \
	/usr/include/sys/resource.h \
	/usr/include/sys/auxv.h \
	/usr/include/sys/errno.h \
	/usr/include/sys/cred.h \
	/usr/include/vm/seg_enum.h \
	/usr/include/sys/kstat.h \
	/usr/include/sys/buf.h \
	/usr/include/sys/aio_req.h \
	/usr/include/sys/uio.h \
	/usr/include/sys/copyops.h \
	/usr/include/sys/watchpoint.h \
	/usr/include/sys/pcb.h \
	/usr/include/sys/msacct.h \
	/usr/include/sys/synch.h \
	/usr/include/sys/lwp.h \
	/usr/include/sys/klwp.h \
	/usr/include/sys/iso/signal_iso.h \
	/usr/include/vm/faultcode.h \
	/usr/include/sys/machsig.h \
	/usr/include/sys/siginfo.h \
	/usr/include/sys/ucontext.h \
	/usr/include/sys/machlock.h \
	/usr/include/sys/rwlock.h \
	/usr/include/sys/semaphore.h \
	/usr/include/sys/condvar.h \
	/usr/include/sys/t_lock.h \
	/usr/include/sys/signal.h \
	/usr/include/sys/thread.h \
	/usr/include/sys/timer.h \
	/usr/include/sys/segment.h \
	/usr/include/sys/utrap.h \
	/usr/include/sys/debug.h \
	/usr/include/sys/model.h \
	/usr/include/sys/refstr.h \
	/usr/include/sys/param.h \
	/usr/include/sys/id_space.h \
	/usr/include/sys/exacct_impl.h \
	/usr/include/sys/vmem.h \
	/usr/include/sys/kmem.h \
	/usr/include/sys/task.h \
	/usr/include/sys/proc.h \
	/usr/include/ia32/sys/reg.h \
	/usr/include/ia32/sys/stack.h \
	/usr/include/ia64/sys/stack.h \
	/usr/include/sys/stack.h \
	/usr/include/ia64/sys/reg.h \
	/usr/include/sys/reg.h \
	/usr/include/sys/regset.h \
	/usr/include/sys/user.h \
	/usr/include/sys/file.h \
	/usr/include/sys/time_std_impl.h \
	/usr/include/sys/stat_impl.h \
	/usr/include/sys/stat.h \
	/usr/include/sys/fcntl.h \
	/usr/include/fcntl.h \
	/usr/include/sys/unistd.h \
	/usr/include/unistd.h \
	/usr/include/sys/timeb.h \
	/usr/include/X11/Xos.h \
	/usr/include/X11/Xosdefs.h \
	/usr/include/ia32/sys/machtypes.h \
	/usr/include/ia64/sys/machtypes.h \
	/usr/include/sys/machtypes.h \
	/usr/include/sys/int_limits.h \
	/usr/include/sys/int_const.h \
	/usr/include/sys/int_fmtio.h \
	/usr/include/sys/inttypes.h \
	/usr/include/sys/mutex.h \
	/usr/include/iso/time_iso.h \
	/usr/include/sys/int_types.h \
	/usr/include/sys/types32.h \
	/usr/include/sys/time_impl.h \
	/usr/include/time.h \
	/usr/include/sys/time.h \
	/usr/include/sys/select.h \
	/usr/include/sys/types.h \
	/usr/include/sys/isa_defs.h \
	/usr/include/sys/feature_tests.h \
	/usr/include/iso/string_iso.h \
	/usr/include/string.h \
	/usr/include/strings.h \
	/usr/include/X11/Core.h \
	/usr/include/X11/Composite.h \
	/usr/include/X11/Constraint.h \
	/usr/include/X11/Object.h \
	/usr/include/X11/RectObj.h \
	/usr/include/X11/Intrinsic.h \
	/opt/ingr/exnucdp/include/exproto.h \
	/opt/ingr/exnucdp/include/exmacros.h \
	/opt/ingr/grnucdp/include/griodef.h \
	/opt/ingr/grnucdp/include/grio.h \
	/opt/ingr/exnucdp/include/OMlimits.h \
	/opt/ingr/exnucdp/include/OMtypes.h \
	/opt/ingr/exnucdp/include/OMminimum.h \
	/opt/ingr/exnucdp/include/exfi.h \
	/opt/ingr/exnucdp/include/ex.h \
	/opt/ingr/grnucdp/include/igrdp.h \
	/opt/ingr/grnucdp/include/gr.h \
	/opt/ingr/grnucdp/include/grdpbdef.h \
	/opt/ingr/grnucdp/include/grdpb.h \
	/opt/ingr/grnucdp/include/grdpbmacros.h \
	/opt/ingr/grnucdp/include/EMSdpb.h \
	/opt/ingr/grnucdp/include/grmacros.h \
	/export/home/isdp/isdp263_08/vds/include/parametric.h \
	/opt/ingr/grnucdp/include/ACrg_collect.h \
	/opt/ingr/grnucdp/include/ACattrib.h \
	/opt/ingr/exnucdp/include/igrtypedef.h \
	/opt/ingr/bspmathdp/include/msdef.h \
	/opt/ingr/exnucdp/include/exms.h \
	/opt/ingr/exnucdp/include/msdef.h \
	/opt/ingr/exnucdp/include/msmacros.h \
	/opt/ingr/bspmathdp/include/igrtypedef.h \
	/opt/ingr/bspmathdp/include/igr.h \
	/opt/ingr/bspmathdp/include/bstypes.h \
	/opt/ingr/bspmathdp/include/bserr.h \
	/opt/ingr/grnucdp/include/GMdef.h \
	/opt/ingr/grnucdp/include/nddef.h \
	/export/home/isdp/isdp263_08/vds/include/VDtypedef.h \
	/export/home/isdp/isdp263_08/vds/include/VDvla.h \
	/export/home/isdp/isdp263_08/vds/include/VDobj.h \
	/export/home/isdp/isdp263_08/vds/include/VDsa.h \
	/export/home/isdp/isdp263_08/vds/include/VDsaProto.h

$(spec_objects):
	@if [ "$(WHY)" ]; then echo "\t$(@): $?"; fi
	@if [ -n "$(@D)" -a "$(@D)" != "." ]; \
	 then \
	     if [ -n "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\tcd $(@D)"; \
	     fi; \
	     cd $(@D); \
	 fi; \
	 if [ "$(FAST)" ]; \
	 then \
	     if [ -f $(@) ]; then rm $(@); fi; \
	     echo "\t$(@:.o=.S) -> opp.list\c"; \
	     echo "$(@:.o=.S)" >>opp.list; \
	 else \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$(SRC)/$(@:.o=.S) -> $(@:.o=.c)"; \
	     fi; \
	     if [ -n "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $(@:.o=.S)"; \
	     fi; \
	     $(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $(@:.o=.S); \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$(@:.o=.c) -> $(@)"; \
	     else \
	         echo "\t$(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $(@F:.o=.c)"; \
	     fi; \
	     $(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $(@F:.o=.c); \
	     if [ "$(COPT)" != "-g" -a "$(DEBUG)" != "yes" ]; \
	     then \
	         if [ -z "$(VERBOSE_RULES)" ]; \
	         then \
	             echo "\tremoving $(@:.o=.c)"; \
	         else \
	             echo "\trm $(@F:.o=.c)"; \
	         fi; \
	         rm $(@F:.o=.c); \
	     else \
	         if [ -z "$(VERBOSE_RULES)" ]; \
	         then \
	             echo "\tleaving $(@:.o=.c)"; \
	         fi; \
	     fi; \
	 fi
	@echo 

$(imp_objects):
	@if [ "$(WHY)" ]; then echo "\t$(@): $?"; fi
	@if [ -n "$(@D)" -a "$(@D)" != "." ]; \
	 then \
	     if [ -n "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\tcd $(@D)"; \
	     fi; \
	     cd $(@D); \
	 fi; \
	 if [ "$(FAST)" ]; \
	 then \
	     if [ -f $(@) ]; then rm $(@); fi; \
	     echo "\t$(@:.o=.I) -> opp.list\c"; \
	     echo "$(@:.o=.I)" >>opp.list; \
	 else \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$(SRC)/$(@:.o=.I) -> $(@:.o=.c)"; \
	     fi; \
	     if [ -n "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $(@:.o=.I)"; \
	     fi; \
	     $(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $(@:.o=.I); \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$(@:.o=.c) -> $(@)"; \
	     else \
	         echo "\t$(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $(@F:.o=.c)"; \
	     fi; \
	     $(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $(@F:.o=.c); \
	     if [ "$(COPT)" != "-g" -a "$(DEBUG)" != "yes" ]; \
	     then \
	         if [ -z "$(VERBOSE_RULES)" ]; \
	         then \
	             echo "\tremoving $(@:.o=.c)"; \
	         else \
	             echo "\trm $(@F:.o=.c)"; \
	         fi; \
	         rm $(@F:.o=.c); \
	     else \
	         if [ -z "$(VERBOSE_RULES)" ]; \
	         then \
	             echo "\tleaving $(@:.o=.c)"; \
	         fi; \
	     fi; \
	 fi
	@echo 

.I.o:
	@if [ "$(WHY)" ]; then echo "\t$<: $?"; fi
	@if [ "$(FAST)" ]; \
	 then \
	     if [ -f $(@) ]; then rm $(@); fi; \
	     echo "\t$< -> opp.list\c"; \
	     echo "$<" >>opp.list; \
	 else \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$< -> $*.c"; \
	     else \
	         echo "\t$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $<"; \
	     fi; \
	     $(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $<; \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$*.c -> $*.o"; \
	     else \
	         echo "\t$(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c"; \
	     fi; \
	     $(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c;  \
	     if [ "$(COPT)" != "-g" -a "$(DEBUG)" != "yes" ]; \
	     then \
	        if [ -z "$(VERBOSE_RULES)" ]; \
	        then \
	            echo "\tremoving $*.c"; \
	        else \
	            echo "\trm $*.c"; \
	        fi; \
	        rm $*.c; \
	     else \
	        if [ -z "$(VERBOSE_RULES)" ]; \
	        then \
	            echo "\tleaving $*.c"; \
	        fi; \
	     fi; \
	 fi
	@echo 

.S.o:
	@if [ "$(WHY)" ]; then echo "\t$<: $?"; fi
	@if [ "$(FAST)" ]; \
	 then \
	     if [ -f $(@) ]; then rm $(@); fi; \
	     echo "\t$< -> opp.list\c"; \
	     echo "$<" >>opp.list; \
	 else \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$< -> $*.c"; \
	     else \
	         echo "\t$(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $<"; \
	     fi; \
	     $(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) $<; \
	     if [ -z "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\t$*.c -> $*.o"; \
	     else \
	         echo "\t$(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c"; \
	     fi; \
	     $(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c;  \
	     if [ "$(COPT)" != "-g" -a "$(DEBUG)" != "yes" ]; \
	     then \
	        if [ -z "$(VERBOSE_RULES)" ]; \
	        then \
	            echo "\tremoving $*.c"; \
	        else \
	            echo "\trm $*.c"; \
	        fi; \
	        rm $*.c; \
	     else \
	        if [ -z "$(VERBOSE_RULES)" ]; \
	        then \
	            echo "\tleaving $*.c"; \
	        fi; \
	     fi; \
	 fi
	@echo 

.c.o:
	@if [ "$(WHY)" ]; then echo "\t$<: $?"; fi
	@if [ -z "$(VERBOSE_RULES)" ]; \
	 then \
	     echo "\t$< -> $*.o"; \
	 else \
	     echo "\t$(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c"; \
	 fi
	@$(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c $*.c
	@echo 

FASTstart:
	@rm -f opp.list cc.list

FASTfinish:
	@if [ "$(FAST)" ]; \
	 then \
	     if [ -s opp.list ]; \
	     then \
	         echo "\topping files"; \
	         if [ -n "$(VERBOSE_RULES)" ]; \
	         then \
	             echo "\t$(ocfiles) $(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) `cat opp.list`"; \
	         fi; \
	         $(ocfiles) $(opp) $(OPPOPT) $(OPPFLAGS) $(DOPT) $(DOPT1) $(DOPT2) `cat opp.list`; \
	         sed -e 's/\.[IS]/.c/' <opp.list >>cc.list; \
	     else \
	         echo "\tnothing to opp"; \
	     fi; \
	     if [ -s cc.list ]; \
	     then \
	         echo "\tcompiling files"; \
	         if [ -n "$(VERBOSE_RULES)" ]; \
	         then \
	             echo "\t$(ocfiles) $(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c `cat cc.list`"; \
	         fi; \
	         $(ocfiles) $(CC) $(COPT) $(IPATH) $(IPATH1) $(IPATH2) $(MOPT) $(DOPT) $(DOPT1) $(DOPT2) -c `cat cc.list`; \
	         if [ "$(COPT)" != "-g" -a "$(DEBUG)" != "yes" ]; \
	         then \
	             echo "\tremoving .c files"; \
	             rm `cat cc.list`; \
	         else \
	             echo "\tleaving .c files"; \
	         fi; \
	     else \
	         echo "\tnothing to compile"; \
	     fi; \
	     if [ -n "$(VERBOSE_RULES)" ]; \
	     then \
	         echo "\trm -f opp.list cc.list"; \
	     fi; \
	     rm -f opp.list cc.list; \
	 fi

FAST:
	$(MAKE) FAST=1 objects_FAST

