#ifndef SC_EXTERN
#define SC_EXTERN

#include <stdio.h>

/* path to nfm -- used to find function_data file */
extern char *nfm_path;

/* info generated by SCcpp */
extern int SCatofn_count;
extern struct SCatofn_st SCatofn[];

/* flag & pointer for debug */
extern int SCdebug;
extern FILE *SCconsole;

extern WINDOW *SCmsg_win;
extern char SCmsg_string[81];

extern WINDOW *SCref_win;
extern char SCref_string[81];

extern WINDOW *SCerr_win;
extern char SCerr_string[81];

extern WINDOW *SCcol_win;
extern WINDOW *SCfree_win;

extern char SCprint_file[133];

#endif
