#ifndef EMSrndtp_include
#define EMSrndtp_include

/* -------------------- Topology Interaction Information ------------------ */
     /*
      * Oft used info about surfaces in rounding.
      */
   struct EMSrnd_sf_info {
       GRobjid objid;
       struct IGRbsp_surface *geom;
       IGRdouble tol;
   };

#define  EMSrnd_tansf_processing        0x100
#define  EMSrnd_fillet_processed        0x200
#define  EMSrnd_sibling                 0x400
#define  EMSrnd_multi_fillet            0x800

#define  EMSrnd_seam_cross_fillet       0x1000
#define  EMSrnd_base_fillet             0x2000
#define  EMSrnd_tp_interaction          0x4000
#define  EMSrnd_multiple_fillet         0x8000

  /*
   * One EMStansf_rnd_info structure is associated with every fillet (base/
   * secondary) for an edge.
   */

  struct EMStansf_rnd_info {

            /*
             * Information about first the tangential surface corresponding
             * to the u0 iso.
             */
            struct EMSrnd_sf_info tansf1;
            
            /*
             * Information about second the tangential surface corresponding
             * to the u1 iso.
             */
            struct EMSrnd_sf_info tansf2;
            
            /*
             * Information about the extra-fillets which need to be generated.
             */
            struct EMSrnd_sf_info fillet;

            /*
             * Fillet iso-edge information (u=0,1)
             */

            struct IGRbsp_curve       *fill_isocvs[2];
            struct EMSdataselect      fill_isocvs_onsfs[2];

            /*
             * Props field.
             */
            IGRlong  props;

            /*
             * Head of a linked list of EMSrnd_tpint_info structs that
             * store the v=constt parametric limits of this fillet lying
             * between interactions.
             */
            struct EMSrnd_tpint_info *tpint_info;

            /*
             * If the fillet interacts across a seam, 
             * for a single interaction, the sibling field stores the
             * second rolbal fillet information. This is NULL, if there
             * is only one boundary with which the fillet interacts.
             */
            struct EMStansf_rnd_info  *sibling;

            /*
             * Points to the next fillet surface info.
             */
            struct EMStansf_rnd_info  *next;
         };         

#define EMSrnd_tpint_processed   0x1
#define EMSrnd_tpint_coinc       0x2   /* Indicates iso coincidence with the
                                          previous tpint node. */
#define EMSrnd_tpint_deletable   0x4   /* This not a useful intpt. */
#define EMSrnd_tpint_head        0x8   /* Used to mark the first interaction
                                          point. */

#define EMSrnd_tpint_dummy       0x20  /* This is an artificially introduced
                                          interaction point. */
#define EMSrnd_tpint_area_start  0x40  /* Region after this interaction point
                                          is area. */
#define EMSrnd_tpint_at_seam     0x80  /* This interaction point is on a
                                          seam edge. */
#define EMSrnd_tpint_start       0x100 /* At the start of a curve. */
#define EMSrnd_tpint_stop        0x200 /* At the stop of a curve. */
#define EMSrnd_tpint_nointers    0x400 /* Do not generate a fillet intersection
                                         from this intpt. */

   /*
    * Stores the interaction info on the supporting face. Stores the edge 
    * id of the boundary edge, the uv parameter on the fillet of the 
    * interaction point, properties if any associated with this interaction.
    *
    * A list of these structures is associated with the u0 & u1 isos of a
    * fillet, whether a base fillet or a secondary fillet.
    */

   struct EMSrnd_tpint_info
   {
      struct EMSrnd_tpint_info *next;
      IGRint     iso_inx;
      GRobjid    int_edge;
      IGRdouble  int_pt[2];                 /* uv parameters on the
                                               fillet corresponding to 
                                               the interaction.*/
      IGRpoint   xyzpt;                     /* xyz counterpart of int_pt
                                               on the fillet. */
      IGRushort  props;
      struct EMStansf_rnd_info *gen_tansf;  /* Pointer to the 
                                               EMStansf_rnd_info node
                                               of the fillet that is
                                               generated by this 
                                               interaction point. */
      struct EMSpypoint *trim_info;         /* Pointer to the pypoint
                                               node from which this
                                               interaction node was
                                               generated. */
      struct EMSintobj *intobj;             /* Valid only if the props
                                               field holds
                                               EMSrnd_tpint_nointers. */
   };

#endif
