
all:
	@cd $(NFM)/src/fto;      make; cd ${NFM}
	@cd $(NFM)/src/mem;      make; cd ${NFM}
	@cd $(NFM)/src/systools; make; cd ${NFM}
	@cd $(NFM)/src/err;      make; cd ${NFM}
	@cd ${NFM}/lib;          make; cd ${NFM}

clean:
	@cd $(NFM)/src/fto;      make clean; cd ${NFM}
	@cd $(NFM)/src/mem;      make clean; cd ${NFM}
	@cd $(NFM)/src/systools; make clean; cd ${NFM}
	@cd $(NFM)/src/err;      make clean; cd ${NFM}
	@cd ${NFM}/lib;          make clean; cd ${NFM}

