TOKEN_NAME:RIS_TOK_ADD
MESSAGE:'add'

TOKEN_NAME:RIS_TOK_ALL
MESSAGE:'all'

TOKEN_NAME:RIS_TOK_AND
MESSAGE:'and'

TOKEN_NAME:RIS_TOK_ANY
MESSAGE:'any'

TOKEN_NAME:RIS_TOK_AS
MESSAGE:'as'

TOKEN_NAME:RIS_TOK_ASYNC
MESSAGE:'async'

TOKEN_NAME:RIS_TOK_AUTOCOMMIT
MESSAGE:'autocommit'

TOKEN_NAME:RIS_TOK_AUTORENAME
MESSAGE:'autorename'

TOKEN_NAME:RIS_TOK_BUFFER
MESSAGE:'buffer'

TOKEN_NAME:RIS_TOK_BY
MESSAGE:'by'

TOKEN_NAME:RIS_TOK_CHAR_STR_LIT
MESSAGE:a character string literal

TOKEN_NAME:RIS_TOK_CHAR_STR_LIT_STB
MESSAGE:a character string literal

TOKEN_NAME:RIS_TOK_COLON
MESSAGE:':'

TOKEN_NAME:RIS_TOK_COMPLETION
MESSAGE:'completion'

TOKEN_NAME:RIS_TOK_CONTINUE
MESSAGE:'continue'

TOKEN_NAME:RIS_TOK_CURSOR
MESSAGE:'cursor'

TOKEN_NAME:RIS_TOK_DATABASE
MESSAGE:'database'

TOKEN_NAME:RIS_TOK_DB2
MESSAGE:'DB2'

TOKEN_NAME:RIS_TOK_DBNAME
MESSAGE:'dbname'

TOKEN_NAME:RIS_TOK_DECLARE
MESSAGE:'declare'

TOKEN_NAME:RIS_TOK_DEFAULT
MESSAGE:'default'

TOKEN_NAME:RIS_TOK_DELETE
MESSAGE:'delete'

TOKEN_NAME:RIS_TOK_DESCRIPTOR
MESSAGE:'descriptor'

TOKEN_NAME:RIS_TOK_DIR
MESSAGE:'dir'

TOKEN_NAME:RIS_TOK_DISTINCT
MESSAGE:'distinct'

TOKEN_NAME:RIS_TOK_ENABLE
MESSAGE:'enable'

TOKEN_NAME:RIS_TOK_EQ
MESSAGE:'='

TOKEN_NAME:RIS_TOK_ERROR
MESSAGE:'error'

TOKEN_NAME:RIS_TOK_EXCLUDE
MESSAGE:'exclude'

TOKEN_NAME:RIS_TOK_EXCLUSIVE
MESSAGE:'exclusive'

TOKEN_NAME:RIS_TOK_FOR
MESSAGE:'for'

TOKEN_NAME:RIS_TOK_FOUND
MESSAGE:'found'

TOKEN_NAME:RIS_TOK_FROM
MESSAGE:'from'

TOKEN_NAME:RIS_TOK_FULL
MESSAGE:'full'

TOKEN_NAME:RIS_TOK_GATEWAY
MESSAGE:'gateway'

TOKEN_NAME:RIS_TOK_GO
MESSAGE:'go'

TOKEN_NAME:RIS_TOK_GOTO
MESSAGE:'goto'

TOKEN_NAME:RIS_TOK_GRANT
MESSAGE:'grant'

TOKEN_NAME:RIS_TOK_IDENT
MESSAGE:an identifier

TOKEN_NAME:RIS_TOK_IN
MESSAGE:'in'

TOKEN_NAME:RIS_TOK_INCLUDE
MESSAGE:'include'

TOKEN_NAME:RIS_TOK_INDEX
MESSAGE:'index'

TOKEN_NAME:RIS_TOK_INFORMIX
MESSAGE:'Informix'

TOKEN_NAME:RIS_TOK_INGRES
MESSAGE:'Ingres'

TOKEN_NAME:RIS_TOK_INITIAL
MESSAGE:'initial'

TOKEN_NAME:RIS_TOK_INPUT
MESSAGE:'input'

TOKEN_NAME:RIS_TOK_INSERT
MESSAGE:'insert'

TOKEN_NAME:RIS_TOK_INTERVAL
MESSAGE:'interval'

TOKEN_NAME:RIS_TOK_INTO
MESSAGE:'into'

TOKEN_NAME:RIS_TOK_LPAREN
MESSAGE:'('

TOKEN_NAME:RIS_TOK_MODE
MESSAGE:'mode'

TOKEN_NAME:RIS_TOK_MODIFY
MESSAGE:'modify'

TOKEN_NAME:RIS_TOK_MSSQL
MESSAGE:'MSSQL'

TOKEN_NAME:RIS_TOK_MUL
MESSAGE:'*'

TOKEN_NAME:RIS_TOK_NETWORK
MESSAGE:'network'

TOKEN_NAME:RIS_TOK_NOT
MESSAGE:'not'

TOKEN_NAME:RIS_TOK_NT
MESSAGE:'NT'

TOKEN_NAME:RIS_TOK_NULL
MESSAGE:'null'

TOKEN_NAME:RIS_TOK_OFF
MESSAGE:'off'

TOKEN_NAME:RIS_TOK_ON
MESSAGE:'on'

TOKEN_NAME:RIS_TOK_ONLY
MESSAGE:'only'

TOKEN_NAME:RIS_TOK_OPTION
MESSAGE:'option'

TOKEN_NAME:RIS_TOK_ORACLE
MESSAGE:'Oracle'

TOKEN_NAME:RIS_TOK_OS400
MESSAGE:'OS400'

TOKEN_NAME:RIS_TOK_OSTYPE
MESSAGE:'ostype'

TOKEN_NAME:RIS_TOK_OSUSER
MESSAGE:'osuser'

TOKEN_NAME:RIS_TOK_OUTPUT
MESSAGE:'output'

TOKEN_NAME:RIS_TOK_PARTIAL
MESSAGE:'partial'

TOKEN_NAME:RIS_TOK_PASSWORD
MESSAGE:'password'

TOKEN_NAME:RIS_TOK_PLUS
MESSAGE:'+'

TOKEN_NAME:RIS_TOK_PRIMARY
MESSAGE:'verify'

TOKEN_NAME:RIS_TOK_PUBLIC
MESSAGE:'public'

TOKEN_NAME:RIS_TOK_RBRACK
MESSAGE:']'

TOKEN_NAME:RIS_TOK_RDB
MESSAGE:'RDB'

TOKEN_NAME:RIS_TOK_REMOTE
MESSAGE:'remote'

TOKEN_NAME:RIS_TOK_RESPONSE
MESSAGE:'response'

TOKEN_NAME:RIS_TOK_RPAREN
MESSAGE:')'

TOKEN_NAME:RIS_TOK_SCHEMA
MESSAGE:'schema'

TOKEN_NAME:RIS_TOK_SECONDARY
MESSAGE:'secondary'

TOKEN_NAME:RIS_TOK_SECTION
MESSAGE:'section'

TOKEN_NAME:RIS_TOK_SECURE
MESSAGE:'secure'

TOKEN_NAME:RIS_TOK_SELECT
MESSAGE:'select'

TOKEN_NAME:RIS_TOK_SEMICOLON
MESSAGE:end of statement

TOKEN_NAME:RIS_TOK_SERVER
MESSAGE:'server'

TOKEN_NAME:RIS_TOK_SET
MESSAGE:'set'

TOKEN_NAME:RIS_TOK_SHARE
MESSAGE:'share'

TOKEN_NAME:RIS_TOK_SIZE
MESSAGE:'size'

TOKEN_NAME:RIS_TOK_SQLDS
MESSAGE:'SQLDS'

TOKEN_NAME:RIS_TOK_SQLERROR
MESSAGE:'sqlerror'

TOKEN_NAME:RIS_TOK_STRIP
MESSAGE:'strip'

TOKEN_NAME:RIS_TOK_SUB
MESSAGE:'-'

TOKEN_NAME:RIS_TOK_SUPERSCHEMA
MESSAGE:'superschema'

TOKEN_NAME:RIS_TOK_SYBASE
MESSAGE:'Sybase'

TOKEN_NAME:RIS_TOK_TABLE
MESSAGE:'table'

TOKEN_NAME:RIS_TOK_TABLES
MESSAGE:'tables'

TOKEN_NAME:RIS_TOK_TIMEOUT
MESSAGE:'timeout'

TOKEN_NAME:RIS_TOK_TIMESTAMP
MESSAGE:'timestamp'

TOKEN_NAME:RIS_TOK_TO
MESSAGE:'to'

TOKEN_NAME:RIS_TOK_TOLERANCE
MESSAGE:'tolerance'

TOKEN_NAME:RIS_TOK_TRANSACTION
MESSAGE:'transaction'

TOKEN_NAME:RIS_TOK_UNIX
MESSAGE:'Unix'

TOKEN_NAME:RIS_TOK_UPDATE
MESSAGE:'update'

TOKEN_NAME:RIS_TOK_USER
MESSAGE:'user'

TOKEN_NAME:RIS_TOK_USING
MESSAGE:'using'

TOKEN_NAME:RIS_TOK_VALUES
MESSAGE:'values'

TOKEN_NAME:RIS_TOK_VERIFICATION
MESSAGE:'verification'

TOKEN_NAME:RIS_TOK_VERIFY
MESSAGE:'verify'

TOKEN_NAME:RIS_TOK_VERSION
MESSAGE:'version'

TOKEN_NAME:RIS_TOK_VIEW
MESSAGE:'view'

TOKEN_NAME:RIS_TOK_VMS
MESSAGE:'VMS'

TOKEN_NAME:RIS_TOK_WITH
MESSAGE:'with'

