#/* $Id: makefile,v 1.1.1.1 2001/01/04 21:08:02 cvs Exp $  */

#/***************************************************************************
# * I/VDS
# *
# * File:        vdct2/imp/makefile
# *
# * Description:
# *
# * Dependencies:
# *
# * Revision History:
# *      $Log: makefile,v $
# *      Revision 1.1.1.1  2001/01/04 21:08:02  cvs
# *      Initial import to CVS
# *
# Revision 1.1  1999/06/29  18:27:38  pinnacle
# ct
#
# Revision 1.1  1999/06/08  14:20:56  pinnacle
# ah
#
# Revision 1.1  1999/05/28  13:59:18  pinnacle
# ct
#
# *
# * History:
# * MM/DD/YY  AUTHOR  DESCRIPTION
# * 05/28/99  ah      creation
# ***************************************************************************/

target:	mkfile
	grmake -r -k -f mkfile

mkfile:	vdict2imp.m
	grmakemake vdict2imp.m mkfile
