# $Id: makefile,v 1.1.1.1 2001/01/04 21:07:56 cvs Exp $

# -------------------------------------------------------------------
# I/VDS
#
# File:		vdbatch/imp/makefile 
#
# Description:
#
# Dependencies:
#
# Revision History:
#	$Log: makefile,v $
#	Revision 1.1.1.1  2001/01/04 21:07:56  cvs
#	Initial import to CVS
#	
# Revision 1.1  1997/05/08  15:23:22  pinnacle
# rep bin w/txt
#
# Revision 1.1  1995/07/25  21:03:40  pinnacle
# Created: vdbatch/imp/makefile by azuurhou for vds.240
#
#
# History:
#	MM/DD/YY	AUTHOR		DESCRIPTION
#	07/25/95	adz		creation date
#
# -------------------------------------------------------------------

target: mkfile
	grmake -r -k -f mkfile

mkfile : vdbatchimp.m
	grmakemake vdbatchimp.m mkfile

